include:
  - path: consumer_banking/connector/consumer_banking/compose.yaml
  - path: consumer_lending/connector/consumer_lending/compose.yaml
  - path: mortgage_services/connector/mortgage_services/compose.yaml
  - path: credit_cards/connector/credit_cards/compose.yaml
  - path: small_business_banking/connector/small_business_banking/compose.yaml
  - path: enterprise/connector/enterprise/compose.yaml
  - path: security/connector/security/compose.yaml
  - path: app_mgmt/connector/app_mgmt/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile: Dockerfile.engine
      pull: true
    environment:
      AUTHN_CONFIG_PATH: /md/auth_config.json
      ENABLE_CORS: "true"
      ENABLE_SQL_INTERFACE: "true"
      INTROSPECTION_METADATA_FILE: /md/metadata.json
      METADATA_PATH: /md/open_dd.json
      OTLP_ENDPOINT: http://local.hasura.dev:4317
    extra_hosts:
      - local.hasura.dev:host-gateway
    labels:
      io.hasura.ddn.service-name: engine
    ports:
      - 3280:3000
  otel-collector:
    command:
      - --config=/etc/otel-collector-config.yaml
    environment:
      HASURA_DDN_PAT: ${HASURA_DDN_PAT}
    image: otel/opentelemetry-collector:0.104.0
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
