query mortgage_demo {

  # --- Mortgage Loan Example ---
  mortgageLoanInfo: mortgageServicesLoans {
    # Loan Details
    mortgageServicesLoanId
    loanAmount
    interestRate
    loanTermMonths
    originationDate
    maturityDate

    # Nested Application Details
    mortgageServicesApplication {
      mortgageServicesApplicationId
      applicationType # Should not be REFINANCE due to filter
      status
      submissionDateTime

      # Nested Property Details
      mortgageServicesProperties {
        mortgageServicesPropertyId
        propertyType
        occupancyType
        yearBuilt
        squareFeet
        bedrooms
        bathrooms
        address
      }
    }
  }
}
