services:
  data_quality_data_quality:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.data_quality
    environment:
      CONNECTION_URI: $DATA_QUALITY_DATA_QUALITY_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $DATA_QUALITY_DATA_QUALITY_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $DATA_QUALITY_DATA_QUALITY_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $DATA_QUALITY_DATA_QUALITY_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6558:8080
