services:
  security_security:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.security
    environment:
      CONNECTION_URI: $SECURITY_SECURITY_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $SECURITY_SECURITY_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $SECURITY_SECURITY_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $SECURITY_SECURITY_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4431:8080
