from fsi_data_generator.fsi_generators.helpers import BaseEnum


class DocumentType(BaseEnum):
    """
    Types of documents that can be associated with mortgage applications.
    Matches the DBML enum 'mortgage_services.document_type'.
    """
    TAX_RETURN = "TAX_RETURN"
    W2 = "W2"
    PAY_STUB = "PAY_STUB"
    BANK_STATEMENT = "BANK_STATEMENT"
    CREDIT_REPORT = "CREDIT_REPORT"
    IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION"
    ASSET_STATEMENT = "ASSET_STATEMENT"
    PURCHASE_AGREEMENT = "PURCHASE_AGREEMENT"
    TITLE_INSURANCE = "TITLE_INSURANCE"
    PROPERTY_APPRAISAL = "PROPERTY_APPRAISAL"
    INSURANCE_PROOF = "INSURANCE_PROOF"
    LOAN_ESTIMATE = "LOAN_ESTIMATE"
    CLOSING_DISCLOSURE = "CLOSING_DISCLOSURE"
    LETTER_OF_EXPLANATION = "LETTER_OF_EXPLANATION"
    GIFT_LETTER = "GIFT_LETTER"
    SELF_EMPLOYMENT = "SELF_EMPLOYMENT"
    BANKRUPTCY_DISCHARGE = "BANKRUPTCY_DISCHARGE"
    DIVORCE_DECREE = "DIVORCE_DECREE"
    MORTGAGE_NOTE = "MORTGAGE_NOTE"
    DEED = "DEED"
    OTHER = "OTHER"

    _DEFAULT_WEIGHTS = [
        0.1,  # TAX_RETURN
        0.1,  # W2
        0.12,  # PAY_STUB
        0.12,  # BANK_STATEMENT
        0.05,  # CREDIT_REPORT
        0.07,  # IDENTITY_VERIFICATION
        0.08,  # ASSET_STATEMENT
        0.05,  # PURCHASE_AGREEMENT
        0.04,  # TITLE_INSURANCE
        0.04,  # PROPERTY_APPRAISAL
        0.03,  # INSURANCE_PROOF
        0.02,  # LOAN_ESTIMATE
        0.02,  # CLOSING_DISCLOSURE
        0.01,  # LETTER_OF_EXPLANATION
        0.01,  # GIFT_LETTER
        0.01,  # SELF_EMPLOYMENT
        0.01,  # BANKRUPTCY_DISCHARGE
        0.01,  # DIVORCE_DECREE
        0.01,  # MORTGAGE_NOTE
        0.01,  # DEED
        0.01  # OTHER
    ]
