from fsi_data_generator.fsi_generators.helpers import BaseEnum


class DocumentType(BaseEnum):
    """
    Types of documents that can be associated with mortgage applications.
    Matches the DBML enum 'mortgage_services.document_type'.
    """
    TAX_RETURN = "TAX_RETURN"
    W2 = "W2"
    PAY_STUB = "PAY_STUB"
    BANK_STATEMENT = "BANK_STATEMENT"
    CREDIT_REPORT = "CREDIT_REPORT"
    IDENTITY_VERIFICATION = "IDENTITY_VERIFICATION"
    ASSET_STATEMENT = "ASSET_STATEMENT"
    PURCHASE_AGREEMENT = "PURCHASE_AGREEMENT"
    TITLE_INSURANCE = "TITLE_INSURANCE"
    PROPERTY_APPRAISAL = "PROPERTY_APPRAISAL"
    INSURANCE_PROOF = "INSURANCE_PROOF"
    LOAN_ESTIMATE = "LOAN_ESTIMATE"
    CLOSING_DISCLOSURE = "CLOSING_DISCLOSURE"
    LETTER_OF_EXPLANATION = "LETTER_OF_EXPLANATION"
    GIFT_LETTER = "GIFT_LETTER"
    SELF_EMPLOYMENT = "SELF_EMPLOYMENT"
    BANKRUPTCY_DISCHARGE = "BANKRUPTCY_DISCHARGE"
    DIVORCE_DECREE = "DIVORCE_DECREE"
    MORTGAGE_NOTE = "MORTGAGE_NOTE"
    DEED = "DEED"
    OTHER = "OTHER"
