from ....helpers import BaseEnum


# Create an Enum for Citizenship Statuses
class CitizenshipStatus(BaseEnum):
    US_CITIZEN = "US_CITIZEN"
    US_PERMANENT_RESIDENT = "US_PERMANENT_RESIDENT"
    US_TEMPORARY_RESIDENT = "US_TEMPORARY_RESIDENT"
    NON_RESIDENT_ALIEN = "NON_RESIDENT_ALIEN"
    FOREIGN_NATIONAL = "FOREIGN_NATIONAL"
    DUAL_CITIZEN_US = "DUAL_CITIZEN_US"
    REFUGEE_ASYLEE = "REFUGEE_ASYLEE"
    TEMPORARY_PROTECTED_STATUS = "TEMPORARY_PROTECTED_STATUS"
    DACA_RECIPIENT = "DACA_RECIPIENT"
    UNDOCUMENTED = "UNDOCUMENTED"
    NOT_SPECIFIED = "NOT_SPECIFIED"
