from fsi_data_generator.fsi_generators.helpers import BaseEnum


class LegalStructure(BaseEnum):
    SOLE_PROPRIETORSHIP = "SOLE_PROPRIETORSHIP"
    GENERAL_PARTNERSHIP = "GENERAL_PARTNERSHIP"
    LIMITED_PARTNERSHIP = "LIMITED_PARTNERSHIP"
    LIMITED_LIABILITY_PARTNERSHIP = "LIMITED_LIABILITY_PARTNERSHIP"
    LIMITED_LIABILITY_COMPANY = "LIMITED_LIABILITY_COMPANY"
    C_CORPORATION = "C_CORPORATION"
    S_CORPORATION = "S_CORPORATION"
    PROFESSIONAL_CORPORATION = "PROFESSIONAL_CORPORATION"
    NONPROFIT_CORPORATION = "NONPROFIT_CORPORATION"
    BENEFIT_CORPORATION = "BENEFIT_CORPORATION"
    COOPERATIVE = "COOPERATIVE"
    JOINT_VENTURE = "JOINT_VENTURE"
    TRUST = "TRUST"
    ESTATE = "ESTATE"
    ASSOCIATION = "ASSOCIATION"
    GOVERNMENT_ENTITY = "GOVERNMENT_ENTITY"
    FOREIGN_ENTITY = "FOREIGN_ENTITY"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    OTHER = "OTHER"


