from enum import Enum


class PartyRelationshipType(Enum):
    POWER_OF_ATTORNEY = "POWER_OF_ATTORNEY"
    GUARDIAN = "GUARDIAN"
    TRUSTEE = "TRUSTEE"
    BENEFICIARY = "BENEFICIARY"
    EXECUTOR = "EXECUTOR"
    CUSTODIAN = "CUSTODIAN"
    AUTHORIZED_USER = "AUTHORIZED_USER"
    BUSINESS_PARTNER = "BUSINESS_PARTNER"
    SPOUSE = "SPOUSE"
    DEPENDENT = "DEPENDENT"
    CO_SIGNER = "CO_SIGNER"
    EMPLOYER_EMPLOYEE = "EMPLOYER_EMPLOYEE"
    AGENT = "AGENT"
    PARENT_CHILD = "PARENT_CHILD"
    SIBLING = "SIBLING"
    CORPORATE_OFFICER = "CORPORATE_OFFICER"
    MEMBER = "MEMBER"
    OWNER = "OWNER"
    OTHER = "OTHER"
