small_business_banking__adverse_action_notices__score_factors = [
  "Proportion of revolving balances to revolving credit limits is too high on banking and national revolving accounts.",
  "Length of time accounts have been established, with insufficient credit history on banking and national accounts.",
  "Too many accounts with balances compared to total number of open accounts in credit history.",
  "Ratio of current revolving debt to available revolving credit limit too high, affecting overall credit utilization.",
  "Number of accounts showing delinquency, with multiple late payments affecting payment history component.",
  "Number of bank or national revolving accounts with high utilization affecting credit capacity metrics.",
  "Lack of recent installment loan information or limited experience with installment credit products.",
  "Number of recent inquiries on credit report affecting new credit component of score.",
  "Too many accounts opened in past 12 months compared to total credit portfolio age.",
  "Proportion of loan balances to loan amounts is too high on banking and national accounts.",
  "Lack of recent bank revolving account information or limited revolving credit experience.",
  "Length of time since most recent account opening too short, indicating potential credit seeking.",
  "Number of accounts with delinquency, with derogatory public records affecting payment history component.",
  "Too many bank or national revolving accounts with balances, indicating potential overextension.",
  "Lack of sufficient credit history length with average account age below optimal threshold.",
  "Serious delinquency, derogatory public record, or collection filed in credit history.",
  "Length of time since derogatory public record or collection is too recent.",
  "Number of bank or national revolving accounts showing high utilization pattern.",
  "Time since most recent delinquency is too recent, affecting payment history component.",
  "Ratio of high credit limit accounts to total accounts is below optimal mix.",
  "Lack of recent revolving account information or limited revolving credit experience.",
  "Number of established accounts below threshold for optimal credit mix factor.",
  "Too many consumer finance accounts relative to prime banking credit relationships.",
  "Proportion of balances to credit limits on revolving accounts too high.",
  "Number of accounts with no recent payment information updates.",
  "Length of time since most recent credit account opening insufficient for score optimization.",
  "Lack of recent bank installment loan information or limited installment credit experience.",
  "Number of months since most recent delinquency is too recent in file.",
  "Too many mortgage accounts with balances relative to income or credit capacity.",
  "Proportion of high balance accounts to total accounts exceeds optimal threshold.",
  "Lack of recent national revolving account information or limited prime credit relationships.",
  "Length of time accounts have been established insufficient for score history component.",
  "Number of accounts with balance compared to total accounts exceeds optimal ratio.",
  "Time since most recent account opened indicates recent credit-seeking behavior.",
  "Ratio of current installment loan balances to original loan amounts too high.",
  "Lack of demonstrated successful payment history on various credit types.",
  "Number of months since most recent inquiry is too recent affecting new credit component.",
  "Too many revolving accounts with high balances relative to limits indicating high utilization.",
  "Proportion of open accounts to total accounts below optimal credit management ratio.",
  "Length of time since derogatory public record or collection is insufficient for score recovery.",
  "Number of accounts currently or previously past due exceeding optimal payment history threshold.",
  "Too many accounts with balances across multiple credit types indicating potential overextension.",
  "Ratio of outstanding balances to original loan amounts higher than optimal for installment loans.",
  "Lack of established credit accounts with sufficient time to demonstrate payment behavior.",
  "Number of inquiries in last 12 months exceeds threshold for optimal new credit component.",
  "Too many recently opened accounts relative to total credit portfolio age.",
  "Proportion of revolving balance to revolving credit limits exceeds optimal utilization.",
  "Length of time since most recent delinquency is too short for score recovery.",
  "Number of bank revolving accounts with balances exceeds optimal credit utilization pattern.",
  "Ratio of accounts with balances to total accounts indicates potential overextension.",
  "Lack of recent installment account information with established payment history.",
  "Number of accounts with delinquency exceeds threshold for good payment history score.",
  "Too many accounts showing high utilization compared to available credit.",
  "Proportion of past due accounts to total accounts exceeds optimal payment pattern.",
  "Length of time since most recent account opening indicates credit-seeking behavior.",
  "Number of recent inquiries from banking institutions indicating credit shopping activity.",
  "Ratio of delinquent accounts to total accounts exceeds threshold for good payment history.",
  "Lack of established banking relationship accounts with sufficient history.",
  "Number of accounts with high credit utilization relative to available limits.",
  "Too many new accounts established in recent time period relative to credit file age.",
  "Proportion of revolving accounts to total credit mix below optimal portfolio diversity.",
  "Length of time since most recent derogatory public record is insufficient for score recovery.",
  "Number of delinquent accounts relative to accounts in good standing exceeds optimal ratio.",
  "Ratio of current balance to high credit limit on revolving accounts indicates high utilization.",
  "Lack of established retail or installment accounts with payment history.",
  "Number of accounts showing serious delinquency affects payment history component.",
  "Too many accounts showing balance increases in recent months indicating rising debt levels.",
  "Proportion of accounts with satisfactory payment history below optimal percentage.",
  "Length of time since oldest account established insufficient for credit history depth.",
  "Number of accounts with recent balance increases indicates potential financial stress.",
  "Ratio of recently opened accounts to established accounts too high for optimal mix.",
  "Lack of varied credit types in portfolio affecting credit mix component of score.",
  "Number of accounts recently brought current after delinquency indicates previous payment issues.",
  "Too many accounts with recent high balance relative to credit limits.",
  "Proportion of closed accounts to open accounts indicates potential credit restriction.",
  "Length of time since most recent revolving inquiry is too recent.",
  "Number of collection accounts relative to total accounts exceeds optimal threshold.",
  "Ratio of accounts never delinquent to total accounts below optimal payment history pattern.",
  "Lack of open accounts with recent activity affecting credit utilization metrics.",
  "Number of accounts with reported charge-offs affects payment history component.",
  "Too many accounts showing minimum payment pattern rather than substantive paydown.",
  "Proportion of accounts with balances increasing month-over-month exceeds optimal trend.",
  "Length of time since oldest revolving account opened insufficient for history depth.",
  "Number of months since most recent account update indicates potential inactive accounts.",
  "Ratio of accounts with recent credit limit decreases indicates potential creditor concern.",
  "Lack of recent mortgage or secured installment loan information in credit history.",
  "Number of new banking accounts opened recently compared to established accounts.",
  "Too many accounts with recent credit inquiries indicating credit-seeking behavior.",
  "Proportion of recently opened accounts to total credit file too high for optimal mix.",
  "Length of time since most recent credit inquiry is too short for score optimization.",
  "Number of months since most recent delinquency on banking account is too recent.",
  "Ratio of average account age to oldest account age below optimal credit history pattern.",
  "Lack of bank revolving accounts with established payment history in credit file.",
  "Number of accounts showing balance at or near credit limit indicates high utilization.",
  "Too many accounts with reported delinquencies in past 24 months affecting payment history.",
  "Proportion of accounts currently delinquent to total open accounts exceeds threshold.",
  "Length of time since most recent open account is too short indicating credit-seeking.",
  "Number of new credit obligations with limited payment history relative to established accounts.",
  "Ratio of revolving accounts to installment accounts indicates imbalanced credit mix.",
  "Lack of established credit card accounts with major banking institutions.",
  "Number of accounts currently in collection status affecting payment history component.",
  "Too many accounts showing historical late payment patterns affecting payment history.",
  "Proportion of credit inquiries resulting in opened accounts indicates aggressive credit seeking.",
  "Length of time since oldest installment account opened insufficient for history depth.",
  "Number of inquiries in past 6 months compared to inquiries in past 24 months indicates recent credit seeking.",
  "Ratio of open and active accounts to total accounts in file below optimal usage pattern.",
  "Lack of revolving accounts with zero balance demonstrating credit restraint.",
  "Number of accounts reporting increased credit utilization in recent months.",
  "Too many accounts with credit limit changes in past 12 months indicating account management issues.",
  "Proportion of accounts paid as agreed to total accounts below optimal payment history.",
  "Length of time since most recent delinquency resolution insufficient for score recovery.",
  "Number of accounts with balance to credit limit ratio exceeding 50% indicates high utilization.",
  "Ratio of average balance to average credit limit across revolving accounts too high.",
  "Lack of recently reported positive payment activity on established accounts.",
  "Number of major banking accounts showing delinquency affecting institution relationship component.",
  "Too many accounts showing only minimum payment activity rather than balance reduction.",
  "Proportion of accounts showing credit limit decreases to total accounts indicates creditor concern.",
  "Length of time since most recent payment delinquency was resolved is too short.",
  "Number of months since most recent credit account closing indicates potential credit restriction.",
  "Ratio of accounts closed by credit grantor to total closed accounts indicates adverse relationship history.",
  "Lack of recently active accounts with established financial institutions.",
  "Number of derogatory public records or third-party collections present in credit file.",
  "Too many accounts reported with partial payments instead of full payments.",
  "Proportion of open accounts with recent activity to total open accounts below optimal usage.",
  "Length of time since most recent credit card account opened indicates recent credit acquisition.",
  "Number of installment loans with high balances relative to original loan amounts.",
  "Ratio of joint accounts to individual accounts below optimal relationship credit pattern.",
  "Lack of secured credit product history demonstrating collateral management experience.",
  "Number of accounts with inconsistent payment patterns rather than steady payment history.",
  "Too many mortgage or secured credit inquiries in short timeframe indicating loan shopping.",
  "Proportion of balances paid down monthly to total revolving balances below optimal reduction rate.",
  "Length of time since most recent credit limit increase insufficient for credit expansion.",
  "Number of new credit obligations obtained following adverse credit events indicates risk.",
  "Ratio of accounts with reported late fees to total accounts indicates payment timing issues.",
  "Lack of major credit card accounts with established history and available credit.",
  "Number of months since derogatory account information first reported is too recent.",
  "Too many accounts showing declining balance payments versus acceleration in pay down rate.",
  "Proportion of credit accounts with updated information in past six months below reporting standard.",
  "Length of time between oldest and newest account insufficient for established credit pattern.",
  "Number of accounts showing isolated late payments indicates inconsistent payment behavior.",
  "Ratio of accounts with on-time payments to total accounts below optimal payment history.",
  "Lack of demonstrated successful management of various credit product types.",
  "Number of recently opened accounts compared to inquiries indicates high approval rate seeking.",
  "Too many authorized user accounts relative to individually liable credit relationships.",
  "Proportion of business-related credit inquiries to personal credit inquiries indicates blended credit use.",
  "Length of time since most recent late payment on any account is too recent.",
  "Number of accounts showing high utilization with minimum payments indicates debt accumulation.",
  "Ratio of accounts closed voluntarily to accounts closed by creditor indicates credit management.",
  "Lack of recent information updates across multiple accounts in credit file.",
  "Number of credit accounts showing term modifications or accommodations indicates previous difficulties.",
  "Too many transactional accounts with high utilization relative to total available credit.",
  "Proportion of accounts with balance increases to those with decreases indicates debt accumulation.",
  "Length of time since most recent collection account first reported is too recent.",
  "Number of accounts with low credit limits relative to other accounts indicates restricted credit.",
  "Ratio of accounts with recent positive payment history to total accounts below optimal pattern.",
  "Lack of accounts demonstrating substantial credit limit increases over time.",
  "Number of payment increases year-over-year on revolving accounts below positive trend.",
  "Too many different credit grantors in limited time period indicating credit acquisition behavior.",
  "Proportion of mature accounts to recently established accounts below optimal credit age mix.",
  "Length of time since last account closure by credit grantor is too recent.",
  "Number of accounts with balance-to-limit ratio over 70% indicates high utilization pattern.",
  "Ratio of reported income to total credit obligations indicates potential repayment strain.",
  "Lack of sustained satisfactory payment history on accounts in good standing.",
  "Number of accounts with no recent balance reduction indicates minimal principal payment.",
  "Too many accounts showing increased frequency of late payments over time.",
  "Proportion of tradelines with positive status updates to total tradelines below optimal ratio.",
  "Length of time since most recent satisfactory account status update insufficient.",
  "Number of recent balance transfers between credit accounts indicates potential debt shuffling.",
  "Ratio of high-impact negative items to total credit file items exceeds optimal threshold.",
  "Lack of credit obligation diversity with concentration in single credit type.",
  "Number of credit obligations with recent significant balance increases indicates debt accumulation.",
  "Too many accounts showing inactive status with balances indicating potential abandoned obligations.",
  "Proportion of secured credit to unsecured credit in portfolio below optimal credit mix.",
  "Length of time accounts have maintained low utilization insufficient for utilization history.",
  "Number of payment accommodations or deferments on credit accounts indicates hardship.",
  "Ratio of accounts with missed payments to accounts never delinquent exceeds optimal threshold.",
  "Lack of consistent utilization management across revolving credit products.",
  "Number of tradelines showing irregular payment patterns rather than consistent payments.",
  "Too many balance increases across multiple accounts in short time period indicating debt accumulation.",
  "Proportion of accounts in current status to historical delinquent accounts below recovery threshold.",
  "Length of time since most recent credit account with major financial institution established.",
  "Number of accounts reporting high utilization with minimal monthly payments."
]
