small_business_banking__regulatory_findings__description = [
    "Inconsistent application of credit criteria for small business loans detected during file review.",
    "Failure to collect complete beneficial ownership information for business accounts opened between March and June.",
    "Late filing of CTR for large cash transaction from retail business customer.",
    "Inadequate monitoring of high-risk business accounts identified during BSA/AML review.",
    "Failure to provide adverse action notices within required timeframe for declined applications.",
    "Incomplete documentation of income verification for self-employed business owners.",
    "Missing HMDA data points for small business properties with dwelling-secured loans.",
    "Outdated CIP procedures not aligned with current FinCEN guidance.",
    "Inadequate staff training on fair lending requirements for small business loans.",
    "Failure to properly identify businesses in LMI census tracts for CRA reporting.",
    "Incorrect risk-rating methodology applied to restaurant industry loans.",
    "Incomplete documentation of business purpose for mixed-use property loans.",
    "Failure to maintain proper evidence of beneficial ownership certification renewal.",
    "Inconsistent application of exception policies for loan decisions.",
    "Inadequate monitoring of insider loans to businesses owned by bank directors.",
    "Failure to file timely CTRs for structured transactions identified after review.",
    "Incomplete documentation of collateral valuation for commercial real estate loans.",
    "Failure to provide required disclosures for adjustable-rate commercial loans.",
    "Inadequate procedures for identifying politically exposed persons among business owners.",
    "Missing documentation of rate exception justifications for preferred clients.",
    "Failure to identify connected borrowers for loan concentration analysis.",
    "Inadequate procedures for commercial flood hazard determination and notification.",
    "Insufficient documentation of business tax return analysis in credit files.",
    "Failure to properly verify business existence for online-only enterprises.",
    "Improper classification of business size based on outdated revenue thresholds.",
    "Missing or incomplete account opening documentation for 12 business customers.",
    "Failure to establish ongoing monitoring procedures for high-risk merchant categories.",
    "Inadequate documentation of underwriting exceptions for startup businesses.",
    "Improper handling of declined applications without sufficient adverse action documentation.",
    "Failure to identify beneficial owners for complex business structures.",
    "Inconsistent application of debt service coverage ratio requirements.",
    "Inadequate procedures for identification and monitoring of MRBs.",
    "Failure to comply with E-Sign requirements for digital business account opening.",
    "Missing documentation for business customer enhanced due diligence reviews.",
    "Improper risk classification of cash-intensive businesses.",
    "Failure to complete beneficial ownership certification for legal entity customers.",
    "Inadequate procedures for monitoring cross-border wire transfers for business accounts.",
    "Inconsistent collection of NAICS codes for business customers.",
    "Failure to properly document reasons for credit score overrides.",
    "Inadequate procedures for identifying shell companies during onboarding.",
    "Missing documentation of site visits for high-risk business customers.",
    "Failure to properly verify source of funds for large initial deposits.",
    "Inconsistent implementation of customer due diligence procedures.",
    "Inadequate documentation of decision factors for approved exceptions.",
    "Failure to establish effective procedures for monitoring politically exposed persons.",
    "Missing documentation of BSA officer review for high-risk customer approvals.",
    "Inadequate procedures for identifying and reporting suspicious activities.",
    "Failure to properly document collateral inspection for asset-based loans.",
    "Inconsistent application of minimum credit score requirements.",
    "Inadequate training for frontline staff on identifying red flags for fraud.",
    "Failure to properly validate business address for online applications.",
    "Missing documentation of approval for policy exceptions on high-risk accounts.",
    "Inadequate procedures for ongoing monitoring of business customer activity.",
    "Failure to properly document purpose of loan for commercial credit applications.",
    "Inconsistent collection and verification of business TIN information.",
    "Missing documentation of site visits for businesses with unusual operations.",
    "Failure to establish appropriate EDD procedures for high-risk industries.",
    "Inadequate procedures for validating business revenue claims.",
    "Inconsistent retention of supporting documentation for business loans.",
    "Failure to properly document fair lending second review process.",
    "Inadequate risk assessment methodology for new business products.",
    "Missing documentation of collateral valuation for secured business loans.",
    "Failure to properly identify aggregate cash transactions for CTR purposes.",
    "Inconsistent application of pricing exceptions for similar business clients.",
    "Inadequate procedures for monitoring business customer negative news.",
    "Failure to properly document reason for denial on declined applications.",
    "Missing documentation of approval for high-risk business accounts.",
    "Inadequate monitoring of unusual activity patterns for businesses in high-risk industries.",
    "Failure to collect beneficial ownership information for existing customers during trigger events.",
    "Inconsistent verification of business existence documentation.",
    "Inadequate procedures for identification of HIDTA businesses.",
    "Failure to properly establish expected account activity profiles.",
    "Missing documentation of credit committee approval for policy exceptions.",
    "Inadequate procedures for monitoring unusual international wire activity.",
    "Failure to properly validate business owner identification documents.",
    "Inconsistent application of documentation requirements for similar businesses.",
    "Inadequate training for lenders on commercial flood insurance requirements.",
    "Missing documentation of business structure verification.",
    "Failure to properly monitor loan covenants for commercial borrowers.",
    "Inadequate procedures for identifying related interests of bank directors.",
    "Inconsistent application of risk-based pricing for small business loans.",
    "Missing documentation of site inspections for construction loans.",
    "Failure to properly document income verification for business guarantors.",
    "Inadequate procedures for validation of appraisals on commercial properties.",
    "Inconsistent collection of financial statements from commercial borrowers.",
    "Missing documentation of environmental assessments for commercial properties.",
    "Failure to properly identify businesses in CRA assessment areas.",
    "Inadequate procedures for monitoring high-risk payment processors.",
    "Inconsistent application of credit analysis standards across business units.",
    "Missing documentation of loan approval authority limits.",
    "Failure to properly document change of beneficial ownership.",
    "Inadequate procedures for monitoring cross-product risks.",
    "Inconsistent implementation of enhanced due diligence for high-risk customers.",
    "Missing documentation of periodic review for high-risk customers.",
    "Failure to properly identify affiliated business entities.",
    "Inadequate procedures for monitoring declined loan applications for fair lending patterns.",
    "Inconsistent application of cash flow analysis methodologies.",
    "Missing documentation of tax lien searches for business borrowers.",
    "Failure to properly identify and report suspicious structuring activities.",
    "Inadequate procedures for monitoring online business account activity.",
    "Inconsistent documentation of site visits for new business customers.",
    "Missing documentation of identity verification for authorized signers.",
    "Failure to properly document compliance with OFAC screening requirements.",
    "Inadequate procedures for validating business operating licenses.",
    "Inconsistent application of global cash flow analysis for related businesses.",
    "Missing documentation of regulatory review for new business products.",
    "Failure to properly assess CRA implications of branch closures in LMI areas.",
    "Inadequate procedures for validation of third-party vendor compliance.",
    "Inconsistent documentation of collateral perfection verification.",
    "Missing documentation of flood determination for commercial properties.",
    "Failure to properly monitor commercial customers for unusual ACH activity.",
    "Inadequate procedures for verification of business purpose loans.",
    "Inconsistent implementation of customer risk rating models.",
    "Missing documentation of compliance review for new marketing materials.",
    "Failure to properly identify high-risk geographic locations for business customers.",
    "Inadequate procedures for identifying third-party payment processors.",
    "Inconsistent documentation of account monitoring for money service businesses.",
    "Missing documentation of BSA/AML risk assessments for business products.",
    "Failure to properly identify customer relationships for CIP purposes.",
    "Inadequate procedures for monitoring loan proceeds utilization.",
    "Inconsistent documentation of property inspections for commercial real estate.",
    "Missing documentation of annual review for revolving credit facilities.",
    "Failure to properly identify commercial loans in flood hazard areas.",
    "Inadequate procedures for verification of commercial insurance coverage.",
    "Inconsistent application of credit policy for similar business types.",
    "Missing documentation of legal review for non-standard loan terms.",
    "Failure to properly monitor concentration risk by industry sector.",
    "Inadequate procedures for validation of agricultural income sources.",
    "Inconsistent documentation of construction draw inspections.",
    "Missing documentation of lien position verification.",
    "Failure to properly document cross-collateralization agreements.",
    "Inadequate procedures for monitoring troubled debt restructuring identification.",
    "Inconsistent documentation of cash equity injection for commercial loans.",
    "Missing documentation of business continuity verification for key customers.",
    "Failure to properly identify and monitor non-bank financial institutions.",
    "Inadequate procedures for verification of international business entities.",
    "Inconsistent documentation of exception tracking and reporting.",
    "Missing documentation of covenant compliance verification.",
    "Failure to properly identify high-risk business transactions for review.",
    "Inadequate procedures for verification of import/export documentation.",
    "Inconsistent implementation of customer identification procedures.",
    "Missing documentation of business credit bureau reports.",
    "Failure to properly document reasons for loan policy exceptions.",
    "Inadequate procedures for monitoring business customer complaint patterns.",
    "Inconsistent documentation of guarantor financial analysis.",
    "Missing documentation of minority-owned business status verification.",
    "Failure to properly identify beneficial owners for trust-owned businesses.",
    "Inadequate procedures for verification of startup business projections.",
    "Inconsistent documentation of loan pricing exception approvals.",
    "Missing documentation of regulatory compliance reviews.",
    "Failure to properly monitor high-risk transaction patterns.",
    "Inadequate procedures for verification of business references.",
    "Inconsistent documentation of commercial appraisal reviews.",
    "Missing documentation of business customer periodic reviews.",
    "Failure to properly identify elder financial exploitation in business accounts.",
    "Inadequate procedures for verification of construction budget feasibility.",
    "Inconsistent documentation of loan disbursement controls.",
    "Missing documentation of legal entity customer certifications.",
    "Failure to properly monitor cash-intensive businesses for unusual activity.",
    "Inadequate procedures for verification of change of business ownership.",
    "Inconsistent documentation of loan participation agreements.",
    "Missing documentation of business banking relationship approvals.",
    "Failure to properly document UDAAP risk assessments for business products.",
    "Inadequate procedures for monitoring of high-risk correspondent relationships.",
    "Inconsistent documentation of high-risk customer approvals.",
    "Missing documentation of business customer beneficial ownership structure.",
    "Failure to properly identify businesses with increased money laundering risk.",
    "Inadequate procedures for monitoring of third-party payment activity.",
    "Inconsistent implementation of watch list screening procedures.",
    "Missing documentation of customer due diligence refresh reviews.",
    "Failure to properly document business customer risk assessment methodology.",
    "Inadequate procedures for verification of international trade documentation.",
    "Inconsistent application of KYC procedures for similar business types.",
    "Missing documentation of high-risk customer enhanced monitoring.",
    "Failure to properly identify indirect beneficial ownership interests.",
    "Inadequate procedures for monitoring of remote deposit capture activity.",
    "Inconsistent documentation of commercial loan stress testing.",
    "Missing documentation of environmental risk assessments.",
    "Failure to properly identify prohibited business types during onboarding.",
    "Inadequate procedures for monitoring commercial deposit account activity patterns.",
    "Inconsistent documentation of suspicious activity investigation findings.",
    "Missing documentation of loan committee deliberations for key approvals.",
    "Failure to properly identify business customers in OFAC sanctioned countries.",
    "Inadequate procedures for verification of commercial property values.",
    "Inconsistent implementation of high-risk business monitoring procedures.",
    "Missing documentation of exception approvals for policy deviations.",
    "Failure to properly identify businesses owned by politically exposed persons.",
    "Inadequate procedures for validation of commercial lease agreements.",
    "Inconsistent documentation of fair lending second review decisions.",
    "Missing documentation of commercial insurance coverage verification.",
    "Failure to properly monitor cross-border transactions for business accounts.",
    "Inadequate procedures for account closure risk assessments.",
    "Inconsistent documentation of high-risk industry determinations.",
    "Missing documentation of corporate resolution validity verification.",
    "Failure to properly identify related party transactions in business accounts.",
    "Inadequate procedures for monitoring business account activity against expectations.",
    "Inconsistent implementation of CDD procedures for business customers."
]
