small_business_banking__adverse_action_notices__secondary_reasons = [
  "Insufficient length of credit history to adequately demonstrate payment patterns and credit management.",
  "Debt service coverage ratio of 0.92:1 below our minimum requirement of 1.20:1 for this loan type.",
  "Excessive number of recent credit inquiries indicating potential credit seeking behavior.",
  "Inadequate business cash reserves representing only 15 days of operating expenses versus 45-day minimum.",
  "Loan-to-value ratio of 85% exceeds our maximum guideline of 75% for commercial property financing.",
  "Delinquent credit obligations with multiple accounts showing 30+ day late payments in past 12 months.",
  "Business debt-to-worth ratio of 4.5:1 exceeds our maximum guideline of 3.0:1 for industry classification.",
  "Lack of established business credit references with minimum two-year payment history.",
  "Excessive personal debt obligations reducing guarantor's capacity to support business debt.",
  "Limited management experience with principal operating current business type for only 14 months.",
  "Unacceptable payment history with three or more payments 60+ days past due within 24 months.",
  "Insufficient owner's equity investment representing only 10% of total project cost versus required 20%.",
  "Inadequate collateral with liquidation value covering only 65% of requested loan amount.",
  "Recent bankruptcy, foreclosure, or repossession within the past 48 months on credit report.",
  "Excessive obligations in relation to business income with debt payments exceeding 50% of cash flow.",
  "Declining revenue trend with 15% year-over-year decrease in most recent fiscal period.",
  "Unverifiable income or revenue with significant discrepancies between reported and documented figures.",
  "Inadequate working capital with current ratio of 0.85:1 below our minimum requirement of 1.2:1.",
  "Excessive existing contingent liabilities through personal guarantees on other business debts.",
  "Business credit report shows multiple slow pays with suppliers and trade creditors.",
  "Limited business operating history with company established 12 months ago versus 24-month minimum.",
  "Collateral property located in declining market area with negative value trends in past 12 months.",
  "Inadequate business cash flow to support proposed debt service based on historical performance.",
  "Credit report indicates high utilization of existing revolving credit exceeding 75% of available limits.",
  "Property securing loan does not meet our minimum standards for condition or marketability.",
  "Significant judgments, tax liens, or collection accounts appearing on credit report.",
  "Insufficient documentation provided to verify business revenue claims or financial projections.",
  "Excessive concentration risk with single customer representing more than 30% of total revenue.",
  "Limited industry experience for specialized business operation or proposed expansion area.",
  "Loan request would result in excessive loan exposure to single borrower or related interests.",
  "Significant discrepancies between financial statements and tax returns without adequate explanation.",
  "Unstable employment history for guarantor with multiple job changes in past 24 months.",
  "Business operates in highly regulated industry with pending adverse regulatory changes.",
  "Incomplete or inaccurate information provided on application after multiple requests for clarification.",
  "Gross profit margin below industry standard indicating potential pricing or cost control issues.",
  "Insufficient cash equity in project with loan-to-cost ratio exceeding our 80% maximum guideline.",
  "Length of time accounts have been established is insufficient to demonstrate stability.",
  "Poor previous loan performance history with our institution including past payment issues.",
  "Business plan presents unrealistic projections inconsistent with industry or market conditions.",
  "Excessive personal withdrawals from business affecting debt service capacity and working capital.",
  "Inability to verify critical application information through standard third-party sources.",
  "Excessive lease or rental expense relative to industry norms impacting overall cash flow.",
  "Unacceptable business credit score of 215 on SBSS, below minimum threshold of 160 for approval.",
  "Irregular cash flow patterns with significant monthly fluctuations without seasonal justification.",
  "Previous business failure or closed business with unpaid creditors within past 48 months.",
  "Collateral specifically excluded by our lending policy for requested loan type or purpose.",
  "Pending litigation against business or guarantor with potential material impact on operations.",
  "Inadequate business debt yield ratio at 7.5%, below minimum requirement of 9% for loan type.",
  "Recent significant decline in personal credit score below our minimum guideline of 680.",
  "Limited collateral diversification with single property representing 90% of total security package.",
  "Unstable or declining industry sector creating elevated risk for business operations.",
  "Inadequate accounts receivable quality with aging exceeding industry standards for collectability.",
  "Financial statements reveal significant adverse trends in liquidity, profitability, or leverage.",
  "Existing loan agreement default or covenant violation with this or other financial institutions.",
  "Recent charge-offs or collection accounts on credit report within past 36 months.",
  "Inadequate business succession planning for owner-dependent operation with aging principal.",
  "Business fixed charge coverage ratio below our minimum requirement of 1.15:1 based on historical performance.",
  "Limited management depth with operations critically dependent on single key individual.",
  "Insufficient customer diversification with excessive concentration in volatile market segment.",
  "Property environmental issues requiring remediation or monitoring affecting collateral value.",
  "Business or guarantor tax returns show losses or inadequate income in recent filing periods.",
  "Negative cash flow from business operations in most recent fiscal period as shown on statements.",
  "Prior or current delinquency on government obligations including taxes or student loans.",
  "Income verification reveals debt-to-income ratio exceeding our maximum guideline of 43%.",
  "Excessive reliance on single supplier or vendor creating unacceptable operational dependency risk.",
  "Business demonstrates inadequate cash management practices through account review and analysis.",
  "Recent significant management changes creating instability in business operations and direction.",
  "Lease terms for business premises expire during proposed loan term without renewal options.",
  "Tax lien, judgment, or garnishment filed against business or guarantor remains unsatisfied.",
  "Inadequate business liquidity with quick ratio of 0.55:1 below minimum requirement of 0.9:1.",
  "Market analysis indicates significant competitive threats to business model and revenue stability.",
  "Information obtained from credit reporting agency indicates debt management plan participation.",
  "Inadequate inventory management with turnover ratio significantly below industry standards.",
  "Excessive operating expense ratio at 92% of gross revenue versus industry benchmark maximum of 80%.",
  "Financial statement quality insufficient with only tax returns provided versus required reviewed statements.",
  "Excessive recent growth without corresponding increase in operational infrastructure or controls.",
  "Business credit shows multiple NSF or returned items indicating cash flow management issues.",
  "Inadequate cash flow-to-debt ratio with total liabilities at 8.2x annual cash flow versus 4.0x maximum.",
  "Business debt-to-EBITDA ratio exceeds our maximum guideline of 4.0 for industry classification.",
  "Excessive monthly debt service would consume over 45% of verified monthly business income.",
  "Limited trade references to establish business credit history and supplier relationship quality.",
  "Unacceptable collateral type for requested loan purpose per bank policy guidelines.",
  "Previous modification or workout arrangement on existing debt within past 36 months.",
  "Business location in market area with adverse economic conditions affecting stability.",
  "Inadequate owner investment in business with excessive reliance on debt financing for operations.",
  "Guarantor's personal financial strength insufficient to provide adequate secondary repayment source.",
  "Inconsistent income pattern with fluctuations exceeding 25% between reporting periods.",
  "Accounts receivable concentration with excessive reliance on single payor or customer.",
  "Business profitability inadequate with net income below 5% of revenue for past fiscal year.",
  "Verification of business operations revealed inconsistencies with application representations.",
  "Inadequate insurance coverage for business operations, professional liability, or collateral property.",
  "Projected debt service coverage ratio based on realistic forecasts fails to meet minimum requirement.",
  "Proposed loan structure does not match business cash flow cycle or repayment capacity.",
  "Business seasonal performance currently in low cycle period with inadequate reserves for debt service.",
  "Business financial trends show declining gross revenue over past three reporting periods.",
  "Excessive personal or family living expenses reducing available income for business obligations.",
  "Inventory value includes excessive obsolete or slow-moving items affecting collateral quality.",
  "Industry-specific risk factors create elevated concern for long-term business viability.",
  "Significant gaps in business operating history indicating instability or interruption.",
  "Business operates in highly competitive market with low barriers to entry and thin margins.",
  "Inability to verify employment or income through standard documentation or third-party sources.",
  "Recent rapid expansion into new markets without demonstrated success or expertise.",
  "Unacceptable landlord reference or history of commercial lease defaults based on verification.",
  "Significant undisclosed liabilities discovered during underwriting process affecting debt service capacity.",
  "Business concept or model unproven in local market creating elevated failure risk assessment.",
  "Limited credit history with insufficient trade lines to establish credit management patterns.",
  "Business operating margins below industry benchmark indicating potential operational inefficiency.",
  "Collateral property has limited use alternatives affecting liquidation value and marketability.",
  "Irregular or incomplete business financial record keeping preventing accurate risk assessment.",
  "Credit report indicates multiple recent inquiries suggesting financial stress or credit shopping.",
  "Previous derogatory credit relationship with our institution within past 48 months.",
  "Significant variance between projected and actual performance on previous financing.",
  "Inadequate financial statement preparation with inconsistent accounting methods or standards.",
  "Business current ratio below our minimum requirement of 1.2:1 indicating working capital constraint.",
  "Substantial recent cash withdrawals from business accounts without adequate explanation.",
  "Debt consolidation request includes excessive percentage of unsecured or high-interest obligations.",
  "Significant related-party transactions without adequate documentation or economic justification.",
  "Length of time between adverse public records and current application does not meet our guidelines.",
  "Excessive debt incurred for non-productive assets relative to operational needs.",
  "Inadequate financial analysis of major customers' creditworthiness for accounts receivable.",
  "Significant inventory or equipment held at third-party locations without adequate controls.",
  "Business shows excessive reliance on seasonal or cyclical revenue without adequate reserves.",
  "Limited tangible net worth relative to total assets and proposed financing obligation.",
  "Financial statements indicate excessive owner compensation relative to business performance.",
  "Recent credit obligation default or charge-off exceeding our risk tolerance threshold.",
  "Business plan reflects inadequate market analysis or competitive assessment for success probability.",
  "Excessive secured debt obligations limiting available collateral for new credit request.",
  "Limited international trade experience for import/export business model in application.",
  "Significant recent investment in fixed assets constraining available working capital.",
  "Incomplete business entity documentation including corporate resolutions or partnership agreements.",
  "Unacceptable payment history with utilities, landlords, or suppliers based on reference checks.",
  "Business ownership structure creates unacceptable liability or operational risk for lending relationship.",
  "Credit bureau information indicates identity theft alerts requiring additional verification steps.",
  "Significant deviation from industry norms in key operating ratios without satisfactory explanation.",
  "Financial statements reveal excessive related-party transactions affecting true profitability.",
  "Collection actions or charge-offs within the past 24 months exceeding our risk tolerance guidelines.",
  "Limited or no deposit relationship with our institution to demonstrate cash flow and account management.",
  "Inadequate submission of required financial documentation despite multiple requests.",
  "Business entity type inappropriate for operational needs or creates unnecessary legal exposure.",
  "Material misrepresentation of financial information discovered during verification process.",
  "Significant recent changes in business model or strategy without demonstrated success.",
  "Loan purpose involves excessive percentage for owner benefit versus business operations.",
  "Inadequate financial reporting systems with manual processes creating reconciliation discrepancies.",
  "Environmental concerns identified during property inspection or assessment review.",
  "Excessive workforce turnover rate exceeding 75% annually indicating management or operational issues.",
  "Insufficient credit references or trade references to establish business credit worthiness.",
  "Absence of established banking relationship with satisfactory balance management history.",
  "Excessive variance between actual and budgeted expenses without management analysis or corrective action.",
  "Aggressive growth strategy lacking adequate capitalization or operational infrastructure.",
  "Previous loan performance with excessive delinquencies or extensions indicating cash flow issues.",
  "Application reflects excessive debt relative to business size and documented revenue streams.",
  "Significant deferred maintenance on business facilities affecting operational capacity.",
  "Limited or negative cash flow trend revealed in recent interim financial statements.",
  "Insufficient documentation of required business licenses, permits, or professional certifications.",
  "Business shows excessive reliance on tax refunds or seasonal income without reserves.",
  "Substantial tax liens or judgments filed against business or guarantor remain unsatisfied.",
  "Unresolved collection accounts appearing on personal or business credit reports.",
  "Failure to establish separate business accounts from personal finances indicating poor financial management.",
  "Credit report shows multiple accounts with past due status indicating financial stress.",
  "Insufficient evidence of required business licenses, permits, or professional certifications.",
  "Customer concentration exceeds our maximum guideline of 20% revenue from any single source.",
  "Inadequate management experience in key operational areas critical to business success.",
  "Business debt service requirements consume excessive percentage of monthly revenue.",
  "Length of business plan projections exceeds reasonable forecasting period for industry.",
  "Inadequate capitalization with tangible net worth representing only 10% of total assets.",
  "Recent public record items including judgments or liens filed within past 24 months.",
  "Business operates predominantly in cash without adequate documentation or controls.",
  "Excessive personal credit inquiries suggesting potential financial distress.",
  "Limited business credit established with minimal supplier or trade references.",
  "Bank account management shows excessive overdraft activity or returned items.",
  "Inadequate documentation of business or guarantor income for loan size requested.",
  "Business facility lease terms unfavorable or inhibitive to operational needs.",
  "Collateral depreciation rate exceeds proposed loan amortization creating negative equity position.",
  "Business model heavily dependent on discretionary consumer spending in uncertain economy.",
  "Credit report indicates excessive revolving debt utilization exceeding 85% of available limits.",
  "Multiple recent address changes for business indicating potential instability.",
  "Inadequate explanation for recent significant changes in financial position or performance.",
  "Loan structure request includes excessive interest-only period not supported by business cycle.",
  "Credit history shows multiple charge-offs or collection accounts with financial institutions.",
  "Business performance shows significant seasonality without adequate financial preparation.",
  "Minimal business assets available for secondary repayment source or additional collateral.",
  "Unrealistic revenue or income projections inconsistent with industry standards or historical performance.",
  "Excessive existing business debt relative to industry peers creating repayment risk.",
  "Poor payment history with existing creditors indicating potential cash flow management issues.",
  "Business tax return analysis reveals inadequate income to support existing and proposed debt obligations.",
  "Limited or no principal experience in current business industry or operation type.",
  "Business debt-to-assets ratio exceeds our maximum guideline of 60% for industry classification.",
  "Frequent banking account changes suggesting potential banking relationship management issues.",
  "Insufficient validation of business revenue through bank statements or payment processor records.",
  "Credit report shows excessive use of revolving credit for apparent business purposes.",
  "Financial statements reveal heavy reliance on factoring or high-cost short-term financing.",
  "Inadequate financial record keeping with significant gaps in documentation or reporting."
]
