small_business_banking__compliance_requirements__verification_procedure = [
    "Review sample of legal entity customer files to verify completion of Certification of Beneficial Ownership form and supporting documentation.",
    "Test CTR filing system to ensure transactions over $10,000 are properly identified, aggregated, and reported within required timeframe.",
    "Review customer identification procedures and sample new business accounts to verify consistent application of CIP requirements.",
    "Assess risk-rating methodology and sample customer files to verify appropriate due diligence based on assigned risk levels.",
    "Review suspicious activity monitoring system and sample alerts to verify proper escalation, investigation, and SAR filing when appropriate.",
    "Sample declined business loan applications to verify timely issuance of adverse action notices with required disclosures.",
    "Review small business loan data collection procedures and test reporting accuracy for demographic data on loan applications.",
    "Assess information security program documentation and test controls to verify protection of business customer information.",
    "Sample high-risk customer files to verify enhanced due diligence procedures are followed with appropriate documentation.",
    "Test flood hazard determination process and sample commercial loan files to verify proper notifications to borrowers.",
    "Sample loans secured by residential property to verify documentation of business purpose and appropriate classification.",
    "Review BSA/AML risk assessment methodology and verify inclusion of all business products and services with risk ratings.",
    "Test transaction monitoring system to verify detection of potential structuring patterns and appropriate investigation procedures.",
    "Sample small business loan files to verify accurate disclosure of fees, terms, and conditions in accordance with requirements.",
    "Review onboarding procedures for complex entities and sample files to verify enhanced verification of shell company indicators.",
    "Test transaction monitoring for elder exploitation red flags and verify escalation procedures and reporting protocols.",
    "Review record retention policy and verify systematic retention of business account documentation for required timeframe.",
    "Test OFAC screening system to verify all business customers and transactions are screened with appropriate resolution of potential matches.",
    "Review monitoring procedures for terrorist financing indicators and verify investigation and reporting protocols.",
    "Sample business accounts to verify proper identification and documentation of customers operating as money service businesses.",
    "Test wire transfer monitoring system to verify risk-based review of cross-border transfers with appropriate documentation.",
    "Sample commercial loan files to verify documentation of loan purpose with appropriate detail and consistency.",
    "Review PEP screening procedures and sample files to verify identification and enhanced monitoring of political figures.",
    "Sample accounts identified as third-party payment processors to verify enhanced due diligence and monitoring protocols.",
    "Review commercial appraisal ordering process and sample files to verify compliance with independence and evaluation standards.",
    "Test account monitoring system to identify personal transactions in business accounts and verify follow-up procedures.",
    "Sample new business accounts to verify validation of business existence through appropriate documentation or third-party sources.",
    "Review business continuity planning documentation and test recovery procedures for critical business banking functions.",
    "Sample large deposit transactions to verify source of funds documentation and appropriate approval for significant amounts.",
    "Review high-risk industry list and sample customer files to verify enhanced due diligence for designated business types.",
    "Assess organizational structure and procedures to verify separation of duties in business loan origination and approval process.",
    "Sample insider-related business loans to verify appropriate approval, terms, and ongoing monitoring.",
    "Test remote deposit capture monitoring system and verify risk-based review procedures for suspicious deposit patterns.",
    "Sample business loan denials to verify consistent application of underwriting standards and non-discriminatory practices.",
    "Review trust-owned business accounts to verify beneficial owner identification and appropriate documentation.",
    "Sample high-risk business relationships to verify completion of periodic reviews with appropriate updates and approvals.",
    "Test account monitoring system to compare business activity against expected patterns with appropriate alert parameters.",
    "Review loan fraud detection procedures and sample applications to verify consistent application of controls.",
    "Review commercial real estate concentration reports and verify monitoring against established risk tolerance limits.",
    "Sample non-bank financial institution accounts to verify proper identification and enhanced due diligence procedures.",
    "Test check kiting detection system and verify investigation and resolution procedures for suspicious patterns.",
    "Sample commercial credit files to verify thorough analysis and documentation supporting lending decisions.",
    "Review loan application verification procedures and test system for detecting potential misrepresentation.",
    "Sample asset-based loans to verify collateral monitoring procedures including periodic inspections and borrowing base certificates.",
    "Review policy exception log and sample exceptions to verify appropriate approval and documentation of rationale.",
    "Test employee fraud detection controls and verify investigation and escalation procedures for suspicious activities.",
    "Sample cash-intensive businesses to verify appropriate monitoring and documentation of large currency transactions.",
    "Review pricing exception log and sample files to verify appropriate approval and documentation of justification.",
    "Test transaction monitoring for trade-based money laundering indicators and verify investigation procedures.",
    "Sample online business account applications to verify enhanced identity verification procedures and documentation.",
    "Review periodic review schedule and sample customer files to verify timely completion of required reassessments.",
    "Test negative news screening process and verify escalation procedures for adverse information about business customers.",
    "Sample loan participation agreements to verify appropriate due diligence and ongoing monitoring procedures.",
    "Review troubled debt restructuring identification procedures and sample modified loans to verify proper classification.",
    "Sample multi-jurisdictional businesses to verify enhanced verification procedures and appropriate documentation.",
    "Review commercial credit policy and sample files to verify adherence to documentation standards.",
    "Sample cash-intensive business accounts to verify enhanced monitoring procedures and appropriate documentation.",
    "Test business-to-business payment monitoring and verify investigation procedures for unusual patterns.",
    "Review deposit fraud detection system and verify investigation and resolution procedures for suspicious activities.",
    "Sample commercial loans to verify covenant tracking system and appropriate follow-up for potential violations.",
    "Test cyber event response procedures and verify reporting protocols for incidents affecting business customers.",
    "Review workout loan procedures and sample files to verify appropriate documentation and approval of modifications.",
    "Sample high-risk customers to verify enhanced due diligence documentation including source of wealth and business purpose.",
    "Review procedures for high-net-worth business owners and verify enhanced verification of source of funds.",
    "Test business credit card monitoring system and verify review procedures for unusual transaction patterns.",
    "Sample mixed-use property loans to verify proper HMDA data collection and reporting procedures.",
    "Review account opening procedures to verify controls for detecting nominee ownership arrangements.",
    "Sample commercial real estate loans to verify environmental risk assessment documentation and appropriate risk mitigation.",
    "Review prohibited business list and verify screening procedures during account opening process.",
    "Test international business transaction monitoring and verify enhanced review procedures for high-risk activities.",
    "Review account closure procedures and sample closed files to verify appropriate documentation of suspicious activity.",
    "Sample commercial loan files to verify analysis of business tax returns with appropriate income calculation methodology.",
    "Review enhanced due diligence procedures and verify controls for identifying potential front or shell companies.",
    "Sample commercial loan files to verify stress testing methodology and documentation of analysis results.",
    "Review construction loan procedures and sample files to verify inspection documentation and draw approval process.",
    "Sample business loan applications to verify income verification procedures and supporting documentation.",
    "Review multi-signer account procedures and verify enhanced due diligence for accounts with numerous authorized individuals.",
    "Sample secured commercial loans to verify collateral perfection documentation and appropriate legal reviews.",
    "Review PEP screening procedures and verify enhanced monitoring for businesses owned by political figures.",
    "Test merchant processing monitoring system and verify review procedures for unusual transaction patterns.",
    "Sample commercial loans to verify flood zone determination documentation and appropriate insurance requirements.",
    "Review account takeover prevention controls and test authentication procedures for high-risk transactions.",
    "Sample cash management service implementations to verify security control setup and customer authorization.",
    "Review periodic information update procedures and verify follow-up for customers failing to provide required information.",
    "Test new account screening procedures to verify controls for detecting synthetic business identities.",
    "Review commercial credit reporting procedures and verify accuracy of reported information for sample accounts.",
    "Sample business ownership changes to verify updated beneficial ownership certification and appropriate due diligence.",
    "Test information security controls and verify protection of business customer information in accordance with policies.",
    "Review account parameter change monitoring and verify enhanced verification procedures for high-risk changes.",
    "Sample high-risk business files to verify site visit documentation with appropriate observations and conclusions.",
    "Test unauthorized activity monitoring and verify alert investigation procedures and customer notification protocols.",
    "Review loan documentation procedures and sample files to verify completeness and accuracy of executed documents.",
    "Test non-documentary verification methods and verify procedures for resolving discrepancies in business information.",
    "Review early warning indicators and verify monitoring procedures to identify potential commercial borrower distress.",
    "Sample commercial loan files to verify proper maintenance of note and security agreement documentation.",
    "Review insurance monitoring procedures and sample files to verify tracking of coverage for commercial collateral.",
    "Test loan application system for red flags and verify enhanced review procedures for applications with warning indicators.",
    "Sample commercial loan portfolio to verify consistent application of risk rating criteria with appropriate documentation.",
    "Review unusual activity investigation procedures and verify documentation of resolution for sample alerts.",
    "Test transaction monitoring scenarios and verify appropriate thresholds for detecting high-risk patterns.",
    "Review loan disbursement procedures and sample transactions to verify appropriate controls and approvals.",
    "Sample customer complaints to verify appropriate resolution process and documentation of outcome.",
    "Test fraud detection system and verify investigation procedures for suspicious commercial account activities.",
    "Review annual review schedule and sample relationships to verify timely completion of required assessments.",
    "Sample high-risk customer designations to verify documented rationale and appropriate approval.",
    "Test monitoring system for insider abuse indicators and verify escalation procedures for suspicious activities.",
    "Review policy exception tracking system and verify trending analysis with appropriate management reporting.",
    "Sample new account approvals to verify appropriate level of review based on risk assessment.",
    "Test loan application procedures to verify controls for identifying potential straw borrowers.",
    "Review transaction limit setting procedures and verify appropriate approval for limit increases.",
    "Sample customer risk ratings to verify consistent application of methodology with appropriate documentation.",
    "Test covenant compliance monitoring system and verify timely identification and reporting of violations.",
    "Sample commercial collateral to verify timely updates to valuations in accordance with policy requirements.",
    "Review entity verification procedures and sample files to verify consistent validation of business existence.",
    "Test transaction monitoring for structuring patterns and verify investigation procedures for suspicious activities.",
    "Sample beneficial ownership certifications to verify timely renewal in accordance with trigger event policy.",
    "Review enhanced due diligence schedule and verify timely completion of reviews for high-risk customers.",
    "Test transaction pattern monitoring and verify alert generation for significant changes in account activity.",
    "Review dormant account procedures and verify appropriate monitoring and notification protocols.",
    "Sample loan portfolio to verify concentration risk analysis with appropriate limits and exception approvals.",
    "Review geographic risk assessment and verify enhanced due diligence for businesses in high-risk locations.",
    "Sample rate lock commitments to verify appropriate documentation and approval of terms.",
    "Review monitoring parameter setting methodology and verify appropriate calibration based on customer risk.",
    "Test relationship identification system and verify aggregation of related commercial credits for risk assessment.",
    "Sample loan servicing transfers to verify appropriate documentation and customer notification.",
    "Review OFAC screening documentation and verify retention of search results and resolution of potential matches.",
    "Test loan fraud detection procedures and verify enhanced review for applications with fraud indicators.",
    "Sample loan modifications to verify appropriate documentation and approval of changed terms.",
    "Review privacy notification procedures and verify delivery to business customers at account opening and annually.",
    "Sample complex business structures to verify enhanced due diligence and visual documentation of ownership.",
    "Review loan file documentation standards and verify consistent application across commercial lending areas.",
    "Sample CIP exemptions to verify appropriate justification and senior level approval documentation.",
    "Review interest rate swap procedures and verify suitability assessment documentation for commercial borrowers.",
    "Test maturity tracking system and verify appropriate notification and renewal procedures for maturing loans.",
    "Sample high-risk customers to verify documentation of enhanced monitoring triggers and appropriate surveillance.",
    "Review underwriting exception tracking and verify appropriate approval and risk mitigation for identified weaknesses.",
    "Sample cash handling limits to verify appropriate setting methodology and approval for limit increases.",
    "Review loan officer authority matrix and verify approval within authorized limits for sample transactions.",
    "Test OFAC screening procedures for international transactions and verify resolution documentation for potential matches.",
    "Sample secured loans to verify timely and accurate perfection of security interests with appropriate documentation.",
    "Review ongoing due diligence schedule and verify completion of required reviews within established timeframes.",
    "Test collateral monitoring system and verify timely identification and resolution of potential deficiencies.",
    "Sample wire transfers to verify enhanced verification procedures for high-risk or unusual transactions.",
    "Review risk rating override procedures and verify appropriate justification and approval documentation.",
    "Test early warning system and verify identification of negative trends with appropriate relationship strategy.",
    "Sample remote deposit capture users to verify appropriate limit setting methodology and periodic review.",
    "Review covenant testing procedures and verify consistent methodology for calculating compliance metrics.",
    "Test policy compliance monitoring and verify identification and resolution of potential violations.",
    "Review currency transaction aggregation procedures and verify proper identification of related transactions.",
    "Sample loans with guarantors to verify appropriate financial analysis and periodic updates.",
    "Test loan documentation exception tracking and verify timely resolution with appropriate reporting.",
    "Review identity verification procedures and verify risk-based approach for different business types.",
    "Sample loan pricing to verify consistent application of methodology with appropriate exception documentation.",
    "Test loan application review procedures to verify enhanced scrutiny for potential misrepresentation.",
    "Review high-risk transaction review procedures and verify appropriate documentation of investigative findings.",
    "Sample portfolio stress testing to verify appropriate methodology and incorporation of results in risk management.",
    "Test transaction screening for export controls and verify enhanced review procedures for high-risk activities.",
    "Sample commercial properties to verify flood insurance monitoring with appropriate coverage verification.",
    "Review enhanced due diligence approval process and verify appropriate senior level involvement for high-risk customers.",
    "Sample construction loans to verify draw request review procedures and appropriate inspection documentation.",
    "Test transaction monitoring scenarios and verify appropriate alert thresholds based on customer risk profiles.",
    "Sample loan participations to verify appropriate pre-purchase due diligence and ongoing monitoring.",
    "Review reputation risk assessment procedures and verify incorporation in customer acceptance decisions.",
    "Test transaction monitoring calibration process and verify periodic review and adjustment of parameters.",
    "Sample loan committee minutes to verify appropriate documentation of discussion and approval rationale.",
    "Test payment application procedures and verify accurate posting of commercial loan payments.",
    "Review customer certification process and verify appropriate follow-up for incomplete or missing information.",
    "Sample debt service calculations to verify consistent methodology and appropriate use in underwriting decisions.",
    "Test fraud detection system and verify investigation procedures for suspicious account activities.",
    "Review transaction documentation standards and verify consistent application for high-risk activities.",
    "Sample collateral inspections to verify completion in accordance with established frequency requirements.",
    "Test covenant calculation procedures and verify accurate determination of compliance status.",
    "Review deceased account holder procedures and verify appropriate controls for business continuity.",
    "Sample loan officer portfolios to verify comprehensive risk assessment with appropriate action plans.",
    "Test loan documentation review procedures and verify identification and resolution of deficiencies.",
    "Review high-risk transaction approval process and verify appropriate level of authority based on risk.",
    "Sample policy compliance testing to verify comprehensive coverage of key requirements and appropriate remediation.",
    "Test early warning system for customer deterioration and verify appropriate relationship strategy development.",
    "Sample beneficial ownership verifications to verify consistent validation methodology and appropriate documentation.",
    "Review commitment tracking system and verify accurate reporting of pipeline and exposure levels.",
    "Test loan stacking identification procedures and verify enhanced review for customers with multiple obligations.",
    "Sample transaction testing methodology and verify statistical validity of sample selection and coverage.",
    "Review environmental assessment procedures and verify appropriate scope based on property type and use.",
    "Test document fraud detection procedures and verify enhanced scrutiny for potentially altered information.",
    "Sample periodic risk reassessments to verify comprehensive review of relationship risk with appropriate updates.",
    "Review exception approval authority matrix and verify appropriate level of approval based on exception type.",
    "Test online banking fraud controls and verify monitoring procedures for unusual digital account activity.",
    "Sample subpoena responses to verify appropriate legal review and documentation of information provided.",
    "Review collateral release procedures and verify appropriate authorization and documentation of approvals.",
    "Test concentration risk monitoring and verify appropriate limits and exception approvals for concentrated exposures."
]
