small_business_banking__regulatory_findings__corrective_action_description = [
    "Conduct comprehensive review of all loan files from Q2 2023 to identify and correct documentation deficiencies.",
    "Implement automated beneficial ownership data collection process for all new accounts and conduct remediation for identified gaps.",
    "Update CTR filing procedures and provide refresher training to all frontline staff on transaction monitoring requirements.",
    "Enhance risk-based monitoring system for high-risk accounts with quarterly review schedule and documented oversight.",
    "Revise adverse action notice process to include automated timing alerts and weekly compliance reviews of declined applications.",
    "Implement enhanced income verification procedures for self-employed business owners with dual review requirement.",
    "Update HMDA data collection system to include all required fields and conduct lookback review of affected applications.",
    "Revise CIP procedures to align with current FinCEN guidance and provide staff training on updated requirements.",
    "Conduct fair lending training for all small business lending staff and implement second review process for decline decisions.",
    "Enhance CRA data collection to properly identify businesses in LMI census tracts and correct historical reporting errors.",
    "Revise risk-rating methodology for restaurant industry loans and conduct portfolio review to apply updated criteria.",
    "Implement enhanced documentation requirements for mixed-use property loans with clear guidelines for business purpose verification.",
    "Establish automated tracking system for beneficial ownership certifications with alerts for required renewals.",
    "Develop consistent exception policy application process with required documentation and approval levels.",
    "Enhance monitoring of insider loans with quarterly board reporting and independent review of terms and conditions.",
    "Implement enhanced transaction monitoring system to identify potential structuring and conduct lookback review.",
    "Revise collateral valuation procedures for commercial real estate with required documentation standards.",
    "Develop comprehensive disclosure checklist for adjustable-rate commercial loans and implement quality control review.",
    "Enhance CDD procedures to include PEP screening for all business owners and establish ongoing monitoring process.",
    "Implement standardized rate exception justification documentation with required approval hierarchy.",
    "Develop connected borrower identification methodology and review existing portfolio for concentration risk.",
    "Update commercial flood hazard determination procedures and provide staff training on notification requirements.",
    "Revise business tax return analysis procedures with standardized documentation requirements and second-level review.",
    "Implement enhanced verification procedures for online-only businesses including third-party validation sources.",
    "Update business size classification methodology to align with current regulatory definitions and review affected accounts.",
    "Conduct comprehensive file review to identify missing documentation and establish remediation plan with deadlines.",
    "Implement risk-based monitoring program for high-risk merchant categories with quarterly activity reviews.",
    "Develop standardized documentation requirements for underwriting exceptions with appropriate approval levels.",
    "Implement automated tracking system for adverse action notices with quality control review process.",
    "Enhance beneficial owner identification procedures for complex business structures with specialized review team.",
    "Standardize DSCR calculation methodology across all business units with documentation requirements.",
    "Develop specific procedures for identification and monitoring of marijuana-related businesses with enhanced due diligence.",
    "Implement compliant E-Sign process for digital business account opening with audit trail and verification controls.",
    "Establish enhanced due diligence review schedule for business customers with documentation requirements.",
    "Revise risk classification matrix for cash-intensive businesses with enhanced monitoring parameters.",
    "Implement automated tracking for beneficial ownership certification with exception reporting and follow-up procedures.",
    "Enhance monitoring system for cross-border wire transfers with risk-based review thresholds and documentation requirements.",
    "Standardize NAICS code collection process across all business units with validation procedures.",
    "Implement documented process for credit score overrides with required justification and approval levels.",
    "Develop enhanced procedures for identifying shell companies during onboarding with red flag indicators.",
    "Establish risk-based site visit schedule for high-risk business customers with documentation requirements.",
    "Implement enhanced procedures for verifying source of funds for large deposits with documentation standards.",
    "Standardize customer due diligence procedures across all business units with quality control review.",
    "Develop standardized documentation requirements for exception approvals with appropriate authority levels.",
    "Implement enhanced PEP screening and monitoring procedures with periodic review requirements.",
    "Establish documented BSA officer review process for high-risk customers with approval documentation standards.",
    "Enhance suspicious activity monitoring with clear escalation procedures and documentation requirements.",
    "Implement standardized collateral inspection procedures for asset-based loans with documentation requirements.",
    "Standardize application of credit score requirements with clear exception criteria and approval documentation.",
    "Conduct comprehensive fraud identification training for frontline staff with periodic refresher requirements.",
    "Implement enhanced address verification procedures for online applications with third-party validation.",
    "Establish clear documentation standards for policy exceptions on high-risk accounts with senior approval requirements.",
    "Implement risk-based ongoing monitoring program for business customers with activity review schedules.",
    "Develop standardized loan purpose documentation requirements with second-level review for certain categories.",
    "Implement enhanced TIN verification procedures with exception tracking and follow-up requirements.",
    "Establish risk-based site visit schedule with standardized documentation requirements for unusual operations.",
    "Develop comprehensive EDD procedures for high-risk industries with periodic review requirements.",
    "Implement enhanced revenue validation procedures for business applicants with documentation standards.",
    "Standardize documentation retention requirements across all business units with quality control reviews.",
    "Establish formalized fair lending second review process with documentation requirements and periodic audits.",
    "Develop comprehensive risk assessment methodology for new business products with regulatory compliance review.",
    "Implement standardized collateral valuation procedures with documentation requirements and independent review.",
    "Enhance cash transaction monitoring system to properly identify aggregate transactions with automated alerts.",
    "Standardize pricing exception process with required justification, approval levels, and documentation standards.",
    "Implement negative news screening for business customers with defined review and escalation procedures.",
    "Standardize documentation of denial reasons with second-level review and quality control process.",
    "Establish multi-level approval process for high-risk business accounts with enhanced documentation requirements.",
    "Implement enhanced monitoring for high-risk industry customers with periodic activity reviews and documentation.",
    "Conduct remediation project to collect beneficial ownership information for customers with trigger events.",
    "Standardize business existence verification procedures with required documentation and validation sources.",
    "Develop enhanced procedures for identification of HIDTA businesses with appropriate monitoring protocols.",
    "Implement expected activity profile development for all business accounts with periodic comparison reviews.",
    "Establish clear documentation standards for credit committee approval of policy exceptions with tracking system.",
    "Enhance international wire monitoring system with risk-based review thresholds and documentation requirements.",
    "Implement comprehensive ID validation procedures for business owners with authentication controls.",
    "Standardize documentation requirements across similar business types with quality control review process.",
    "Conduct comprehensive training on commercial flood insurance requirements with knowledge assessment.",
    "Implement enhanced business structure verification procedures with required documentation standards.",
    "Develop automated loan covenant monitoring system with exception reporting and follow-up procedures.",
    "Enhance procedures for identifying director-related interests with periodic certification and review.",
    "Implement standardized risk-based pricing model for small business loans with exception documentation requirements.",
    "Establish construction loan inspection procedures with documentation requirements and quality control review.",
    "Implement enhanced income verification procedures for business guarantors with required documentation standards.",
    "Develop comprehensive appraisal validation procedures with independence requirements and documentation standards.",
    "Standardize financial statement collection requirements for commercial borrowers with tracking and follow-up.",
    "Implement environmental assessment requirement for commercial properties with documentation standards.",
    "Enhance CRA assessment area identification procedures with geocoding validation and periodic review.",
    "Develop comprehensive monitoring procedures for high-risk payment processors with enhanced due diligence.",
    "Standardize credit analysis standards across all business units with quality control review process.",
    "Implement clear documentation requirements for loan approval authority with periodic compliance review.",
    "Enhance procedures for identifying and documenting beneficial ownership changes with verification requirements.",
    "Develop cross-product risk monitoring program with holistic customer relationship review.",
    "Standardize enhanced due diligence procedures for high-risk customers with documentation requirements.",
    "Implement periodic review schedule for high-risk customers with comprehensive documentation standards.",
    "Enhance procedures for identifying affiliated business entities with relationship mapping and documentation.",
    "Develop fair lending monitoring system for declined applications with statistical analysis and reporting.",
    "Standardize cash flow analysis methodologies across all business units with documentation requirements.",
    "Implement tax lien search requirement for all business borrowers with documentation standards.",
    "Enhance transaction monitoring system to identify potential structuring with investigation procedures.",
    "Develop comprehensive monitoring procedures for online business account activity with risk-based review.",
    "Standardize site visit documentation for new business customers with required elements and review process.",
    "Implement identity verification procedures for all authorized signers with documentation requirements.",
    "Enhance OFAC screening procedures with documentation requirements and periodic independent testing.",
    "Develop comprehensive business license validation procedures with periodic renewal verification.",
    "Implement standardized global cash flow analysis for related businesses with documentation requirements.",
    "Establish regulatory review process for new business products with compliance sign-off and documentation.",
    "Develop enhanced CRA impact analysis procedures for branch closures with community feedback component.",
    "Implement comprehensive third-party vendor compliance validation with documentation requirements.",
    "Standardize collateral perfection verification procedures with documentation and independent review.",
    "Implement automated tracking system for flood determinations on commercial properties with renewal alerts.",
    "Enhance ACH monitoring for commercial customers with risk-based review thresholds and documentation.",
    "Develop comprehensive verification procedures for business purpose loans with required documentation.",
    "Standardize customer risk rating model application across all business units with periodic validation.",
    "Implement compliance review process for all marketing materials with documentation and approval requirements.",
    "Enhance customer due diligence to identify high-risk geographic locations with appropriate controls.",
    "Develop specific procedures for identifying and monitoring third-party payment processors with enhanced due diligence.",
    "Standardize account monitoring procedures for money service businesses with documentation requirements.",
    "Implement comprehensive BSA/AML risk assessment for all business products with periodic review.",
    "Enhance CIP procedures to properly identify related customer relationships with documentation requirements.",
    "Develop loan proceeds utilization monitoring program with verification procedures and documentation.",
    "Standardize property inspection procedures for commercial real estate with documentation requirements.",
    "Implement annual review process for all revolving credit facilities with standardized analysis and documentation.",
    "Enhance flood hazard area identification for commercial loans with automated monitoring and notification system.",
    "Develop comprehensive verification procedures for commercial insurance coverage with renewal tracking.",
    "Standardize credit policy application across all business types with exception tracking and reporting.",
    "Implement legal review requirement for non-standard loan terms with documentation standards.",
    "Enhance concentration risk monitoring by industry sector with board reporting and limit structures.",
    "Develop comprehensive agricultural income verification procedures with specialized documentation requirements.",
    "Standardize construction draw inspection procedures with documentation requirements and approval process.",
    "Implement enhanced lien position verification procedures with title update requirements.",
    "Develop comprehensive documentation standards for cross-collateralization with legal review requirement.",
    "Implement troubled debt restructuring identification procedures with appropriate approval and documentation.",
    "Standardize documentation requirements for cash equity injection with verification procedures.",
    "Develop business continuity verification process for key customers with periodic assessment.",
    "Implement enhanced due diligence procedures for non-bank financial institutions with monitoring requirements.",
    "Enhance verification procedures for international business entities with specialized documentation standards.",
    "Develop comprehensive exception tracking and reporting system with trend analysis and root cause identification.",
    "Implement enhanced covenant compliance verification procedures with documentation and follow-up requirements.",
    "Develop risk-based transaction monitoring system with clear identification of high-risk transactions.",
    "Enhance import/export documentation verification procedures with specialized training and review requirements.",
    "Standardize customer identification procedures across all business units with quality control review.",
    "Implement business credit bureau reporting requirement with documentation and analysis standards.",
    "Develop comprehensive documentation standards for loan policy exceptions with appropriate approval levels.",
    "Implement business customer complaint monitoring system with pattern identification and root cause analysis.",
    "Standardize guarantor financial analysis procedures with documentation requirements and periodic updates.",
    "Develop enhanced verification procedures for minority-owned business status with documentation standards.",
    "Implement comprehensive beneficial owner identification for trust-owned businesses with specialized review.",
    "Enhance startup business projection validation with industry benchmarking and sensitivity analysis.",
    "Standardize loan pricing exception approval process with required documentation and justification.",
    "Implement comprehensive regulatory compliance review schedule with documentation and corrective action tracking.",
    "Develop enhanced monitoring system for high-risk transaction patterns with investigation procedures.",
    "Implement standardized business reference verification procedures with documentation requirements.",
    "Standardize commercial appraisal review process with independence requirements and documentation standards.",
    "Develop comprehensive periodic review program for business customers with risk-based frequency and scope.",
    "Implement enhanced monitoring for potential elder financial exploitation with alert parameters and investigation procedures.",
    "Develop comprehensive validation procedures for construction budget feasibility with independent review.",
    "Standardize loan disbursement control procedures with required approvals and documentation.",
    "Implement enhanced certification procedures for legal entity customers with verification requirements.",
    "Develop risk-based monitoring program for cash-intensive businesses with transaction pattern analysis.",
    "Enhance procedures for verifying and documenting business ownership changes with appropriate approvals.",
    "Standardize documentation requirements for loan participation agreements with legal review and approval.",
    "Implement comprehensive approval process for business banking relationships with appropriate risk assessment.",
    "Develop UDAAP risk assessment methodology for business products with documentation and mitigation strategies.",
    "Enhance monitoring procedures for high-risk correspondent relationships with periodic review requirements.",
    "Standardize high-risk customer approval process with multi-level review and documentation requirements.",
    "Implement comprehensive beneficial ownership structure documentation with visualization requirements.",
    "Develop enhanced procedures for identifying businesses with increased money laundering risk with appropriate controls.",
    "Implement monitoring system for third-party payment activity with risk-based review thresholds.",
    "Standardize watch list screening procedures across all business units with documentation requirements.",
    "Develop risk-based schedule for customer due diligence refresh reviews with documentation standards.",
    "Implement comprehensive documentation of business customer risk assessment methodology with periodic validation.",
    "Enhance verification procedures for international trade documentation with specialized training.",
    "Standardize KYC procedures across similar business types with quality control review process.",
    "Develop enhanced monitoring program for high-risk customers with expanded scope and frequency.",
    "Implement comprehensive procedures for identifying indirect beneficial ownership with appropriate documentation.",
    "Enhance monitoring of remote deposit capture activity with risk-based review thresholds and documentation.",
    "Standardize commercial loan stress testing methodology with documentation requirements and periodic validation.",
    "Implement comprehensive environmental risk assessment procedures with appropriate expertise and documentation.",
    "Develop enhanced procedures for identifying prohibited business types with screening methodology.",
    "Implement pattern monitoring for commercial deposit accounts with baseline comparison and alert thresholds.",
    "Standardize suspicious activity investigation documentation with clear findings and supporting evidence.",
    "Develop comprehensive documentation standards for loan committee deliberations with voting records.",
    "Implement enhanced OFAC screening for international business relationships with periodic re-screening.",
    "Enhance commercial property value verification procedures with independent validation requirements.",
    "Standardize high-risk business monitoring procedures across all business units with documentation standards.",
    "Develop comprehensive exception approval documentation with appropriate authority levels and justification.",
    "Implement enhanced PEP identification procedures for business owners with appropriate controls.",
    "Enhance validation procedures for commercial lease agreements with existence verification.",
    "Standardize fair lending second review decision documentation with appropriate analysis and rationale.",
    "Develop comprehensive verification procedures for commercial insurance coverage with renewal tracking.",
    "Implement enhanced monitoring for cross-border transactions with documentation and investigation standards.",
    "Develop risk assessment methodology for account closures with appropriate documentation and approval.",
    "Standardize high-risk industry determination criteria with periodic review and validation.",
    "Implement enhanced verification procedures for corporate resolution validity with legal review when appropriate.",
    "Develop monitoring procedures for related party transactions with identification methodology and documentation.",
    "Implement comprehensive monitoring of business account activity against expected patterns with documentation.",
    "Standardize CDD procedures for business customers across all channels with quality control review."
]
