small_business_banking__beneficial_owner_verification__notes = [
  "Beneficial owner verified as co-founder and CEO with 51% ownership stake confirmed through articles of incorporation and shareholder agreement.",
  "Subject verified as trustee of family trust owning 35% of business. Trust documentation reviewed confirming grantor and beneficiaries.",
  "Ownership percentage verified through review of operating agreement and Schedule K-1 showing consistent 25% ownership interest.",
  "Individual serves as control person without ownership interest as confirmed through corporate resolution designating signatory authority.",
  "Subject is both beneficial owner (30%) and designated control person with signatory authority per corporate resolution and bylaws.",
  "Confirmed 25% ownership through partnership agreement and tax documentation. No other reportable ownership interests identified.",
  "Individual has indirect ownership through holding company structure requiring additional verification of ultimate beneficial ownership.",
  "Subject verified as minority owner with 10% direct interest, below reporting threshold but included due to control person status.",
  "Ownership documentation shows recent transfer of shares increasing ownership from 15% to 30%, triggering beneficial owner reporting requirement.",
  "Individual identified through business credit report as guarantor but corporate documents confirm no ownership stake or control status.",
  "Beneficial ownership certification completed with notarized signature and supporting documentation confirming 40% ownership interest.",
  "Subject verified as senior officer with significant control but ownership percentage below reporting threshold at 15%.",
  "Foreign national ownership verified with passport documentation and appropriate certification of ownership percentage at 35%.",
  "Individual recently assumed control person status through corporate resolution while maintaining 25% ownership interest.",
  "Beneficial owner verified through multiple sources including corporate resolution, tax filings, and secretary of state records.",
  "Subject confirmed as trustee with control of voting shares representing 45% ownership as documented in trust agreement.",
  "Ownership verification includes review of stock transfer documentation showing recent acquisition of additional 10% interest.",
  "Individual verified as legal representative with proxy voting authority but no direct ownership interest in entity.",
  "Beneficial owner documentation updated following buyout of minority partner increasing ownership from 20% to 35%.",
  "Subject confirmed as both board chairperson and 25% owner through corporate bylaws and stock certificate verification.",
  "Multiple verification sources confirm consistent ownership information with 25% direct interest and no indirect ownership.",
  "Individual identified as PEP with 25% ownership interest requiring enhanced due diligence and senior management approval.",
  "Ownership verified through operating agreement showing equal 25% distribution among four founding members.",
  "Subject confirmed as manager-member with both 30% ownership interest and operational control of LLC.",
  "Beneficial ownership verification included review of stock purchase agreement documenting recent acquisition of 25% interest.",
  "Individual verified as trustee of irrevocable trust with controlling interest and documented beneficial ownership structure.",
  "Complex ownership structure involving multiple entities with subject as ultimate beneficial owner of 35% interest.",
  "Subject confirmed as authorized officer with no ownership interest but significant control per corporate resolution.",
  "Stock certificate verification confirms 25% ownership consistent with beneficial ownership certification provided.",
  "Individual owns 15% directly and additional 15% through family holding company meeting reporting threshold.",
  "Beneficial ownership documentation consistent with business tax returns showing distribution of profits aligned with stated percentages.",
  "Subject verified through corporate bylaws as both CEO and 30% owner with additional voting proxy from minority owner.",
  "Ownership interest verified through multiple sources with consistent information regarding 25% ownership stake.",
  "Individual control person status documented through corporate resolution with limited ownership interest below threshold.",
  "Beneficial owner verification includes confirmation of indirect ownership through intermediate holding company structure.",
  "Subject documented as both managing partner and 40% owner through partnership agreement and tax filings.",
  "Recent corporate restructuring changed ownership percentages requiring updated beneficial ownership certification.",
  "Individual verified as having 25% ownership through stock certificates and shareholder registry review.",
  "Certified copy of corporate minutes documents election of subject as control person with signatory authority.",
  "Beneficial owner confirmed through operating agreement and tax documentation showing consistent 30% ownership.",
  "Subject verified as having ownership through family trust arrangement with appropriate trust documentation reviewed.",
  "Complex organizational structure mapped with individual confirmed as 25% ultimate beneficial owner.",
  "Corporate resolution designates individual as authorized person with full signatory authority despite minority ownership.",
  "Beneficial owner verification included review of purchase agreement documenting recent acquisition of controlling interest.",
  "Subject confirmed as both president and 35% shareholder through corporate documentation and state filings.",
  "Verification of ownership percentage consistent across multiple sources including tax returns and corporate records.",
  "Individual identified as beneficial owner through indirect ownership meeting 25% aggregate threshold.",
  "Subject serves as control person with limited ownership interest as documented in corporate governance records.",
  "Multiple layers of ownership traced to confirm individual as reportable beneficial owner with 30% ultimate interest.",
  "Subject verified as managing member with both operational control and 45% ownership interest per operating agreement.",
  "Corporate documentation shows individual as minority owner with significant control through voting agreement arrangements.",
  "Beneficial ownership certification verified against multiple sources confirming accuracy of reported 25% ownership.",
  "Subject confirmed as trustee with beneficial interest through grantor trust arrangement documented in trust agreement.",
  "Ownership structure includes individual with reportable interest through multiple related business entities.",
  "Subject verified as Chief Financial Officer with signatory authority but ownership below reporting threshold.",
  "Beneficial owner documentation updated following transfer of shares from retiring partner increasing interest to 35%.",
  "Individual confirmed as controlling officer through corporate resolution with ownership interest verified at 25%.",
  "Ownership verification included review of subscription agreement documenting initial 30% equity investment.",
  "Subject verified through secretary of state filings as registered agent and 25% owner of business entity.",
  "Beneficial owner certification cross-referenced with tax filings confirming consistent reporting of ownership percentage.",
  "Individual documented as having both direct and indirect ownership totaling 40% through related entities.",
  "Subject confirmed as senior executive with limited ownership but significant control through operational authority.",
  "Multiple source verification confirms individual as 25% owner consistent with beneficial ownership certification.",
  "Subject identified with complex ownership structure requiring mapping of intermediate entities to confirm reportable interest.",
  "Beneficial owner verification supported by stock transfer documentation showing recent acquisition of shares.",
  "Individual confirmed as having significant control as board chairperson with 25% ownership interest.",
  "Ownership verification through partnership documentation showing capital and profit distribution percentages.",
  "Subject documented as beneficial owner through family trust arrangement with certification from trustee.",
  "Corporate resolution identifies individual as authorized person with full signatory authority and 30% ownership.",
  "Beneficial owner confirmation includes verification of recently modified operating agreement showing current interests.",
  "Subject verified as having equal 25% ownership with other founders as documented in corporate charter.",
  "Multiple documentation sources confirm consistent ownership information with no discrepancies noted.",
  "Individual identified with indirect ownership through intermediate holding company requiring additional verification.",
  "Subject confirmed as managing partner with both operational control and 35% ownership interest.",
  "Business tax return Schedule K-1 review confirms ownership percentages consistent with certification provided.",
  "Individual verified as senior officer with significant control and 25% ownership meeting reporting threshold.",
  "Beneficial ownership traced through complex structure with appropriate documentation of ultimate ownership percentages.",
  "Subject confirmed as both authorized signatory and 25% owner through corporate documentation review.",
  "Stock certificate verification confirms ownership percentage consistent with beneficial ownership certification.",
  "Individual documented as partial owner through operating agreement with additional control through management role.",
  "Subject verified through multiple sources as 25% owner with no discrepancies in reported information.",
  "Corporate minutes document selection of individual as control person with significant operational authority.",
  "Beneficial owner confirmed through share registry and stock transfer documentation showing 30% ownership.",
  "Subject documented as trustee with control over significant ownership without direct beneficial interest.",
  "Ownership verification completed through review of partnership agreement confirming profit distribution percentages.",
  "Individual verified as having reportable ownership interest through combination of direct and family holdings.",
  "Subject confirmed as CEO with both operational control and 25% ownership meeting reporting threshold.",
  "Beneficial ownership certification verified against corporate documentation showing consistent information.",
  "Individual identified as authorized officer through corporate resolution with limited ownership interest.",
  "Subject confirmed as equal partner in business with 25% ownership through partnership agreement verification.",
  "Corporate documentation shows individual as significant minority owner with controlling interest through voting trust.",
  "Beneficial owner verification included tracing ownership through multiple related entities to ultimate interest.",
  "Subject verified as having recently acquired additional interest through documented stock purchase transaction.",
  "Ownership confirmation through operating agreement showing distribution of membership interests and voting rights.",
  "Individual documented as control person with limited ownership but significant authority through corporate position.",
  "Subject verified through tax documentation and corporate records showing consistent 25% ownership interest.",
  "Beneficial owner identified through complex structure requiring additional documentation of ownership chain.",
  "Individual confirmed as senior executive with both operational authority and 35% ownership interest.",
  "Corporate records verification confirms ownership interest consistent with beneficial ownership certification.",
  "Subject documented as trust beneficiary with reportable ownership interest through trust arrangement.",
  "Ownership verification includes review of stock purchase agreement documenting acquisition of interest.",
  "Individual confirmed as authorized signatory through corporate resolution with 25% ownership interest.",
  "Subject verified through multiple sources with consistent information regarding ownership percentage.",
  "Beneficial owner documentation updated following corporate restructuring affecting ownership percentages.",
  "Individual verified as having significant control through management role with 25% ownership interest.",
  "Ownership confirmed through review of operating agreement showing distribution of membership interests.",
  "Subject documented as both officer and significant shareholder through corporate verification process.",
  "Beneficial owner certification cross-referenced with secretary of state filings showing consistent information.",
  "Individual verified through partnership agreement as having 25% capital interest meeting reporting threshold.",
  "Subject confirmed through stock certificate verification showing ownership consistent with certification.",
  "Complex ownership structure mapped to identify ultimate beneficial owners including subject with 30% interest.",
  "Individual documented as control person with operational authority through corporate governance documentation.",
  "Beneficial owner verification includes confirmation of ownership interest through tax filing documentation.",
  "Subject confirmed as managing member with both ownership interest and operational control of entity.",
  "Ownership verification through multiple sources shows consistent information regarding 25% interest.",
  "Individual identified as senior officer with significant control and reportable ownership percentage.",
  "Subject verified as trustee with control over voting shares representing beneficial ownership interest.",
  "Beneficial ownership documentation updated following transfer of shares from retiring business partner.",
  "Individual confirmed as authorized signatory through corporate resolution with 25% ownership interest.",
  "Ownership verification includes review of subscription agreement documenting initial equity investment.",
  "Subject documented as having indirect ownership through related entity requiring additional verification.",
  "Corporate records confirm individual as board member with significant influence and 25% ownership.",
  "Beneficial owner verified through operating agreement showing distribution of membership interests.",
  "Individual confirmed as having recently increased ownership percentage through documented transaction.",
  "Subject verified through multiple sources with consistent information regarding ownership structure.",
  "Ownership documentation shows individual as minority owner with significant control through position.",
  "Beneficial owner verification includes review of trust documentation confirming reportable interest.",
  "Individual confirmed as both operational manager and 30% owner through corporate documentation.",
  "Subject documented through stock transfer records showing acquisition of reportable ownership interest.",
  "Complex ownership structure requiring mapping of intermediate entities to confirm beneficial ownership.",
  "Individual verified as control person with significant operational authority and 25% ownership interest.",
  "Beneficial owner certification consistent with multiple verification sources showing 35% ownership.",
  "Subject confirmed as senior executive with both management authority and significant ownership stake.",
  "Ownership verification through tax documentation showing consistent profit distribution percentages.",
  "Individual documented as authorized person with signatory authority and 25% ownership interest.",
  "Subject verified through corporate minutes as appointed officer with significant control authority.",
  "Beneficial ownership traced through multiple entities with appropriate documentation of ultimate interest.",
  "Individual confirmed as equal partner with 25% ownership through partnership agreement verification.",
  "Subject documented as managing member with both operational control and ownership interest.",
  "Corporate documentation review confirms ownership percentage consistent with certification provided.",
  "Individual verified as director with significant influence and 25% ownership meeting reporting threshold.",
  "Beneficial owner identification included review of stock purchase documentation confirming interest.",
  "Subject confirmed through tax filings showing consistent ownership interest over multiple years.",
  "Individual documented as authorized signatory through corporate resolution with ownership verification.",
  "Complex organization structure mapped to confirm ultimate beneficial ownership percentages.",
  "Subject verified as having acquired reportable interest through recent business transaction.",
  "Ownership confirmation through review of operating agreement and membership interest certificates.",
  "Individual documented as control person through corporate governance records with ownership verification.",
  "Beneficial owner certification cross-referenced with business registration documents showing consistency.",
  "Subject confirmed as having indirect ownership through family holding company structure.",
  "Corporate documentation shows individual as significant minority owner with additional control rights.",
  "Ownership verification through multiple sources shows no discrepancies in reported information.",
  "Individual identified as both operational manager and 25% owner through documentation review.",
  "Subject verified through stock certificate examination confirming ownership percentage reported.",
  "Beneficial owner documented through partnership agreement showing profit and loss allocation percentages.",
  "Individual confirmed as authorized officer with significant control and 30% ownership interest.",
  "Ownership verification includes review of recent corporate transactions affecting ownership structure.",
  "Subject documented as trust beneficiary with reportable ownership interest requiring verification.",
  "Corporate minutes confirm appointment of individual as control person with significant authority.",
  "Beneficial owner verification completed with multiple source confirmation of reported percentage.",
  "Individual identified through business credit report with ownership verified through corporate records.",
  "Subject confirmed as having equal ownership share with other founders through corporate documentation.",
  "Ownership structure includes individual with both direct interest and indirect ownership through related entity.",
  "Corporate documentation verification confirms individual as senior officer with 25% ownership interest.",
  "Beneficial owner certification verified against tax filings showing consistent reporting of percentage.",
  "Individual documented as managing partner with both operational control and ownership interest.",
  "Subject verified through multiple sources with consistent information regarding 25% ownership stake.",
  "Corporate structure reviewed to identify all reportable beneficial owners including subject with 30% interest.",
  "Individual confirmed as board chairperson with significant influence and 25% ownership interest.",
  "Beneficial ownership documentation updated following corporate restructuring affecting percentages.",
  "Subject verified as having acquired additional interest through recent stock purchase transaction.",
  "Ownership confirmation through review of subscription agreement and corporate share registry.",
  "Individual documented as control person with operational authority through corporate resolution.",
  "Complex ownership verification completed with mapping of intermediate entities to ultimate beneficial owners.",
  "Subject confirmed as both officer and significant shareholder through corporate documentation review.",
  "Beneficial owner verification included review of trust documentation confirming ownership structure.",
  "Individual verified as authorized signatory through corporate resolution with ownership confirmation.",
  "Ownership documentation reviewed showing consistent information across multiple verification sources.",
  "Subject documented as managing member with both operational control and ownership interest.",
  "Corporate records confirm individual as director with significant influence and 30% ownership stake.",
  "Beneficial owner certification verified against partnership agreement showing consistent percentages.",
  "Individual confirmed as senior executive with management authority and 25% ownership interest."
]
