small_business_banking__credit_decisions__exception_reason = [
  "Strong deposit relationship with average balances exceeding $250,000 for past 24 months mitigates debt service coverage ratio below guideline.",
  "Personal guarantor's substantial outside income and liquid assets offset business cash flow shortfall with secondary repayment source.",
  "Recent one-time expense for facility upgrade affected current year DSCR; normalized cash flow excluding this item meets policy guideline.",
  "Established client relationship since 2015 with perfect payment history on three previous loans demonstrates strong repayment behavior.",
  "Loan purpose to acquire key competitor strengthens market position and eliminates primary pricing pressure affecting margins.",
  "Collateral value exceeding 200% of loan amount compensates for business debt service coverage ratio slightly below minimum guideline.",
  "Industry-specific seasonality temporarily affects current financial ratios; twelve-month average performance meets all policy guidelines.",
  "Highly specialized business with documented barriers to entry and limited competition justifies debt-to-worth ratio exception.",
  "Principal owner's strong personal balance sheet with $1.2M in liquid assets provides substantial secondary repayment source.",
  "Transitional financing during ownership change with demonstrated management expertise of acquiring principal justifies policy exception.",
  "Extensive banking relationship across multiple business entities and personal accounts with combined deposits exceeding $500,000.",
  "Bridge financing with committed takeout from SBA 504 loan program mitigates interim loan-to-value ratio exceeding guideline.",
  "Specialized medical practice with contracted insurance reimbursements providing stable revenue stream justifies higher leverage.",
  "Predictable government contract revenue with 3-year renewal option substantiates cash flow projections despite limited operating history.",
  "Loan request supports acquisition of major client that stabilizes revenue base and eliminates business development expense.",
  "Temporary working capital shortage due to extraordinary growth of 45% in past 12 months with confirmed orders supporting expansion.",
  "Longstanding client relationship with owners' combined personal deposits exceeding $350,000 and perfect payment history.",
  "Debt service coverage ratio calculation affected by accelerated depreciation; cash flow ratio exceeds 1.5:1 on adjusted basis.",
  "Additional collateral in form of marketable securities valued at 50% of loan amount supplements business collateral shortfall.",
  "Strategic financing to secure essential patent rights critical to business model justifies policy exception on operating history.",
  "Conservative business valuation methodology results in artificially high loan-to-value ratio not reflecting true enterprise value.",
  "Highly profitable professional services firm with 28% net margin despite debt-to-worth ratio exceeding standard guideline.",
  "Temporary inventory buildup for confirmed seasonal order affecting current ratio; historical working capital management is strong.",
  "Principal's industry expertise with 25+ years of successful experience in same field mitigates limited business operating history.",
  "Loan purpose to fulfill major new contract with Fortune 500 client justifies temporary increase in leverage beyond guidelines.",
  "Strong global cash flow from multiple related entities under common ownership supports debt service despite single entity shortfall.",
  "Temporary cash flow impact from recent technology upgrade with demonstrated efficiency improvements already materializing.",
  "Specialized manufacturing business with proprietary processes and products justifies higher leverage than standard policy.",
  "Franchise business with corporate parent support and territory exclusivity mitigates risk despite higher leverage than guideline.",
  "Personal guarantor's substantial real estate holdings with $3.2M equity provides significant secondary repayment source.",
  "Recent acquisition of competitor's assets at below market value creates strong collateral position despite limited operating history.",
  "Longstanding client relationship since 2008 with impeccable payment history across multiple loans and deposit accounts.",
  "Loan purpose to refinance higher-interest debt improves cash flow by $3,500 monthly despite debt service coverage below guideline.",
  "Current ratio affected by inventory purchase at year-end to capture vendor discount; pro forma working capital meets guideline.",
  "Business model with 80% recurring revenue from subscriptions provides stable cash flow despite higher leverage than standard policy.",
  "Strong deposit relationship with daily average balance exceeding $175,000 and significant treasury management services.",
  "Committed capital contribution from equity investors provides additional cash flow support beyond projected debt service needs.",
  "Loan purpose to acquire specialized equipment not available from other sources justifies loan-to-value ratio exception.",
  "Highly seasonal business with strong peak period performance offsetting annual cash flow ratio below standard guideline.",
  "Professional practice transition loan with senior doctor remaining for 24-month mentoring period mitigates experience risk.",
  "Principal's proven track record of successfully developing and selling three previous similar businesses in same industry.",
  "Temporary impact on financial performance due to recent facilities expansion with demonstrable capacity increase of 60%.",
  "Debt-to-worth ratio exception mitigated by substantial off-balance sheet real estate assets owned by business principals.",
  "Collateral exception justified by specialized equipment with strong secondary market in current supply-constrained environment.",
  "Recently signed long-term supply contract with minimum purchase requirements provides stability despite limited operating history.",
  "Personal guarantor maintains substantial investment portfolio valued at 300% of loan request as additional repayment source.",
  "Temporary cash flow disruption due to one-time litigation settlement; normalized operations demonstrate strong debt service capacity.",
  "Recently secured government certification creating competitive advantage and documented pipeline of new contracts.",
  "Client relationship of 12+ years with combined business and personal deposits exceeding $425,000 and perfect payment history.",
  "Loan purpose to consolidate fragmented debt structure improves overall financial flexibility despite elevated total leverage.",
  "Strategic acquisition below market value creates immediate equity position offsetting borrower's limited cash injection.",
  "Highly specialized technical business with documented intellectual property and limited competitive alternatives in market.",
  "Industry leader with 35% market share and proprietary technology justifies higher leverage than standard industry guidelines.",
  "Temporary working capital ratio below guideline due to accelerated tax payments; historical liquidity management is strong.",
  "Confirmed equity injection scheduled within 90 days from pending sale of non-core assets strengthens overall capital position.",
  "Bridge financing with committed long-term mortgage takeout from life insurance company justifies temporary LTV exception.",
  "Principal owner's strong personal liquidity with cash reserves exceeding 12 months of debt service provides repayment assurance.",
  "Recent expansion into adjacent market temporarily impacts profitability ratios; consolidated operations meet policy guidelines.",
  "Debt service coverage exception mitigated by significant cash reserves exceeding annual debt service requirements by 200%.",
  "Manufacturing business with confirmed orders exceeding 6 months of production capacity supports cash flow projections.",
  "Specialized medical equipment with manufacturer repurchase agreement provides additional collateral protection despite LTV exception.",
  "Acquisition financing structure includes significant seller note subordinated to bank debt improving effective loan-to-value ratio.",
  "High-margin service business with 45% gross profit provides substantial debt repayment capacity despite limited tangible assets.",
  "Partner buy-in loan with existing successful practice and established patient base mitigates limited management experience risk.",
  "Temporary impact on debt service ratio due to one-time investment in efficiency improvements with 18-month ROI projection.",
  "Long-term client relationship since 2010 with perfect loan performance history and significant deposit relationship.",
  "Loan purpose to secure key retail location critical to business expansion strategy justifies policy exception on debt coverage.",
  "Agricultural business with seasonal performance affected by timing of fiscal year-end; peak season metrics meet all guidelines.",
  "Temporary cash flow impact from extraordinary inventory purchase to mitigate supply chain disruption with firm customer orders.",
  "Specialized professional services firm with limited capital requirements justifies higher leverage than manufacturing guidelines.",
  "Principal owner's industry expertise with previous successful exit of similar business for 8x EBITDA demonstrates capability.",
  "Strategic equipment purchase with documented 35% productivity improvement justifies temporary cash flow ratio exception.",
  "Unique business model with 90% recurring revenue and net retention rate exceeding 100% supports debt service projections.",
  "Presold inventory securing loan with firm purchase orders from creditworthy customers mitigates standard collateral requirements.",
  "Affiliated operating companies under common ownership with strong consolidated financial performance supports global cash flow.",
  "Relationship pricing exception based on substantial deposit balances, trust department assets, and treasury management services.",
  "Recent business acquisition at favorable multiple creates stronger market position and immediate cost synergies improving cash flow.",
  "Loan purpose to fulfill major contract with 50% advance payment schedule mitigates working capital and collateral concerns.",
  "Professional practice with stable client base and minimal capital expenditure requirements supports higher leverage ratio.",
  "Temporary balance sheet impact from strategic inventory buildup ahead of confirmed seasonal demand with firm orders.",
  "Strong guarantor support with personal net worth exceeding 5x loan amount and liquid assets covering 24 months of debt service.",
  "Well-established professional practice with transferable client base during ownership transition mitigates succession risk.",
  "Franchise renewal financing with 10-year operating history demonstrating consistent performance through market cycles.",
  "Recent extraordinary expenses for technology implementation temporarily affect debt service ratio; normalized EBITDA meets guideline.",
  "Deferred equipment maintenance catching up with significant capex temporarily impacts cash flow ratio below standard guideline.",
  "Strong banking relationship with multiple commercial and consumer accounts generating combined annual revenue of $42,000.",
  "Acquisition financing with 40% seller financing subordinated to bank debt improves effective loan-to-value position.",
  "Collateral exception mitigated by specialized equipment with manufacturer buyback guarantee at 70% of original value.",
  "Temporary financial ratio impact from recent expansion into adjacent market with demonstrable revenue already materializing.",
  "Loan purpose to secure critical intellectual property rights essential to maintaining competitive advantage in niche market.",
  "Professional services firm with limited capital needs and strong cash generation supports higher leverage than standard guideline.",
  "Transitional financing during business restructuring with demonstrated improvement in operating metrics over past two quarters.",
  "Longstanding deposit relationship exceeding $300,000 average balance with significant cash management services utilization.",
  "Debt service coverage below guideline due to recent facility upgrades; historical performance demonstrates repayment capacity.",
  "Additional collateral from closely-held investment real estate with equity exceeding $750,000 supplements business assets.",
  "Strategic acquisition financing for competitor at below-market multiple creates immediate positive cash flow contribution.",
  "Loan request to fund contract performance bond for major government project with confirmed award and payment schedule.",
  "Specialized business with limited industry capacity and strong customer relationships justifies policy exception on leverage.",
  "Partnership buy-in loan with established professional practice and transferable client relationships mitigates risk.",
  "Temporary seasonal working capital needs affecting current ratio with demonstrated pattern of successful cycle management.",
  "Export financing with confirmed letters of credit from investment-grade financial institutions mitigates standard collateral concerns.",
  "Principal's personal financial strength with $2.5M in liquid assets provides substantial secondary repayment source.",
  "Loan purpose to consolidate existing higher-cost debt improves monthly cash flow by $4,200 despite total leverage concerns.",
  "Recent investment in automation temporarily impacts debt service metrics; projected efficiency gains demonstrate 15-month ROI.",
  "Specialized industry with documented barriers to entry, limited competition, and stable customer base justifies leverage exception.",
  "Ten-year banking relationship with spotless payment history and combined deposit balances exceeding $275,000.",
  "Healthcare practice acquisition with transitioning physician remaining 18 months to ensure patient retention and knowledge transfer.",
  "Temporary debt service impact from one-time legal expenses; normalized operations demonstrate 1.4x coverage ratio.",
  "Loan purpose to secure long-term supply agreement with fixed pricing provides cost stability despite limited operating history.",
  "Manufacturing business with substantial backlog of confirmed orders supports cash flow projections despite leverage concerns.",
  "Personal guarantor's substantial liquid assets exceeding $900,000 provide significant secondary repayment source.",
  "Specialized equipment with limited useful life but essential to securing major contract justifies loan-to-value exception.",
  "Strategic real estate acquisition adjacent to existing location at below-market pricing justifies loan-to-value exception.",
  "Excellent credit history with no delinquencies across personal and business accounts spanning 15+ year relationship.",
  "Professional services firm with minimal capital requirements and high margins supports higher leverage than standard guidelines.",
  "Temporary DSCR impact from unusually high tax payment due to asset sale gain; normalized operations meet debt service requirement.",
  "Working capital exception necessary to fulfill seasonal inventory build for confirmed retail distribution agreement.",
  "Highly specialized business with limited competition and intellectual property protection justifies cash flow ratio exception.",
  "Private equity-supported transaction with significant sponsor equity contribution mitigates overall leverage concerns.",
  "Loan purpose to finance contract with Fortune 100 customer with history of prompt payment and ongoing relationship.",
  "Restaurant with prime location and proven operator despite industry's higher leverage due to real estate component.",
  "Temporary impact on cash flow from inventory stockpiling due to supply chain concerns with confirmed customer orders.",
  "Client relationship of 10+ years with combined business and personal deposits exceeding $400,000 and perfect payment history.",
  "Industry-specific accounting treatment creates artificially high leverage ratio; adjusted for operating leases meets guideline.",
  "Strong personal guarantee from principal with personal net worth exceeding $5M and liquid assets of $1.2M.",
  "Short-term bridge financing with committed takeout from confirmed SBA 7(a) loan approval pending disbursement.",
  "Demonstrated ability to successfully operate through industry downturn with minimal impact on financial performance.",
  "Recent acquisition of customer list from competitor at favorable terms improves market position and revenue stability.",
  "Temporary cash flow impact due to key staff additions ahead of growth; trailing 6-month performance shows improvement.",
  "Specialized collateral with strong marketability in current equipment-constrained environment justifies LTV exception.",
  "Predictable government contract revenue with historical renewal pattern provides stability despite recent performance variance.",
  "Term loan structure matched to equipment useful life despite policy exception on amortization based on cash flow analysis.",
  "Proven operator with successful track record in same industry offsetting concerns about limited operation at current location.",
  "Strategic financing to secure exclusive territorial rights creates competitive advantage justifying exception on debt coverage.",
  "Temporary balance sheet impact from strategic raw material purchase ahead of announced supplier price increases.",
  "Professional practice transition with retiring principal providing seller financing and remaining as consultant during transition.",
  "Loan purpose to fund insurance settlement gap for business interruption claim with documented reopening timeline.",
  "Specialized manufacturing operation with government security clearance creates high barrier to entry supporting higher leverage.",
  "Operating line increase to support confirmed contract with credit-worthy customer having established payment history.",
  "Principal's successful exit from previous similar business demonstrates industry expertise and management capability.",
  "Temporary DSCR impact from growth-related expenses with trailing 3-month performance showing return to policy compliance.",
  "Extensive banking relationship with multiple related entities and substantial deposit balances exceeding $350,000.",
  "Strategic real estate acquisition in supply-constrained market at below replacement cost justifies loan-to-value exception.",
  "Recent business line divestiture improves focus on core operations with streamlined cost structure improving debt service capacity.",
  "Equipment financing for productivity improvement with demonstrated 24-month ROI supporting debt service extension.",
  "Specialized business with high switching costs for customers creates stable revenue stream despite higher leverage than guideline.",
  "Loan purpose supporting contract with upfront payment structure mitigates traditional working capital financing concerns.",
  "Strong personal guarantee with guarantor's liquid assets exceeding total loan commitment provides repayment assurance.",
  "Temporary ratio impact from significant pre-paid expenses; adjusted working capital position meets policy guidelines.",
  "Long-term banking relationship since 2007 with perfect payment history on multiple loans across business cycles.",
  "Collateral exception justified by specialized equipment with manufacturer repurchase agreement at 65% of original cost.",
  "Acquisition includes significant customer list value and key employee retention agreements supporting cash flow projections.",
  "Leverage exception offset by confirmed equity injection scheduled within 60 days from pending real estate refinance.",
  "Professional practice with high recurring revenue from insurance reimbursements supports higher leverage ratio.",
  "Temporary working capital ratio exception due to timing of major contract milestone payment scheduled within 30 days.",
  "Loan request to support contract with Fortune 500 client with historical prompt payment pattern and ongoing relationship.",
  "Customer concentration mitigated by long-term contract with liquidated damages clause and history of renewals.",
  "Business acquisition at favorable multiple with demonstrated synergies improving consolidated debt service coverage.",
  "Equipment financing exception based on essential production capacity required to fulfill confirmed customer orders.",
  "Highly profitable service business with limited capital requirements justifies higher leverage than standard policy.",
  "Temporary DSCR impact from one-time moving expenses; pro forma operations at new location demonstrate strong coverage.",
  "Medical practice with established patient base and insurance contracts provides stable cash flow despite recent expansion.",
  "Loan purpose to consolidate predatory merchant cash advances significantly improves monthly cash flow despite leverage concerns.",
  "Family business transition financing with senior generation remaining involved during phased ownership transfer.",
  "Strong deposit relationship exceeding $225,000 with active treasury management services mitigates debt service exception.",
  "Specialized software business with 85% recurring revenue and minimal capital expenditure requirements supports higher leverage.",
  "Franchise agreement renewal with demonstrated performance in top quartile of system justifies exception on loan-to-value.",
  "Recent business expansion temporarily impacts debt service metrics; trailing 3-month performance shows positive trend.",
  "Strategic acquisition of supplier secures supply chain and creates vertical integration efficiencies justifying leverage exception.",
  "Working capital loan to support major contract requiring performance bond with confirmed payment milestones.",
  "Principal's strong industry expertise with 20+ years and documented success with similar operations mitigates risk.",
  "Temporary ratio impact from significant non-cash expenses; adjusted cash flow metrics meet policy guidelines.",
  "Longstanding banking relationship across multiple businesses owned by principal with excellent payment history.",
  "Demonstration of business resilience through COVID-19 pandemic with minimal revenue impact in restricted industry.",
  "Specialized business with limited competition due to technical certification requirements justifies policy exception.",
  "Bridge financing with committed takeout from confirmed equipment sale closing within 90 days justifies temporary exception.",
  "Professional practice acquisition with existing clientele and transitioning owner remaining as consultant during handover.",
  "Temporary cash flow impact from expansion to second location; established location demonstrates strong debt service coverage.",
  "Strategic inventory financing to secure limited-availability components necessary for product assembly and confirmed orders.",
  "Substantial cash reserves exceeding 6 months of operating expenses provides additional cushion despite DSCR below guideline."
]
