small_business_banking__beneficial_owner_verification__verification_method = [
  "Primary government-issued photo ID cross-referenced with business registration documents filed with secretary of state.",
  "Current U.S. passport verified through ID validation service with ownership percentage confirmed via operating agreement.",
  "Driver's license authenticated using fraud detection software and ownership verified through articles of incorporation.",
  "Documentary verification of unexpired government ID with additional non-documentary verification through credit bureau records.",
  "In-person verification of beneficial owner using two forms of government-issued identification with one containing a photograph.",
  "Secretary of state business filing cross-referenced with certified corporate resolution identifying ownership percentages.",
  "U.S. passport verification combined with corporate tax return Schedule K-1 confirming ownership stake percentage.",
  "Driver's license authenticated through DMV database with corporate meeting minutes documenting ownership interests.",
  "Certification of Beneficial Ownership form completed and signed in presence of bank officer with supporting documentation.",
  "Current state-issued photo ID verified with ownership confirmed through operating agreement and business tax returns.",
  "Passport verification through government database combined with articles of organization showing membership interests.",
  "Documentary verification of foreign passport with U.S. visa plus verification of corporate records filed with state authority.",
  "Enhanced due diligence with in-person verification of government ID and cross-reference to business formation documents.",
  "Multiple identification documents verified through ID validation service with ownership confirmed via shareholder agreement.",
  "Driver's license verification combined with review of filed corporate tax returns showing ownership distribution.",
  "Beneficial Ownership certification form with notarized signature and supporting corporate documentation of ownership interests.",
  "Foreign government-issued ID verified through embassy with ownership percentage confirmed through corporate resolutions.",
  "U.S. military ID verification combined with business formation documents filed with secretary of state.",
  "In-person verification by relationship manager with government ID and supporting business documentation of ownership.",
  "Documentary verification of unexpired passport combined with review of partnership agreement showing profit distribution.",
  "State-issued photo ID authentication combined with certified organizational documents showing ownership structure.",
  "Certification form completed and verified against business registration documents showing consistent ownership information.",
  "Enhanced verification for high-risk customer using multiple forms of government ID and certified business filings.",
  "Driver's license verified through electronic authentication service with corporate bylaws confirming ownership position.",
  "Non-documentary verification using credit bureau and public records database combined with business ownership documentation.",
  "In-branch verification of beneficial owner's government-issued photo ID with signature comparison to corporate documents.",
  "U.S. passport authentication combined with review of business formation documents and corporate meeting minutes.",
  "Documentary verification of current government ID with cross-reference to state business registration information.",
  "Enhanced due diligence for foreign beneficial owner using passport with supporting ownership documentation.",
  "State-issued ID verified through fraud detection system with operating agreement confirming ownership percentage.",
  "Government database verification of identification combined with certified articles of organization.",
  "In-person verification by business banking officer with photo ID and supporting business ownership documentation.",
  "Documentary verification of multiple identification forms with business tax returns confirming ownership distribution.",
  "Enhanced verification process using ID validation service and comprehensive review of corporate documentation.",
  "Foreign passport verified through appropriate embassy with corporate resolution documenting ownership interests.",
  "Driver's license verification through state DMV database with corporate filings confirming beneficial ownership.",
  "Multi-factor authentication including government ID verification and certified business ownership documentation.",
  "Passport verification service combined with certified copy of partnership agreement showing ownership percentages.",
  "In-branch verification using two forms of government-issued identification with corporate documentation review.",
  "Documentary verification of state-issued ID with business formation documents and tax filings showing ownership.",
  "Enhanced due diligence with government database verification of ID and certified corporate ownership documents.",
  "Beneficial ownership certification form verified against secretary of state business registration information.",
  "ID verification through fraud detection software with corporate bylaws and meeting minutes confirming ownership.",
  "In-person verification by relationship manager with government photo ID and certified business documentation.",
  "U.S. passport verification through appropriate government database with supporting ownership documentation.",
  "Documentary verification of driver's license with ownership confirmed through partnership tax returns.",
  "Non-documentary verification through public records database with business formation documents review.",
  "Enhanced verification process for high-risk entity with multiple forms of government ID and certified business filings.",
  "State-issued photo ID verified with fraud detection technology and corporate documentation of ownership structure.",
  "Certification form with notarized signature verified against business registration documents and tax filings.",
  "In-person verification using unexpired government-issued photo ID with signature comparison to corporate documents.",
  "Documentary verification of U.S. passport combined with certified copy of operating agreement.",
  "Driver's license authenticated through state database with corporate tax filings confirming ownership distribution.",
  "Enhanced due diligence with verification of government ID and comprehensive review of business ownership documents.",
  "Multiple identification documents verified with ownership confirmation through secretary of state business filings.",
  "Foreign government-issued ID verified through appropriate channels with corporate resolutions confirming ownership.",
  "In-branch verification by business banking specialist with photo ID and certified business documentation.",
  "Documentary verification of state ID with cross-reference to business registration and ownership documentation.",
  "Beneficial ownership certification form verified through internal and external database checks for consistency.",
  "Government-issued photo ID authenticated using fraud detection software with corporate documents review.",
  "Enhanced verification for foreign beneficial owner with passport verification and certified ownership documentation.",
  "Driver's license verification combined with review of LLC operating agreement showing membership percentages.",
  "In-person verification with two forms of government ID and cross-reference to business formation documents.",
  "Documentary verification of passport with corporate tax returns and minutes confirming ownership interests.",
  "Non-documentary verification through credit bureau and government databases with business document review.",
  "State-issued photo ID verified through authentication service with corporate filings confirming ownership.",
  "Certification of Beneficial Ownership form with supporting documentation verified against public records.",
  "Enhanced due diligence with government ID verification and comprehensive review of business organization documents.",
  "Multiple identification documents verified through fraud detection service with corporate resolution confirmation.",
  "In-branch verification by relationship manager with unexpired government ID and business ownership documentation.",
  "Documentary verification of driver's license combined with secretary of state business registration review.",
  "U.S. passport authenticated through appropriate database with business tax returns confirming ownership.",
  "Foreign government-issued ID verified with apostille certification and corporate documentation review.",
  "Enhanced verification process using multiple identification sources and certified business filings.",
  "State-issued photo ID verification with corporate bylaws and meeting minutes confirming ownership position.",
  "In-person verification by business banking officer with government ID and notarized ownership documentation.",
  "Documentary verification of unexpired passport with cross-reference to business formation documents.",
  "Beneficial ownership certification form verified against multiple business documentation sources.",
  "Driver's license authentication through DMV database with partnership agreement confirming ownership interest.",
  "Enhanced due diligence with government database verification and comprehensive corporate document review.",
  "Multiple identification documents verified with business tax filings showing consistent ownership information.",
  "In-branch verification using government-issued photo ID with signature comparison to corporate documents.",
  "Documentary verification of state ID combined with certified copy of articles of incorporation.",
  "Non-documentary verification through public records and credit bureau with business ownership documentation.",
  "Government-issued photo ID verified through fraud detection system with corporate filings confirmation.",
  "Enhanced verification for high-risk customer with multiple forms of identification and business documentation.",
  "Foreign passport verification through appropriate government database with corporate resolution review.",
  "Certification form completed with notarized signature and cross-referenced with business registration.",
  "In-person verification by relationship manager with unexpired government ID and ownership documentation.",
  "Documentary verification of driver's license with corporate tax returns showing ownership distribution.",
  "U.S. passport authenticated through verification service with operating agreement confirming ownership.",
  "Enhanced due diligence with multiple identification verification methods and business document review.",
  "State-issued photo ID verification combined with secretary of state business registration information.",
  "Beneficial ownership certification form verified against corporate documentation and public records.",
  "In-branch verification with government-issued photo ID and comprehensive business document review.",
  "Documentary verification of multiple identification forms with certified corporate ownership documents.",
  "Driver's license verified through state database with articles of organization confirming membership interests.",
  "Enhanced verification process using ID validation technology and business formation document review.",
  "Multiple identification documents verified with corporate meeting minutes documenting ownership structure.",
  "In-person verification by business banking specialist with government ID and certified ownership documentation.",
  "Foreign government-issued ID verified through appropriate channels with business tax returns confirmation.",
  "Documentary verification of U.S. passport with partnership agreement showing ownership percentages.",
  "Beneficial ownership certification with supporting documentation verified against public records databases.",
  "State-issued photo ID authenticated using fraud detection software with corporate filing review.",
  "Enhanced due diligence with government database verification and comprehensive ownership documentation.",
  "In-branch verification by relationship manager with photo ID and business registration document review.",
  "Documentary verification of driver's license with cross-reference to corporate bylaws and tax filings.",
  "Non-documentary verification through credit bureau and government databases with ownership documentation.",
  "Multiple identification documents verified with secretary of state business registration information.",
  "Certification form verified against corporate resolution and business tax returns showing ownership.",
  "Enhanced verification for foreign beneficial owner with passport authentication and corporate documentation.",
  "State-issued photo ID verified through DMV database with operating agreement confirming ownership percentage.",
  "In-person verification with unexpired government ID and business formation documents review.",
  "Documentary verification of passport with corporate documents filed with secretary of state.",
  "Beneficial ownership certification form with notarized signature and supporting business documentation.",
  "Driver's license verification through authentication service with business tax filings confirmation.",
  "Enhanced due diligence with multiple identification verification methods and ownership document review.",
  "U.S. passport verified through government database with corporate meeting minutes confirmation.",
  "In-branch verification by business banking officer with government ID and certified ownership documentation.",
  "Documentary verification of state ID with cross-reference to business registration and tax filings.",
  "Foreign government-issued ID verified with supporting business documentation of ownership structure.",
  "Enhanced verification process using fraud detection technology and comprehensive corporate document review.",
  "Multiple identification documents verified with partnership agreement showing ownership distribution.",
  "Certification form verified against secretary of state business filings and corporate resolutions.",
  "In-person verification by relationship manager with unexpired government ID and ownership documentation.",
  "Documentary verification of driver's license with articles of incorporation confirming ownership position.",
  "Non-documentary verification through public records database with business tax returns review.",
  "Government-issued photo ID authenticated using verification service with corporate document confirmation.",
  "Enhanced due diligence for high-risk entity with multiple identification verification methods.",
  "State-issued photo ID verified with business formation documents and ownership certification.",
  "In-branch verification with two forms of government ID and comprehensive business document review.",
  "Documentary verification of U.S. passport with operating agreement showing membership percentages.",
  "Beneficial ownership certification form verified against multiple public and private databases.",
  "Driver's license authentication through state database with corporate filings confirming ownership.",
  "Enhanced verification process using multiple identification sources and certified ownership documentation.",
  "Foreign passport verified through appropriate government channels with business documentation review.",
  "In-person verification by business banking specialist with photo ID and corporate resolution review.",
  "Documentary verification of state ID with cross-reference to secretary of state business registration.",
  "Multiple identification documents verified with tax filings showing consistent ownership information.",
  "Certification form with notarized signature verified against business formation documents.",
  "Enhanced due diligence with government database verification and corporate document review.",
  "U.S. passport verified through authentication service with business tax returns confirmation.",
  "In-branch verification by relationship manager with government ID and ownership documentation.",
  "Documentary verification of driver's license with corporate bylaws confirming ownership position.",
  "Foreign government-issued ID verified with apostille certification and business document review.",
  "Enhanced verification for high-risk customer using multiple identification verification methods.",
  "State-issued photo ID authenticated using fraud detection software with ownership documentation.",
  "Beneficial ownership certification form verified against corporate records and public filings.",
  "In-person verification with unexpired government ID and certified business documentation.",
  "Documentary verification of passport with partnership agreement showing ownership percentages.",
  "Driver's license verification through state database with business tax filings confirmation.",
  "Enhanced due diligence with multiple forms of government ID and comprehensive document review.",
  "Multiple identification documents verified with corporate resolutions documenting ownership structure.",
  "In-branch verification by business banking officer with photo ID and business registration review.",
  "Documentary verification of state ID with cross-reference to articles of organization.",
  "Non-documentary verification through credit bureau and public records with ownership documentation.",
  "Government-issued photo ID verified through authentication service with corporate filing review.",
  "Enhanced verification process using ID validation technology and certified business documents.",
  "Foreign passport verified through appropriate channels with business tax returns confirmation.",
  "Certification form verified against secretary of state business registration information.",
  "In-person verification by relationship manager with government ID and corporate document review.",
  "Documentary verification of driver's license with operating agreement confirming ownership percentage.",
  "U.S. passport authenticated through government database with business formation document review.",
  "Enhanced due diligence with multiple identification verification methods and ownership documentation.",
  "State-issued photo ID verified with corporate meeting minutes confirming ownership position.",
  "Beneficial ownership certification form with supporting documentation verified against public records.",
  "In-branch verification with unexpired government ID and comprehensive business document review.",
  "Documentary verification of multiple identification forms with business tax filings confirmation.",
  "Driver's license verification through DMV database with corporate resolutions confirming ownership.",
  "Enhanced verification for foreign beneficial owner with passport authentication and business documentation.",
  "Multiple identification documents verified with secretary of state business registration information.",
  "In-person verification by business banking specialist with government ID and ownership documentation.",
  "Documentary verification of U.S. passport with cross-reference to corporate bylaws and tax filings.",
  "Certification form with notarized signature verified against business formation documents.",
  "State-issued photo ID authenticated using fraud detection software with corporate filing review.",
  "Enhanced due diligence with government database verification and comprehensive ownership documentation.",
  "Foreign government-issued ID verified through appropriate channels with business document review.",
  "In-branch verification by relationship manager with photo ID and corporate resolution review.",
  "Documentary verification of driver's license with partnership agreement showing ownership distribution.",
  "Non-documentary verification through public records database with business tax returns review.",
  "Multiple identification documents verified with articles of incorporation confirming ownership position.",
  "Beneficial ownership certification form verified against corporate documents and public filings.",
  "Enhanced verification process using multiple identification sources and certified business documentation.",
  "U.S. passport verified through authentication service with operating agreement confirmation.",
  "In-person verification with government-issued photo ID and business registration document review.",
  "Documentary verification of state ID with cross-reference to corporate meeting minutes.",
  "Driver's license authentication through state database with business tax filings confirmation.",
  "Enhanced due diligence for high-risk entity with multiple forms of identification verification.",
  "Foreign passport verified through appropriate government channels with corporate document review."
]
