small_business_banking__loan_fair_lending__denial_reason_3 = [
  "Unacceptable business credit report with multiple collection accounts and slow payment history on trade accounts.",
  "Inadequate business liquidity with quick ratio of 0.6:1 versus minimum requirement of 1.0:1 for industry type.",
  "Excessive concentration risk with 75% of business revenue derived from single customer relationship.",
  "Insufficient documentation of cash flow with unexplained large deposits inconsistent with business model.",
  "Unacceptable debt-to-tangible net worth ratio of 5.2:1, exceeding industry maximum guideline of 3.0:1.",
  "Inadequate secondary source of repayment with no personal liquidity outside of business investment.",
  "Excessive lease obligations not reflected on balance sheet creating understated liability position.",
  "Insufficient management experience in industry with principal engaged less than 18 months in current business type.",
  "Unacceptable trend in profitability with declining net margin in three consecutive quarters.",
  "Inadequate collateral with liquidation value covering only 60% of requested loan amount.",
  "Excessive owner distributions exceeding net income by 35% over prior fiscal year eroding business capital.",
  "Insufficient business operating history with 14 months of operations versus 24-month minimum requirement.",
  "Unacceptable accounts receivable quality with 42% beyond 90 days past due versus 20% maximum guideline.",
  "Inadequate fixed charge coverage ratio of 0.92:1, below required minimum of 1.25:1 for loan type.",
  "Excessive leverage with proposed financing increasing debt-to-worth ratio to 6.5:1 versus maximum 3.0:1.",
  "Insufficient working capital with negative position after adjusting for current portion of long-term debt.",
  "Unacceptable guarantor credit score of 580, below minimum threshold of 680 for program qualification.",
  "Inadequate revenue stability with monthly fluctuations exceeding 40% without seasonal business justification.",
  "Excessive judgments and tax liens against business assets affecting collateral position and lien priority.",
  "Insufficient cash equity in project with only 8% owner investment versus required minimum of 20%.",
  "Unacceptable debt service coverage ratio of 0.88:1 based on historical financial performance versus 1.25:1 minimum.",
  "Inadequate inventory management with turnover ratio of 1.8x annually versus industry average of 6.0x.",
  "Excessive personal withdrawals depleting business capital needed for operational liquidity and growth.",
  "Insufficient documentation to verify revenue sources with material unexplained discrepancies in reported figures.",
  "Unacceptable collateral value with recent appraisal 25% below original estimate affecting loan-to-value ratio.",
  "Inadequate business plan with unrealistic projections exceeding industry growth rates by 300%.",
  "Excessive reliance on short-term debt for long-term asset financing creating maturity mismatch risk.",
  "Insufficient financial statement quality with compilation only versus required reviewed statements for loan size.",
  "Unacceptable personal credit history with multiple delinquencies on existing debt obligations.",
  "Inadequate business succession planning for owner-dependent operation with principal over age 60.",
  "Excessive industry concentration within current loan portfolio exceeding regulatory guidance thresholds.",
  "Insufficient controls with commingling of business and personal finances evident in bank statements.",
  "Unacceptable payment history on existing debt with multiple instances of 30+ day delinquency.",
  "Inadequate collateral diversification with single property representing 90% of total security package.",
  "Excessive tax liabilities with delinquent payments and no formal resolution plan in place.",
  "Insufficient business debt yield ratio at 7.4% below minimum requirement of 9.0% for loan type.",
  "Unacceptable analysis of market competition in business plan with unrealistic market share projections.",
  "Inadequate management depth with operations critically dependent on single key individual.",
  "Excessive accounts payable aging with 42% beyond terms creating potential supply chain disruption risk.",
  "Insufficient documentation of revenue sources with bank deposits inconsistent with reported income.",
  "Unacceptable global cash flow analysis with debt service coverage ratio below 1.0 including all obligations.",
  "Inadequate internal controls with limited financial oversight and lack of separation of duties.",
  "Excessive related-party transactions representing 30% of total expenses without arm's length documentation.",
  "Insufficient collateral control due to prior liens restricting ability to obtain required security position.",
  "Unacceptable financial record keeping with incomplete statements and supporting documentation.",
  "Inadequate gross profit margin at 18% compared to industry average of 40% for similar operations.",
  "Excessive operating expenses at 92% of gross revenue versus industry benchmark maximum of 75%.",
  "Insufficient equipment maintenance with deferred upkeep affecting operational reliability and collateral value.",
  "Unacceptable number of recent credit inquiries indicating potential undisclosed debt obligations.",
  "Inadequate sales-to-assets ratio at 0.75x versus industry benchmark of 1.8x minimum.",
  "Excessive owner salary and benefits representing 45% of net profit versus industry norm of 25%.",
  "Insufficient property insurance coverage at 70% of replacement value versus required 100% coverage.",
  "Unacceptable trend in sales with year-over-year decline of 22% in most recent fiscal period.",
  "Inadequate verification of financial information with material inconsistencies in reported figures.",
  "Excessive projected growth rate of 60% annually without demonstrated capacity or market justification.",
  "Insufficient equity relative to proposed debt with equity comprising only 8% of total capitalization.",
  "Unacceptable loan structure with interest-only period exceeding policy guidelines for loan type.",
  "Inadequate business contingency planning for disaster recovery and business interruption scenarios.",
  "Excessive cash flow-to-debt ratio with total liabilities at 7.5x annual cash flow versus 4.0x maximum.",
  "Insufficient collateral marketability with highly specialized equipment having limited resale potential.",
  "Unacceptable level of returned items in deposit accounts with 15 incidents in past six months.",
  "Inadequate customer base with top three clients representing 85% of total revenue stream.",
  "Excessive overhead costs at 48% of gross revenue versus industry standard of 32% maximum.",
  "Insufficient analysis of cash flow seasonality with no demonstrated management strategy for fluctuations.",
  "Unacceptable business organization with frequent operational structure changes in past 24 months.",
  "Inadequate documentation of projected revenue growth with assumptions exceeding proven capabilities.",
  "Excessive concentration in high-risk product lines comprising 80% of total revenue stream.",
  "Insufficient business premises control with lease expiring within 12 months and no renewal option documented.",
  "Unacceptable vendor stability with critical supplier concentration creating potential inventory disruption risk.",
  "Inadequate expense control with operating costs increasing 30% while revenue remained flat.",
  "Excessive employee turnover ratio at 70% annually indicating potential management or operational issues.",
  "Insufficient business plan detail regarding implementation timeline and resource allocation.",
  "Unacceptable financial covenant compliance with multiple violations on existing debt obligations.",
  "Inadequate current ratio of 0.82:1 versus required minimum of 1.2:1 for industry category.",
  "Excessive business credit card debt comprising 40% of total liabilities with high interest expense.",
  "Insufficient owner investment in proposed expansion with only 5% equity contribution versus required 25%.",
  "Unacceptable level of business tax debt with payments 90 days past due without approved plan.",
  "Inadequate contingency reserves for specialized business facing significant regulatory changes.",
  "Excessive contract cancellation rate of 40% annually indicating customer satisfaction or delivery issues.",
  "Insufficient documentation to verify annual revenue figures with material unexplained discrepancies.",
  "Unacceptable fraud prevention controls with recent loss incidents reported and inadequate remediation.",
  "Inadequate accounts receivable management with average collection period of 82 days versus industry norm of 40 days.",
  "Excessive reliance on cash transactions representing 70% of sales without adequate controls.",
  "Insufficient sales backlog with forward orders covering only 20 days of operations versus 90-day minimum.",
  "Unacceptable equipment collateral with average age exceeding 80% of useful life for industry.",
  "Inadequate business credit history with limited established trade references or reported credit.",
  "Excessive contingent liabilities from pending litigation with potential material adverse effect on operations.",
  "Insufficient inventory control systems with unexplained shrinkage exceeding 10% of total inventory value.",
  "Unacceptable collateral type for requested loan purpose based on internal policy guidelines.",
  "Inadequate business capitalization with tangible net worth representing only 10% of total assets.",
  "Excessive owner distributions exceeding 90% of net income versus policy maximum of 40% for growth-stage business.",
  "Insufficient documentation of cash equity source with evidence suggesting potentially borrowed funds.",
  "Unacceptable fixed charge coverage ratio of 0.85:1, below required minimum of 1.15:1 for loan type.",
  "Inadequate business continuity planning for critical personnel with no documented succession strategy.",
  "Excessive monthly loan payment at 25% of average monthly revenue versus policy maximum of 15%.",
  "Insufficient business insurance coverage with key person insurance inadequate for operational dependency.",
  "Unacceptable customer returns and allowances at 18% of gross sales versus industry average of 3%.",
  "Inadequate revenue diversification with 90% derived from single product line or service category.",
  "Excessive seasonal fluctuations with peak-to-trough revenue variation exceeding 75% without adequate reserves.",
  "Insufficient guarantor strength with guarantor's net worth covering only 60% of requested loan amount.",
  "Unacceptable operating losses in three consecutive fiscal periods without credible turnaround strategy.",
  "Inadequate management expertise in critical business function essential to proposed expansion.",
  "Excessive projected debt service consuming 60% of forecast cash flow versus policy maximum of 35%.",
  "Insufficient business liquidity with cash representing only 2% of annual operating expenses.",
  "Unacceptable quality of financial reporting with significant unexplained discrepancies between statements.",
  "Inadequate industry experience for specialized business operation with principals having less than 2 years in field.",
  "Excessive fixed asset investment relative to revenue generation capacity and industry benchmarks.",
  "Insufficient project budget with contingency reserve below 5% minimum for project type and scope.",
  "Unacceptable property condition based on inspection report indicating significant deferred maintenance issues.",
  "Inadequate debt to tangible net worth ratio of 7.0:1, exceeding industry maximum of 3.5:1.",
  "Excessive supplier concentration with single vendor providing 80% of inventory or critical components.",
  "Insufficient revenue-to-assets ratio indicating inefficient use of business resources versus industry norms.",
  "Unacceptable business credit report with multiple collection accounts and slow payment history.",
  "Inadequate verification of financial information with material inconsistencies in reported figures.",
  "Excessive exposure to pending regulatory changes affecting core business operations or revenue model.",
  "Insufficient inventory turnover at 1.8x annually versus industry benchmark of 6x minimum.",
  "Unacceptable debt yield of 6.5% for commercial real estate collateral versus minimum requirement of 10%.",
  "Inadequate business tax payment history with multiple quarters of delinquent employment taxes.",
  "Excessive foreign exchange exposure with 60% of costs in different currency than revenue stream.",
  "Insufficient cash flow stability with standard deviation exceeding 45% of mean monthly cash flow.",
  "Unacceptable reliance on third-party financing of customer purchases representing 70% of total sales.",
  "Inadequate business premises with capacity constraints limiting growth potential during loan term.",
  "Excessive risk from intellectual property disputes affecting core product or service offering.",
  "Insufficient equipment maintenance reserves for mission-critical operational assets.",
  "Unacceptable concentration in accounts receivable with single customer representing 50% of total outstanding.",
  "Inadequate market position trend with documented loss of market share in three consecutive years.",
  "Excessive technology infrastructure risk with systems beyond recommended replacement cycle.",
  "Insufficient employee staffing for current operations creating delivery risk for projected growth.",
  "Unacceptable professional licensing status with pending regulatory issues affecting business operations.",
  "Inadequate refinancing history with four debt restructurings in past 36 months indicating financial stress.",
  "Excessive capacity utilization with operations at 40% of available capacity indicating operational inefficiency.",
  "Insufficient geographic diversification with 95% of revenue from single economic region.",
  "Unacceptable ownership structure with indirect or complex arrangements obscuring beneficial control.",
  "Inadequate liability insurance claims history indicating operational risk management deficiencies.",
  "Excessive profit distribution with withdrawals exceeding net income in two consecutive fiscal years.",
  "Insufficient sales-per-employee ratio at 45% of industry average indicating operational inefficiency.",
  "Unacceptable quick ratio of 0.48:1 indicating potential inability to meet short-term obligations.",
  "Inadequate customer acquisition cost relative to customer lifetime value based on historical data.",
  "Excessive integration risk for recently acquired business comprising 65% of projected revenue.",
  "Insufficient documentation of inventory valuation methodology and supporting records.",
  "Unacceptable accounts payable management with average days outstanding of 85 versus terms of 30 days.",
  "Inadequate evidence of required regulatory compliance for business operations or expansion.",
  "Excessive goodwill or intangible assets comprising 70% of total business asset valuation.",
  "Insufficient interest coverage ratio of 1.05:1 versus required minimum of 2.0:1 for loan structure.",
  "Unacceptable cost control systems with expenses growing at 1.75x rate of revenue growth.",
  "Inadequate equipment appraisal with valuation based on inappropriate comparables or methodology.",
  "Excessive debt service requirements absorbing 55% of operating cash flow versus 30% maximum guideline.",
  "Insufficient supporting data for projections with assumptions exceeding industry performance metrics.",
  "Unacceptable loan purpose involving significant related-party transaction without demonstrated business benefit.",
  "Inadequate commercial property occupancy rate at 55% versus minimum requirement of 80% for loan type.",
  "Excessive warranty or return obligations not adequately reserved for in financial statements.",
  "Insufficient business stability with four location changes in past 24 months without strategic rationale.",
  "Unacceptable deviation between business tax returns and financial statements without reconciliation.",
  "Inadequate analysis of business's competitive positioning with unrealistic market share assumptions.",
  "Excessive decline in gross margin of 15 percentage points over past three reporting periods.",
  "Insufficient documentation of intellectual property rights critical to business value proposition.",
  "Unacceptable accounts receivable to sales ratio exceeding industry benchmark by 40%.",
  "Inadequate operating expense control with ratio exceeding 90% of revenue versus industry average of 65%.",
  "Excessive dividend or distribution rate at 95% of annual profits versus policy maximum of 40%.",
  "Insufficient analysis of cash conversion cycle with significant working capital inefficiencies identified.",
  "Unacceptable legal structure for lending purpose with entity type creating additional risk factors.",
  "Inadequate vehicle fleet age with average exceeding 80% of useful life affecting operational reliability.",
  "Excessive pricing pressure in core market with gross margin compression of 25% in 12 months.",
  "Insufficient insurance coverage for business risks with multiple exclusions on critical exposures.",
  "Unacceptable level of non-operating expenses comprising 40% of total cash outflow.",
  "Inadequate evidence of required environmental compliance for business operations.",
  "Excessive inventory age with 45% of stock exceeding 180 days without valuation adjustment.",
  "Insufficient internet security measures for business conducting significant e-commerce activity.",
  "Unacceptable balance sheet leverage with debt comprising 90% of total business capitalization.",
  "Inadequate point-of-sale systems with limited ability to track sales and inventory movement.",
  "Excessive cost structure relative to revenue with break-even point at 90% of current sales level.",
  "Insufficient compliance with industry-specific regulatory requirements based on due diligence findings.",
  "Unacceptable facilities maintenance reserve for commercial property with aging infrastructure.",
  "Inadequate terms on critical supplier contracts with unfavorable pricing or exclusivity provisions.",
  "Excessive technical obsolescence risk for key production equipment or business systems.",
  "Insufficient evidence of positive cash flow trend with recent quarterly deterioration noted.",
  "Unacceptable customer contract duration with 80% of revenue from agreements expiring within six months.",
  "Inadequate loan-to-value ratio trend with recent market conditions reducing collateral coverage.",
  "Excessive revenue recognition issues with advance payments comprising 70% of reported sales.",
  "Insufficient business differentiation in highly competitive market with commoditized offerings.",
  "Unacceptable concentration in government contracts subject to budget appropriation uncertainty.",
  "Inadequate financial performance compared to projections provided for previous financing.",
  "Excessive product diversification lacking management expertise across disparate business lines.",
  "Insufficient cash reserve policy with less than 15 days of operating expenses maintained.",
  "Unacceptable software or technology licensing status critical to business operations.",
  "Inadequate customer service metrics with complaint rate exceeding industry standard by 200%.",
  "Excessive exposure to single geographic market subject to economic distress conditions."
]
