small_business_banking__business_due_diligence__expected_activity = [
    "Monthly deposits averaging $35,000-45,000 primarily via electronic payments and checks from established business customers within the tri-state area.",
    "Weekly cash deposits ranging from $2,000-3,500 consistent with retail business model, with higher volume during weekend processing periods.",
    "Average of 20-30 outgoing ACH transfers monthly for vendor payments and operating expenses, typically ranging from $500-5,000 each.",
    "Bi-weekly payroll processing via ACH for 12 employees totaling approximately $22,000 per cycle with appropriate tax withholdings.",
    "Quarterly tax payments to state and federal authorities ranging from $12,000-15,000 based on seasonal business performance.",
    "Monthly merchant card processing deposits averaging $65,000-75,000 with typical transaction counts of 500-600 retail customers.",
    "Occasional incoming domestic wire transfers from distributors, not exceeding $25,000 per transaction with 3-5 expected monthly.",
    "Regular monthly account transfers to business savings account for tax reserves and equipment replacement fund of $3,000-5,000.",
    "Seasonal fluctuation with revenue increasing approximately 40% during Q4 holiday season compared to baseline activity.",
    "Weekly check deposits from established business clients averaging $15,000-20,000 with 10-15 items per deposit.",
    "Monthly rent payment via recurring ACH debit of $4,250 to commercial property management company for retail location.",
    "Periodic equipment purchases via wire transfer or ACH, typically 2-3 transactions annually ranging from $10,000-30,000 each.",
    "Daily credit card batch settlements averaging $2,200-2,800 on weekdays and $3,500-4,500 on weekends based on retail patterns.",
    "Monthly insurance premium payments via ACH debit ranging from $1,800-2,200 for various business coverage policies.",
    "Quarterly dividend distributions to two business partners via transfers to personal accounts, typically $15,000-25,000 each based on profitability.",
    "Weekly inventory purchases from primary suppliers via ACH or check payments ranging from $5,000-8,000 per order.",
    "Annual business license and permit renewal payments to local authorities via check or ACH, typically totaling $3,000-5,000.",
    "Monthly utility payments via autopay arrangements totaling $1,200-1,800 depending on seasonal usage patterns.",
    "Bi-monthly transfers to separate payroll account of approximately $25,000 to cover upcoming employee compensation and taxes.",
    "Periodic cash withdrawals for petty cash purposes, not exceeding $1,000 per transaction with 1-2 transactions monthly.",
    "Recurring monthly loan payment of $3,750 for business equipment financing via automatic ACH debit arrangement.",
    "Average monthly balance maintained between $45,000-75,000 with seasonal fluctuations aligned with business cycle.",
    "Annual insurance proceeds for business claims not expected to exceed $50,000 based on coverage limits and history.",
    "Monthly professional service payments for accounting and legal support averaging $2,000-3,000 via check or ACH.",
    "Occasional incoming wire transfers from new commercial clients with expected due diligence documentation for amounts over $10,000.",
    "Recurring quarterly payments to franchise parent company averaging $12,000-15,000 based on revenue sharing agreement.",
    "Monthly credit card payments for business expenses averaging $8,000-10,000 with detailed receipt documentation.",
    "Weekly payroll tax deposits via EFTPS system ranging from $5,000-6,500 based on current employee headcount.",
    "Periodic international wire transfers to Canadian supplier, typically $15,000-20,000 monthly with appropriate import documentation.",
    "Regular incoming ACH transfers from online sales platforms averaging $25,000-30,000 monthly with supporting transaction records.",
    "Monthly lease payments for business equipment totaling $3,200 via recurring ACH debits to established leasing company.",
    "Quarterly bonus payments to employees via payroll system, typically totaling $15,000-25,000 depending on performance metrics.",
    "Periodic large check deposits from insurance reimbursements for covered patient services ranging from $5,000-15,000 each.",
    "Annual property tax payments via check or wire transfer ranging from $8,000-10,000 for business premises.",
    "Recurring monthly transfers of $4,500 to business money market account for emergency operating reserves.",
    "Weekly deposits from retail cash sales averaging $4,000-6,000 with higher volumes during holiday shopping periods.",
    "Monthly service fees for business software and technology subscriptions via ACH debits totaling $1,500-2,500.",
    "Periodic equipment maintenance payments via check or ACH ranging from $1,000-3,000 per service event.",
    "Bi-weekly ACH credits from government healthcare programs averaging $18,000-22,000 for covered professional services.",
    "Monthly investment activity in business sweep account with average collected balances maintained at $50,000-75,000.",
    "Recurring payments to marketing agencies via ACH or wire transfer averaging $5,000-8,000 monthly based on campaign schedule.",
    "Weekly fuel purchases for delivery fleet via business debit card totaling $800-1,200 depending on delivery volume.",
    "Monthly merchant processing fees deducted via ACH ranging from $1,800-2,200 based on transaction volume.",
    "Annual tax refund deposits ranging from $5,000-15,000 typically received in Q2 following tax filing season.",
    "Regular international wire transfers to Chinese manufacturers, 3-4 transactions quarterly ranging from $20,000-50,000 each.",
    "Periodic capital distributions to business partners, typically 2-3 times annually ranging from $25,000-50,000 each.",
    "Monthly rental income deposits from sub-leased office space via check or ACH transfer averaging $3,500-4,500.",
    "Weekly payments to contract labor via ACH transfer or check, typically 5-10 transactions of $500-2,000 each.",
    "Recurring automatic payments for business vehicle loans totaling $2,200 monthly to established auto finance company.",
    "Quarterly estimated tax payments ranging from $15,000-25,000 depending on business profitability and seasonal factors.",
    "Monthly transfers between operating and payroll accounts averaging $45,000-55,000 based on current staffing levels.",
    "Periodic large deposits from construction project completions, typically 3-4 annually ranging from $50,000-100,000 each.",
    "Recurring monthly health insurance premium payments via ACH debit averaging $8,500-9,500 for employee coverage.",
    "Regular online bill payments to vendors and suppliers, 30-40 transactions monthly ranging from $250-3,000 each.",
    "Annual business insurance premium payment via check or wire transfer typically ranging from $15,000-20,000.",
    "Monthly revenue from credit card processing deposits averaging $120,000-150,000 from retail customer transactions.",
    "Periodic transfers to tax reserve account, typically $8,000-12,000 monthly based on projected tax obligations.",
    "Bi-weekly payroll processing for 25 employees via direct deposit totaling approximately $45,000 per pay period.",
    "Recurring monthly rent payment of $6,800 via check or ACH transfer to commercial property management company.",
    "Regular supplier payments via ACH or check, typically 20-30 transactions monthly ranging from $1,000-7,500 each.",
    "Quarterly bonus distributions to management team, typically totaling $30,000-50,000 based on performance metrics.",
    "Monthly business loan payment of $4,875 via automatic ACH debit for commercial mortgage on business premises.",
    "Regular cash deposits from retail operations averaging $3,000-5,000 daily with established transaction patterns.",
    "Periodic equipment purchases for business expansion, typically 2-3 transactions annually ranging from $15,000-75,000 each.",
    "Monthly transfers to business savings for equipment replacement reserves averaging $2,500-4,000 based on depreciation schedule.",
    "Weekly ACH debits for inventory purchases from primary distributor ranging from $8,000-12,000 based on sales volume.",
    "Regular incoming wire transfers from established export clients, typically 3-5 monthly ranging from $15,000-40,000 each.",
    "Monthly dividend distributions to four shareholders via ACH transfer, typically totaling $20,000-40,000 based on profitability.",
    "Periodic large check deposits from commercial insurance claims, typically 1-2 annually not exceeding $75,000 each.",
    "Regular payroll tax deposits via EFTPS system averaging $18,000-22,000 monthly based on current employee withholdings.",
    "Monthly utility and service payments via scheduled ACH debits totaling $3,500-4,500 for business operations.",
    "Quarterly franchise fee payments via wire transfer to parent company averaging $22,000-28,000 based on gross revenue.",
    "Regular credit card payments for business expenses, typically $12,000-18,000 monthly with itemized documentation.",
    "Periodic large outgoing wire transfers for equipment purchases, typically 1-2 annually ranging from $50,000-150,000 each.",
    "Monthly merchant account deposits averaging $180,000-220,000 from customer credit card transactions with supporting records.",
    "Regular transfers between business checking and investment accounts for cash management purposes averaging $25,000-50,000 monthly.",
    "Quarterly profit distributions to business partners via transfers to personal accounts, typically $30,000-60,000 each.",
    "Monthly professional service payments for legal, accounting, and consulting services averaging $4,000-7,000 via check or ACH.",
    "Periodic escrow deposits for business real estate transactions, typically 1-2 annually ranging from $25,000-100,000 each.",
    "Regular payroll processing via ACH for 35 employees totaling approximately $75,000 bi-weekly with appropriate tax withholdings.",
    "Monthly lease payments for business equipment totaling $5,200 via recurring ACH debits to established leasing company.",
    "Quarterly estimated tax payments via EFTPS or check ranging from $25,000-40,000 depending on profitability.",
    "Regular invoice payments to suppliers via check or ACH, typically 40-60 transactions monthly ranging from $500-8,000 each.",
    "Periodic international wire transfers to European suppliers, typically monthly ranging from $10,000-30,000 with supporting documentation.",
    "Monthly transfers to operating reserve account averaging $10,000-15,000 for business contingency planning.",
    "Regular incoming ACH transfers from third-party payment processors averaging $45,000-60,000 monthly from online sales.",
    "Bi-weekly transfers to payroll account of approximately $85,000 to cover upcoming employee compensation and taxes.",
    "Monthly business insurance premium payments via ACH debit totaling $4,200-4,800 for property and liability coverage.",
    "Periodic equipment maintenance payments via check or ACH ranging from $2,500-7,500 per scheduled service.",
    "Regular cash deposits from retail operations not exceeding daily amounts of $8,000 with established patterns by day of week.",
    "Monthly loan payment of $8,350 for business expansion financing via automatic ACH debit arrangement.",
    "Quarterly bonus payments to employees via payroll system, typically totaling $30,000-50,000 depending on company performance.",
    "Regular electronic deposits from healthcare insurance providers averaging $65,000-80,000 monthly for medical services rendered.",
    "Periodic large outgoing wire transfers for inventory purchases, typically quarterly ranging from $75,000-125,000 each.",
    "Monthly rent payment for commercial space via ACH transfer or check of $12,500 to property management company.",
    "Regular payments to marketing and advertising vendors via ACH or wire, typically $15,000-25,000 monthly based on campaigns.",
    "Quarterly technology infrastructure investments via wire transfer or ACH, typically ranging from $20,000-60,000 each.",
    "Monthly merchant processing fee deductions via ACH ranging from $3,500-4,500 based on credit card transaction volume.",
    "Regular transfers between related business entities for cash management purposes, typically $15,000-30,000 monthly.",
    "Periodic capital investments from business owners, typically 1-2 annually ranging from $50,000-250,000 as needed.",
    "Monthly service subscription payments via credit card or ACH for business software totaling $3,000-5,000.",
    "Regular payroll tax deposits via EFTPS system averaging $30,000-35,000 monthly based on employee compensation.",
    "Quarterly partnership distributions to five partners via transfers, typically totaling $75,000-150,000 based on profitability.",
    "Monthly rent collections from sub-tenants via check or ACH deposit averaging $8,500-10,000 for shared office space.",
    "Periodic facility improvement expenditures via check or wire, typically 2-3 annually ranging from $25,000-75,000 each.",
    "Regular incoming wire transfers from export clients in Asia, typically 2-3 monthly ranging from $25,000-60,000 each.",
    "Monthly transfers to tax reserve accounts averaging $15,000-25,000 based on projected tax liabilities.",
    "Recurring vendor payments via ACH or online bill pay, 50-70 transactions monthly ranging from $250-5,000 each.",
    "Quarterly insurance premium payments via ACH or check averaging $12,000-18,000 for various business coverages.",
    "Regular employee expense reimbursements via ACH, typically 15-25 transactions monthly ranging from $100-1,500 each.",
    "Monthly revenue from government contract payments via ACH credit averaging $85,000-110,000 with appropriate documentation.",
    "Periodic equipment leasing payments via ACH debit, typically totaling $8,500-10,000 monthly to multiple lessors.",
    "Regular transfers to business money market account for excess cash management averaging $20,000-40,000 monthly.",
    "Monthly credit card processing deposits averaging $250,000-300,000 from customer transactions with supporting records.",
    "Quarterly profit sharing payments to employees via payroll system, typically totaling $40,000-75,000 based on performance.",
    "Regular outgoing wire transfers to international suppliers, typically 5-8 monthly ranging from $10,000-35,000 each.",
    "Monthly commercial mortgage payment of $15,750 via recurring ACH debit for business property financing.",
    "Periodic large check deposits from business insurance claims, typically 1-2 annually not exceeding $100,000 each.",
    "Regular cash deposits from daily business operations averaging $5,000-8,000 with consistent weekly patterns.",
    "Monthly healthcare premium payments via ACH debit averaging $12,000-15,000 for employee benefit coverage.",
    "Quarterly tax estimate payments via EFTPS ranging from $40,000-60,000 depending on business performance.",
    "Regular incoming ACH credits from online payment platforms averaging $75,000-95,000 monthly from e-commerce sales.",
    "Periodic investment purchases for business treasury management, typically 3-4 annually ranging from $50,000-200,000 each.",
    "Monthly transfers between operating and payroll accounts averaging $120,000-150,000 based on current staffing levels.",
    "Regular vendor payments via ACH and check, typically 60-80 transactions monthly ranging from $500-12,000 each.",
    "Quarterly dividend distributions to shareholders via ACH or wire transfer, typically totaling $50,000-100,000 based on profitability.",
    "Monthly professional service payments for outsourced operations averaging $20,000-30,000 via wire or ACH.",
    "Periodic large deposits from project completions or contract milestones, typically 4-6 annually ranging from $75,000-200,000 each.",
    "Regular equipment maintenance payments via ACH or check, typically 8-12 transactions annually ranging from $5,000-15,000 each.",
    "Monthly rent payment for multiple business locations totaling $22,500 via ACH transfers to property managers.",
    "Quarterly royalty payments to intellectual property holders via wire transfer averaging $25,000-40,000 based on sales volume.",
    "Regular loan payments for equipment financing totaling $12,500 monthly via recurring ACH debits to multiple lenders.",
    "Periodic international wire transfers for overseas operations support, typically monthly ranging from $25,000-75,000 each.",
    "Monthly payroll processing for 50+ employees via direct deposit totaling approximately $225,000 with appropriate tax withholdings.",
    "Regular transfers to capital expenditure reserve account averaging $25,000-40,000 monthly for future expansion plans.",
    "Quarterly performance bonuses to management team via ACH, typically totaling $75,000-125,000 based on business metrics.",
    "Monthly inventory purchases from primary vendors via ACH or wire transfer averaging $150,000-200,000 with supporting documentation.",
    "Periodic tax refund deposits from amended filings, typically 1-2 annually not exceeding $35,000 each.",
    "Regular incoming wire transfers from commercial clients, typically 10-15 monthly ranging from $5,000-50,000 each.",
    "Monthly service contract payments via ACH debits totaling $8,000-12,000 for maintenance and support agreements.",
    "Quarterly facility lease payments via wire transfer or check averaging $45,000-55,000 for commercial properties.",
    "Regular employee benefit provider payments via ACH, typically 5-8 monthly totaling $18,000-25,000 for various programs.",
    "Periodic capital investments in business equipment via wire transfer, typically 2-3 annually ranging from $100,000-350,000 each.",
    "Monthly liability insurance premium payments via ACH debit averaging $8,500-10,500 for business operation coverage.",
    "Regular transfers between business entities for centralized cash management, typically $50,000-100,000 monthly.",
    "Quarterly distribution of profits to multiple partners via ACH transfers, typically totaling $100,000-200,000 based on performance.",
    "Monthly credit card processing deposits from customer payments averaging $350,000-450,000 with supporting transaction records.",
    "Periodic large wire transfers for real estate acquisitions, typically 1-2 annually ranging from $200,000-1,000,000 each.",
    "Regular payroll tax deposits via EFTPS system averaging $65,000-80,000 monthly based on employee compensation levels.",
    "Monthly utility and service payments for multiple locations via ACH debits totaling $15,000-22,000 based on seasonal factors.",
    "Quarterly estimated tax payments via wire transfer ranging from $75,000-125,000 depending on business profitability.",
    "Regular supplier payments via ACH and wire transfer, typically 80-100 transactions monthly ranging from $1,000-20,000 each.",
    "Periodic receipt of large insurance proceeds for business claims, typically 1-2 annually not exceeding $250,000 each.",
    "Monthly commercial loan payments totaling $28,500 via recurring ACH debits for multiple business financing obligations.",
    "Regular transfers to business investment accounts for excess cash management averaging $50,000-100,000 monthly.",
    "Quarterly franchise royalty payments via wire transfer averaging $75,000-100,000 based on revenue sharing agreement.",
    "Monthly revenue from government or institutional clients via ACH credit averaging $200,000-250,000 with contract documentation.",
    "Periodic large capital expenditures via wire transfer, typically 3-4 annually ranging from $100,000-500,000 each.",
    "Regular cash deposits from retail operations averaging $10,000-15,000 daily with consistent patterns by location.",
    "Monthly payroll processing via ACH for 100+ employees totaling approximately $450,000 with appropriate tax withholdings.",
    "Quarterly profit sharing distributions to partners via transfers, typically totaling $150,000-300,000 based on performance.",
    "Regular international wire transfers to multiple suppliers, typically 15-20 monthly ranging from $10,000-75,000 each.",
    "Monthly property management fee payments via ACH debits averaging $18,000-25,000 for multiple commercial locations.",
    "Periodic large check deposits from insurance reimbursements, typically monthly totaling $85,000-120,000 for services rendered.",
    "Regular transfers between operating accounts and cash management vehicles averaging $75,000-150,000 for optimal returns.",
    "Monthly professional service payments for outsourced business functions totaling $35,000-50,000 via wire or ACH.",
    "Quarterly tax payments to multiple jurisdictions via wire transfer or ACH, typically totaling $100,000-175,000 based on activity.",
    "Regular incoming wire transfers from distribution partners, typically 8-12 monthly ranging from $25,000-100,000 each.",
    "Monthly dividend payments to investor group via ACH or wire transfer averaging $50,000-75,000 based on profit sharing agreement.",
    "Periodic equipment upgrade expenditures via wire transfer, typically 2-3 annually ranging from $150,000-500,000 each.",
    "Regular payroll processing for seasonal workforce fluctuating between $300,000-600,000 monthly based on business cycle.",
    "Monthly commercial rent payments for multiple locations totaling $65,000 via ACH transfers to various property managers.",
    "Quarterly bonus distributions to executive team, typically totaling $200,000-400,000 based on performance targets.",
    "Regular vendor payments via ACH and wire, typically 120-150 transactions monthly ranging from $1,000-30,000 each.",
    "Periodic large deposits from significant contract awards, typically 3-5 annually ranging from $250,000-1,000,000 each.",
    "Monthly marketing and advertising payments via ACH or wire averaging $45,000-65,000 to multiple service providers.",
    "Regular international payments for global operations support, typically 20-30 monthly ranging from $5,000-50,000 each.",
    "Quarterly partnership distributions to multiple investors via wire transfer, typically totaling $250,000-500,000 based on agreement.",
    "Monthly revenue from credit card processing and online payments averaging $750,000-1,000,000 with supporting transaction records.",
    "Periodic large wire transfers for business acquisitions, typically 1-2 annually ranging from $500,000-5,000,000 each.",
    "Regular employee benefit program payments via ACH debits totaling $75,000-100,000 monthly for comprehensive offerings.",
    "Monthly commercial property expenses via various payment methods totaling $40,000-60,000 for maintenance and operations.",
    "Quarterly capital expenditures for infrastructure improvements via wire transfer ranging from $200,000-750,000 each.",
    "Regular supplier payments for inventory via ACH and wire transfer averaging $500,000-750,000 monthly with appropriate documentation.",
    "Monthly revenue from institutional clients via ACH credits averaging $850,000-1,200,000 with contractual support.",
    "Periodic receipt of significant investment capital, typically 1-2 annually ranging from $1,000,000-10,000,000 for expansion.",
    "Regular payroll tax deposits via EFTPS system averaging $180,000-220,000 monthly based on employee compensation.",
    "Monthly transfers between operating and investment accounts for cash management averaging $200,000-500,000 based on liquidity needs.",
    "Quarterly distribution of profits to shareholder group via wire transfers, typically totaling $500,000-1,500,000 based on performance."
]
