small_business_banking__business_card_users__merchant_category_restrictions = [
  "{\"blocked_categories\": [\"gambling\", \"adult entertainment\"]}",
  "{\"allowed_categories\": [\"office supplies\", \"travel\"]}",
  "{\"max_spend_per_category\": {\"restaurants\": 500, \"fuel\": 200}}",
  "{\"blocked_merchants\": [\"Amazon\", \"Walmart\"]}",
  "{\"require_approval_for_categories\": [\"electronics\", \"luxury goods\"]}",
  "{\"allowed_mcc_codes\": [5122, 5541, 5912]}",
  "{\"blocked_mcc_codes\": [7993, 7933, 7273]}",
  "{\"max_transaction_amount\": 1000}",
  "{\"allowed_countries\": [\"US\", \"CA\"]}",
  "{\"blocked_countries\": [\"CN\", \"RU\"]}",
  "{\"require_receipt_for_categories\": [\"entertainment\", \"gifts\"]}",
  "{\"require_approval_for_merchants\": [\"Apple\", \"Best Buy\"]}",
  "{\"max_spend_per_merchant\": {\"Home Depot\": 1000, \"Lowes\": 1000}}",
  "{\"allowed_transaction_types\": [\"purchase\", \"refund\"]}",
  "{\"blocked_transaction_types\": [\"cash advance\", \"balance transfer\"]}",
  "{\"require_approval_for_international\": true}",
  "{\"require_approval_for_online\": true}",
  "{\"max_spend_per_day\": 500}",
  "{\"max_spend_per_week\": 2000}",
  "{\"allowed_days_of_week\": [\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\"]}",
  "{\"blocked_days_of_week\": [\"Saturday\", \"Sunday\"]}",
  "{\"allowed_time_of_day\": {\"start\": \"09:00\", \"end\": \"17:00\"}}",
  "{\"blocked_time_of_day\": {\"start\": \"22:00\", \"end\": \"06:00\"}}",
  "{\"require_approval_for_recurring\": true}",
  "{\"max_number_of_transactions_per_day\": 10}",
  "{\"max_number_of_transactions_per_week\": 50}",
  "{\"require_approval_for_high_risk_merchants\": true}",
  "{\"require_approval_for_new_merchants\": true}",
  "{\"require_manager_approval\": true}",
  "{\"require_department_head_approval\": true}",
  "{\"require_finance_team_approval\": true}",
  "{\"require_approval_for_amount_over\": 500}",
  "{\"require_approval_for_amount_under\": 10}",
  "{\"require_approval_for_first_time_merchant\": true}",
  "{\"require_approval_for_suspicious_activity\": true}",
  "{\"require_approval_for_declined_transactions\": true}",
  "{\"require_approval_for_duplicate_transactions\": true}",
  "{\"require_approval_for_out_of_policy_transactions\": true}",
  "{\"require_approval_for_high_risk_countries\": true}",
  "{\"require_approval_for_card_not_present_transactions\": true}",
  "{\"require_approval_for_recurring_transactions_over\": 100}",
  "{\"require_approval_for_cash_withdrawals_over\": 50}",
  "{\"require_approval_for_balance_transfers_over\": 1000}",
  "{\"require_approval_for_international_transactions_over\": 200}",
  "{\"require_approval_for_online_transactions_over\": 500}",
  "{\"require_approval_for_gas_station_transactions_over\": 100}",
  "{\"require_approval_for_restaurant_transactions_over\": 200}",
  "{\"require_approval_for_hotel_transactions_over\": 500}",
  "{\"require_approval_for_airline_transactions_over\": 1000}",
  "{\"require_approval_for_car_rental_transactions_over\": 300}",
  "{\"require_approval_for_entertainment_transactions_over\": 200}",
  "{\"require_approval_for_gift_transactions_over\": 100}",
  "{\"require_approval_for_grocery_transactions_over\": 200}",
  "{\"require_approval_for_pharmacy_transactions_over\": 100}",
  "{\"require_approval_for_utilities_transactions_over\": 300}",
  "{\"require_approval_for_telecom_transactions_over\": 200}",
  "{\"require_approval_for_education_transactions_over\": 1000}",
  "{\"require_approval_for_healthcare_transactions_over\": 500}",
  "{\"require_approval_for_charity_transactions_over\": 100}",
  "{\"require_approval_for_government_transactions_over\": 500}",
  "{\"require_approval_for_insurance_transactions_over\": 300}",
  "{\"require_approval_for_legal_transactions_over\": 500}",
  "{\"require_approval_for_accounting_transactions_over\": 300}",
  "{\"require_approval_for_consulting_transactions_over\": 500}",
  "{\"require_approval_for_marketing_transactions_over\": 200}",
  "{\"require_approval_for_advertising_transactions_over\": 100}",
  "{\"require_approval_for_public_relations_transactions_over\": 200}",
  "{\"require_approval_for_event_planning_transactions_over\": 500}",
  "{\"require_approval_for_travel_agency_transactions_over\": 1000}",
  "{\"require_approval_for_shipping_transactions_over\": 100}",
  "{\"require_approval_for_printing_transactions_over\": 50}",
  "{\"require_approval_for_office_supplies_transactions_over\": 200}",
  "{\"require_approval_for_furniture_transactions_over\": 500}",
  "{\"require_approval_for_equipment_rental_transactions_over\": 300}",
  "{\"require_approval_for_software_transactions_over\": 1000}",
  "{\"require_approval_for_technology_transactions_over\": 500}",
  "{\"require_approval_for_maintenance_transactions_over\": 100}",
  "{\"require_approval_for_repair_transactions_over\": 200}",
  "{\"require_approval_for_construction_transactions_over\": 1000}",
  "{\"require_approval_for_real_estate_transactions_over\": 5000}",
  "{\"require_approval_for_transportation_transactions_over\": 300}",
  "{\"require_approval_for_logistics_transactions_over\": 500}",
  "{\"require_approval_for_warehousing_transactions_over\": 200}",
  "{\"require_approval_for_manufacturing_transactions_over\": 1000}",
  "{\"require_approval_for_wholesale_transactions_over\": 500}",
  "{\"require_approval_for_retail_transactions_over\": 200}",
  "{\"require_approval_for_e-commerce_transactions_over\": 1000}",
  "{\"require_approval_for_food_and_beverage_transactions_over\": 200}",
  "{\"require_approval_for_hospitality_transactions_over\": 500}",
  "{\"require_approval_for_tourism_transactions_over\": 1000}",
  "{\"require_approval_for_entertainment_and_leisure_transactions_over\": 200}",
  "{\"require_approval_for_arts_and_culture_transactions_over\": 100}",
  "{\"require_approval_for_sports_and_recreation_transactions_over\": 200}",
  "{\"require_approval_for_education_and_training_transactions_over\": 1000}",
  "{\"require_approval_for_healthcare_and_social_assistance_transactions_over\": 500}",
  "{\"require_approval_for_non-profit_transactions_over\": 100}",
  "{\"require_approval_for_government_and_public_administration_transactions_over\": 500}",
  "{\"require_approval_for_professional_services_transactions_over\": 500}",
  "{\"require_approval_for_scientific_and_technical_services_transactions_over\": 1000}",
  "{\"require_approval_for_administrative_and_support_services_transactions_over\": 300}",
  "{\"require_approval_for_waste_management_and_remediation_services_transactions_over\": 200}",
  "{\"require_approval_for_agriculture_forestry_fishing_and_hunting_transactions_over\": 500}",
  "{\"require_approval_for_mining_quarrying_and_oil_and_gas_extraction_transactions_over\": 1000}",
  "{\"require_approval_for_utilities_transactions_over\": 300}",
  "{\"require_approval_for_construction_transactions_over\": 1000}",
  "{\"require_approval_for_manufacturing_transactions_over\": 1000}",
  "{\"require_approval_for_wholesale_trade_transactions_over\": 500}",
  "{\"require_approval_for_retail_trade_transactions_over\": 200}",
  "{\"require_approval_for_transportation_and_warehousing_transactions_over\": 500}",
  "{\"require_approval_for_information_transactions_over\": 1000}",
  "{\"require_approval_for_finance_and_insurance_transactions_over\": 500}",
  "{\"require_approval_for_real_estate_rental_and_leasing_transactions_over\": 300}",
  "{\"require_approval_for_professional_scientific_and_technical_services_transactions_over\": 500}",
  "{\"require_approval_for_management_of_companies_and_enterprises_transactions_over\": 1000}",
  "{\"require_approval_for_administrative_and_waste_services_transactions_over\": 300}",
  "{\"require_approval_for_educational_services_transactions_over\": 1000}",
  "{\"require_approval_for_health_care_and_social_assistance_transactions_over\": 500}",
  "{\"require_approval_for_arts_entertainment_and_recreation_transactions_over\": 200}",
  "{\"require_approval_for_accommodation_and_food_services_transactions_over\": 500}",
  "{\"require_approval_for_other_services_except_public_administration_transactions_over\": 200}",
  "{\"require_approval_for_public_administration_transactions_over\": 500}"
]
