small_business_banking__loan_fair_lending__denial_reason_1 = [
  "Insufficient cash flow to service proposed debt based on debt service coverage ratio of 0.87:1, below required 1.20:1 minimum.",
  "Inadequate collateral value with loan-to-value ratio of 92% exceeding policy maximum of 80% for commercial real estate.",
  "Excessive leverage with debt-to-worth ratio of 5.3:1, above policy maximum of 3.0:1 for industry classification.",
  "Unacceptable credit history with multiple delinquencies on existing debt obligations within the past 12 months.",
  "Insufficient business operating history with only 9 months of operations, below 24-month minimum requirement.",
  "Negative cash flow demonstrated in two consecutive years of business tax returns (2021-2022).",
  "Inadequate owner liquidity to support operations during projected growth phase based on cash flow analysis.",
  "Unacceptable business credit score of 32, below minimum threshold of 50 for approval consideration.",
  "Excessive concentration in single industry with loan request exceeding internal exposure limits.",
  "Collateral property environmental concerns identified in Phase I Environmental Site Assessment.",
  "Inadequate management experience in relevant industry with principal having less than 12 months in current business type.",
  "Excessive existing contingent liabilities that materially impact global cash flow and repayment capacity.",
  "Unrealistic business projections unsupported by historical performance or industry benchmarks.",
  "Unacceptable personal credit score of 578 for guarantor, below minimum requirement of 650.",
  "Significant judgments or liens identified in public records search against business or principals.",
  "Unresolved pending litigation with potential material impact on business operations or financial condition.",
  "Inability to verify critical financial information provided in application package after multiple requests.",
  "Collateral property located outside approved lending territory per bank policy guidelines.",
  "Unstable or declining revenue trend based on three years of business financial statements (2020-2022).",
  "Excessive debt relative to business cash flow with proposed debt to EBITDA ratio of 7.2x, above 4.5x maximum.",
  "Material adverse change in financial condition since application submission date.",
  "Unacceptable business repayment history with existing creditors showing multiple late payments.",
  "Insufficient owner investment with equity contribution below required 20% of project costs.",
  "Significant tax liens identified against business assets that impair collateral position.",
  "Inadequate business liquidity with current ratio of 0.68:1, below required 1.1:1 minimum for industry.",
  "Material discrepancy in financial information provided compared to third-party verified data.",
  "Excessive project cost relative to demonstrated business repayment capacity and industry benchmarks.",
  "Inadequate cash reserves to manage seasonal fluctuations based on historical operating cycle.",
  "Unacceptable appraisal with material limiting conditions affecting collateral valuation reliability.",
  "Significant concentration risk with single customer representing over 65% of total business revenue.",
  "Insufficient documentation to validate source of cash equity for proposed project after multiple requests.",
  "Unacceptable industry risk due to demonstrated volatility and unfavorable economic outlook.",
  "Inadequate secondary source of repayment with guarantor showing limited outside income or liquid assets.",
  "Excessive lease or rental expense relative to industry norms impacting overall cash flow.",
  "Significant deferred maintenance on collateral property identified during site inspection.",
  "Unacceptable prior bankruptcy of business principal within past 48 months (discharged June 2021).",
  "Inadequate business credit references with multiple suppliers reporting slow payment history.",
  "Failure to meet critical loan covenant on existing debt with no realistic remediation plan.",
  "Significant variance between tax returns and financial statements without satisfactory explanation.",
  "Unacceptable collateral type for requested loan purpose per bank policy guidelines.",
  "Inadequate gross profit margins relative to industry benchmarks indicating potential business model weakness.",
  "Significant undisclosed liabilities discovered during underwriting verification process.",
  "Unacceptable ownership structure with inability to obtain required guarantees from all principal owners.",
  "Inadequate debt service reserve funds relative to projected cash flow volatility.",
  "Significant accounts receivable concentration with high percentage of past-due status.",
  "Unacceptable loan structure with requested terms exceeding policy guidelines for amortization period.",
  "Inadequate inventory management with turnover ratios significantly below industry benchmarks.",
  "Significant discrepancy between projected and actual performance on previous financing.",
  "Unacceptable property zoning for proposed business use indicated in loan purpose.",
  "Inadequate insurance coverage relative to business assets and operational risks.",
  "Significant related-party transactions without adequate documentation or economic justification.",
  "Unacceptable length of ownership with business recently acquired and lacking performance history under current management.",
  "Inadequate working capital to support projected growth based on cash conversion cycle analysis.",
  "Significant customer concentration risk with top three clients representing over 70% of revenue.",
  "Unacceptable financial information quality with inconsistent or incompatible accounting methods.",
  "Inadequate financial controls with deficiencies noted in internal accounting and reporting systems.",
  "Significant currency in declared total income that cannot be verified through traditional sources.",
  "Unacceptable site location for proposed business expansion based on market analysis.",
  "Inadequate sales-to-assets ratio indicating inefficient use of business resources compared to industry norms.",
  "Significant upward trend in operating expenses without corresponding revenue growth.",
  "Unacceptable profitability with net margin below 2% for past three consecutive years.",
  "Inadequate accounts receivable quality with aging showing over 40% beyond 90 days past due.",
  "Significant seasonal fluctuation in cash flow without adequate reserves or mitigation strategy.",
  "Unacceptable collateral control issues preventing perfection of security interest.",
  "Inadequate debt capacity with fixed charge coverage ratio of 0.92:1, below required 1.15:1 minimum.",
  "Significant inventory obsolescence indicated in product aging report affecting collateral value.",
  "Unacceptable guarantee strength with guarantor showing negative net worth excluding primary residence.",
  "Inadequate equipment maintenance evident in site inspection affecting collateral value and useful life.",
  "Significant market area decline where business operations are concentrated based on economic indicators.",
  "Unacceptable financial statement quality with compilation vs required review or audit level.",
  "Inadequate business succession planning for owner-dependent operation with aging principal.",
  "Significant deviation from industry norms in key operating ratios without satisfactory explanation.",
  "Unacceptable business credit report with multiple collection accounts and past-due trade lines.",
  "Inadequate business cash flow to personal income ratio for owner-operated business model.",
  "Significant reduction in line of credit availability from existing lenders indicating increased risk perception.",
  "Unacceptable lease terms with impending expiration and no documented renewal option.",
  "Inadequate financial covenant compliance on existing debt obligations with multiple waivers required.",
  "Significant decline in business backlog or order pipeline compared to previous operating periods.",
  "Unacceptable payment history on existing bank obligations with multiple instances of 30+ day delinquency.",
  "Inadequate documentation of business cash flow with bank statements inconsistent with reported income.",
  "Significant customer contract expirations without documented renewals affecting revenue stability.",
  "Unacceptable conduct by applicant during application process, including material misrepresentations.",
  "Inadequate project budget with contingency reserves below required minimum for project scope.",
  "Significant tax payment delinquencies without approved payment plan in place.",
  "Unacceptable loan purpose not meeting business banking policy guidelines for commercial financing.",
  "Inadequate equity-to-assets ratio of 11%, below required 20% minimum for loan request size.",
  "Significant changes in business model or strategy without demonstrated success in new direction.",
  "Unacceptable global cash flow analysis with debt service coverage ratio below 1.0 including all obligations.",
  "Inadequate business plan with insufficient detail regarding market analysis and competitive positioning.",
  "Significant deferred taxes without adequate reserves or payment strategy in place.",
  "Unacceptable receivables quality with high concentration in single payor or industry sector.",
  "Inadequate management depth with business operations critically dependent on single individual.",
  "Significant regulatory compliance issues identified during due diligence process.",
  "Unacceptable collateral depreciation rate relative to proposed loan amortization schedule.",
  "Inadequate break-even analysis with projected volume significantly above historical performance.",
  "Significant discrepancy in reported business revenue between tax returns and loan application.",
  "Unacceptable ownership structure complexity preventing clear understanding of control and responsibility.",
  "Inadequate documentation of cash equity injection source indicating potentially borrowed funds.",
  "Significant discrepancy between business address and actual operating location without explanation.",
  "Unacceptable property condition based on inspection report with material deferred maintenance issues.",
  "Inadequate financial record keeping with significant gaps in documentation provided.",
  "Significant ongoing operating losses with no credible path to profitability in business plan.",
  "Unacceptable business debt yield ratio of 6.8%, below minimum requirement of 9.0% for loan type.",
  "Inadequate principal industry experience for specialized business operation or expansion plan.",
  "Significant recent ownership changes with limited operating history under current structure.",
  "Unacceptable profit trend with consecutive quarterly declines throughout preceding fiscal year.",
  "Inadequate liquidity ratios with quick ratio of 0.42:1, below industry benchmark of 0.8:1.",
  "Significant volatility in monthly cash flow patterns indicating unstable business operations.",
  "Unacceptable legal structure for proposed financing per commercial loan policy requirements.",
  "Inadequate market analysis in business plan with unrealistic competitive positioning assumptions.",
  "Significant declining collateral value in proposed security property based on recent market analysis.",
  "Unacceptable concentration in assets proposed as loan collateral relative to total business assets.",
  "Inadequate documentation of business licensing or required regulatory approvals for operations.",
  "Significant recent credit inquiries indicating potential additional undisclosed debt obligations.",
  "Unacceptable debt to tangible net worth ratio of 4.8:1, exceeding policy maximum of 3.5:1.",
  "Inadequate financial cushion with minimal cash reserves relative to monthly operating expenses.",
  "Significant number of business NSF or returned items within review period indicating cash flow stress.",
  "Unacceptable reliance on related party transactions representing over 35% of total revenue.",
  "Inadequate internal controls with commingling of business and personal finances evident in bank statements.",
  "Significant pending tax assessment or audit that materially impacts financial projections.",
  "Unacceptable level of cash transactions relative to documented business model and industry norms.",
  "Inadequate documentation to support projected revenue increase in business plan assumptions.",
  "Significant discrepancy between tax returns and financial statements regarding owner compensation.",
  "Unacceptable turnover in key management positions indicating potential business instability.",
  "Inadequate debt to tangible net worth ratio of 8.2:1, substantially exceeding industry norm of 3.0:1.",
  "Significant pension or retirement plan funding deficiencies creating contingent liability risk.",
  "Unacceptable environmental history of collateral property with prior contamination issues.",
  "Inadequate sales volume relative to inventory levels indicating potential obsolescence concerns.",
  "Significant contingent liabilities from pending litigation with potential material financial impact.",
  "Unacceptable customer base stability with high turnover in major accounts during past 12 months.",
  "Inadequate owner experience in managing debt obligations of requested size and complexity.",
  "Significant industry risk factors including pending regulatory changes affecting business model.",
  "Unacceptable guarantor credit history with charge-offs and collection accounts in past 24 months.",
  "Inadequate operational cash flow coverage of proposed debt payment with ratio of 0.95:1.",
  "Significant variances between interim financial statements and year-end audited results.",
  "Unacceptable asset quality with equipment exceeding typical useful life for industry standards.",
  "Inadequate financial reporting frequency with statements provided only annually versus required quarterly.",
  "Significant lease obligations not reflected in financial statements materially affecting debt service capacity.",
  "Unacceptable accounts payable aging with substantial portion exceeding 90 days indicating liquidity issues.",
  "Inadequate gross profit margin of 18% compared to industry average of 35% for similar operations.",
  "Significant past-due tax obligations without formal installment agreement in place.",
  "Unacceptable bond or surety capacity for project size and scope based on industry requirements.",
  "Inadequate capital expenditure planning with essential equipment replacement needs unaddressed.",
  "Significant cash flow seasonality without demonstrated effective management strategy in place.",
  "Unacceptable market share trend with documented decline in competitive positioning.",
  "Inadequate documentation of required professional licensing for specialized business operations.",
  "Significant reliance on single supplier representing over 65% of material inputs creating dependency risk.",
  "Unacceptable number of overdraft incidents on business accounts indicating cash flow management issues.",
  "Inadequate sales pipeline documentation to support revenue projections in loan request.",
  "Significant weakness in operating efficiency with labor cost ratio exceeding industry benchmarks.",
  "Unacceptable refinance purpose with minimal economic benefit compared to existing debt structure.",
  "Inadequate business continuity planning for operation critically dependent on key individuals.",
  "Significant expense ratio deterioration trend without corresponding productivity improvements.",
  "Unacceptable guarantor liquidity with minimal liquid assets relative to size of requested loan guarantee.",
  "Inadequate collateral margins with loan-to-cost ratio of 95% exceeding policy maximum of 80%.",
  "Significant pending legislation or regulatory changes with potential adverse impact on business model.",
  "Unacceptable delinquency history on trade payables with multiple vendors reporting past-due status.",
  "Inadequate insurance coverage for key personnel in owner-dependent business operation.",
  "Significant competitive market pressure from new entrants in primary business territory.",
  "Unacceptable collateral location in area with documented economic decline and property value deterioration.",
  "Inadequate business exit strategy or succession planning for loan term exceeding owner retirement timeline.",
  "Significant existing loan covenant violations without formal waiver or resolution documentation.",
  "Unacceptable customer acquisition cost relative to lifetime value based on historical data.",
  "Inadequate industry experience for specialized operation with owner actively engaged for less than two years.",
  "Significant funding gaps in project budget with unidentified sources for required additional capital.",
  "Unacceptable level of personal withdrawals from business affecting entity's debt service capacity.",
  "Inadequate business premises condition with building code violations noted in recent inspection.",
  "Significant undisclosed business interests of owner creating unknown contingent liability exposure.",
  "Unacceptable quality of receivables with concentration in financially distressed customer segment.",
  "Inadequate inventory controls with unexplained shrinkage exceeding industry standard percentages.",
  "Significant risk of technology obsolescence in core business equipment proposed as collateral.",
  "Unacceptable commercial real estate concentration exceeding regulatory guidance thresholds.",
  "Inadequate employee retention with high turnover in key operational positions affecting stability.",
  "Significant loss of major customer representing over 20% of revenue within past six months.",
  "Unacceptable cash handling controls with inadequate separation of duties in small business context.",
  "Inadequate profit reinvestment with excessive distributions relative to business capital needs.",
  "Significant risk from pending intellectual property claims affecting core business processes.",
  "Unacceptable loan request structure with balloon payment requirements exceeding policy guidelines.",
  "Inadequate budget variance analysis with actual results consistently below projections.",
  "Significant weakness in product or service diversification creating concentrated business risk.",
  "Unacceptable trend in gross revenue with consecutive annual declines of greater than 10%.",
  "Inadequate analysis of accounts receivable with unclear aging methodology and collection practices.",
  "Significant outstanding tax liens on business assets affecting collateral position priority.",
  "Unacceptable documentation of cash flow with unexplained large deposits inconsistent with business model.",
  "Inadequate financial stability with net losses in two of past three fiscal years.",
  "Significant principal distributions exceeding net income affecting business capitalization.",
  "Unacceptable concentration in high-risk product lines subject to pending regulatory changes.",
  "Inadequate expertise in proposed expansion area with limited demonstrated success in new field.",
  "Significant fluctuations in monthly sales exceeding 50% variation without seasonal explanation."
]
