small_business_banking__loan_fair_lending__denial_reason_2 = [
    "Inadequate business cash reserves with only 15 days of operating expenses maintained, below 45-day minimum requirement.",
    "Unacceptable loan-to-value ratio of 87% exceeding maximum guideline of 75% for requested loan purpose.",
    "Insufficient management experience with principal operating current business type for only 14 months.",
    "Excessive debt-to-income ratio of 56% for guarantor, above maximum guideline of 43% for personal guarantee.",
    "Inadequate collateral with liquidation value covering only 65% of requested loan amount versus required 100% coverage.",
    "Unacceptable business credit score of 175 on SBSS, below minimum threshold of 160 for approval consideration.",
    "Insufficient owner's equity investment representing only 12% of total project cost versus required 20% minimum.",
    "Excessive industry concentration within current loan portfolio at 22%, above internal guideline of 15% for sector.",
    "Inadequate secondary repayment source with guarantor's liquid assets covering only 3 months of proposed debt service.",
    "Unacceptable profit trend with declining margins in each of past three fiscal years without reasonable explanation.",
    "Insufficient historical debt service coverage ratio of 0.95:1 based on prior two years' financial performance.",
    "Excessive reliance on single customer accounting for 65% of total sales creating unacceptable concentration risk.",
    "Inadequate working capital with current ratio of 0.78:1, below minimum requirement of 1.2:1 for industry type.",
    "Unacceptable personal credit history with recent bankruptcy discharge within past 36 months for primary guarantor.",
    "Insufficient business operating history with company established 12 months ago, below 24-month minimum requirement.",
    "Excessive judgments and liens against business assets affecting collateral position and lien priority.",
    "Inadequate market analysis in business plan with unrealistic sales projections unsupported by market data.",
    "Unacceptable financial statement quality with compilation only vs. required reviewed statements for loan size.",
    "Insufficient revenue stability with monthly fluctuations exceeding 35% without seasonal business justification.",
    "Excessive personal withdrawals from business depleting working capital needed for ongoing operations.",
    "Inadequate inventory management with turnover ratio of 2.4x annually versus industry average of 6x.",
    "Unacceptable accounts receivable quality with 45% beyond 90 days past due, exceeding 20% maximum guideline.",
    "Insufficient cash flow to support additional debt with debt service coverage ratio of 0.89:1 below 1.25:1 minimum.",
    "Excessive lease expense ratio at 12% of gross revenue compared to industry benchmark of 6% maximum.",
    "Inadequate business liquidity with quick ratio of 0.55:1 below minimum requirement of 0.9:1.",
    "Unacceptable guarantor liquidity with liquid assets covering only 4 months of proposed debt service obligations.",
    "Insufficient collateral diversification with single property representing 95% of total security package.",
    "Excessive operating expense ratio at 92% of gross revenue versus industry benchmark maximum of 80%.",
    "Inadequate business succession plan for owner-dependent operation with principal over age 65.",
    "Unacceptable use of proceeds with 40% of loan allocated to non-business purposes.",
    "Insufficient debt service coverage from global cash flow analysis at 0.92:1, below required 1.15:1 minimum.",
    "Excessive existing debt maturing within 12 months creating refinancing risk during loan term.",
    "Inadequate documentation of revenue sources with unexplained large deposits inconsistent with business model.",
    "Unacceptable leverage with proposed debt to tangible net worth ratio of 5.2:1, exceeding 3.0:1 maximum.",
    "Insufficient analysis of market competition in business plan with unrealistic market share projections.",
    "Excessive tax liabilities with delinquent payments and no formal resolution or payment plan in place.",
    "Inadequate management depth with operations critically dependent on single key individual.",
    "Unacceptable project feasibility with break-even point exceeding 75% of projected capacity.",
    "Insufficient collateral margin with advance rate exceeding internal guidelines by 25% for asset type.",
    "Excessive fluctuation in profit margins indicating unstable pricing strategy or cost control issues.",
    "Inadequate financial record keeping with incomplete financial statements and supporting documentation.",
    "Unacceptable number of recent credit inquiries indicating potential undisclosed debt obligations.",
    "Insufficient equity relative to proposed debt with equity comprising only 10% of total capitalization.",
    "Excessive owner salary and benefits relative to business size and industry benchmarks.",
    "Inadequate business debt yield ratio at 7.5%, below minimum requirement of 9% for loan type.",
    "Unacceptable trend in sales with year-over-year decline of 18% in most recent fiscal period.",
    "Insufficient equipment maintenance with deferred upkeep affecting operational reliability and collateral value.",
    "Excessive accounts payable aging with 38% beyond terms creating potential supply chain disruption risk.",
    "Inadequate gross profit margin at 22% compared to industry average of 38% for similar operations.",
    "Unacceptable cash flow-to-debt ratio with total liabilities at 8.2x annual cash flow versus 4.0x maximum.",
    "Insufficient controls in financial management with commingling of business and personal expenses.",
    "Excessive employee turnover ratio at 65% annually indicating potential management or operational issues.",
    "Inadequate sales-to-assets ratio at 0.8x versus industry benchmark of 1.5x minimum.",
    "Unacceptable concentration in high-risk product lines comprising 75% of total revenue stream.",
    "Insufficient analysis of cash flow seasonality with no demonstrated management strategy for cyclical nature.",
    "Excessive reliance on short-term debt for long-term asset financing creating maturity mismatch risk.",
    "Inadequate property insurance coverage at 65% of replacement value versus required 100% coverage.",
    "Unacceptable business organization with frequent operational structure changes in past 24 months.",
    "Insufficient customer base with top five clients representing 80% of total revenue stream.",
    "Excessive overhead costs at 45% of gross revenue versus industry standard of 30% maximum.",
    "Inadequate documentation of projected revenue growth with assumptions exceeding industry growth rates by 300%.",
    "Unacceptable level of returned items in deposit accounts with 12 incidents in past six months.",
    "Insufficient collateral marketability with highly specialized equipment having limited resale potential.",
    "Excessive related-party transactions representing 35% of total expenses without market-based pricing documentation.",
    "Inadequate expense control with operating costs increasing 25% while revenue remained flat.",
    "Unacceptable financial covenant compliance with multiple violations on existing debt obligations.",
    "Insufficient business plan detail regarding implementation timeline and resource allocation.",
    "Excessive personal guarantor credit utilization ratio at 85% of available credit versus 50% maximum.",
    "Inadequate vendor stability with critical supplier concentration creating potential inventory disruption risk.",
    "Unacceptable level of business credit card debt comprising 35% of total liabilities.",
    "Insufficient owner investment in proposed expansion with only 5% equity contribution versus required 25%.",
    "Excessive industry volatility with standard deviation of returns exceeding lending risk parameters.",
    "Inadequate internal controls with limited financial oversight and lack of separation of duties.",
    "Unacceptable equipment collateral with average age exceeding 75% of useful life for industry.",
    "Insufficient sales backlog with forward orders covering only 30 days of operations versus 90-day minimum.",
    "Excessive reliance on cash transactions representing 65% of sales without adequate controls.",
    "Inadequate accounts receivable management with average collection period of 78 days versus industry norm of 45 days.",
    "Unacceptable fixed charge coverage ratio of 0.88:1, below required minimum of 1.15:1 for loan type.",
    "Insufficient business premises control with lease expiring within 12 months and no renewal option documented.",
    "Excessive contingent liabilities from pending litigation with potential material adverse effect on operations.",
    "Inadequate inventory control systems with unexplained shrinkage exceeding 8% of total inventory value.",
    "Unacceptable principal credit score of 585, below minimum threshold of 660 for loan program.",
    "Insufficient business insurance coverage with key person insurance inadequate for operational dependency.",
    "Excessive customer returns and allowances at 15% of gross sales versus industry average of 3%.",
    "Inadequate business continuity planning for disaster recovery and succession management.",
    "Unacceptable collateral type for requested loan purpose per bank policy guidelines.",
    "Insufficient documentation of cash equity source with evidence suggesting potentially borrowed funds.",
    "Excessive owner distributions exceeding 85% of net income versus policy maximum of 50% for growth-stage business.",
    "Inadequate capitalization with tangible net worth representing only 8% of total assets.",
    "Unacceptable payment history on existing credit with three payments exceeding 30 days past due in last 12 months.",
    "Insufficient cash equity in project with loan-to-cost ratio of 92% exceeding maximum guideline of 80%.",
    "Excessive monthly loan payment at 22% of average monthly revenue versus policy maximum of 15%.",
    "Inadequate revenue diversification with 85% derived from single product line or service category.",
    "Unacceptable industry risk rating with elevated regulatory concerns for sector lending exposure.",
    "Insufficient guarantor strength with guarantor's net worth covering only 65% of requested loan amount.",
    "Excessive seasonal fluctuations with peak-to-trough revenue variation exceeding 70% without adequate reserves.",
    "Inadequate debt to tangible net worth ratio of 6.5:1, exceeding industry maximum of 3:1.",
    "Unacceptable quality of financial reporting with significant unexplained discrepancies between statements.",
    "Insufficient business liquidity with cash representing only 2% of annual operating expenses.",
    "Excessive operating losses in two consecutive fiscal periods without credible turnaround strategy.",
    "Inadequate management expertise in critical business function essential to proposed expansion.",
    "Unacceptable documentation of income sources with bank deposits inconsistent with reported revenue.",
    "Insufficient collateral control due to prior liens restricting ability to obtain required security position.",
    "Excessive fixed asset investment relative to revenue generation capacity and industry benchmarks.",
    "Inadequate project budget with contingency reserve below 10% minimum for project type and scope.",
    "Unacceptable business credit report with multiple collection accounts and slow payment history.",
    "Insufficient revenue-to-assets ratio indicating inefficient use of business resources versus industry norms.",
    "Excessive supplier concentration with single vendor providing 75% of inventory or critical components.",
    "Inadequate verification of financial information with material inconsistencies in reported figures.",
    "Unacceptable property condition based on inspection report indicating deferred maintenance issues.",
    "Insufficient industry experience for specialized business operation or planned expansion area.",
    "Excessive projected growth rate of 50% annually without demonstrated capacity or market justification.",
    "Inadequate business tax payment history with multiple quarters of delinquent employment taxes.",
    "Unacceptable debt yield of 7.2% for commercial real estate collateral versus minimum requirement of 10%.",
    "Insufficient operating margin at 3.5% versus industry average of 12% for comparable businesses.",
    "Excessive exposure to pending regulatory changes affecting core business operations or revenue model.",
    "Inadequate inventory turnover at 2.1x annually versus industry benchmark of 6x minimum.",
    "Unacceptable collateral valuation methodology with material limiting conditions affecting reliability.",
    "Insufficient cash flow stability with standard deviation exceeding 40% of mean monthly cash flow.",
    "Excessive reliance on third-party financing of customer purchases representing 60% of total sales.",
    "Inadequate business premises with capacity constraints limiting growth potential during loan term.",
    "Unacceptable concentration in accounts receivable with single customer representing 45% of total outstanding.",
    "Insufficient equipment maintenance reserves for mission-critical operational assets.",
    "Excessive foreign exchange exposure with 55% of costs in different currency than revenue stream.",
    "Inadequate technology infrastructure with systems beyond recommended replacement cycle.",
    "Unacceptable market position trend with documented loss of market share in two consecutive years.",
    "Insufficient employee staffing for current operations creating delivery risk for projected growth.",
    "Excessive risk from intellectual property disputes affecting core product or service offering.",
    "Inadequate professional licensing or certification for regulated business activities.",
    "Unacceptable loan structure with interest-only period exceeding policy guidelines for loan type.",
    "Insufficient documentation of business legal structure with incomplete governance documentation.",
    "Excessive refinancing frequency with three debt restructurings in past 36 months.",
    "Inadequate capacity utilization with operations at 45% of available capacity indicating inefficiency.",
    "Unacceptable ownership structure with indirect or complex arrangements obscuring beneficial control.",
    "Insufficient geographic diversification with 90% of revenue from single economic region.",
    "Excessive liability insurance claims history indicating operational risk management deficiencies.",
    "Inadequate profit retention with distributions exceeding net income in most recent fiscal year.",
    "Unacceptable quick ratio of 0.5:1 indicating potential inability to meet short-term obligations.",
    "Insufficient sales-per-employee ratio at 50% of industry average indicating operational inefficiency.",
    "Excessive customer acquisition cost relative to customer lifetime value based on historical data.",
    "Inadequate documentation of inventory valuation methodology and supporting records.",
    "Unacceptable current ratio of 0.75:1 versus required minimum of 1.2:1 for industry category.",
    "Insufficient evidence of required regulatory compliance for business operations or expansion.",
    "Excessive integration risk for recently acquired business comprising 60% of projected revenue.",
    "Inadequate accounts payable management with average days outstanding of 75 versus terms of 30 days.",
    "Unacceptable level of business tax debt with payments 120 days past due without approved plan.",
    "Insufficient documentation to verify annual revenue figures with material unexplained discrepancies.",
    "Excessive contract cancellation rate of 35% annually indicating customer satisfaction or delivery issues.",
    "Inadequate fraud prevention controls with recent internal loss incidents reported.",
    "Unacceptable interest coverage ratio of 1.1:1 versus required minimum of 2.0:1 for loan structure.",
    "Insufficient equipment appraisal with valuation based on inappropriate comparables or methodology.",
    "Excessive goodwill or intangible assets comprising 65% of total business asset valuation.",
    "Inadequate cost control systems with expenses growing at 1.5x rate of revenue growth.",
    "Unacceptable loan purpose involving significant related-party transaction without demonstrated business benefit.",
    "Insufficient supporting data for projections with assumptions exceeding industry performance metrics.",
    "Excessive debt service requirements absorbing 50% of operating cash flow versus 30% maximum guideline.",
    "Inadequate commercial property occupancy rate at 60% versus minimum requirement of 80% for loan type.",
    "Unacceptable deviation between business tax returns and financial statements without reconciliation.",
    "Insufficient business stability with three location changes in past 24 months without strategic rationale.",
    "Excessive warranty or return obligations not adequately reserved for in financial statements.",
    "Inadequate analysis of business's competitive positioning with unrealistic market share assumptions.",
    "Unacceptable accounts receivable to sales ratio exceeding industry benchmark by 35%.",
    "Insufficient documentation of intellectual property rights critical to business value proposition.",
    "Excessive decline in gross margin of 12 percentage points over past three reporting periods.",
    "Inadequate operating expense control with ratio exceeding 85% of revenue versus industry average of 65%.",
    "Unacceptable legal structure for lending purpose with entity type creating additional risk factors.",
    "Insufficient evidence of required bonding capacity for project scope and contractual obligations.",
    "Excessive dividend or distribution rate at 90% of annual profits versus policy maximum of 40%.",
    "Inadequate analysis of cash conversion cycle with significant working capital inefficiencies identified.",
    "Unacceptable vehicle fleet age with average exceeding 75% of useful life affecting operational reliability.",
    "Insufficient insurance coverage for business risks with multiple exclusions on critical exposures.",
    "Excessive pricing pressure in core market with gross margin compression of 20% in 12 months.",
    "Inadequate internet security measures for business conducting significant e-commerce activity.",
    "Unacceptable level of non-operating expenses comprising 35% of total cash outflow.",
    "Insufficient evidence of required environmental compliance for business operations.",
    "Excessive inventory age with 40% of stock exceeding 180 days without valuation adjustment.",
    "Inadequate point-of-sale systems with limited ability to track sales and inventory movement.",
    "Unacceptable balance sheet leverage with debt comprising 85% of total business capitalization.",
    "Insufficient compliance with industry-specific regulatory requirements based on due diligence findings.",
    "Excessive cost structure relative to revenue with break-even point at 85% of current sales level.",
    "Inadequate facilities maintenance reserve for commercial property with aging infrastructure.",
    "Unacceptable terms on critical supplier contracts with unfavorable pricing or exclusivity provisions.",
    "Insufficient evidence of positive cash flow trend with recent quarterly deterioration noted.",
    "Excessive technical obsolescence risk for key production equipment or business systems.",
    "Inadequate customer contract duration with 75% of revenue from agreements expiring within six months.",
    "Unacceptable loan-to-value ratio trend with recent market conditions reducing collateral coverage.",
    "Insufficient business differentiation in highly competitive market with commoditized offerings.",
    "Excessive revenue recognition issues with advance payments comprising 65% of reported sales.",
    "Inadequate financial performance compared to projections provided for previous financing.",
    "Unacceptable concentration in government contracts subject to budget appropriation uncertainty.",
    "Insufficient product diversification with single offering generating 85% of total business revenue."
]
