small_business_banking__compliance_cases__resolution = [
    "Customer provided legitimate business explanation for deposit pattern; transaction monitoring parameters adjusted for business model.",
    "Additional documentation verified legitimate ownership structure; account monitoring adjusted to normal risk level.",
    "Business operations confirmed to include legitimate international customers; enhanced monitoring maintained as precaution.",
    "Investigation determined media reports related to different individual with similar name; case closed with no further action.",
    "Seasonal business fluctuations verified through industry analysis and historical records; account classification updated.",
    "Business expansion verified through documentation and site visit; transaction parameters updated to reflect new activity level.",
    "PEP status confirmed and appropriate enhanced due diligence completed; account approved with quarterly review schedule.",
    "Cash flow verified as consistent with legitimate business operations through site visit and documentation review.",
    "Fund transfers confirmed as normal business operations between affiliated entities; consolidated monitoring implemented.",
    "Business location verified through site visit; address discrepancy resulted from recent move with proper documentation provided.",
    "Fraudulent transactions originated from external compromise; account security enhanced and customer reimbursed per Reg E.",
    "Investigation confirmed financial statements were accurate; discrepancies resulted from accounting method differences.",
    "Third-party deposit activity verified as legitimate payments from new business contract; documentation added to customer file.",
    "Complete beneficial ownership information obtained after escalation to relationship manager; EDD review completed satisfactorily.",
    "Currency exchange activity verified as legitimate for import/export business; enhanced monitoring maintained due to risk.",
    "Loan applications independently verified as legitimate for separate business purposes; relationship pricing applied appropriately.",
    "Regulatory actions disclosed after further inquiry; remediation plan in place and verified through documentation.",
    "Early loan payoffs verified as result of business sale transactions; no suspicious activity identified.",
    "Adjustment to transaction pattern verified as legitimate response to regulatory changes; monitoring parameters updated.",
    "Enhanced due diligence confirmed legitimate business operations; complex structure due to investor requirements with documentation.",
    "Original formation documents verified with secretary of state; scanning quality issue created appearance of alteration.",
    "Changes to authorized signers verified as legitimate due to management restructuring; documentation completed properly.",
    "Business operations in multiple jurisdictions verified through site visits and documentation; legitimate business purpose confirmed.",
    "Transaction pattern identified as potential money laundering; SAR filed and account closed with appropriate exit process.",
    "Business activities aligned with stated purpose after further documentation provided; monitoring parameters adjusted.",
    "Account structure modified to separate personal and business activities after client education on proper account management.",
    "MCC code updated to accurately reflect current business activities; appropriate due diligence completed for new classification.",
    "Third-party deposits verified as legitimate payments from online marketplace sales; documentation added to customer file.",
    "Investigation determined borrower acting independently; additional verification procedures implemented and loan approved.",
    "Further investigation revealed undisclosed relationship; beneficial ownership documentation updated and enhanced monitoring implemented.",
    "Nominee structure rejected through due diligence process; customer unwilling to provide required transparency and account closed.",
    "Check cashing activity verified as legitimate service to customers; BSA compliance program reviewed and deemed adequate.",
    "Loan covenant violation identified; customer notified and remediation plan implemented with additional reporting requirements.",
    "Account activity monitoring identified ongoing structuring; SAR filed and account closed following investigation.",
    "Intercompany transfers documented with legitimate business purpose; treasury management services implemented to optimize cash flow.",
    "Source of funds verified through documented business sale; initial deposit accepted with supporting documentation on file.",
    "Ownership documentation consolidated and verified for accuracy; customer profile updated with complete information.",
    "Affiliate businesses properly disclosed after additional questioning; customer profile updated with complete relationship information.",
    "Check kiting investigation completed; account access restricted and exit strategy implemented due to confirmed fraud.",
    "Business expansion verified through updated business plan and financial projections; account profile updated accordingly.",
    "Limited cash activity verified as normal for specific business model utilizing electronic payments; risk rating adjusted.",
    "Independent appraisal obtained confirming appropriate collateral value; original valuation discrepancy due to recent improvements.",
    "Employee fraud investigation completed; funds recovered, employee terminated, and case referred to law enforcement.",
    "International business connections fully disclosed after further inquiry; enhanced monitoring implemented for high-risk jurisdictions.",
    "Pattern resulted from temporary cash flow issues now resolved; account stabilized with no further unusual activity.",
    "Prior regulatory action fully remediated with documentation; enhanced monitoring implemented as precautionary measure.",
    "Payment processing activities fully documented with appropriate licenses verified; account monitoring customized for volume.",
    "Customer educated on proper account segregation; separate accounts established for business and personal use.",
    "Tax ID verification completed after correction of transposition error; account documentation updated with verified information.",
    "Variance explained through documented business expansion; account parameters updated to reflect new activity levels.",
    "Unauthorized access addressed through account security enhancement; customer issued new credentials with fraud monitoring.",
    "Transaction pattern identified as potential money laundering; SAR filed and exit process initiated with appropriate notifications.",
    "Application discrepancies resolved through additional documentation; loan approved with standard terms and conditions.",
    "Cryptocurrency-related transactions prohibited under bank policy; customer notified and transactions discontinued.",
    "Investigation confirmed fraudulent invoice scheme; SAR filed, customer notified, and enhanced fraud controls implemented.",
    "Prior bankruptcy disclosed after confrontation; loan application denied due to material misrepresentation.",
    "Attempted synthetic identity fraud prevented; case referred to fraud department and reported to appropriate authorities.",
    "Unusual activity verified as legitimate response to industry changes; account monitoring parameters adjusted accordingly.",
    "Collateral ownership verified through additional documentation; loan processed with proper security interest recorded.",
    "Business location verified through site visit; mailing address updated to reflect current operations location.",
    "International transactions supported with appropriate documentation; enhanced due diligence completed for high-risk jurisdictions.",
    "Investigation determined legitimate import/export business; enhanced monitoring maintained due to inherent industry risk.",
    "Seasonal business pattern verified through historical analysis; account monitoring adjusted to accommodate expected fluctuations.",
    "Multiple business operations properly documented and segmented into appropriate accounts after customer education.",
    "Third-party check deposits verified as legitimate customer payments; deposit review thresholds adjusted for business model.",
    "Growth verified through business expansion documentation; transaction monitoring parameters updated accordingly.",
    "Import/export documentation verified for all high-risk transactions; enhanced due diligence maintained as ongoing requirement.",
    "Industry analysis confirmed transaction patterns as normal for business type; monitoring parameters adjusted accordingly.",
    "Source of initial capital verified through investment documentation; customer profile updated with complete information.",
    "Wire recipients verified as legitimate business partners; transaction documentation requirements established for ongoing monitoring.",
    "Account restructured to properly reflect business operations; treasury management services implemented to improve efficiency.",
    "Confirmed fraud scheme; SAR filed, account closed, and case referred to law enforcement with appropriate documentation.",
    "Business relationships verified through contracts and invoices; transaction monitoring parameters updated accordingly.",
    "Financial statement manipulation confirmed; loan denied and investigation findings documented with appropriate notifications.",
    "Physical business location verified; address discrepancy resolved with complete documentation and site visit confirmation.",
    "Transaction pattern explanation accepted after verification; enhanced monitoring continued as precautionary measure.",
    "Ownership information consolidated and verified across systems; customer profile updated with complete documentation.",
    "Merchant fraud scheme identified; funds sequestered, SAR filed, and relationship terminated with appropriate notices.",
    "Deposit sources verified as legitimate business relationships; transaction documentation requirements established.",
    "Transactions verified as outside bank's risk tolerance; account exit strategy implemented with appropriate notices.",
    "Business purpose for cash withdrawals documented; limits established and enhanced monitoring implemented.",
    "Loan closing timeline maintained after verification of all required documentation; no suspicious factors identified.",
    "Currency conversion activity verified as necessary for international business operations; documentation requirements established.",
    "Identity verification completed with additional documentation; account opened with standard monitoring parameters.",
    "Rapid growth verified through venture capital funding documentation; transaction parameters adjusted for expected activity.",
    "Complete ownership structure documented after further inquiry; enhanced due diligence completed for foreign beneficial owners.",
    "Customer educated on proper account segregation; business banking standards established and monitored for compliance.",
    "Adverse information determined to be immaterial after investigation; standard monitoring maintained with notation in file.",
    "ACH return issue resolved through merchant processor settings adjustment; additional staff training implemented.",
    "Check fraud attempt confirmed; account closed, SAR filed, and case referred to law enforcement with documentation.",
    "Loan proceeds usage verified through invoice documentation; disbursement protocols enhanced for future transactions.",
    "Legitimate business explanation provided for payment patterns; additional documentation requirements implemented.",
    "Business jurisdiction selection documented with legitimate tax planning purpose; enhanced due diligence completed.",
    "Cash deposit pattern identified as potential structuring; SAR filed and account closed following investigation.",
    "Elder exploitation confirmed; protective action taken, SAR filed, and case referred to adult protective services.",
    "Business relationships verified through appropriate documentation; transaction monitoring thresholds adjusted accordingly.",
    "Account activity stabilized after customer interview; enhanced monitoring continued for 90-day period with no further concerns.",
    "Government payments verified as legitimate program participation; documentation added to customer file with monitoring.",
    "Account parameter changes verified as necessary for business operations; documentation completed and monitoring adjusted.",
    "Deposit capture issue resolved through system setting adjustment and staff training; monitoring continued for 60 days.",
    "Import/export documentation verified for international transactions; enhanced due diligence maintained as ongoing requirement.",
    "Payment acceptance methods documented with appropriate licensing; transaction monitoring customized for business model.",
    "Account information updated with current business documentation; periodic review schedule established for ongoing compliance.",
    "International wire pattern identified as potential money laundering; SAR filed and account closed following investigation.",
    "Cryptocurrency payment acceptance discontinued after notification of bank policy; account monitoring continued for compliance.",
    "Offshore jurisdiction documented with legitimate business purpose; enhanced due diligence completed with acceptable results.",
    "Branch staff provided additional training on CTR requirements; customer educated on currency transaction reporting obligations.",
    "Check deposits verified with appropriate business documentation; transaction monitoring parameters adjusted for business model.",
    "Operational expense pattern verified against industry standards; business model documented with satisfactory explanation.",
    "Customer explanation verified through supporting documentation; transaction monitoring parameters adjusted accordingly.",
    "Tax document alteration confirmed; loan denied, SAR filed, and relationship terminated with appropriate notices.",
    "Required licensing verified through regulatory database; documentation added to customer file with periodic verification schedule.",
    "Loan proceeds usage verified through follow-up documentation; disbursement monitoring implemented for compliance.",
    "Withdrawal pattern identified as potential structuring; SAR filed and case referred for further investigation.",
    "Shell company network investigation completed; SAR filed and high-risk accounts exited with appropriate documentation.",
    "Authorized signer removed after bank notification of risk concerns; enhanced monitoring implemented for account.",
    "Transaction pattern verified with legitimate business purpose; account monitoring adjusted to reflect expected activity.",
    "Business lease documentation provided after delay; address verification completed with satisfactory results.",
    "New business relationship verified through appropriate documentation; transaction monitoring established for expected activity.",
    "Business scale verified through site visit and documentation; account parameters adjusted to reflect actual operations.",
    "International transaction pattern supported by documented export contracts; enhanced monitoring maintained as precaution.",
    "Loan usage violation identified; customer notified of covenant breach and remediation plan implemented with monitoring.",
    "Enhanced due diligence completed with acceptable results; ongoing monitoring implemented due to inherent industry risk.",
    "Deposit coordination explained through centralized cash management; separate account monitoring with consolidated reporting implemented.",
    "Transaction pattern identified as money laundering; SAR filed and account closed with appropriate exit documentation.",
    "Complex structure documented with legitimate business purpose; ownership chart maintained in customer file with periodic updates.",
    "Wire transfer pattern identified as suspicious; SAR filed and additional transaction verification requirements implemented.",
    "Authentic utility documentation provided after address verification escalation; account documentation updated accordingly.",
    "International sanctions screening enhanced; certain transaction types restricted with customer notification and acceptance.",
    "Credit references independently verified after additional research; loan approved with enhanced monitoring requirements.",
    "After-hours deposits explained through documented business operations; account monitoring adjusted for expected pattern.",
    "Source of funds verified through appropriate business documentation; account monitoring parameters adjusted accordingly.",
    "Cash to cashier's check pattern identified as potential layering; SAR filed and account closed following investigation.",
    "Merchant activity aligned with updated business model after documentation; monitoring adjusted for current operations.",
    "Collateral documentation discrepancies resolved with additional verification; loan closed with proper security interest.",
    "Weekend transactions verified through business operations documentation; monitoring parameters adjusted for normal activity.",
    "Beneficial ownership update completed after formal request; customer profile updated with current structure information.",
    "Wire description anomalies addressed through treasury management training; template implementation for consistency.",
    "Unlicensed money transmission activity confirmed; SAR filed and account closed with appropriate exit documentation.",
    "Payroll activity reconciled with documented contractor relationships; payroll processing documentation verified as accurate.",
    "Deposit sources verified with appropriate documentation; transaction monitoring thresholds adjusted for business model.",
    "Debt obligation disclosure omission identified; loan restructured with comprehensive debt inclusion and enhanced reporting.",
    "Regulatory compliance verified through license documentation; periodic verification schedule established for ongoing monitoring.",
    "Return pattern addressed through cash management services implementation; deposit review procedures enhanced.",
    "Business activities aligned with account documentation after verification; website updated to reflect current service offerings.",
    "Expense pattern verified through industry analysis; business model efficiency documented in customer file.",
    "Account structure revised to properly segregate personal and business finances; customer education provided.",
    "Guarantor financial capacity verified through additional documentation; loan structure modified with enhanced collateral.",
    "Currency exchange activity documented with international client base; transaction monitoring customized for business needs.",
    "MSB activities identified; appropriate registration verified and enhanced due diligence implemented for account monitoring.",
    "Revenue misrepresentation confirmed; loan denied and relationship terminated due to material misrepresentation.",
    "Activity deviation explained through documented business change; account parameters updated to reflect new operations.",
    "Prohibited business activities confirmed; account closed following appropriate exit procedures and notifications.",
    "ATM deposit pattern identified as potential structuring; SAR filed and account closed following investigation.",
    "Source of deposits verified through appropriate documentation; transaction monitoring adjusted for expected activity.",
    "Personal use of loan proceeds confirmed; loan covenant violation addressed with remediation plan and monitoring.",
    "Transaction pattern verified as normal for specialized business model; monitoring parameters customized accordingly.",
    "Authorized signers verified with appropriate relationship to business; documentation updated in customer file.",
    "Unlicensed money transmission confirmed; SAR filed and account closed with appropriate exit documentation.",
    "Business model verified as innovative but legitimate; transaction parameters adjusted for unique operational pattern.",
    "Counterparty concentration explained through exclusive distribution agreement; documentation added to customer file.",
    "Transaction pattern reviewed with no tax implications requiring reporting; standard monitoring maintained.",
    "Material loan discrepancy identified; application denied and relationship reassessment initiated with risk notification.",
    "Currency conversion documented as necessary for international operations; transaction monitoring customized accordingly.",
    "Address changes verified as related to business expansion; documentation updated with current information.",
    "International relationships documented with appropriate due diligence; enhanced monitoring implemented for high-risk jurisdictions.",
    "Third-party processing disclosed and documented; MSB registration verified with ongoing monitoring requirements.",
    "Transaction structuring confirmed; SAR filed and account closed following appropriate investigation and documentation.",
    "Business operations clarified through additional documentation; customer profile updated with complete information.",
    "Cash activity verified as consistent with legitimate business operations; industry-specific monitoring implemented.",
    "Document fraud confirmed; loan denied, SAR filed, and relationship terminated with appropriate notifications.",
    "Ownership structure simplified after bank consultation; transparent documentation provided with verification.",
    "Refund pattern investigation identified merchant processing issue; terminal reconfigured with staff training.",
    "Entity relationships documented with legitimate business purpose; transaction monitoring adjusted accordingly.",
    "Marijuana-related business confirmed; account closed due to bank policy with appropriate exit documentation.",
    "MSB activities discontinued after notification of bank requirements; account monitoring continued for compliance.",
    "Account segregation implemented after customer education; business operations properly documented in designated accounts.",
    "Seasonal pattern verified through historical analysis and industry research; monitoring parameters adjusted accordingly.",
    "International transactions supported with appropriate documentation; enhanced monitoring maintained as precaution.",
    "Deposit/withdrawal pattern explained through cash-intensive business model; enhanced monitoring maintained.",
    "Zoning compliance verified through municipal documentation; business address properly registered with updated information.",
    "International wire pattern supported with vendor payment documentation; enhanced monitoring maintained as precaution.",
    "Synthetic identity attempt confirmed; account closed and reported to fraud prevention networks with documentation.",
    "Invoice manipulation scheme identified; SAR filed, account closed, and case referred to law enforcement.",
    "Deposit sources verified through appropriate documentation; transaction monitoring parameters adjusted accordingly.",
    "Cash deposit pattern identified as intentional structuring; SAR filed and account closed following investigation.",
    "Projection methodology verified as consistent with startup experience; loan terms structured with appropriate milestones.",
    "Jurisdiction selection documented with legitimate business purpose; ownership transparency verified through enhanced due diligence.",
    "Related business activities properly documented after further inquiry; relationship monitoring implemented with consolidated view.",
    "Transaction activity aligned with updated business operations; customer profile revised with current information.",
    "Rapid withdrawal pattern identified as potential fraud scheme; SAR filed and account closed following investigation.",
    "Payment acceptance methods properly disclosed after further inquiry; risk assessment completed with appropriate monitoring.",
    "Operating history verified through additional documentation; loan approved with standard terms and conditions.",
    "Nominee account usage confirmed; SAR filed and account closed following appropriate investigation and documentation.",
    "Required documentation provided after formal escalation; enhanced due diligence completed with acceptable results."
]
