small_business_banking__compliance_requirements__description = [
  "Collect and verify beneficial ownership information for legal entity customers with at least 25% ownership or significant control.",
  "File Currency Transaction Reports (CTRs) for cash transactions exceeding $10,000 in a single business day.",
  "Maintain written Customer Identification Program (CIP) for verifying business customer identity during onboarding.",
  "Implement risk-based Customer Due Diligence (CDD) procedures appropriate to customer type and transaction activity.",
  "Monitor business accounts for suspicious activity and file Suspicious Activity Reports (SARs) when appropriate.",
  "Provide adverse action notices when declining business credit applications as required by Regulation B.",
  "Collect and report data on small business loan applications from women-owned and minority-owned businesses.",
  "Implement and maintain written information security program to protect customer information.",
  "Establish enhanced due diligence procedures for high-risk business customers and politically exposed persons.",
  "Provide flood hazard determination notifications for commercial properties securing loans.",
  "Maintain appropriate documentation of business purpose for loans secured by residential property.",
  "Conduct periodic risk assessments of small business products and services for BSA/AML compliance.",
  "Establish procedures for identifying potential structuring of transactions to avoid BSA reporting requirements.",
  "Provide accurate disclosure of loan terms and conditions for small business borrowers as required.",
  "Establish procedures to identify and verify shell companies and other high-risk entity structures.",
  "Train staff on identifying and reporting suspected elder financial exploitation.",
  "Maintain records of business account activity for at least five years as required by BSA.",
  "Establish procedures to screen business customers against OFAC sanctions lists.",
  "Develop processes to identify and report suspicious activity related to potential terrorist financing.",
  "Establish written procedures for identifying money service businesses among commercial customers.",
  "Conduct risk-based monitoring of cross-border wire transfers for business customers.",
  "Maintain documentation of purpose of commercial loans as required by regulatory guidance.",
  "Develop procedures to identify and monitor politically exposed persons with business relationships.",
  "Implement procedures to identify and monitor third-party payment processors among business customers.",
  "Establish and maintain appropriate procedures for commercial real estate appraisals and evaluations.",
  "Develop controls to identify potential misuse of business accounts for personal purposes.",
  "Implement procedures to validate business existence and legitimacy during customer onboarding.",
  "Maintain written procedures for Business Continuity Planning as required by regulatory guidance.",
  "Establish procedures to collect and verify sources of funds for significant business transactions.",
  "Implement enhanced due diligence procedures for business customers in high-risk industries.",
  "Maintain appropriate segregation of duties for processing business loans and transactions.",
  "Establish procedures for monitoring insider loans to bank directors' business interests.",
  "Implement risk-based monitoring of remote deposit capture activity for business customers.",
  "Maintain documentation of small business lending decisions to support fair lending compliance.",
  "Establish procedures to identify and verify beneficial owners for trust-owned businesses.",
  "Implement periodic review procedures for high-risk business customer relationships.",
  "Establish procedures for monitoring commercial customer deposit account activity against expected patterns.",
  "Develop controls to identify potential commercial loan fraud during application process.",
  "Maintain written procedures for commercial real estate lending concentration risk management.",
  "Implement procedures to monitor transactions with non-bank financial institutions.",
  "Establish procedures for identifying potential check kiting schemes by business customers.",
  "Maintain appropriate documentation of commercial credit analyses and underwriting decisions.",
  "Implement procedures to identify potential misrepresentation in business loan applications.",
  "Establish appropriate collateral monitoring procedures for asset-based commercial lending.",
  "Maintain appropriate approval procedures for business banking policy exceptions.",
  "Implement procedures for identifying potential employee fraud in business accounts.",
  "Establish monitoring procedures for high-volume currency transactions by business customers.",
  "Maintain appropriate documentation for commercial lending pricing exceptions.",
  "Implement procedures to identify potential money laundering through trade-based activities.",
  "Establish appropriate customer verification procedures for online business account opening.",
  "Maintain documentation of business customer periodic risk assessment and review.",
  "Implement procedures to monitor business customer negative news and adverse media.",
  "Establish appropriate controls for commercial loan participation purchases and sales.",
  "Maintain written procedures for identifying commercial loan troubled debt restructuring.",
  "Implement procedures to identify and verify businesses operating in multiple jurisdictions.",
  "Establish appropriate documentation standards for commercial credit file documentation.",
  "Maintain procedures for monitoring cash-intensive business customers.",
  "Implement appropriate monitoring of business-to-business payment activity.",
  "Establish procedures for identifying and mitigating risks of commercial deposit fraud.",
  "Maintain appropriate documentation of commercial loan covenant monitoring.",
  "Implement procedures to identify and report suspicious cyber events affecting business customers.",
  "Establish appropriate procedures for commercial loan workout and collection activities.",
  "Maintain appropriate documentation of business customer enhanced due diligence.",
  "Implement procedures to identify and verify high-net-worth business owners.",
  "Establish appropriate procedures for monitoring business credit card activity.",
  "Maintain appropriate documentation of HMDA data collection for mixed-use properties.",
  "Implement procedures to identify potential nominee ownership structures for businesses.",
  "Establish appropriate documentation for commercial loan environmental risk assessments.",
  "Maintain procedures for identifying prohibited business types according to bank policy.",
  "Implement appropriate monitoring of international business customer activity.",
  "Establish procedures for commercial account closure due to suspicious activity.",
  "Maintain appropriate documentation of business tax return analysis for lending decisions.",
  "Implement procedures to identify potential front companies and shell companies.",
  "Establish appropriate procedures for commercial loan stress testing.",
  "Maintain documentation of commercial real estate inspection and construction monitoring.",
  "Implement procedures to verify business income and revenue claims during underwriting.",
  "Establish appropriate procedures for identifying business accounts with multiple signers.",
  "Maintain appropriate documentation of commercial loan collateral perfection.",
  "Implement procedures to identify businesses owned by politically exposed persons.",
  "Establish appropriate procedures for monitoring merchant processing activity.",
  "Maintain documentation of commercial real estate property flood zone determinations.",
  "Implement procedures to identify potential commercial account takeover attempts.",
  "Establish appropriate procedures for commercial account cash management services.",
  "Maintain documentation of business customer periodic information updates.",
  "Implement procedures to identify potential synthetic business identities.",
  "Establish appropriate procedures for commercial credit bureau reporting.",
  "Maintain documentation of beneficial ownership changes for business customers.",
  "Implement appropriate procedures for commercial account information security.",
  "Establish procedures for identifying high-risk changes to business account parameters.",
  "Maintain appropriate documentation of business customer site visits.",
  "Implement procedures to identify potential unauthorized business account activity.",
  "Establish appropriate procedures for commercial loan document preparation and review.",
  "Maintain documentation of business customer identification for non-documentary methods.",
  "Implement procedures to identify commercial borrower distress signals.",
  "Establish appropriate procedures for commercial note and security agreement maintenance.",
  "Maintain documentation of commercial loan insurance requirements and monitoring.",
  "Implement procedures to identify commercial loan application red flags.",
  "Establish appropriate procedures for commercial credit risk rating and migration.",
  "Maintain documentation of business account unusual activity investigations.",
  "Implement procedures to identify high-risk commercial transaction patterns.",
  "Establish appropriate procedures for commercial loan disbursement controls.",
  "Maintain documentation of business customer complaint resolution.",
  "Implement procedures to identify potential commercial account fraud schemes.",
  "Establish appropriate procedures for commercial loan annual review process.",
  "Maintain documentation of business customer high-risk designation rationale.",
  "Implement procedures to identify commercial insider abuse warning signs.",
  "Establish appropriate procedures for commercial loan policy exception tracking.",
  "Maintain documentation of business account opening approval process.",
  "Implement procedures to identify potential commercial loan straw borrowers.",
  "Establish appropriate procedures for business account transaction limits.",
  "Maintain documentation of business customer risk rating methodology.",
  "Implement procedures to identify commercial loan covenant violations.",
  "Establish appropriate procedures for commercial loan collateral valuation updates.",
  "Maintain documentation of business entity verification methods.",
  "Implement procedures to identify commercial deposit structuring patterns.",
  "Establish appropriate procedures for business account beneficial ownership certification renewal.",
  "Maintain documentation of business customer enhanced due diligence review schedule.",
  "Implement procedures to identify changes in business account transaction patterns.",
  "Establish appropriate procedures for business account dormancy monitoring.",
  "Maintain documentation of commercial loan concentration risk analysis.",
  "Implement procedures to identify high-risk business customer geographic locations.",
  "Establish appropriate procedures for commercial loan rate lock commitments.",
  "Maintain documentation of business account risk-based monitoring parameters.",
  "Implement procedures to identify potential related commercial credits.",
  "Establish appropriate procedures for commercial loan servicing transfers.",
  "Maintain documentation of business customer OFAC screening results.",
  "Implement procedures to identify potential commercial loan fraud red flags.",
  "Establish appropriate procedures for commercial loan modification documentation.",
  "Maintain documentation of business customer information privacy notifications.",
  "Implement procedures to identify business accounts with unusual or complex ownership structures.",
  "Establish appropriate procedures for commercial loan file documentation standards.",
  "Maintain documentation of business customer CIP exemption justification.",
  "Implement procedures to identify potential commercial interest rate swaps suitability.",
  "Establish appropriate procedures for commercial loan maturity date tracking.",
  "Maintain documentation of business customer enhanced monitoring triggers.",
  "Implement procedures to identify potential commercial loan underwriting weaknesses.",
  "Establish appropriate procedures for business account cash handling limitations.",
  "Maintain documentation of commercial loan officer approval authorities.",
  "Implement procedures to identify potential OFAC violations in business transactions.",
  "Establish appropriate procedures for commercial loan security interest perfection.",
  "Maintain documentation of business customer ongoing due diligence schedule.",
  "Implement procedures to identify potential commercial loan collateral deficiencies.",
  "Establish appropriate procedures for business account wire transfer verification.",
  "Maintain documentation of commercial loan risk rating override justification.",
  "Implement procedures to identify potential commercial borrower negative trends.",
  "Establish appropriate procedures for business account remote deposit capture limits.",
  "Maintain documentation of commercial loan covenant testing methodology.",
  "Implement procedures to identify potential commercial loan policy violations.",
  "Establish appropriate procedures for business account currency transaction aggregation.",
  "Maintain documentation of commercial loan guarantor financial analysis.",
  "Implement procedures to identify potential commercial loan documentation exceptions.",
  "Establish appropriate procedures for business customer risk-based identity verification.",
  "Maintain documentation of commercial loan pricing methodology.",
  "Implement procedures to identify potential commercial loan misrepresentation.",
  "Establish appropriate procedures for business account high-risk transaction review.",
  "Maintain documentation of commercial loan portfolio stress testing methodology.",
  "Implement procedures to identify potential export control violations in business transactions.",
  "Establish appropriate procedures for commercial loan flood insurance monitoring.",
  "Maintain documentation of business customer enhanced due diligence approval process.",
  "Implement procedures to identify potential commercial loan construction draw irregularities.",
  "Establish appropriate procedures for business account transaction monitoring scenarios.",
  "Maintain documentation of commercial loan participations purchased due diligence.",
  "Implement procedures to identify potential commercial customer reputation risk.",
  "Establish appropriate procedures for business account transaction monitoring calibration.",
  "Maintain documentation of commercial loan approval committee minutes.",
  "Implement procedures to identify potential commercial loan payment application errors.",
  "Establish appropriate procedures for business customer periodic certification.",
  "Maintain documentation of commercial loan debt service coverage ratio calculation methodology.",
  "Implement procedures to identify potential commercial account fraud attempts.",
  "Establish appropriate procedures for business account activity documentation standards.",
  "Maintain documentation of commercial loan collateral inspection frequency.",
  "Implement procedures to identify potential commercial loan covenant calculation errors.",
  "Establish appropriate procedures for business account holder death handling.",
  "Maintain documentation of commercial loan officer portfolio risk assessment.",
  "Implement procedures to identify potential commercial loan documentation deficiencies.",
  "Establish appropriate procedures for business account high-risk transaction approval.",
  "Maintain documentation of commercial loan policy compliance monitoring.",
  "Implement procedures to identify potential commercial customer financial deterioration.",
  "Establish appropriate procedures for business account beneficial ownership verification.",
  "Maintain documentation of commercial loan commitment tracking and reporting.",
  "Implement procedures to identify potential commercial loan stacking by borrowers.",
  "Establish appropriate procedures for business account transaction verification sampling.",
  "Maintain documentation of commercial loan environmental liability assessment.",
  "Implement procedures to identify potential commercial loan fraudulent documentation.",
  "Establish appropriate procedures for business account periodic risk reassessment.",
  "Maintain documentation of commercial loan policy exception approval authorities.",
  "Implement procedures to identify potential commercial account internet banking fraud.",
  "Establish appropriate procedures for business account subpoena response.",
  "Maintain documentation of commercial loan collateral release authorization.",
  "Implement procedures to identify potential commercial loan portfolio concentration risks."
]
