small_business_banking__products__description = [
    "Basic checking for daily business needs. No monthly fees with minimum balance.",
    "Savings account with competitive interest rates. Grow your business funds.",
    "Business line of credit for flexible working capital. Quick access to funds.",
    "Business credit card with rewards and cashback. Manage expenses easily.",
    "Term deposit with fixed interest rate. Ideal for long-term investments.",
    "Premium checking with unlimited transactions. Enhanced features for growing businesses.",
    "High-yield savings account for maximum returns. Maximize your savings.",
    "Small business loan for expansion and growth. Flexible repayment terms.",
    "Business debit card with direct access to your checking account.",
    "Merchant services for accepting card payments. Streamline your sales.",
    "Payroll services for easy employee payments. Simplify payroll.",
    "Online banking for 24/7 account access. Manage finances anytime.",
    "Mobile banking app for on-the-go management. Check balances, transfer funds.",
    "Business analysis tools for financial insights. Track your performance.",
    "Automated bill pay for timely payments. Never miss a payment.",
    "Remote deposit capture for quick check deposits. Deposit checks remotely.",
    "Business overdraft protection to avoid declined transactions. Protect your funds.",
    "Commercial real estate loan for property purchases. Invest in real estate.",
    "Equipment financing for purchasing business equipment. Upgrade your tools.",
    "SBA loan assistance for government-backed financing. Get SBA loan help.",
    "Business checking with free checks. Order checks online.",
    "Savings account with tiered interest rates. Earn more with higher balances.",
    "Business credit line with no annual fee. Access funds without fees.",
    "Corporate credit card with travel rewards. Travel for less.",
    "Certificate of deposit with flexible terms. Choose your term.",
    "Business checking with interest. Earn interest on your balance.",
    "Money market account with check writing. Access your funds easily.",
    "Small business startup loan for new ventures. Start your business.",
    "Business ATM card for convenient cash access. Access cash anytime.",
    "Point of sale (POS) systems for retail businesses. Improve sales.",
    "Business alerts for account activity. Stay informed.",
    "Automated savings transfers for consistent growth. Save automatically.",
    "Business fraud protection services. Protect your business from fraud.",
    "Commercial mortgage for business properties. Own your space.",
    "Vehicle financing for company vehicles. Finance your fleet.",
    "Business rewards program for loyal customers. Reward your customers.",
    "Business check scanning for digital records. Digitize your checks.",
    "Escrow services for secure transactions. Secure your transactions.",
    "Sweep account for automatic balance optimization. Maximize your funds.",
    "Business checking with no minimum balance. No balance requirements.",
    "Savings account with monthly interest payments. Get monthly income.",
    "Business credit line with variable interest rate. Flexible interest.",
    "Business travel card with airport lounge access. Travel in comfort.",
    "Long-term CD with high interest rate. Long-term returns.",
    "Business checking with unlimited check writing. Write as many checks as needed.",
    "Savings account with bonus interest. Earn extra interest.",
    "Business expansion loan for growth initiatives. Expand your business.",
    "Business wire transfer services. Send and receive funds quickly."
]
