consumer_lending__compliance_exceptions__description = [
    "Missing borrower signature on loan application.",
    "Incorrect APR disclosed in Loan Estimate.",
    "Late delivery of Closing Disclosure.",
    "Incomplete income verification documents.",
    "Missing appraisal report.",
    "Inaccurate calculation of finance charge.",
    "Failure to provide adverse action notice.",
    "Incorrectly identified as high-cost mortgage.",
    "Missing flood insurance disclosure.",
    "Error in calculating loan-to-value ratio.",
    "Misidentified borrower's ethnicity.",
    "Incorrectly classified loan purpose.",
    "Missing documentation for self-employment income.",
    "Failure to verify borrower's identity.",
    "Inaccurate reporting of credit score.",
    "Late payment not reported to credit bureau.",
    "Incorrectly applied late fee.",
    "Failure to provide required disclosures.",
    "Mismatched borrower information.",
    "Incorrectly calculated escrow payment.",
    "Missing borrower signature on loan agreement.",
    "Incorrect interest rate disclosed in closing documents.",
    "Late delivery of initial Truth in Lending disclosure.",
    "Incomplete documentation for rental income.",
    "Missing proof of homeowner's insurance.",
    "Inaccurate calculation of total loan costs.",
    "Failure to provide notice of right to receive appraisal.",
    "Incorrectly identified as covered borrower under MLA.",
    "Missing special information booklet for ARM loans.",
    "Error in calculating debt-to-income ratio.",
    "Misidentified borrower's race.",
    "Incorrectly classified property type.",
    "Missing documentation for child support income.",
    "Failure to verify borrower's address.",
    "Inaccurate reporting of credit inquiries.",
    "Late payment not properly documented.",
    "Incorrectly applied prepayment penalty.",
    "Failure to provide required notices.",
    "Mismatched co-borrower information.",
    "Incorrectly calculated payoff amount.",
    "Missing borrower signature on modification agreement.",
    "Incorrect payment amount disclosed in loan documents.",
    "Late delivery of revised Loan Estimate.",
    "Incomplete documentation for alimony income.",
    "Missing proof of flood insurance.",
    "Inaccurate calculation of closing costs.",
    "Failure to provide notice of action taken.",
    "Incorrectly identified as exempt from HOEPA.",
    "Missing information about loan servicing.",
    "Error in calculating loan term.",
    "Misidentified borrower's sex.",
    "Incorrectly classified occupancy type.",
    "Missing documentation for investment income.",
    "Failure to verify borrower's employment.",
    "Inaccurate reporting of public records.",
    "Late payment not reflected in account history.",
    "Incorrectly applied origination fee.",
    "Failure to provide required disclosures in a timely manner.",
    "Mismatched property address information.",
    "Incorrectly calculated refund amount.",
    "Missing borrower signature on forbearance agreement.",
    "Incorrect disbursement amount.",
    "Late delivery of initial escrow statement.",
    "Incomplete documentation for retirement income.",
    "Missing proof of hazard insurance.",
    "Inaccurate calculation of prepayment penalty.",
    "Failure to provide notice of right to cancel.",
    "Incorrectly identified as high-cost mortgage under HOEPA.",
    "Missing information about loan assumptions.",
    "Error in calculating loan payoff date.",
    "Misidentified borrower's marital status.",
    "Incorrectly classified loan type.",
    "Missing documentation for government assistance income.",
    "Failure to verify borrower's citizenship status.",
    "Inaccurate reporting of credit limit.",
    "Late payment not properly coded.",
    "Incorrectly applied annual fee.",
    "Failure to provide required disclosures electronically.",
    "Mismatched applicant and co-applicant information.",
    "Incorrectly calculated escrow refund.",
    "Missing borrower signature on payment arrangement.",
    "Incorrect payment frequency disclosed.",
    "Late delivery of updated Closing Disclosure.",
    "Incomplete documentation for disability income.",
    "Missing proof of title insurance.",
    "Inaccurate calculation of daily interest.",
    "Failure to provide notice of credit score used.",
    "Incorrectly identified as exempt from MLA.",
    "Missing information about loan modification options.",
    "Error in calculating loan origination date.",
    "Misidentified borrower's age.",
    "Incorrectly classified loan status.",
    "Missing documentation for other income sources.",
    "Failure to verify borrower's phone number.",
    "Inaccurate reporting of credit utilization.",
    "Late payment not properly disclosed.",
    "Incorrectly applied late charge.",
    "Failure to provide required disclosures in Spanish.",
    "Mismatched loan account information.",
    "Incorrectly calculated principal balance.",
    "Missing borrower signature on loan payoff statement.",
    "Incorrect interest rate applied.",
    "Late delivery of periodic statement.",
    "Incomplete documentation for self-employment expenses.",
    "Missing proof of liability insurance.",
    "Inaccurate calculation of escrow shortage.",
    "Failure to provide notice of adverse action."
]
