consumer_lending__adverse_action_details__credit_score_factors = [
    "Late payments",
    "High credit utilization",
    "Short credit history",
    "Too many inquiries",
    "Collections accounts",
    "Bankruptcy",
    "Foreclosure",
    "Insufficient credit",
    "Limited credit experience",
    "Derogatory marks",
    "Negative public records",
    "Thin credit file",
    "Lack of recent credit",
    "Unestablished credit",
    "Credit mix",
    "Credit age",
    "Recent credit applications",
    "High debt-to-income ratio",
    "Low income",
    "Unstable employment",
    "Insufficient collateral",
    "High loan-to-value ratio",
    "Property condition",
    "Low appraisal value",
    "Title issues",
    "Insurance concerns",
    "Tax liens",
    "Judgements",
    "Fraud risk",
    "Identity theft risk",
    "Compliance risk",
    "Regulatory risk",
    "Reputational risk",
    "Operational risk",
    "Credit risk",
    "Market risk",
    "Interest rate risk",
    "Liquidity risk",
    "Counterparty risk",
    "Systemic risk",
    "Country risk",
    "Political risk",
    "Environmental risk",
    "Social risk",
    "Governance risk",
    "Compliance risk",
    "Legal risk",
    "Operational risk",
    "Strategic risk",
    "Financial risk",
    "Credit risk",
    "Market risk",
    "Interest rate risk",
    "Liquidity risk",
    "Counterparty risk",
    "Systemic risk",
    "Country risk",
    "Political risk",
    "Environmental risk",
    "Social risk",
    "Governance risk"
]
