consumer_lending__loan_communications__subject = [
    "Loan application received",
    "Application update",
    "Missing documents",
    "Loan approved!",
    "Loan denied",
    "Closing scheduled",
    "Payment received",
    "Payment past due",
    "Loan modification",
    "Insurance reminder",
    "Welcome to [Bank Name]",
    "Account update",
    "Important information",
    "Action needed",
    "Request received",
    "Thank you",
    "Loan information",
    "Payment details",
    "Account access",
    "Contact us",
    "Loan application decision",
    "Document request",
    "Loan closing details",
    "Payment confirmation",
    "Delinquency notice",
    "Account statement",
    "Loan servicing",
    "Customer support",
    "Fraud alert",
    "Security update",
    "Application in progress",
    "Verification required",
    "Loan offer",
    "Payment reminder",
    "Account closure",
    "Loan payoff",
    "Dispute resolution",
    "Complaint response",
    "Feedback request",
    "New product offer",
    "Promotional offer",
    "Account maintenance",
    "Loan documents",
    "Payment options",
    "Insurance information",
    "Tax documents",
    "Legal notices",
    "General inquiry",
    "Welcome call",
    "Follow-up call",
    "Account review",
    "Loan review",
    "Payment schedule",
    "Escrow analysis",
    "Insurance update",
    "Loan transfer",
    "Customer satisfaction survey",
    "Online banking access",
    "Mobile app access",
    "Account security",
    "Loan agreement",
    "Payment history",
    "Interest rate change",
    "Late payment forgiveness",
    "Hardship assistance",
    "Collections update",
    "Settlement offer",
    "Account reinstatement",
    "Loan refinancing",
    "Debt consolidation",
    "Credit counseling",
    "Financial education",
    "Identity theft protection",
    "Fraud prevention",
    "Security tips",
    "Account protection",
    "Loan protection",
    "Payment protection",
    "Insurance options",
    "Tax benefits",
    "Legal rights",
    "Customer resources",
    "Loan calculators",
    "Financial planning tools",
    "Budgeting assistance",
    "Credit monitoring",
    "Debt management",
    "Financial literacy",
    "Consumer protection",
    "Regulatory updates",
    "Industry news",
    "Market trends",
    "Loan comparison",
    "Product recommendations",
    "Personalized offers",
    "Account alerts",
    "Payment notifications",
    "Loan status updates",
    "Customer service updates",
    "Important changes",
    "New features",
    "System enhancements",
    "Technical support",
    "Account access issues",
    "Password reset",
    "Security questions",
    "Online banking help",
    "Mobile app help",
    "Technical difficulties",
    "Troubleshooting",
    "Error messages",
    "System maintenance",
    "Scheduled downtime",
    "Service interruption",
    "Contact information",
    "Branch locations",
    "Customer service hours",
    "Feedback and suggestions",
    "Complaint resolution",
    "Dispute process",
    "Terms and conditions",
    "Privacy policy",
    "Security policy",
    "Legal disclaimers",
    "Regulatory disclosures"
]
