consumer_lending__product_eligibility_criteria__description = [
    "Minimum credit score of 620.",
    "Minimum annual income of $50,000.",
    "Maximum debt-to-income ratio of 45%.",
    "Minimum 2 years employment history.",
    "No bankruptcies in past 5 years.",
    "Minimum 3 open tradelines.",
    "Maximum credit utilization of 30%.",
    "No delinquencies in past 12 months.",
    "Valid Social Security number.",
    "Minimum age of 18 years.",
    "US citizen or permanent resident.",
    "Verifiable income source.",
    "Positive credit history.",
    "No active collections.",
    "Stable housing history.",
    "Minimum credit score of 640.",
    "Minimum annual income of $60,000.",
    "Maximum debt-to-income ratio of 40%.",
    "Minimum 3 years employment history.",
    "No bankruptcies in past 7 years.",
    "Minimum 4 open tradelines.",
    "Maximum credit utilization of 25%.",
    "No delinquencies in past 24 months.",
    "Valid driver's license.",
    "Minimum age of 21 years.",
    "Proof of residency required.",
    "Verifiable employment.",
    "Good credit standing.",
    "No recent late payments.",
    "Stable address history.",
    "Minimum credit score of 660.",
    "Minimum annual income of $70,000.",
    "Maximum debt-to-income ratio of 35%.",
    "Minimum 5 years employment history.",
    "No bankruptcies in past 10 years.",
    "Minimum 5 open tradelines.",
    "Maximum credit utilization of 20%.",
    "No delinquencies in past 36 months.",
    "Valid bank account.",
    "Minimum age of 25 years.",
    "No criminal record.",
    "Verifiable assets.",
    "Excellent credit history.",
    "No derogatory marks.",
    "Strong financial profile.",
    "Minimum credit score of 680.",
    "Minimum annual income of $80,000.",
    "Maximum debt-to-income ratio of 30%.",
    "Minimum 7 years employment history.",
    "No bankruptcies in past 15 years.",
    "Minimum 6 open tradelines.",
    "Maximum credit utilization of 15%.",
    "No delinquencies in past 48 months.",
    "Valid email address.",
    "Minimum age of 30 years.",
    "No tax liens.",
    "Verifiable income and assets.",
    "Exceptional credit history.",
    "No credit issues.",
    "Sound financial standing.",
    "Minimum credit score of 700.",
    "Minimum annual income of $90,000.",
    "Maximum debt-to-income ratio of 25%.",
    "Minimum 10 years employment history.",
    "No bankruptcies in past 20 years.",
    "Minimum 7 open tradelines.",
    "Maximum credit utilization of 10%.",
    "No delinquencies in past 60 months.",
    "Valid phone number.",
    "Minimum age of 35 years.",
    "No judgments.",
    "Verifiable income, assets, and employment.",
    "Outstanding credit history.",
    "No adverse credit events.",
    "Impeccable financial profile.",
    "Minimum credit score of 720.",
    "Minimum annual income of $100,000.",
    "Maximum debt-to-income ratio of 20%.",
    "No employment history required.",
    "No bankruptcies ever.",
    "Minimum 8 open tradelines.",
    "Maximum credit utilization of 5%.",
    "No delinquencies ever.",
    "Valid government-issued ID.",
    "Minimum age of 40 years.",
    "No foreclosures.",
    "Verifiable income, assets, employment, and credit.",
    "Perfect credit history.",
    "No negative credit history.",
    "Exceptional financial strength.",
    "Minimum credit score of 740.",
    "Minimum annual income of $120,000.",
    "Maximum debt-to-income ratio of 15%.",
    "No credit score required.",
    "No income verification required.",
    "Minimum 9 open tradelines.",
    "No credit utilization limit.",
    "No credit history required.",
    "Valid mailing address.",
    "Minimum age of 45 years.",
    "No credit inquiries in past 6 months.",
    "Verifiable income, assets, employment, credit, and references.",
    "Flawless credit history.",
    "No credit blemishes.",
    "Unmatched financial stability.",
    "Minimum credit score of 760.",
    "Minimum annual income of $150,000.",
    "Maximum debt-to-income ratio of 10%.",
    "No minimum age requirement.",
    "No citizenship requirement.",
    "Minimum 10 open tradelines.",
    "No credit limit restrictions.",
    "No credit report required.",
    "Valid proof of identity.",
    "No maximum age limit.",
    "No inquiries in past 12 months.",
    "Verifiable income, assets, employment, credit, references, and background.",
    "Impeccable credit record.",
    "No adverse credit information.",
    "Unparalleled financial strength.",
    "Minimum credit score of 780.",
    "Minimum annual income of $200,000.",
    "Maximum debt-to-income ratio of 5%.",
    "No minimum income requirement.",
    "No residency requirement.",
    "No open tradelines required.",
    "No credit restrictions.",
    "No credit check required.",
    "Valid proof of address.",
    "No age restrictions.",
    "No inquiries in past 24 months.",
    "Verifiable income, assets, employment, credit, references, background, and insurance.",
    "Spotless credit history.",
    "No credit delinquencies.",
    "Unwavering financial strength.",
    "Minimum credit score of 800.",
    "No minimum annual income.",
    "No debt-to-income ratio limit.",
    "No employment required.",
    "No credit history required.",
    "No credit inquiries required.",
    "No age requirement.",
    "No citizenship required.",
    "No residency requirement.",
    "No credit restrictions.",
    "No documentation required.",
    "No verification required.",
    "No restrictions."
]
