consumer_lending__compliance_exceptions__root_cause = [
    "Incomplete application process.",
    "System error in APR calculation.",
    "Vendor delay in delivering disclosure.",
    "Misunderstanding of income verification requirements.",
    "Appraisal not completed on time.",
    "Manual calculation error.",
    "Failure to follow adverse action procedures.",
    "Incorrect interpretation of HOEPA rules.",
    "Lack of awareness of flood insurance requirements.",
    "Error in loan origination system.",
    "Data entry error for ethnicity.",
    "Misinterpretation of loan purpose.",
    "Lack of clear guidance on self-employment income.",
    "Inadequate identity verification process.",
    "Error in credit report retrieval.",
    "Failure to update credit reporting system.",
    "Incorrect fee schedule applied.",
    "Outdated disclosure forms used.",
    "Typographical error in borrower information.",
    "Incorrect escrow calculation formula.",
    "Missing signature on loan documents.",
    "System error in interest rate calculation.",
    "Delay in generating TIL disclosure.",
    "Misunderstanding of rental income documentation.",
    "Lack of communication with insurance agent.",
    "Manual error in calculating total costs.",
    "Failure to follow appraisal disclosure rules.",
    "Incorrect interpretation of MLA coverage.",
    "ARM booklet not included in loan package.",
    "Error in debt-to-income calculation formula.",
    "Data entry error for race.",
    "Misinterpretation of property type.",
    "Lack of clear guidance on child support income.",
    "Inadequate address verification process.",
    "Error in credit report processing.",
    "Failure to document late payment properly.",
    "Incorrect prepayment penalty calculation.",
    "Outdated notice templates used.",
    "Typographical error in co-borrower information.",
    "Incorrect payoff calculation formula.",
    "Missing signature on modification documents.",
    "System error in payment amount calculation.",
    "Delay in generating revised Loan Estimate.",
    "Misunderstanding of alimony income documentation.",
    "Lack of communication with insurance company.",
    "Manual error in calculating closing costs.",
    "Failure to follow notice of action taken procedures.",
    "Incorrect interpretation of HOEPA exemption rules.",
    "Loan servicing information not updated.",
    "Error in loan term calculation formula.",
    "Data entry error for sex.",
    "Misinterpretation of occupancy type.",
    "Lack of clear guidance on investment income.",
    "Inadequate employment verification process.",
    "Error in credit report interpretation.",
    "Failure to update account history with late payment.",
    "Incorrect origination fee calculation.",
    "Outdated disclosure delivery system.",
    "Typographical error in property address.",
    "Incorrect refund calculation formula.",
    "Missing signature on forbearance documents.",
    "System error in disbursement amount calculation.",
    "Delay in generating initial escrow statement.",
    "Misunderstanding of retirement income documentation.",
    "Lack of communication with insurance provider.",
    "Manual error in calculating prepayment penalty.",
    "Failure to follow notice of right to cancel procedures.",
    "Incorrect interpretation of high-cost mortgage rules.",
    "Loan assumption information not provided.",
    "Error in loan payoff date calculation formula.",
    "Data entry error for marital status.",
    "Misinterpretation of loan type.",
    "Lack of clear guidance on government assistance income.",
    "Inadequate citizenship status verification process.",
    "Error in credit limit reporting.",
    "Failure to code late payment correctly.",
    "Incorrect annual fee calculation.",
    "Outdated disclosure delivery system.",
    "Typographical error in applicant/co-applicant information.",
    "Incorrect escrow refund calculation formula.",
    "Missing signature on payment arrangement documents.",
    "System error in payment frequency calculation.",
    "Delay in generating updated Closing Disclosure.",
    "Misunderstanding of disability income documentation.",
    "Lack of communication with title company.",
    "Manual error in calculating daily interest.",
    "Failure to follow credit score disclosure rules.",
    "Incorrect interpretation of MLA exemption rules.",
    "Loan modification information not updated.",
    "Error in loan origination date calculation formula.",
    "Data entry error for age.",
    "Misinterpretation of loan status.",
    "Lack of clear guidance on other income sources.",
    "Inadequate phone number verification process.",
    "Error in credit utilization reporting.",
    "Failure to disclose late payment properly.",
    "Incorrect late charge calculation.",
    "Lack of Spanish language disclosure forms.",
    "Typographical error in loan account information.",
    "Incorrect principal balance calculation formula.",
    "Missing signature on loan payoff statement.",
    "System error in interest rate application.",
    "Delay in generating periodic statement.",
    "Misunderstanding of self-employment expense documentation.",
    "Lack of communication with insurance agent.",
    "Manual error in calculating escrow shortage.",
    "Failure to follow adverse action notice procedures."
]
