consumer_lending__collection_actions__notes = [
    "Left voicemail, no response.",
    "Sent payment reminder email.",
    "Mailed collection letter.",
    "Customer promised to pay next week.",
    "No answer, call again tomorrow.",
    "Payment arrangement discussed.",
    "Customer disputed charges.",
    "Referred to collections agency.",
    "Account settled in full.",
    "Legal action initiated.",
    "Customer requested hardship program.",
    "Payment plan approved.",
    "Account closed.",
    "Follow-up call scheduled.",
    "No contact made.",
    "Customer unavailable.",
    "Payment received.",
    "Account updated.",
    "Notes added to file.",
    "Next action: send email.",
    "Next action: make call.",
    "Next action: send letter.",
    "Next action: field visit.",
    "Customer contacted.",
    "Message left.",
    "No answer.",
    "Busy signal.",
    "Wrong number.",
    "Disconnected number.",
    "Customer hung up.",
    "Customer refused to pay.",
    "Customer disputed debt.",
    "Customer requested more time.",
    "Customer offered partial payment.",
    "Customer agreed to payment plan.",
    "Payment plan rejected.",
    "Customer broke payment plan.",
    "Account escalated.",
    "Legal action pending.",
    "Account settled.",
    "Account charged off.",
    "Customer made payment.",
    "Customer updated contact info.",
    "Customer requested financial assistance.",
    "Customer provided updated information.",
    "Customer explained hardship.",
    "Customer expressed dissatisfaction.",
    "Customer filed complaint.",
    "Customer thanked for assistance.",
    "Customer expressed appreciation.",
    "Customer reported fraud.",
    "Customer reported identity theft.",
    "Customer requested credit report review.",
    "Customer requested loan modification.",
    "Customer requested forbearance.",
    "Customer requested deferment.",
    "Customer requested settlement.",
    "Customer requested payment extension.",
    "Customer requested payment reduction.",
    "Customer requested interest rate reduction.",
    "Customer requested waiver of fees.",
    "Customer requested refund.",
    "Customer requested credit reporting correction.",
    "Customer requested account closure.",
    "Customer requested information.",
    "Customer provided documentation.",
    "Customer verified information.",
    "Customer confirmed payment.",
    "Customer disputed transaction.",
    "Customer requested investigation.",
    "Customer requested escalation.",
    "Customer threatened legal action.",
    "Customer expressed frustration.",
    "Customer expressed anger.",
    "Customer expressed sadness.",
    "Customer expressed fear.",
    "Customer expressed confusion.",
    "Customer expressed concern.",
    "Customer expressed gratitude.",
    "Customer expressed understanding.",
    "Customer expressed cooperation.",
    "Customer expressed willingness to pay.",
    "Customer expressed unwillingness to pay.",
    "Customer expressed inability to pay.",
    "Customer expressed financial hardship.",
    "Customer expressed dissatisfaction with service.",
    "Customer expressed satisfaction with service.",
    "Customer requested callback.",
    "Customer requested follow-up.",
    "Customer requested to speak to supervisor.",
    "Customer requested to speak to manager.",
    "Customer requested to speak to attorney.",
    "Customer requested to speak to credit counselor.",
    "Customer requested to speak to financial advisor.",
    "Customer requested to speak to debt consolidation specialist.",
    "Customer requested to speak to customer service representative.",
    "Customer requested to speak to collections specialist.",
    "Customer requested to speak to loan officer.",
    "Customer requested to speak to account manager.",
    "Customer requested to speak to someone in authority.",
    "Customer requested to file a complaint.",
    "Customer requested to dispute a charge.",
    "Customer requested to close account.",
    "Customer requested to modify loan.",
    "Customer requested to settle account.",
    "Customer requested to pay off loan.",
    "Customer requested to reinstate account.",
    "Customer requested to update contact information.",
    "Customer requested to change payment due date.",
    "Customer requested to change payment method.",
    "Customer requested to change payment frequency.",
    "Customer requested to change payment amount.",
    "Customer requested to change loan terms.",
    "Customer requested to change interest rate.",
    "Customer requested to change loan amount.",
    "Customer requested to change loan product.",
    "Customer requested to change loan purpose.",
    "Customer requested to change loan collateral.",
    "Customer requested to change loan insurance.",
    "Customer requested to change loan documents.",
    "Customer requested to change loan communications.",
    "Customer requested to change loan statements.",
    "Customer requested to change loan payment history.",
    "Customer requested to change loan fees.",
    "Customer requested to change loan status.",
    "Customer requested to change loan account number.",
    "Customer requested to change loan account type."
]
