consumer_lending__high_cost__mortgage_tests__notes = [
    "Loan passes HOEPA tests.",
    "Loan fails HOEPA tests.",
    "Additional disclosures required.",
    "Review required for accuracy.",
    "Test results verified.",
    "Data validated.",
    "Calculations confirmed.",
    "Thresholds met.",
    "Thresholds exceeded.",
    "No further action needed.",
    "Follow-up required.",
    "Escalated to compliance.",
    "Documentation reviewed.",
    "Exception granted.",
    "Waiver approved.",
    "Loan restructured.",
    "Terms adjusted.",
    "Fees reduced.",
    "APR recalculated.",
    "Points and fees recalculated.",
    "APOR updated.",
    "Test results documented.",
    "Compliance review completed.",
    "Loan closed successfully.",
    "Loan canceled.",
    "Borrower declined.",
    "Further review needed.",
    "Information pending.",
    "Awaiting documentation.",
    "Contact borrower.",
    "Contact loan officer.",
    "Contact underwriter.",
    "Contact compliance.",
    "Escalate to management.",
    "Review loan terms.",
    "Review loan purpose.",
    "Review borrower's financial situation.",
    "Review property appraisal.",
    "Review title report.",
    "Review insurance coverage.",
    "Review closing documents.",
    "Review loan disclosures.",
    "Review loan servicing.",
    "Review loan history.",
    "Review customer communications.",
    "Review regulatory requirements.",
    "Review internal policies.",
    "Review best practices.",
    "Review industry standards.",
    "Review market conditions.",
    "Review risk assessment.",
    "Review compliance checklist.",
    "Review exception request.",
    "Review waiver request.",
    "Review loan modification.",
    "Review loan restructure.",
    "Review fee reduction.",
    "Review APR recalculation.",
    "Review points and fees recalculation.",
    "Review APOR update.",
    "Review test results documentation.",
    "Review compliance review findings.",
    "Review loan closing process.",
    "Review loan cancellation process.",
    "Review borrower decline process.",
    "Review further review process.",
    "Review information pending process.",
    "Review awaiting documentation process.",
    "Review contact borrower process.",
    "Review contact loan officer process.",
    "Review contact underwriter process.",
    "Review contact compliance process.",
    "Review escalate to management process.",
    "Review loan terms review process.",
    "Review loan purpose review process.",
    "Review borrower's financial situation review process.",
    "Review property appraisal review process.",
    "Review title report review process.",
    "Review insurance coverage review process.",
    "Review closing documents review process.",
    "Review loan disclosures review process.",
    "Review loan servicing review process.",
    "Review loan history review process.",
    "Review customer communications review process.",
    "Review regulatory requirements review process.",
    "Review internal policies review process.",
    "Review best practices review process.",
    "Review industry standards review process.",
    "Review market conditions review process.",
    "Review risk assessment review process.",
    "Review compliance checklist review process.",
    "Review exception request review process.",
    "Review waiver request review process.",
    "Review loan modification review process.",
    "Review loan restructure review process.",
    "Review fee reduction review process.",
    "Review APR recalculation review process.",
    "Review points and fees recalculation review process.",
    "Review APOR update review process.",
    "Review test results documentation review process.",
    "Review compliance review findings review process.",
    "Review loan closing process review process.",
    "Review loan cancellation process review process.",
    "Review borrower decline process review process.",
    "Review further review process review process.",
    "Review information pending process review process.",
    "Review awaiting documentation process review process.",
    "Review contact borrower process review process.",
    "Review contact loan officer process review process.",
    "Review contact underwriter process review process.",
    "Review contact compliance process review process.",
    "Review escalate to management process review process."
]
