consumer_lending__reg_z_disclosures__security_interest = [
    "First mortgage on property",
    "Second mortgage on property",
    "Deed of trust",
    "Mortgage lien",
    "Security agreement",
    "Collateral assignment",
    "Personal guarantee",
    "None",
    "Not applicable",
    "See loan agreement",
    "First mortgage",
    "Second mortgage",
    "Property lien",
    "Security interest in collateral",
    "Borrower's personal guarantee",
    "No security interest",
    "N/A",
    "To be determined",
    "Subject to change",
    "First mortgage on real estate",
    "Second mortgage on real estate",
    "Deed of trust on property",
    "Mortgage lien on residence",
    "Security agreement for loan",
    "Collateral assignment of assets",
    "Personal guarantee by borrower",
    "No security interest required",
    "Not applicable to this loan",
    "Details in loan agreement",
    "Primary lien on property",
    "Secondary lien on property",
    "Security interest in home",
    "Guarantee by co-borrower",
    "No collateral pledged",
    "Information not available",
    "Pending further review",
    "Subject to final approval",
    "Security interest in vehicle",
    "Security interest in equipment",
    "Security interest in investments",
    "Security interest in other assets",
    "Combination of security interests",
    "Shared security interest",
    "Subordinate security interest",
    "Limited security interest",
    "Conditional security interest",
    "Contingent security interest",
    "Future security interest",
    "Undisclosed security interest",
    "Security interest waived",
    "Security interest released",
    "Security interest perfected",
    "Security interest enforced",
    "Security interest disputed",
    "Security interest challenged",
    "Security interest litigation",
    "Security interest foreclosure",
    "Security interest repossession",
    "Security interest bankruptcy",
    "Security interest insolvency",
    "Security interest default",
    "Security interest breach",
    "Security interest violation",
    "Security interest fraud",
    "Security interest misrepresentation",
    "Security interest error",
    "Security interest omission",
    "Security interest clarification",
    "Security interest amendment",
    "Security interest modification",
    "Security interest termination",
    "Security interest satisfaction",
    "Security interest discharge",
    "Security interest release of lien",
    "Security interest reconveyance",
    "Security interest quiet title action",
    "Security interest declaratory judgment",
    "Security interest indemnity",
    "Security interest insurance",
    "Security interest guarantee",
    "Security interest surety bond",
    "Security interest letter of credit",
    "Security interest escrow",
    "Security interest reserve account",
    "Security interest holdback",
    "Security interest set-off",
    "Security interest cross-collateralization",
    "Security interest subordination",
    "Security interest non-disturbance",
    "Security interest attornment",
    "Security interest estoppel certificate",
    "Security interest opinion of counsel",
    "Security interest due diligence",
    "Security interest title insurance",
    "Security interest environmental indemnity",
    "Security interest zoning compliance",
    "Security interest usury",
    "Security interest predatory lending",
    "Security interest consumer protection",
    "Security interest fair lending",
    "Security interest regulatory compliance",
    "Security interest legal opinion",
    "Security interest documentation",
    "Security interest perfection",
    "Security interest priority",
    "Security interest enforcement",
    "Security interest remedies",
    "Security interest litigation",
    "Security interest bankruptcy",
    "Security interest insolvency",
    "Security interest workout",
    "Security interest restructuring",
    "Security interest forbearance",
    "Security interest modification",
    "Security interest settlement",
    "Security interest compromise",
    "Security interest release",
    "Security interest discharge",
    "Security interest satisfaction",
    "Security interest termination"
]
