mortgage_services__loan_modifications__reason = [
    "Financial hardship due to job loss.",
    "Reduced income due to illness.",
    "Divorce or separation leading to financial strain.",
    "Unexpected medical expenses.",
    "Death of a co-borrower.",
    "Interest rate reduction request.",
    "Lower monthly payments needed.",
    "Extend loan term to reduce payments.",
    "Avoid foreclosure.",
    "Damage to property affecting value.",
    "Natural disaster impacting finances.",
    "Change in employment status.",
    "Disability affecting income.",
    "Business downturn impacting self-employment.",
    "Unexpected home repairs.",
    "Military deployment affecting income.",
    "Incarceration affecting income.",
    "Adjust loan terms to current market.",
    "Refinance out of adjustable-rate mortgage.",
    "Remove private mortgage insurance.",
    "Lower interest rates available.",
    "Improve affordability of loan.",
    "Change in family size.",
    "Retirement affecting income.",
    "Desire to pay off loan faster.",
    "Consolidate debt with lower interest rate.",
    "Access equity for home improvements.",
    "Change in property occupancy.",
    "Relocation affecting finances.",
    "Temporary financial hardship.",
    "Need for lower monthly payments.",
    "Interest rate reset causing higher payments.",
    "Desire for fixed-rate loan.",
    "Change in financial circumstances.",
    "Unexpected increase in expenses.",
    "Loss of rental income.",
    "Adjust loan terms to fit budget.",
    "Avoid default on loan.",
    "Maintain home ownership.",
    "Financial hardship due to unexpected expenses.",
    "Reduced income due to change in employment.",
    "Divorce or separation leading to financial instability.",
    "Unexpected medical bills.",
    "Death of a family member impacting finances.",
    "Interest rate reduction to save money.",
    "Lower monthly payments for better cash flow.",
    "Extend loan term for affordability.",
    "Prevent foreclosure proceedings.",
    "Property damage affecting loan-to-value ratio.",
    "Natural disaster causing financial hardship.",
    "Change in employment leading to lower income.",
    "Disability resulting in reduced income.",
    "Business downturn impacting self-employment income.",
    "Unexpected home repairs and maintenance costs.",
    "Military deployment causing financial strain.",
    "Incarceration leading to loss of income.",
    "Adjust loan terms to reflect current market conditions.",
    "Refinance to a more stable loan product.",
    "Eliminate private mortgage insurance.",
    "Take advantage of lower interest rates.",
    "Improve loan affordability and sustainability.",
    "Change in family size requiring financial adjustments.",
    "Retirement leading to lower income.",
    "Accelerate loan payoff.",
    "Consolidate high-interest debt.",
    "Access home equity for investments.",
    "Change in property occupancy status.",
    "Relocation leading to financial changes.",
    "Temporary financial difficulties.",
    "Reduce monthly payments for financial relief.",
    "Interest rate reset causing payment shock.",
    "Secure a fixed-rate loan for stability.",
    "Adapt to changing financial circumstances.",
    "Unexpected increase in living expenses.",
    "Loss of rental income affecting finances.",
    "Align loan terms with current budget.",
    "Prevent loan default and foreclosure.",
    "Preserve home ownership.",
    "Financial hardship due to unforeseen circumstances.",
    "Reduced income due to job change.",
    "Marital separation causing financial difficulties.",
    "Unexpected medical costs.",
    "Loss of a family member impacting income.",
    "Seek lower interest rate for savings.",
    "Reduce monthly payments for affordability.",
    "Extend loan term for manageable payments.",
    "Avoid foreclosure and loss of home.",
    "Property damage impacting value and equity.",
    "Natural disaster creating financial strain.",
    "Change in job leading to income reduction.",
    "Disability causing financial hardship.",
    "Business downturn affecting self-employment earnings.",
    "Unexpected home repair expenses.",
    "Military deployment leading to financial challenges.",
    "Incarceration resulting in loss of income.",
    "Adjust loan terms to match current market.",
    "Refinance to a more suitable loan program.",
    "Remove PMI for lower monthly payments.",
    "Benefit from lower interest rates.",
    "Enhance loan affordability and long-term sustainability.",
    "Family size change requiring financial adaptation.",
    "Retirement causing income adjustments.",
    "Pay off mortgage sooner.",
    "Consolidate debt for lower interest payments.",
    "Access equity for home improvements or investments.",
    "Change in property use or occupancy.",
    "Relocation leading to financial adjustments.",
    "Temporary financial setback.",
    "Lower monthly payments for financial breathing room.",
    "Interest rate reset causing payment increase.",
    "Obtain a fixed-rate loan for predictability.",
    "Respond to changing financial needs.",
    "Unexpected rise in cost of living.",
    "Loss of rental income affecting cash flow.",
    "Adjust loan terms to current financial situation.",
    "Prevent loan default and potential foreclosure.",
    "Maintain ownership of home.",
    "Financial difficulties due to unforeseen events.",
    "Reduced income due to career change.",
    "Relationship breakdown causing financial strain.",
    "Unexpected health-related expenses.",
    "Loss of a loved one impacting finances.",
    "Obtain a lower interest rate for financial relief.",
    "Reduce monthly payments for better affordability.",
    "Extend loan term for more manageable payments.",
    "Avoid foreclosure and protect home ownership.",
    "Property damage affecting loan-to-value.",
    "Natural disaster causing financial hardship.",
    "Job transition leading to income reduction.",
    "Disability resulting in financial challenges.",
    "Business downturn impacting self-employment income.",
    "Unexpected costs for home repairs.",
    "Military deployment creating financial strain.",
    "Incarceration leading to loss of income.",
    "Adjust loan terms to reflect current market conditions.",
    "Refinance to a more appropriate loan product.",
    "Eliminate PMI to lower monthly obligations.",
    "Take advantage of lower interest rate environment.",
    "Improve loan affordability and sustainability.",
    "Change in family size requiring financial adaptation.",
    "Retirement leading to income adjustments.",
    "Accelerate loan payoff for financial freedom.",
    "Consolidate debt for improved financial management.",
    "Access home equity for strategic purposes.",
    "Change in property occupancy or use.",
    "Relocation leading to financial changes.",
    "Temporary financial hardship or setback.",
    "Lower monthly payments for increased financial flexibility.",
    "Interest rate reset causing payment shock.",
    "Secure a fixed-rate loan for long-term stability.",
    "Adapt to evolving financial circumstances.",
    "Unexpected increase in essential expenses.",
    "Loss of rental income affecting overall budget.",
    "Adjust loan terms to align with current financial capabilities.",
    "Prevent loan default and preserve home ownership.",
    "Maintain stable housing and financial well-being."
]
