mortgage_services__hmda_application_demographics__ethnicity_free_form = [
    "Hispanic or Latino",
    "Not Hispanic or Latino",
    "Mexican, Mexican American, Chicano",
    "Puerto Rican",
    "Cuban",
    "Other Hispanic or Latino",
    "Do not wish to provide",
    "Information not available",
    "Decline to answer",
    "Prefer not to say",
    "Not disclosed",
    "Unavailable",
    "Unknown",
    "Undetermined",
    "Not collected",
    "Not reported",
    "Not specified",
    "Not indicated",
    "No information",
    "Data missing",
    "Not applicable",
    "Blank",
    "Null",
    "Empty",
    "Not answered",
    "No response",
    "Withheld",
    "Redacted",
    "Confidential",
    "Suppressed",
    "Restricted",
    "Protected",
    "Private"
]
