mortgage_services__documents__notes = [
  "Missing borrower signature on page 3.",
  "Document appears to be from previous tax year, please request current year.",
  "Credit explanation letter accepted.",
  "Blurry scan, please resubmit with higher quality.",
  "Employment verification incomplete, missing employer contact information.",
  "Bank statement missing pages 2-3, please resubmit complete document.",
  "Incorrect property address listed, needs correction.",
  "Supporting documentation matches requirements, approved.",
  "Gift letter requires donor's bank statement to verify source of funds.",
  "Explanation letter for credit inquiry satisfactory.",
  "Bank statement shows large deposit requiring sourcing.",
  "Paystub date doesn't meet timing requirements, need more recent document.",
  "W-2 amounts don't match stated income on application.",
  "Acceptable HOA documentation received.",
  "Property tax bill shows different owner name, requires explanation.",
  "Insurance declaration page shows insufficient coverage.",
  "Second home documentation satisfies occupancy requirements.",
  "Self-employment documentation incomplete, requires 2 years of returns.",
  "Retirement account statement accepted as asset verification.",
  "Divorce decree satisfactorily explains alimony income.",
  "Borrower name misspelled throughout document.",
  "Conditional approval letter from previous lender received.",
  "Previous mortgage statement confirms payoff amount.",
  "Closing disclosure from previous transaction received.",
  "Child support documentation accepted.",
  "Rental income documentation meets guidelines.",
  "Bankruptcy discharge papers verified and acceptable.",
  "Condo HOA certification shows pending special assessment.",
  "Document older than 90 days, please provide updated version.",
  "All pages present and clear, document accepted.",
  "Student loan deferment documentation received.",
  "Award letter confirms social security income.",
  "Profit and loss statement missing accountant certification.",
  "Investment account statement confirms sufficient assets for closing.",
  "Lease agreement confirms rental income.",
  "Retirement award letter verifies pension income.",
  "PMI cancellation documentation received.",
  "Title commitment shows outstanding lien.",
  "Appraisal indicates property condition issues requiring repair.",
  "Flood certification received, property not in flood zone.",
  "Power of attorney documentation properly executed.",
  "Trust documentation incomplete, missing signature page.",
  "Refinance interest rate lock confirmation received.",
  "Property survey shows encroachment issue.",
  "Tax transcript differs from submitted tax return.",
  "Citizenship documentation verified.",
  "Letter of explanation for address discrepancy accepted.",
  "Condominium project approval documentation received.",
  "Borrower's ID expired, need current identification.",
  "VA Certificate of Eligibility confirms available entitlement.",
  "Divorce decree missing page detailing property division.",
  "Homebuyer education certificate received.",
  "Proof of mortgage insurance premium payment received.",
  "Down payment gift documentation complete.",
  "Earnest money deposit verified with cleared check.",
  "Purchase agreement amendment changes closing date.",
  "VA funding fee receipt received.",
  "Authorization to release information signed by all parties.",
  "Final inspection report shows completed repairs.",
  "Completed 4506-T form for tax transcript request.",
  "Mortgage interest credit certificate received.",
  "Borrower authorization to pull credit report expired.",
  "Homeowners association budget appears financially sound.",
  "Property sold disclosure satisfies secondary residence requirements.",
  "Subordination agreement for existing second mortgage received.",
  "Relocation benefit confirmation from employer received.",
  "Construction-to-permanent loan documentation complete.",
  "Solar panel lease agreement received.",
  "Mortgage credit certificate from state housing agency received.",
  "Loan estimate acknowledgment signed by borrower.",
  "Borrower letter explaining gap in employment history.",
  "VA disability income documentation verified.",
  "Foreign national documentation meets requirements.",
  "Non-traditional credit references verified.",
  "First-time homebuyer program eligibility confirmed.",
  "Contract for deed payoff information received.",
  "Manufactured home title documentation incomplete.",
  "Bridge loan approval from other lender received.",
  "Documentation of resolved collections received.",
  "Lien release for previously paid debt received.",
  "Death certificate for deceased co-borrower received.",
  "Completed FHA loan application addendum.",
  "USDA eligibility confirmation received.",
  "Proof of property insurance premium payment.",
  "Hazard insurance declaration page meets requirements.",
  "Borrower's permanent resident card verified.",
  "Flood insurance documentation satisfies requirements.",
  "Borrower clarification on employment history received.",
  "Homeowners association litigation disclosure reviewed.",
  "Completed homeowners association questionnaire.",
  "Proof of business ownership percentage received.",
  "Farm income documentation meets requirements.",
  "Military leave and earnings statement received.",
  "Verification of rent payment history received.",
  "Proof of resolved judgment received.",
  "Student loan income-based repayment documentation.",
  "Borrower's written explanation for large bank deposit received.",
  "Retirement income verification from former employer.",
  "Stock option documentation from employer received.",
  "Commission income documentation meets requirements.",
  "Bonus income documentation shows 2-year history.",
  "Investment property rental income verification.",
  "Verification of mortgage from previous lender received.",
  "Trust income documentation meets requirements.",
  "HELOC agreement shows sufficient remaining credit line.",
  "Pre-approval letter for backup offer financing.",
  "Documentation of non-borrowing spouse income.",
  "Underwriter exception approval for debt ratio.",
  "Borrower's letter explaining recent credit inquiries.",
  "Proof of pay-off for collections.",
  "Verification of down payment source complete.",
  "Borrower's authorization for verification of deposit.",
  "Missing Schedule E from tax returns.",
  "Property address verification matches application.",
  "Completed request for transcript of tax return.",
  "Borrower attestation for undisclosed debt received.",
  "Proof of business location lease extension.",
  "Completed escrow waiver form.",
  "Third-party verification of employment received.",
  "Self-employed business license verification.",
  "Proof of insurance for additional properties owned.",
  "Income calculation worksheet completed by underwriter.",
  "Year-to-date profit and loss statement signed.",
  "Insurance binder listing lender as mortgagee.",
  "Property tax verification shows current status.",
  "Completed condominium project questionnaire.",
  "Verification of deposit shows sufficient funds.",
  "Gift funds transfer confirmed via bank statement.",
  "Loan officer notes on borrower's qualifying ratios.",
  "Confirmation of zero balance on paid accounts.",
  "Divorce settlement showing property distribution.",
  "Borrower explanation for address history gaps.",
  "Military service verification for VA loan.",
  "Settlement statement from sale of previous home.",
  "Bank statement shows recurring income deposits.",
  "Documentation of resolved tax liens.",
  "Initial escrow disclosure statement signed.",
  "Borrower's explanation for recent change in employment.",
  "Proof of ownership for business assets used.",
  "Proof of receipt of child support income.",
  "Notice of right to cancel signed by borrowers.",
  "Asset verification through automated system complete.",
  "Employment verification for second job.",
  "Explanation for credit score discrepancy between bureaus.",
  "Proof of closing costs received from alternative source.",
  "Completed FHA amendatory clause.",
  "Borrower's explanation for credit report discrepancies.",
  "Proof of mortgage interest rate reduction.",
  "Income calculation for variable income sources.",
  "Proof of homeowners association dues payment.",
  "Rental property agreement with current tenant.",
  "Certificate of reasonable value for VA loan.",
  "Proof of business continuation insurance.",
  "Verification of timeshare ownership and expenses.",
  "Proof of deposit for earnest money.",
  "Documentation of co-borrower contribution percentage.",
  "Statement of occupancy intent signed.",
  "Borrower's explanation for collection accounts.",
  "Completed credit supplement with updated information.",
  "Documentation for excluded debts in debt-to-income ratio.",
  "Third-party verification of business income.",
  "Verification of employment stability assessment.",
  "Retirement income verification with continuation terms.",
  "Borrower's explanation for large cash deposit.",
  "Debt consolidation plan explanation letter.",
  "Documentation of borrower name variation.",
  "Previous mortgage payment history verification.",
  "Verification of borrower-paid mortgage insurance termination.",
  "Borrower's explanation for previous foreclosure.",
  "Underwriter's notes on income verification exceptions.",
  "Borrower's letter explaining purpose of cash-out refinance.",
  "Proof of resolution for previous bankruptcy.",
  "Documentation of separate property agreement.",
  "Explanation for source of down payment changing.",
  "Student loan deferment or income-based repayment verification.",
  "Completed statement of information for title.",
  "Documentation of source of large deposit.",
  "Property appraisal review notes.",
  "Borrower's explanation for credit score change.",
  "Verification of mortgage insurance coverage.",
  "Borrower acknowledgment of final loan terms.",
  "Completed private mortgage insurance disclosure.",
  "Explanation of non-occupant co-borrower relationship.",
  "Property tax assessment verification.",
  "Borrower's explanation for previous loan denial.",
  "Completed real estate certification.",
  "Third-party employment verification service results received.",
  "Updated paystub showing bonus payment received.",
  "HOA special assessment documentation reviewed.",
  "Borrower's explanation for short job tenure accepted.",
  "Evidence of gift funds transfer from donor to borrower.",
  "Seller credit for closing costs documentation.",
  "Homeowners insurance premium amount verification.",
  "Borrower's explanation of rental property vacancy history.",
  "Appraisal review completed with value confirmation.",
  "Documentation of retirement account liquidation for down payment."
]
