mortgage_services__customer_communications__content = [
  "Thank you for your recent mortgage application. We've received all your documents and are proceeding with the review process.",
  "We need your updated pay stubs for the last 30 days to proceed with your application. Please upload them to your secure portal.",
  "Your loan has been approved! We're now preparing the closing documents. Our closing department will contact you to schedule the signing.",
  "We've received your inquiry about lowering your interest rate. Please call us to discuss refinancing options that may be available to you.",
  "Your escrow analysis is complete. Your monthly payment will increase by $45.21 starting next month due to increased property taxes.",
  "This is a reminder that your mortgage payment is due in 5 days. Please ensure funds are available if you use autopay.",
  "We've received your mortgage application and assigned loan officer Sarah Johnson to your file. She'll contact you within 24 hours.",
  "Your rate lock is set to expire on 06/15/2023. Please contact us immediately if you need to extend it.",
  "We've scheduled your closing for Tuesday, July 12th at 10:00 AM at First Title Company on Main Street.",
  "Your appraisal has been completed. We'll share the results with you after our underwriting team reviews it.",
  "We've received your homeowners insurance information. No further action is needed regarding insurance at this time.",
  "We need clarification about the large deposit of $12,500 in your checking account on 3/15. Please provide documentation of its source.",
  "Your loan modification application has been received. We'll review it and contact you within 5-7 business days.",
  "We've received your request to cancel PMI. We're reviewing your current loan-to-value ratio and will notify you of our decision soon.",
  "This confirms receipt of your extra principal payment of $5,000. It has been applied to your loan balance.",
  "Thank you for enrolling in autopay. Your monthly payment of $1,456.32 will be automatically withdrawn on the 1st of each month.",
  "Your request for a payoff statement has been received. We'll send it to your email address within 3 business days.",
  "We need additional information about your self-employment income. Please submit your business tax returns for the past two years.",
  "Your property tax payment of $3,245.68 was disbursed from your escrow account on October 15th.",
  "We've reviewed your financial hardship letter. A member of our loss mitigation team will call you within 48 hours.",
  "We need your signature on page 4 of the loan estimate. Please sign and return it as soon as possible.",
  "Your loan application is currently in underwriting. We anticipate completing this process within 10 business days.",
  "We've received your homebuyer education certificate. This satisfies the requirement for your first-time homebuyer program.",
  "Your hazard insurance premium of $876.45 was paid from your escrow account on September 5th.",
  "Our records show your mortgage payment is 15 days past due. Please remit payment immediately to avoid late fees.",
  "We've completed the verification of your employment. No further documentation is needed at this time.",
  "Your request to change your payment due date has been approved. Your new due date will be the 15th of each month.",
  "We've received your flood insurance documentation. It meets our requirements, and no further action is needed.",
  "Your closing disclosure has been prepared. Please review it carefully and let us know if you have any questions.",
  "We were unable to verify your rental history. Please provide contact information for your current and previous landlords.",
  "Your loan is now in the final approval stage. We anticipate clearing for closing within the next 5 business days.",
  "We've received your signed disclosures. Thank you for returning them promptly.",
  "Your escrow shortage is $867.23. You can pay it in full or have it spread over the next 12 months (adding $72.27 to monthly payment).",
  "We need documentation to verify the source of your down payment funds. Please provide bank statements showing the money trail.",
  "Your credit report shows a recently opened account that wasn't disclosed on your application. Please provide details about this account.",
  "We've ordered your appraisal, which typically takes 7-10 business days to complete. We'll notify you when it's finished.",
  "Your request for a forbearance plan has been approved. Your payments will be suspended for the next 3 months.",
  "We need updated bank statements for all accounts listed on your application. Please provide statements for the last 60 days.",
  "Your loan has been transferred to our servicing department. Your first payment is due on August 1st.",
  "We've received your inquiry about removing a co-borrower from your loan. This will require a full refinance application.",
  "Your mortgage statement is now available in your online account. You can view and download it at any time.",
  "We need a copy of your divorce decree to verify the alimony income stated on your application.",
  "Your appraisal came in lower than expected. Please contact your loan officer to discuss your options.",
  "We've received your request to postpone your closing date. We've rescheduled it for Friday, October 23rd.",
  "Your PMI cancellation has been approved. It will be removed effective with your next monthly payment.",
  "We need additional information about your previous address history. Please fill out the enclosed form.",
  "Your loan modification has been approved! Your new monthly payment will be $1,235.67 beginning next month.",
  "We've received your homeowners association contact information. No further action is needed at this time.",
  "Your loan application requires a co-signer due to your debt-to-income ratio. Please let us know if you'd like to proceed with this option.",
  "We need verification of your retirement income. Please send your award letter or recent benefit statement.",
  "Your property tax assessment has increased, which will affect your escrow payment starting in January.",
  "We've received your request for a streamline refinance. A loan officer will contact you within 2 business days to discuss.",
  "Your closing costs will be approximately $8,500. Please arrange to bring a cashier's check to your closing appointment.",
  "We need your signature on the attached tax transcript request form to proceed with your application.",
  "Your interest rate of 4.25% has been locked for 45 days, expiring on November 30th.",
  "We've received your inquiry about making biweekly payments. Please call our customer service to set up this arrangement.",
  "Your application is suspended pending receipt of additional documentation. Please see the attached list of required items.",
  "We need written explanation for the recent gap in your employment history to proceed with underwriting.",
  "Your request for a loan assumption has been received. We'll review it and contact you within 10 business days.",
  "We've verified receipt of your earnest money deposit of $5,000 through the title company.",
  "Your escrow account is projected to have a surplus of $345.87 after this year's tax and insurance payments.",
  "We need a copy of the purchase agreement addendum mentioned by your real estate agent.",
  "Your loan is clear to close! We'll schedule your closing appointment within the next 5 business days.",
  "We've received your request for a mortgage loan verification. We'll send it directly to the requesting party.",
  "Your annual escrow account disclosure statement is enclosed. Please review it for important information about your account.",
  "We need documentation regarding the solar panels on the property you're purchasing. Please clarify if they're leased or owned.",
  "Your loan file is currently with our quality control department for a standard pre-closing review.",
  "We've received your notice of address change. Your records have been updated accordingly.",
  "Your request for a principal reduction quote has been processed. Please see the attached statement.",
  "We need clarification about the non-borrowing spouse information on your loan application.",
  "Your flood insurance requirement has been waived based on the updated flood certification.",
  "We've received your inquiry about loan subordination. Please complete the enclosed request form.",
  "Your closing costs have been revised due to changes in your homeowners insurance premium. Please review the updated disclosure.",
  "We need verification of the sale of your current home to proceed with your new purchase loan.",
  "Your loan application has been denied. Please refer to the enclosed adverse action notice for specific reasons.",
  "We've received your request for information about our first-time homebuyer programs. Please see the attached brochure.",
  "Your monthly payment will change due to an adjustment in your adjustable-rate mortgage. The new rate will be 4.75%.",
  "We need verification of your bonus income. Please provide documentation showing a two-year history.",
  "Your appraisal inspection is scheduled for Thursday, May 18th at 2:00 PM. Please ensure access to all areas of the home.",
  "We've received your request for a mortgage credit certificate. The application is being processed.",
  "Your loan is subject to property tax proration at closing. This will be calculated by the title company.",
  "We need a complete copy of your trust documents to proceed with your application.",
  "Your VA funding fee has been processed and added to your loan amount as requested.",
  "We've received your inquiry about debt consolidation options. A loan officer will contact you to discuss possibilities.",
  "Your request to waive escrow has been denied based on your current loan-to-value ratio.",
  "We need verification of your child support income. Please provide court documents and proof of receipt.",
  "Your homeowners association has returned the completed questionnaire. No issues were identified.",
  "We've received your inquiry about assumable mortgage options. Please see the attached information sheet.",
  "Your loan is in the final review stage. We anticipate clearing all conditions within the next 48 hours.",
  "We need verification of the earnest money deposit mentioned in your purchase agreement.",
  "Your private mortgage insurance premium will increase by $12.35 monthly due to changes in coverage requirements.",
  "We've received your documents related to your military service. Your VA eligibility has been confirmed.",
  "Your rate lock extension has been processed. The new expiration date is December 15th.",
  "We need clarification about the rental income shown on your tax returns.",
  "Your loan approval is contingent on the completion of the home renovations. Please send photos when work is finished.",
  "We've received your request for information about reverse mortgage options. A specialist will contact you.",
  "Your pre-approval letter has been issued and is valid for 90 days from today's date.",
  "We need your written authorization to verify your employment with your current employer.",
  "Your loan is approved with conditions. Please review the attached list of items still needed.",
  "We've received your inquiry about debt-to-income ratio requirements. Your loan officer will call to discuss.",
  "Your escrow account shows a deficit due to increased insurance premiums. Your monthly payment will be adjusted accordingly.",
  "We need documentation regarding your student loan deferment to accurately calculate your debt-to-income ratio.",
  "Your interest rate will adjust on July 1st based on the terms of your adjustable-rate mortgage.",
  "We've received your hardship letter explaining the circumstances of your late payments.",
  "Your application for our special first responder mortgage program has been received.",
  "We need verification of your current rental payment amount and history.",
  "Your loan has been sold to a new servicer. You'll receive official notification within 15 days.",
  "We've received your homeowners association dues information. It has been included in your escrow calculation.",
  "Your request for a subordination agreement for your home equity line of credit has been approved.",
  "We need a copy of your homeowners insurance binder before we can schedule your closing.",
  "Your loan documentation is being prepared for closing. We'll contact you to schedule an appointment soon.",
  "We've received your inquiry about paying off your mortgage early. There is no prepayment penalty on your loan.",
  "Your escrow account has insufficient funds to pay your upcoming property tax bill. Please remit $1,240.56.",
  "We need your updated income documentation as your paystubs are now more than 60 days old.",
  "Your certificate of eligibility for a VA loan has been verified. We'll proceed with processing your application.",
  "We've received your request to skip a payment. This option is not available on your type of loan.",
  "Your loan terms offer an interest rate reduction after 36 consecutive on-time payments.",
  "We need documentation verifying your down payment gift funds have been transferred to your account.",
  "Your loan is being reviewed by our underwriting committee due to the unique aspects of your financial situation.",
  "We've received your inquiry about government-backed loan programs. Please see the comparison chart attached.",
  "Your loan modification application is incomplete. Please provide the items listed on the enclosed form.",
  "We need proof of resolution for the judgment that appears on your credit report.",
  "Your mortgage recast request has been received. We'll determine your eligibility and contact you.",
  "We've received your request for historical mortgage interest statements. They'll be mailed within 10 business days.",
  "Your loan requires a minimum down payment of 5% based on your credit score and property type.",
  "We need verification of your self-employment income using the attached form completed by your accountant.",
  "Your loan-to-value ratio is currently 85%, which requires private mortgage insurance.",
  "We've received your request to change the way tax and insurance payments are handled on your loan.",
  "Your current loan balance is $325,456.78 as of April 30th.",
  "We need documentation explaining the recent large deposits in your checking account.",
  "Your loan application file has been assigned to underwriter Michael Chen for review.",
  "We've received your inquiry about cash-out refinance options. A loan officer will contact you to discuss.",
  "Your escrow analysis shows a surplus of $437.89, which will be refunded to you within 30 days.",
  "We need a signed letter explaining the recent inquiries on your credit report.",
  "Your interest rate lock request has been received. We'll process it once we receive your signed disclosures.",
  "We've received your homeowners association contact information. Thank you for providing it promptly.",
  "Your adjustable-rate mortgage will have its first rate adjustment in August. We'll send details in advance.",
  "We need clarification on your ownership interest in other properties listed on your tax return.",
  "Your request for rapid refinance has been received. We'll need minimal documentation as you're an existing customer.",
  "We've received your inquiry about building a home. Please review the attached construction loan information.",
  "Your application indicates you'll occupy the property as your primary residence. Please confirm this is correct.",
  "We need documentation regarding the business loss shown on your tax returns.",
  "Your conditional approval expires in 30 days. Please submit the remaining documentation as soon as possible.",
  "We've received your inquiry about USDA rural housing loans. A specialist will contact you to discuss eligibility.",
  "Your loan has been approved! Congratulations on this important milestone toward homeownership.",
  "We need verification of the source of funds for your recent large bank deposit.",
  "Your escrow account will need an additional $342.67 to cover the increased property insurance premium.",
  "We've received your inquiry about our energy-efficient mortgage options. Please see the attached information.",
  "Your application indicates rental income. Please provide copies of your current lease agreements.",
  "We need written explanation for the address discrepancies that appeared during our verification process.",
  "Your loan terms include a prepayment penalty if the loan is paid off within the first 3 years.",
  "We've received your request for duplicate tax forms. They will be mailed to your address on file.",
  "Your loan application shows multiple real estate owned properties. Please complete the attached schedule.",
  "We need verification of your retirement assets to establish sufficient reserves for your loan approval.",
  "Your appraisal fee of $550 has been collected and the appraisal has been ordered.",
  "We've received your request to cancel automatic payments. This change will take effect after your next scheduled payment.",
  "Your mortgage statement will arrive by the 10th of each month. You can also access it online anytime.",
  "We need documentation verifying the dissolution of your business mentioned in your hardship letter.",
  "Your loan approval is subject to verification of rent payments for the past 12 months.",
  "We've received your inquiry about down payment assistance programs. A housing counselor will contact you.",
  "Your interest rate lock extension will cost $375. Please let us know if you wish to proceed.",
  "We need a copy of your bankruptcy discharge papers to proceed with your loan application.",
  "Your mortgage has an adjustable interest rate that can change once per year after the initial fixed period.",
  "We've received your request for a second review of your denied application. Our appeals committee will evaluate it.",
  "Your property appraisal shows a value of $345,000, which supports your requested loan amount.",
  "We need verification of your identity. Please provide a copy of your driver's license or passport.",
  "Your loan commitment expires on August 15th. All conditions must be cleared by that date.",
  "We've received your inquiry about special programs for medical professionals. Please see the attached information.",
  "Your application indicates a previous foreclosure. Please provide details and explanation.",
  "We need your authorization to obtain verification of mortgage on your current home.",
  "Your escrow account is projected to have a shortage next year due to increasing property taxes.",
  "We've received your inquiry about refinancing your investment property. Different terms apply for non-owner occupied homes.",
  "Your loan application has been received, but we need your signature on page 3 of the disclosure form.",
  "We need documentation regarding the timeshare ownership listed on your credit report.",
  "Your closing disclosure must be delivered at least 3 business days before your scheduled closing date.",
  "We've received your question about whether points are tax-deductible. Please consult your tax advisor for guidance.",
  "Your interest rate can be lowered by 0.25% if you establish automatic payments from your checking account.",
  "We need the contact information for your homeowners association to complete the condo questionnaire.",
  "Your request for an interest-only payment option cannot be accommodated with your loan program.",
  "We've received your inquiry about mortgage assumption. Please review the eligibility requirements in the attached document.",
  "Your monthly mortgage statement will now be delivered electronically as requested.",
  "We need verification of funds for closing. Please provide your most recent bank statement."
]
