mortgage_services__hmda_application_demographics__race_observed = [
    "Not applicable",
    "Visual observation",
    "Surname",
    "Language",
    "Not provided",
    "Observed",
    "Not observed",
    "Unavailable",
    "Undetermined",
    "Information not available",
    "Based on visual cues",
    "Inferred from name",
    "Assumed based on appearance",
    "Determined through interaction",
    "Not explicitly stated",
    "Gathered from context",
    "Implied but not confirmed",
    "Unclear from documentation",
    "Based on limited information",
    "Visual assessment",
    "Name analysis",
    "Cultural cues",
    "Behavioral observation",
    "Indirect indicators",
    "Not self-reported",
    "Observed characteristics",
    "Assumed race",
    "Limited visibility",
    "Partial information",
    "Not fully disclosed",
    "Observation-based",
    "Name-based inference",
    "Contextual clues",
    "Implied race",
    "Documentation ambiguity",
    "Information scarcity",
    "Visual cues only",
    "Name suggests",
    "Appearance implies",
    "Interaction suggests",
    "Not explicitly provided",
    "Contextual determination",
    "Implied but unverified",
    "Documentation limitations",
    "Partial observation",
    "Limited disclosure",
    "Visual estimation",
    "Name-based assumption",
    "Cultural indicators",
    "Behavioral cues",
    "Indirect assessment",
    "Non-self-reported",
    "Observed traits",
    "Assumed background",
    "Visibility constraints",
    "Information gaps",
    "Disclosure limitations",
    "Observation-driven",
    "Name-driven inference",
    "Contextual hints",
    "Implied heritage",
    "Documentation uncertainty",
    "Data insufficiency",
    "Visual evidence",
    "Name indicates",
    "Appearance suggests",
    "Interaction implies",
    "Not directly stated",
    "Contextual interpretation",
    "Implied but not certain",
    "Documentation constraints",
    "Incomplete observation",
    "Restricted disclosure",
    "Visual approximation",
    "Name-based conjecture",
    "Cultural markers",
    "Behavioral hints",
    "Indirect determination",
    "Non-self-identification",
    "Observed features",
    "Assumed origin",
    "Limited observability",
    "Information deficit",
    "Disclosure restrictions",
    "Observation-oriented",
    "Name-oriented inference",
    "Contextual suggestions",
    "Implied ancestry",
    "Documentation ambiguity",
    "Data limitations",
    "Visual perception",
    "Name association",
    "Cultural associations",
    "Behavioral patterns",
    "Indirect evidence",
    "Non-self-declared",
    "Observed attributes",
    "Assumed descent",
    "Limited exposure",
    "Information constraints",
    "Disclosure constraints",
    "Observation-focused",
    "Name-focused inference",
    "Contextual inferences",
    "Implied lineage",
    "Documentation inconsistency",
    "Data scarcity",
    "Visual appraisal",
    "Name-based deduction",
    "Cultural background",
    "Behavioral indicators",
    "Indirect observation",
    "Non-self-professed",
    "Observed qualities",
    "Assumed heritage",
    "Limited access",
    "Information restrictions",
    "Disclosure limitations"
]
