mortgage_services__hmda_application_demographics__race_free_form = [
    "White",
    "Black or African American",
    "Asian",
    "American Indian or Alaska Native",
    "Native Hawaiian or Other Pacific Islander",
    "Some other race",
    "Two or more races",
    "Decline to answer",
    "Information not provided",
    "Not applicable",
    "No information",
    "Data missing",
    "Not collected",
    "Not reported",
    "Not specified",
    "Not indicated",
    "Blank",
    "Null",
    "Empty",
    "Not answered",
    "No response",
    "Withheld"
]
