INSERT INTO "enterprise"."currency" (code, name) VALUES
('USD', 'United States Dollar'),
('EUR', 'Euro'),
('GBP', 'British Pound Sterling'),
('JPY', 'Japanese Yen'),
('AUD', 'Australian Dollar'),
('CAD', 'Canadian Dollar'),
('CHF', 'Swiss Franc'),
('CNY', 'Chinese Yuan Renminbi'),
('HKD', 'Hong Kong Dollar'),
('NZD', 'New Zealand Dollar'),
('SEK', 'Swedish Krona'),
('NOK', 'Norwegian Krone'),
('DKK', 'Danish Krone'),
('SGD', 'Singapore Dollar'),
('MXN', 'Mexican Peso'),
('BRL', 'Brazilian Real'),
('INR', 'Indian Rupee'),
('RUB', 'Russian Ruble'),
('ZAR', 'South African Rand'),
('TRY', 'Turkish Lira'),
('KRW', 'South Korean Won'),
('PLN', 'Polish Zloty'),
('ILS', 'Israeli Shekel'),
('AED', 'United Arab Emirates Dirham'),
('SAR', 'Saudi Riyal'),
('THB', 'Thai Baht'),
('MYR', 'Malaysian Ringgit'),
('IDR', 'Indonesian Rupiah'),
('PHP', 'Philippine Peso'),
('ARS', 'Argentine Peso');
