__statement_fees__type = [
    "SERVICE",
    "TRANSACTION",
    "OVERDRAFT",
    "LATE_PAYMENT",
    "MAINTENANCE",
    "ATM",
    "INSUFFICIENT_FUNDS",
    "STOP_PAYMENT",
    "WIRE_TRANSFER",
    "FOREIGN_TRANSACTION",
    "ACCOUNT_CLOSURE",
    "PAPER_STATEMENT",
    "INACTIVITY"
]
