services:
  globals_documents:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $GLOBALS_DOCUMENTS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $GLOBALS_DOCUMENTS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $GLOBALS_DOCUMENTS_OTEL_SERVICE_NAME
      DOCUMENTS_URI: $DOCUMENTS_URI
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6148:8080
