enterprise__accounts__description_dict = {
  "personal": [
    "Checking account for daily use",
    "Savings for short-term goals",
    "Personal investment account",
    "High-yield savings account",
    "Emergency fund savings",
    "Joint checking account",
    "Mortgage escrow account",
    "Online savings account",
    "Foreign currency account",
    "Student checking account",
    "Holiday savings account",
    "Home improvement fund",
    "Child's education savings",
    "Wedding savings fund",
    "Down payment savings",
    "Medical savings account",
    "Vehicle maintenance fund",
    "Technology upgrade fund",
    "Event planning account",
    "Subscription payment account",
    "Gift savings account",
    "Insurance premium account",
    "Utilities payment account",
    "Debt repayment account",
    "Vacation savings account",
    "Investment dividends account",
    "Recurring expenses account",
    "Daily spending account",
    "Monthly bills account",
    "Personal budget account",
    "Real estate investment",
    "Stock trading account",
    "Cryptocurrency trading",
    "Collectibles investment",
    "Art investment fund",
    "Personal expense tracking",
    "Financial planning account",
    "Budget planning account",
    "Goal tracking account",
    "Net worth tracking",
    "Tax preparation fund",
    "Donation processing account",
    "Alimony payment account",
    "Child support account",
    "Rewards program account",
    "Loyalty program account",
    "Gift card account",
    "Prepaid expense account"
  ],
  "business": [
    "Business operating account",
    "Payroll processing account",
    "Travel expense account",
    "Rent collection account",
    "Tax payment account",
    "Startup business account",
    "Freelance income account",
    "Side hustle earnings",
    "Small business savings",
    "Business expansion fund",
    "Research and development",
    "Marketing campaign fund",
    "Employee benefits fund",
    "Equipment purchase fund",
    "Inventory management fund",
    "Legal expenses fund",
    "Consulting services fund",
    "Training and education fund",
    "Software development fund",
    "Website maintenance fund",
    "Data storage fund",
    "Cybersecurity fund",
    "Network infrastructure fund",
    "Cloud services fund",
    "Mobile app development",
    "Content creation fund",
    "Social media marketing",
    "Public relations fund",
    "Customer support fund",
    "Shipping and logistics fund",
    "Product design fund",
    "Manufacturing expenses",
    "Raw materials fund",
    "Quality control fund",
    "Retail sales account",
    "Wholesale sales account",
    "E-commerce sales account",
    "Affiliate marketing fund",
    "Grant funding account",
    "Scholarship fund account",
    "Endowment fund account",
    "Merchant services account",
    "Point of sale account",
    "Business expense tracking",
    "Audit preparation fund",
    "Customer acquisition",
    "Customer retention fund",
    "Sales pipeline fund",
    "Lead generation fund",
    "Referral program fund",
    "Partnership fund",
    "Supplier payments",
    "Distributor payments",
    "Commission payments",
    "Royalty payments",
    "Franchise fee account",
    "Licensing fee account",
    "Service fees account",
    "Consulting fees",
    "Training fees",
    "Installation fees",
    "Maintenance fees",
    "Repair fees",
    "Delivery fees",
    "Shipping fees",
    "Storage fees",
    "Handling fees",
    "Processing fees",
    "Transaction fees"
  ],
  "retirement": [
    "Retirement savings account",
    "Trust fund account",
    "Estate planning fund",
    "Inheritance distribution"
  ]
}
