consumer_lending__compliance_exceptions__remediation_plan = [
    "Obtain missing signature.",
    "Correct APR disclosure.",
    "Reissue disclosure on time.",
    "Obtain complete documents.",
    "Provide missing appraisal.",
    "Recalculate finance charge.",
    "Issue adverse action notice.",
    "Correct HOEPA determination.",
    "Provide flood insurance disclosure.",
    "Correct loan-to-value calculation.",
    "Correct borrower's ethnicity.",
    "Correct loan purpose classification.",
    "Obtain self-employment income documents.",
    "Verify borrower's identity.",
    "Correct credit score reporting.",
    "Report late payment to credit bureau.",
    "Correct late fee assessment.",
    "Provide missing disclosures.",
    "Correct borrower information mismatch.",
    "Recalculate escrow payment.",
    "Obtain missing signature on agreement.",
    "Correct interest rate disclosure.",
    "Reissue TIL disclosure on time.",
    "Obtain rental income documentation.",
    "Provide proof of insurance.",
    "Recalculate total loan costs.",
    "Provide appraisal notice.",
    "Correct MLA covered borrower status.",
    "Provide ARM booklet.",
    "Correct debt-to-income calculation.",
    "Correct borrower's race.",
    "Correct property type classification.",
    "Obtain child support income documents.",
    "Verify borrower's address.",
    "Correct credit inquiry reporting.",
    "Document late payment properly.",
    "Correct prepayment penalty assessment.",
    "Provide missing notices.",
    "Correct co-borrower information mismatch.",
    "Recalculate payoff amount.",
    "Obtain missing signature on modification.",
    "Correct payment amount disclosure.",
    "Reissue Loan Estimate on time.",
    "Obtain alimony income documentation.",
    "Provide proof of flood insurance.",
    "Recalculate closing costs.",
    "Provide notice of action taken.",
    "Correct HOEPA exemption determination.",
    "Provide loan servicing information.",
    "Correct loan term calculation.",
    "Correct borrower's sex.",
    "Correct occupancy type classification.",
    "Obtain investment income documentation.",
    "Verify borrower's employment.",
    "Correct public records reporting.",
    "Update account history with late payment.",
    "Correct origination fee assessment.",
    "Provide disclosures in a timely manner.",
    "Correct property address information.",
    "Recalculate refund amount.",
    "Obtain missing signature on forbearance.",
    "Correct disbursement amount.",
    "Reissue escrow statement on time.",
    "Obtain retirement income documentation.",
    "Provide proof of hazard insurance.",
    "Recalculate prepayment penalty.",
    "Provide notice of right to cancel.",
    "Correct high-cost mortgage determination.",
    "Provide loan assumption information.",
    "Correct loan payoff date calculation.",
    "Correct borrower's marital status.",
    "Correct loan type classification.",
    "Obtain government assistance income documents.",
    "Verify borrower's citizenship status.",
    "Correct credit limit reporting.",
    "Correct late payment coding.",
    "Correct annual fee assessment.",
    "Provide disclosures electronically.",
    "Correct applicant/co-applicant information.",
    "Recalculate escrow refund.",
    "Obtain missing signature on arrangement.",
    "Correct payment frequency disclosure.",
    "Reissue Closing Disclosure on time.",
    "Obtain disability income documentation.",
    "Provide proof of title insurance.",
    "Recalculate daily interest.",
    "Provide notice of credit score used.",
    "Correct MLA exemption determination.",
    "Provide loan modification information.",
    "Correct loan origination date calculation.",
    "Correct borrower's age.",
    "Correct loan status classification.",
    "Obtain other income source documentation.",
    "Verify borrower's phone number.",
    "Correct credit utilization reporting.",
    "Disclose late payment properly.",
    "Correct late charge assessment.",
    "Provide disclosures in Spanish.",
    "Correct loan account information.",
    "Recalculate principal balance.",
    "Obtain signature on payoff statement.",
    "Apply correct interest rate.",
    "Deliver periodic statement on time.",
    "Obtain self-employment expense documentation.",
    "Provide proof of liability insurance.",
    "Recalculate escrow shortage.",
    "Provide notice of adverse action."
]
