consumer_banking__beneficiaries__supplementary_data = [
    "Secondary contact: John Smith (555-123-4567)",
    "Beneficiary is a minor, trust managed by Jane Doe",
    "Payment instructions: wire transfer only",
    "Address verification required before first payment",
    "Relationship to account holder: spouse",
    "Share percentage: 25%",
    "Charity registration number: 1234567890",
    "Designated for scholarship fund",
    "Legal document reference: Trust Agreement dated 2023-03-01",
    "Beneficiary is a non-profit organization",
    "Tax ID number: 9876543210",
    "Payment to be made in installments",
    "Requires additional KYC/AML verification",
    "Preferred contact method: email",
    "Payment subject to court approval",
    "Beneficiary is a foreign entity",
    "Requires currency conversion",
    "Payment instructions attached",
    "Special handling instructions for beneficiary",
    "Beneficiary requires paper checks",
    "Do not contact beneficiary directly",
    "Account holder's authorization on file",
    "Beneficiary details confirmed by phone",
    "Payment subject to withholding tax",
    "Beneficiary's address is a PO Box",
    "Payment requires manual approval",
    "Beneficiary is deceased, estate handling payment",
    "Payment contingent on beneficiary reaching age 18",
    "Beneficiary is a business partner",
    "Payment instructions provided by beneficiary",
    "Beneficiary requires payment by specific date",
    "Account holder's relationship to beneficiary: sibling",
    "Beneficiary's ID document on file",
    "Payment subject to regulatory restrictions",
    "Beneficiary's contact information updated recently",
    "Payment requires additional internal review",
    "Beneficiary is a former employee",
    "Payment to be split between multiple accounts",
    "Beneficiary's bank details to be verified",
    "Payment instructions subject to change",
    "Beneficiary is a government agency",
    "Payment requires special coding",
    "Beneficiary's tax status needs clarification",
    "Payment subject to anti-fraud checks",
    "Beneficiary's signature required on receipt",
    "Payment requires dual authorization",
    "Beneficiary is a trust fund",
    "Payment instructions vary by payment type",
    "Beneficiary's preferred language: Spanish",
    "Payment subject to internal audit",
    "Beneficiary's risk profile needs assessment",
    "Payment requires additional documentation",
    "Beneficiary is a politically exposed person (PEP)",
    "Payment subject to enhanced due diligence",
    "Beneficiary's identity needs further verification",
    "Payment instructions are time-sensitive",
    "Beneficiary is a high-net-worth individual",
    "Payment requires special security measures",
    "Beneficiary's account is under investigation",
    "Payment requires legal counsel review",
    "Beneficiary is a vulnerable adult",
    "Payment requires social worker approval",
    "Beneficiary is a minor, guardian information attached",
    "Payment requires probate court authorization",
    "Beneficiary is a charity organization",
    "Payment requires board of directors approval",
    "Beneficiary is a foreign government official",
    "Payment requires anti-corruption screening",
    "Beneficiary is a sanctioned individual",
    "Payment requires OFAC compliance check",
    "Beneficiary is a high-risk customer",
    "Payment requires enhanced monitoring",
    "Beneficiary is a victim of identity theft",
    "Payment requires fraud prevention measures",
    "Beneficiary is a customer with a disability",
    "Payment requires accessibility accommodations",
    "Beneficiary is a customer with limited English proficiency",
    "Payment requires language support services",
    "Beneficiary is a customer with a financial hardship",
    "Payment requires special consideration",
    "Beneficiary is a customer with a history of fraud",
    "Payment requires additional scrutiny",
    "Beneficiary is a customer with a complex financial situation",
    "Payment requires expert advice",
    "Beneficiary is a customer with a high volume of transactions",
    "Payment requires operational efficiency",
    "Beneficiary is a customer with a long-term relationship",
    "Payment requires personalized service",
    "Beneficiary is a customer with a high value to the bank",
    "Payment requires priority handling",
    "Beneficiary is a customer with a sensitive account",
    "Payment requires confidentiality",
    "Beneficiary is a customer with a unique payment need",
    "Payment requires customization",
    "Beneficiary is a customer with a specific payment deadline",
    "Payment requires timeliness",
    "Beneficiary is a customer with a preferred payment method",
    "Payment requires flexibility",
    "Beneficiary is a customer with a history of payment problems",
    "Payment requires caution",
    "Beneficiary is a customer with a need for payment tracking",
    "Payment requires transparency",
    "Beneficiary is a customer with a requirement for payment confirmation",
    "Payment requires reliability",
    "Beneficiary is a customer with a preference for digital payments",
    "Payment requires innovation",
    "Beneficiary is a customer with a need for payment security",
    "Payment requires protection",
    "Beneficiary is a customer with a desire for payment convenience",
    "Payment requires ease of use",
    "Beneficiary is a customer with a preference for personalized payments",
    "Payment requires customization",
    "Beneficiary is a customer with a need for payment reconciliation",
    "Payment requires accuracy",
    "Beneficiary is a customer with a requirement for payment reporting",
    "Payment requires data",
    "Beneficiary is a customer with a preference for automated payments",
    "Payment requires efficiency",
    "Beneficiary is a customer with a need for payment integration",
    "Payment requires connectivity",
    "Beneficiary is a customer with a desire for payment control",
    "Payment requires empowerment",
    "Beneficiary is a customer with a preference for sustainable payments",
    "Payment requires responsibility",
    "Beneficiary is a customer with a need for payment advice",
    "Payment requires guidance",
    "Beneficiary is a customer with a requirement for payment support",
    "Payment requires assistance",
    "Beneficiary is a customer with a preference for transparent payments",
    "Payment requires clarity",
    "Beneficiary is a customer with a need for payment innovation",
    "Payment requires progress",
    "Beneficiary is a customer with a desire for payment excellence",
    "Payment requires quality",
    "Beneficiary is a customer with a preference for secure payments",
    "Payment requires trust",
    "Beneficiary is a customer with a need for payment solutions",
    "Payment requires expertise"
]
