consumer_banking__standing_orders__supplementary_data = [
    "Transfer for rent payment.",
    "Automatic savings deposit.",
    "Recurring bill payment for utilities.",
    "Monthly contribution to investment account.",
    "Regular payment for loan installment.",
    "Automatic transfer to child's account.",
    "Recurring donation to charity.",
    "Payment for subscription service.",
    "Automatic payment for insurance premium.",
    "Regular transfer for property taxes.",
    "Monthly payment for gym membership.",
    "Recurring payment for online service.",
    "Automatic transfer to retirement account.",
    "Regular payment for credit card bill.",
    "Payment for tuition fees.",
    "Automatic transfer to emergency fund.",
    "Recurring payment for home maintenance.",
    "Monthly payment for streaming service.",
    "Regular transfer for travel savings.",
    "Payment for language course.",
    "Automatic payment for pet insurance.",
    "Recurring transfer for holiday gifts.",
    "Monthly payment for music subscription.",
    "Regular payment for sports club membership.",
    "Automatic transfer to education fund.",
    "Recurring payment for home security.",
    "Payment for online gaming subscription.",
    "Automatic transfer to travel fund.",
    "Regular payment for magazine subscription.",
    "Payment for professional membership.",
    "Automatic payment for life insurance.",
    "Recurring transfer for concert tickets.",
    "Monthly payment for book club.",
    "Regular payment for fitness classes.",
    "Automatic transfer to savings goal.",
    "Recurring payment for home cleaning.",
    "Payment for online courses.",
    "Automatic transfer to investment portfolio.",
    "Regular payment for language exchange.",
    "Payment for personal trainer.",
    "Automatic payment for health insurance.",
    "Recurring transfer for birthday gifts.",
    "Monthly payment for wine club.",
    "Regular payment for dance classes.",
    "Automatic transfer to down payment fund.",
    "Recurring payment for pet care.",
    "Payment for online therapy.",
    "Automatic transfer to emergency savings.",
    "Regular payment for sports equipment.",
    "Payment for art classes.",
    "Automatic payment for car insurance.",
    "Recurring transfer for travel expenses.",
    "Monthly payment for food subscription.",
    "Regular payment for yoga classes.",
    "Automatic transfer to retirement plan.",
    "Recurring payment for home repairs.",
    "Payment for online tutoring.",
    "Automatic transfer to investment fund.",
    "Regular payment for sports league.",
    "Payment for music lessons.",
    "Automatic payment for dental insurance.",
    "Recurring transfer for charitable donations.",
    "Monthly payment for coffee subscription.",
    "Regular payment for cooking classes.",
    "Automatic transfer to savings account.",
    "Recurring payment for landscaping.",
    "Payment for online fitness program.",
    "Automatic transfer to investment account.",
    "Regular payment for language learning app.",
    "Payment for financial advisor.",
    "Automatic payment for vision insurance.",
    "Recurring transfer for anniversary gifts.",
    "Monthly payment for beer club.",
    "Regular payment for photography classes.",
    "Automatic transfer to college fund.",
    "Recurring payment for babysitting.",
    "Payment for online coding bootcamp.",
    "Automatic transfer to emergency fund.",
    "Regular payment for sports tickets.",
    "Payment for art supplies.",
    "Automatic payment for renters insurance.",
    "Recurring transfer for vacation rental.",
    "Monthly payment for meal kit service.",
    "Regular payment for dance lessons.",
    "Automatic transfer to savings goal.",
    "Recurring payment for home security system.",
    "Payment for online language classes.",
    "Automatic transfer to investment portfolio.",
    "Regular payment for gym membership.",
    "Payment for personal trainer sessions.",
    "Automatic payment for pet insurance.",
    "Recurring transfer for holiday shopping.",
    "Monthly payment for streaming service.",
    "Regular payment for fitness classes.",
    "Automatic transfer to retirement plan.",
    "Recurring payment for home maintenance.",
    "Payment for online courses.",
    "Automatic transfer to investment fund.",
    "Regular payment for sports league fees.",
    "Payment for music lessons.",
    "Automatic payment for health insurance.",
    "Recurring transfer for charitable giving.",
    "Monthly payment for book club subscription.",
    "Regular payment for dance classes.",
    "Automatic transfer to down payment fund.",
    "Recurring payment for pet care expenses.",
    "Payment for online therapy sessions.",
    "Automatic transfer to emergency savings.",
    "Regular payment for sports equipment.",
    "Payment for art classes and supplies.",
    "Automatic payment for car insurance.",
    "Recurring transfer for travel expenses.",
    "Monthly payment for food subscription box.",
    "Regular payment for yoga classes.",
    "Automatic transfer to retirement plan.",
    "Recurring payment for home repairs and renovations.",
    "Payment for online tutoring services.",
    "Automatic transfer to investment account.",
    "Regular payment for sports league dues.",
    "Payment for music lessons and instruments.",
    "Automatic payment for dental insurance.",
    "Recurring transfer for charitable donations.",
    "Monthly payment for coffee subscription.",
    "Regular payment for cooking classes."
]
