consumer_lending__fairlending_analysis__controls_applied = [
    "Credit score",
    "Income",
    "Debt-to-income ratio",
    "Loan amount",
    "Loan term",
    "Collateral value",
    "Geographic location",
    "Age",
    "Employment history",
    "Credit history",
    "Account balance",
    "Number of accounts",
    "Product type",
    "Channel",
    "Marketing source",
    "Time of application",
    "Day of week",
    "Seasonality",
    "Economic conditions",
    "Interest rates",
    "Regulatory changes",
    "Underwriting score",
    "Pricing tier",
    "Risk grade",
    "Loan purpose",
    "Occupancy type",
    "Property type",
    "Number of units",
    "Down payment",
    "Loan-to-value ratio",
    "Credit utilization",
    "Number of inquiries",
    "Length of credit history",
    "Number of delinquencies",
    "Number of public records",
    "Bankruptcy flag",
    "Foreclosure flag",
    "Loan performance",
    "Default rate",
    "Prepayment rate",
    "Loss severity",
    "Profitability",
    "Customer lifetime value",
    "Customer segmentation",
    "Marketing campaign",
    "Channel effectiveness",
    "Conversion rate",
    "Customer acquisition cost",
    "Customer retention rate",
    "Customer satisfaction",
    "Net Promoter Score",
    "Complaint rate",
    "Regulatory compliance",
    "Fair lending risk",
    "Reputational risk",
    "Operational risk",
    "Credit risk",
    "Market risk",
    "Interest rate risk",
    "Liquidity risk",
    "Counterparty risk",
    "Systemic risk",
    "Country risk",
    "Political risk",
    "Environmental risk",
    "Social risk",
    "Governance risk",
    "Compliance risk",
    "Legal risk",
    "Strategic risk",
    "Financial risk",

    "Credit score, income",
    "Debt-to-income ratio, loan amount",
    "Loan term, collateral value",
    "Geographic location, age",
    "Employment history, credit history",
    "Account balance, number of accounts",
    "Product type, channel",
    "Marketing source, time of application",
    "Day of week, seasonality",
    "Economic conditions, interest rates",
    "Regulatory changes, underwriting score",
    "Pricing tier, risk grade",
    "Loan purpose, occupancy type",
    "Property type, number of units",
    "Down payment, loan-to-value ratio",
    "Credit utilization, number of inquiries",
    "Length of credit history, number of delinquencies",
    "Number of public records, bankruptcy flag",
    "Foreclosure flag, loan performance",
    "Default rate, prepayment rate",
    "Loss severity, profitability",
    "Customer lifetime value, customer segmentation",
    "Marketing campaign, channel effectiveness",
    "Conversion rate, customer acquisition cost",
    "Customer retention rate, customer satisfaction",
    "Net Promoter Score, complaint rate",
    "Regulatory compliance, fair lending risk",
    "Reputational risk, operational risk",
    "Credit risk, market risk",
    "Interest rate risk, liquidity risk",

    "Credit score, debt-to-income ratio, loan amount",
    "Loan term, collateral value, geographic location",
    "Age, employment history, credit history",
    "Account balance, number of accounts, product type",
    "Channel, marketing source, time of application",
    "Day of week, seasonality, economic conditions",
    "Interest rates, regulatory changes, underwriting score",
    "Pricing tier, risk grade, loan purpose",
    "Occupancy type, property type, number of units",
    "Down payment, loan-to-value ratio, credit utilization",
    "Number of inquiries, length of credit history, number of delinquencies",
    "Number of public records, bankruptcy flag, foreclosure flag",

    "Loan performance, default rate, prepayment rate, loss severity",
    "Profitability, customer lifetime value, customer segmentation, marketing campaign",
    "Channel effectiveness, conversion rate, customer acquisition cost, customer retention rate",
    "Customer satisfaction, Net Promoter Score, complaint rate, regulatory compliance",
    "Fair lending risk, reputational risk, operational risk, credit risk",
    "Market risk, interest rate risk, liquidity risk, counterparty risk",
    "Systemic risk, country risk, political risk, environmental risk",
    "Social risk, governance risk, compliance risk, legal risk",
    "Credit score, income, debt-to-income ratio, loan amount",
    "Loan term, collateral value, geographic location, age",
    "Employment history, credit history, account balance, number of accounts",
    "Product type, channel, marketing source, time of application",
    "Day of week, seasonality, economic conditions, interest rates",
    "Regulatory changes, underwriting score, pricing tier, risk grade",
    "Loan purpose, occupancy type, property type, number of units",
    "Down payment, loan-to-value ratio, credit utilization, number of inquiries"
]
