enterprise__departments__department_name = [
    "Executive Leadership",
    "Board of Directors",
    "CEO Office",
    "CFO Office",
    "COO Office",
    "CIO Office",
    "CTO Office",
    "CMO Office",
    "Chief Strategy Officer (CSO) Office",
    "Chief Risk Officer (CRO) Office",
    "Chief Compliance Officer (CCO) Office",
    "Chief Human Resources Officer (CHRO) Office",
    "Legal Department",
    "Compliance Department",
    "Risk Management",
    "Operational Risk Management",
    "Credit Risk Management",
    "Market Risk Management",
    "Regulatory Compliance",
    "Financial Crimes Compliance",
    "Internal Audit",
    "Human Resources",
    "Talent Acquisition",
    "Recruitment Marketing",
    "Employer Branding",
    "Employee Relations",
    "Labor Relations",
    "Training and Development",
    "Leadership Development",
    "Organizational Development",
    "Compensation and Benefits",
    "Payroll",
    "Benefits Administration",
    "Retirement Planning",
    "Facilities Management",
    "Corporate Security",
    "Information Technology",
    "Software Development",
    "Application Development",
    "Web Development",
    "Mobile Development",
    "Network Operations",
    "Infrastructure Management",
    "Cloud Computing",
    "Cybersecurity",
    "Threat Intelligence",
    "Vulnerability Management",
    "Incident Response",
    "Data Management",
    "Database Administration",
    "Data Warehousing",
    "Data Analytics",
    "Business Intelligence",
    "Data Visualization",
    "Marketing",
    "Digital Marketing",
    "Search Engine Optimization (SEO)",
    "Search Engine Marketing (SEM)",
    "Social Media Marketing",
    "Email Marketing",
    "Content Marketing",
    "Brand Management",
    "Advertising",
    "Public Relations",
    "Media Relations",
    "Corporate Communications",
    "Customer Service",
    "Call Center Operations",
    "Customer Support",
    "Customer Success",
    "Customer Relationship Management (CRM)",
    "Customer Experience",
    "Voice of the Customer (VoC)",
    "Sales",
    "Retail Banking",
    "Branch Banking",
    "Commercial Banking",
    "Corporate Banking",
    "Investment Banking",
    "Wealth Management",
    "Private Banking",
    "Financial Planning",
    "Retirement Planning",
    "Estate Planning",
    "Mortgage Lending",
    "Residential Mortgage Lending",
    "Commercial Mortgage Lending",
    "Consumer Lending",
    "Auto Lending",
    "Personal Lending",
    "Student Lending",
    "Credit Card Services",
    "Credit Risk Assessment",
    "Fraud Prevention",
    "Treasury Management",
    "Cash Management",
    "Foreign Exchange",
    "International Banking",
    "Trade Finance",
    "Mergers and Acquisitions",
    "Corporate Development",
    "Actuarial Services",
    "Economic Research",
    "Portfolio Management",
    "Investment Research",
    "Equity Research",
    "Fixed Income Research",
    "Securities Processing",
    "Clearing and Settlement",
    "Loan Origination",
    "Loan Servicing",
    "Collections",
    "Debt Recovery",
    "Anti-Money Laundering (AML)",
    "Know Your Customer (KYC)",
    "Regulatory Reporting",
    "Securities and Exchange Commission (SEC) Reporting",
    "Federal Reserve Reporting",
    "Vendor Management",
    "Procurement",
    "Sourcing",
    "Contract Management",
    "Real Estate",
    "Property Management",
    "Branch Operations",
    "ATM Operations",
    "Online Banking",
    "Mobile Banking",
    "Payment Processing",
    "Card Processing",
    "ACH Processing",
    "Wire Transfers",
    "Financial Reporting",
    "Management Reporting",
    "Accounting",
    "Accounts Payable",
    "Accounts Receivable",
    "General Ledger",
    "Tax Department",
    "Corporate Tax",
    "Indirect Tax",
    "Budgeting and Forecasting",
    "Financial Planning and Analysis (FP&A)",
    "Strategic Planning",
    "Project Management Office (PMO)",
    "Innovation",
    "Product Development",
    "Product Management",
    "Data Science",
    "Artificial Intelligence (AI)",
    "Machine Learning (ML)",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "User Experience (UX)",
    "User Interface (UI)",
    "Content Management",
    "Social Media Management",
    "Analytics",
    "Web Analytics",
    "Marketing Analytics",
    "Sales Analytics",
    "Risk Analytics",
    "Business Analysis",
    "Process Improvement",
    "Lean Management",
    "Six Sigma",
    "Quality Assurance",
    "Research and Development",
    "Investor Relations",
    "Government Relations",
    "Community Relations",
    "Sustainability",
    "Corporate Social Responsibility",
    "Diversity and Inclusion",
    "Records Management",
    "Mail Services",
    "Travel Services",
    "Physical Security",
    "Information Security",
    "Disaster Recovery",
    "Business Continuity",
    "Training Operations",
    "eLearning Development",
    "Knowledge Management",
    "Retail Operations",
    "Branch Security",
    "Financial Crimes Unit",
    "Digital Transformation",
    "Change Management",
    "Customer Insights",
    "Competitive Intelligence",
    "Pricing Strategy",
    "Promotional Planning",
    "Event Management",
    "Internal Communications",
    "Employee Communications",
    "Reputation Management",
    "Crisis Communications",
    "Public Affairs",
    "Corporate Giving",
    "Philanthropy",
    "Volunteer Programs",
    "Environmental Sustainability",
    "Social Impact",
    "Ethics and Compliance",
    "Data Governance",
    "Privacy",
    "Legal Operations",
    "Contract Administration",
    "Intellectual Property",
    "Litigation",
    "Regulatory Affairs",
    "Audit Committee",
    "Compensation Committee",
    "Nominating and Governance Committee"
]
