enterprise__associates__job_title = [
    "Teller",
    "Senior Teller",
    "Head Teller",
    "Personal Banker",
    "Senior Personal Banker",
    "Lead Personal Banker",
    "Financial Services Representative",
    "Senior Financial Services Representative",
    "Branch Manager",
    "Assistant Branch Manager",
    "Retail Banking Manager",
    "Commercial Loan Officer",
    "Senior Commercial Loan Officer",
    "Commercial Lending Manager",
    "Mortgage Loan Officer",
    "Senior Mortgage Loan Officer",
    "Mortgage Lending Manager",
    "Consumer Loan Officer",
    "Senior Consumer Loan Officer",
    "Consumer Lending Manager",
    "Credit Analyst",
    "Senior Credit Analyst",
    "Credit Manager",
    "Underwriter",
    "Senior Underwriter",
    "Underwriting Manager",
    "Collections Specialist",
    "Senior Collections Specialist",
    "Collections Manager",
    "Fraud Analyst",
    "Senior Fraud Analyst",
    "Fraud Manager",
    "Compliance Analyst",
    "Senior Compliance Analyst",
    "Compliance Manager",
    "Risk Analyst",
    "Senior Risk Analyst",
    "Risk Manager",
    "Auditor",
    "Senior Auditor",
    "Audit Manager",
    "Operations Specialist",
    "Senior Operations Specialist",
    "Operations Manager",
    "Accountant",
    "Senior Accountant",
    "Accounting Manager",
    "Financial Analyst",
    "Senior Financial Analyst",
    "Financial Planning Manager",
    "Investment Advisor",
    "Senior Investment Advisor",
    "Investment Manager",
    "Portfolio Manager",
    "Senior Portfolio Manager",
    "Trust Officer",
    "Senior Trust Officer",
    "Trust Manager",
    "Wealth Management Advisor",
    "Senior Wealth Management Advisor",
    "Wealth Management Manager",
    "Relationship Manager",
    "Senior Relationship Manager",
    "Relationship Management Manager",
    "Private Banker",
    "Senior Private Banker",
    "Private Banking Manager",
    "Customer Service Representative",
    "Senior Customer Service Representative",
    "Customer Service Manager",
    "Call Center Representative",
    "Senior Call Center Representative",
    "Call Center Manager",
    "ATM Technician",
    "Senior ATM Technician",
    "ATM Operations Manager",
    "Online Banking Specialist",
    "Senior Online Banking Specialist",
    "Online Banking Manager",
    "Mobile Banking Specialist",
    "Senior Mobile Banking Specialist",
    "Mobile Banking Manager",
    "Payment Processing Specialist",
    "Senior Payment Processing Specialist",
    "Payment Processing Manager",
    "Card Services Representative",
    "Senior Card Services Representative",
    "Card Services Manager",
    "ACH Specialist",
    "Senior ACH Specialist",
    "ACH Manager",
    "Wire Transfer Specialist",
    "Senior Wire Transfer Specialist",
    "Wire Transfer Manager",
    "Financial Reporting Analyst",
    "Senior Financial Reporting Analyst",
    "Financial Reporting Manager",
    "Tax Analyst",
    "Senior Tax Analyst",
    "Tax Manager",
    "Budget Analyst",
    "Senior Budget Analyst",
    "Budget Manager",
    "Forecasting Analyst",
    "Senior Forecasting Analyst",
    "Forecasting Manager",
    "Strategic Planning Analyst",
    "Senior Strategic Planning Analyst",
    "Strategic Planning Manager",
    "Project Manager",
    "Senior Project Manager",
    "Program Manager",
    "Business Analyst",
    "Senior Business Analyst",
    "Business Analysis Manager",
    "Data Analyst",
    "Senior Data Analyst",
    "Data Manager",
    "Data Scientist",
    "Senior Data Scientist",
    "Data Science Manager",
    "Software Developer",
    "Senior Software Developer",
    "Development Manager",
    "Network Administrator",
    "Senior Network Administrator",
    "Network Manager",
    "Cybersecurity Analyst",
    "Senior Cybersecurity Analyst",
    "Cybersecurity Manager",
    "IT Support Specialist",
    "Senior IT Support Specialist",
    "IT Support Manager",
    "Marketing Specialist",
    "Senior Marketing Specialist",
    "Marketing Manager",
    "Digital Marketing Specialist",
    "Senior Digital Marketing Specialist",
    "Digital Marketing Manager",
    "SEO Specialist",
    "Senior SEO Specialist",
    "SEO Manager",
    "SEM Specialist",
    "Senior SEM Specialist",
    "SEM Manager",
    "Social Media Specialist",
    "Senior Social Media Specialist",
    "Social Media Manager",
    "Content Writer",
    "Senior Content Writer",
    "Content Manager",
    "Brand Manager",
    "Senior Brand Manager",
    "Public Relations Specialist",
    "Senior Public Relations Specialist",
    "Public Relations Manager",
    "Human Resources Generalist",
    "Senior Human Resources Generalist",
    "Human Resources Manager",
    "Recruiter",
    "Senior Recruiter",
    "Recruiting Manager",
    "Training Specialist",
    "Senior Training Specialist",
    "Training Manager",
    "Compensation Analyst",
    "Senior Compensation Analyst",
    "Compensation Manager",
    "Benefits Administrator",
    "Senior Benefits Administrator",
    "Benefits Manager",
    "Payroll Specialist",
    "Senior Payroll Specialist",
    "Payroll Manager",
    "Facilities Manager",
    "Senior Facilities Manager",
    "Security Officer",
    "Senior Security Officer",
    "Security Manager",
    "Procurement Specialist",
    "Senior Procurement Specialist",
    "Procurement Manager",
    "Vendor Manager",
    "Senior Vendor Manager",
    "Real Estate Specialist",
    "Senior Real Estate Specialist",
    "Real Estate Manager",
    "Compliance Officer",
    "AML Analyst",
    "KYC Analyst",
    "Financial Crimes Investigator",
    "Business Continuity Planner",
    "Disaster Recovery Specialist",
    "UX Designer",
    "UI Designer",
    "Data Governance Analyst",
    "Privacy Officer",
    "Legal Counsel",
    "Contract Administrator",
    "Internal Communications Specialist",
    "External Communications Specialist",
    "Community Relations Specialist",
    "Sustainability Analyst",
    "Corporate Social Responsibility Specialist",
    "Diversity and Inclusion Specialist",
    "Records Management Specialist"
]
