mortgage_services__hmda_application_demographics__sex_observed = [
    "Not applicable",
    "Visually observed",
    "Not provided",
    "Observed",
    "Not observed",
    "Unavailable",
    "Undetermined",
    "Information not available",
    "Based on visual cues",
    "Assumed based on appearance",
    "Determined through interaction",
    "Not explicitly stated",
    "Gathered from context",
    "Implied but not confirmed",
    "Unclear from documentation",
    "Based on limited information",
    "Visual assessment",
    "Not self-reported",
    "Observed characteristics",
    "Assumed sex",
    "Limited visibility",
    "Partial information",
    "Not fully disclosed",
    "Observation-based",
    "Contextual clues",
    "Implied sex",
    "Documentation ambiguity",
    "Information scarcity",
    "Visual cues only",
    "Appearance implies",
    "Interaction suggests",
    "Not explicitly provided",
    "Contextual determination",
    "Implied but unverified",
    "Documentation limitations",
    "Partial observation",
    "Limited disclosure",
    "Visual estimation",
    "Behavioral cues",
    "Indirect assessment",
    "Non-self-reported",
    "Observed traits",
    "Visibility constraints",
    "Information gaps",
    "Disclosure limitations",
    "Observation-driven",
    "Contextual hints",
    "Documentation uncertainty",
    "Data insufficiency",
    "Visual evidence",
    "Appearance suggests",
    "Interaction implies",
    "Not directly stated",
    "Contextual interpretation",
    "Implied but not certain",
    "Documentation constraints",
    "Incomplete observation",
    "Restricted disclosure",
    "Visual approximation",
    "Limited observability",
    "Information deficit",
    "Disclosure restrictions",
    "Observation-oriented",
    "Contextual suggestions",
    "Documentation ambiguity",
    "Data limitations",
    "Visual perception",
    "Indirect evidence",
    "Non-self-declared",
    "Observed attributes",
    "Limited exposure",
    "Information constraints",
    "Disclosure constraints",
    "Observation-focused",
    "Contextual inferences",
    "Documentation inconsistency",
    "Data scarcity",
    "Visual appraisal",
    "Indirect observation",
    "Non-self-professed",
    "Observed qualities",
    "Limited access",
    "Information restrictions",
    "Disclosure limitations"
]
