mortgage_services__hmda_application_demographics__sex = [
    "Male",
    "Female",
    "Not applicable",
    "Do not wish to provide",
    "Information not available",
    "Decline to answer",
    "Prefer not to say",
    "Not disclosed",
    "Unavailable",
    "Unknown",
    "Undetermined",
    "Not collected",
    "Not reported",
    "Not specified",
    "Not indicated",
    "No information",
    "Data missing",
    "Not applicable",
    "Blank",
    "Null",
    "Empty",
    "Not answered",
    "No response",
    "Withheld",
    "Redacted",
    "Confidential",
    "Suppressed",
    "Restricted",
    "Protected",
    "Private"
]
