mortgage_services__closing__appointments_notes = [
    "Borrower requested clarification on escrow.",
    "Closing delayed due to title issue.",
    "Signed documents returned electronically.",
    "Agent confirmed all parties present.",
    "Borrower inquired about PMI cancellation.",
    "Notary public verified all signatures.",
    "Funds wired successfully to title company.",
    "Property insurance proof received.",
    "Final walkthrough completed and approved.",
    "Borrowers asked about property tax payments.",
    "Closing rescheduled due to lender error.",
    "Agent noted minor discrepancy in address.",
    "Borrower provided updated bank statement.",
    "Closing agent requested additional funds.",
    "Seller requested early release of funds.",
    "Borrower asked about loan amortization schedule.",
    "Final loan documents reviewed and signed.",
    "Agent confirmed receipt of all required docs.",
    "Borrower requested copies of signed forms.",
    "Closing delayed due to weather conditions.",
    "Agent noted minor repairs needed on property.",
    "Borrower clarified source of down payment.",
    "Funds transfer confirmed by title company.",
    "Borrower inquired about homestead exemption.",
    "Closing agent requested updated contact info.",
    "Borrower provided proof of homeowners insurance.",
    "Agent confirmed all utilities are transferred.",
    "Borrower asked about early payment options.",
    "Closing delayed waiting for seller's attorney.",
    "Agent noted minor issue with survey report.",
    "Borrower requested clarification on APR.",
    "Funds confirmed received by escrow account.",
    "Borrower asked about property tax assessment.",
    "Closing agent requested additional ID proof.",
    "Borrower provided gift letter for down payment.",
    "Agent confirmed all keys handed over.",
    "Borrower inquired about mortgage servicer.",
    "Closing delayed due to missing document.",
    "Agent noted minor damage to property exterior.",
    "Borrower requested extension for rate lock.",
    "Funds confirmation pending from lender.",
    "Borrower asked about tax deductibility of interest.",
    "Closing agent requested updated contact details.",
    "Borrower provided proof of earnest money deposit.",
    "Agent confirmed all appliances are working.",
    "Borrower inquired about flood insurance.",
    "Closing delayed due to power outage.",
    "Agent noted minor issue with title commitment.",
    "Borrower requested clarification on closing costs.",
    "Funds transfer initiated by lender.",
    "Borrower asked about property tax due dates.",
    "Closing agent requested additional signature.",
    "Borrower provided proof of income verification.",
    "Agent confirmed all smoke detectors are installed.",
    "Borrower inquired about home warranty.",
    "Closing delayed due to notary availability.",
    "Agent noted minor discrepancy in legal description.",
    "Borrower requested clarification on loan terms.",
    "Funds confirmation received from lender.",
    "Borrower asked about escrow account management.",
    "Closing agent requested updated address.",
    "Borrower provided proof of asset verification.",
    "Agent confirmed all garage door openers work.",
    "Borrower inquired about hazard insurance.",
    "Closing delayed due to system outage.",
    "Agent noted minor issue with appraisal report.",
    "Borrower requested clarification on interest rate.",
    "Funds transfer completed to seller's account.",
    "Borrower asked about property tax exemptions.",
    "Closing agent requested additional information.",
    "Borrower provided proof of debt payoff.",
    "Agent confirmed all window locks are functional.",
    "Borrower inquired about mortgage insurance.",
    "Closing delayed waiting for lender approval.",
    "Agent noted minor issue with property survey.",
    "Borrower requested clarification on payment schedule.",
    "Funds confirmed received by seller's bank.",
    "Borrower asked about property tax appeals.",
    "Closing agent requested updated phone number.",
    "Borrower provided proof of employment verification.",
    "Agent confirmed all light fixtures are working.",
    "Borrower inquired about title insurance.",
    "Closing delayed due to document error.",
    "Agent noted minor issue with home inspection.",
    "Borrower requested clarification on closing fees.",
    "Funds transfer pending from escrow.",
    "Borrower asked about property tax credits.",
    "Closing agent requested additional documentation.",
    "Borrower provided proof of identity.",
    "Agent confirmed all water faucets are working.",
    "Borrower inquired about homeowners association.",
    "Closing delayed due to scheduling conflict.",
    "Agent noted minor discrepancy in loan amount.",
    "Borrower requested clarification on escrow payments.",
    "Funds transfer completed by title company.",
    "Borrower asked about property tax rates.",
    "Closing agent requested updated email address.",
    "Borrower provided proof of residency.",
    "Agent confirmed all HVAC systems are working.",
    "Borrower inquired about flood zone.",
    "Closing delayed due to lender review.",
    "Agent noted minor issue with final walkthrough.",
    "Borrower requested clarification on loan origination.",
    "Funds confirmation received by borrower.",
    "Borrower asked about property tax payment history.",
    "Closing agent requested additional proof of funds.",
    "Borrower provided proof of marital status.",
    "Agent confirmed all security systems are working.",
    "Borrower inquired about private mortgage insurance.",
    "Closing delayed due to missing signature.",
    "Agent noted minor discrepancy in property address.",
    "Borrower requested clarification on loan servicing.",
    "Funds transfer pending from title company.",
    "Borrower asked about property tax assessments.",
    "Closing agent requested updated proof of insurance.",
    "Borrower provided proof of dependent verification.",
    "Agent confirmed all appliances are included in sale.",
    "Borrower inquired about home warranty options.",
    "Closing delayed due to loan documentation.",
    "Agent noted minor issue with property title.",
    "Borrower requested clarification on loan payoff.",
    "Funds transfer completed to borrower's account.",
    "Borrower asked about property tax payment options.",
    "Closing agent requested additional proof of identity.",
    "Borrower provided proof of previous address.",
    "Agent confirmed all smoke alarms are working.",
    "Borrower inquired about lender requirements.",
    "Closing delayed due to legal review.",
    "Agent noted minor issue with loan documents.",
    "Borrower requested clarification on loan closing.",
    "Funds confirmation received from title company.",
    "Borrower asked about property tax exemptions and credits.",
    "Closing agent requested updated contact information.",
    "Borrower provided proof of financial documentation.",
    "Agent confirmed all keys and garage door openers were provided.",
    "Borrower inquired about mortgage insurance cancellation.",
    "Closing delayed due to final document review.",
    "Agent noted minor discrepancy in closing disclosure.",
    "Borrower requested clarification on interest rate calculation.",
    "Funds transfer pending final approval.",
    "Borrower asked about property tax payment frequency.",
    "Closing agent requested additional borrower information.",
    "Borrower provided proof of required documentation.",
    "Agent confirmed all required repairs were completed.",
    "Borrower inquired about escrow account setup.",
    "Closing delayed due to final lender approval.",
    "Agent noted minor issue with the appraisal.",
    "Borrower requested clarification on loan terms and conditions.",
    "Funds transfer completed successfully.",
    "Borrower asked about property tax payment methods.",
    "Closing agent requested updated borrower contact details.",
    "Borrower provided proof of required financial documents.",
    "Agent confirmed all utilities were transferred to the borrower.",
    "Borrower inquired about homeowners insurance policy details."
]
