mortgage_services__conditions__description = [
    "Provide updated pay stubs.",
    "Verify employment.",
    "Explain credit inquiry.",
    "Provide bank statements.",
    "Update tax returns.",
    "Clarify source of funds.",
    "Resolve credit report discrepancy.",
    "Provide gift letter.",
    "Verify property ownership.",
    "Obtain homeowner's insurance.",
    "Complete appraisal.",
    "Clear title defects.",
    "Provide flood insurance.",
    "Confirm employment status.",
    "Explain large deposit.",
    "Provide proof of residency.",
    "Verify down payment source.",
    "Obtain mortgage insurance.",
    "Provide debt verification.",
    "Confirm child support payments.",
    "Explain credit history gap.",
    "Provide rental agreement.",
    "Verify self-employment income.",
    "Obtain updated credit report.",
    "Confirm bankruptcy discharge.",
    "Provide divorce decree.",
    "Verify alimony payments.",
    "Obtain property tax statement.",
    "Confirm HOA dues payment.",
    "Provide evidence of assets.",
    "Explain credit card balance.",
    "Provide updated pay stubs.",
    "Verify employment history.",
    "Explain recent credit inquiry.",
    "Provide current bank statements.",
    "Update tax returns for latest year.",
    "Clarify source of down payment funds.",
    "Resolve discrepancy on credit report.",
    "Provide gift letter for down payment.",
    "Verify ownership of current property.",
    "Obtain homeowner's insurance policy.",
    "Complete appraisal of subject property.",
    "Clear any title defects on property.",
    "Provide flood insurance if required.",
    "Confirm current employment status.",
    "Explain large deposit in bank account.",
    "Provide proof of current residency.",
    "Verify source of down payment funds.",
    "Obtain private mortgage insurance.",
    "Provide verification of outstanding debts.",
    "Confirm child support payment history.",
    "Explain gap in credit history.",
    "Provide current rental agreement.",
    "Verify self-employment income documentation.",
    "Obtain updated credit report from bureau.",
    "Confirm bankruptcy discharge date.",
    "Provide copy of divorce decree.",
    "Verify alimony payment history.",
    "Obtain current property tax statement.",
    "Confirm HOA dues payment status.",
    "Provide evidence of assets and liabilities.",
    "Explain high credit card balance.",
    "Provide updated pay stubs for recent months.",
    "Verify employment history and income stability.",
    "Explain recent credit inquiry from creditor.",
    "Provide bank statements for all accounts.",
    "Update tax returns with latest filing.",
    "Clarify source of funds for down payment.",
    "Resolve any discrepancies on credit report.",
    "Provide gift letter explaining down payment assistance.",
    "Verify ownership of current property with deed.",
    "Obtain homeowner's insurance policy for full coverage.",
    "Complete appraisal of subject property by certified appraiser.",
    "Clear any title defects affecting property ownership.",
    "Provide flood insurance if located in flood zone.",
    "Confirm current employment status and income details.",
    "Explain large deposit in bank account with supporting documentation.",
    "Provide proof of current residency with utility bills.",
    "Verify source of down payment funds with bank statements.",
    "Obtain private mortgage insurance if required by LTV.",
    "Provide verification of outstanding debts and liabilities.",
    "Confirm child support payment history with court documents.",
    "Explain gap in credit history with reasonable justification.",
    "Provide current rental agreement with landlord contact.",
    "Verify self-employment income with tax returns and profit/loss statements.",
    "Obtain updated credit report showing current credit standing.",
    "Confirm bankruptcy discharge date with court documentation.",
    "Provide copy of divorce decree outlining financial obligations.",
    "Verify alimony payment history with bank records.",
    "Obtain current property tax statement from local government.",
    "Confirm HOA dues payment status with HOA management.",
    "Provide evidence of assets and liabilities to demonstrate financial stability.",
    "Explain high credit card balance with plan for repayment.",
    "Provide updated pay stubs demonstrating consistent income.",
    "Verify employment history with previous employers.",
    "Explain recent credit inquiry as legitimate and authorized.",
    "Provide bank statements showing sufficient reserves.",
    "Update tax returns to include all relevant income sources.",
    "Clarify source of funds for down payment with detailed explanation.",
    "Resolve any discrepancies on credit report with supporting evidence.",
    "Provide gift letter outlining terms of down payment assistance.",
    "Verify ownership of current property with clear title documentation.",
    "Obtain homeowner's insurance policy meeting coverage requirements.",
    "Complete appraisal of subject property by licensed appraiser.",
    "Clear any title defects to ensure marketable title.",
    "Provide flood insurance if property is in designated flood zone.",
    "Confirm current employment status and income with employer verification.",
    "Explain large deposit in bank account with clear and verifiable source.",
    "Provide proof of current residency with acceptable documentation.",
    "Verify source of down payment funds with complete bank statements.",
    "Obtain private mortgage insurance to mitigate risk for high LTV loans.",
    "Provide verification of outstanding debts and liabilities with account statements.",
    "Confirm child support payment history with official payment records.",
    "Explain gap in credit history with verifiable reasons.",
    "Provide current rental agreement with landlord signature and contact information.",
    "Verify self-employment income with comprehensive financial documentation.",
    "Obtain updated credit report reflecting current creditworthiness.",
    "Confirm bankruptcy discharge date with official court records.",
    "Provide copy of divorce decree outlining financial responsibilities.",
    "Verify alimony payment history with documented payment records.",
    "Obtain current property tax statement from relevant taxing authority.",
    "Confirm HOA dues payment status with HOA contact and records.",
    "Provide evidence of assets and liabilities to support financial capacity.",
    "Explain high credit card balance with reasonable justification and repayment plan."
]
