mortgage_services__hmda_edits__edit_description = [
    "Missing loan type.",
    "Invalid loan purpose.",
    "Incorrect action taken date.",
    "Missing race information.",
    "Invalid ethnicity code.",
    "Incorrect sex selection.",
    "Missing income data.",
    "Invalid credit score.",
    "Missing property value.",
    "Incorrect loan amount.",
    "Missing lien status.",
    "Invalid HOEPA status.",
    "Incorrect state code.",
    "Missing county code.",
    "Invalid census tract.",
    "Missing applicant age.",
    "Incorrect reporting year.",
    "Missing preapproval code.",
    "Invalid construction method.",
    "Missing occupancy type.",
    "Incorrect rate spread.",
    "Missing denial reason.",
    "Invalid AUS code.",
    "Missing total loan costs.",
    "Incorrect points and fees.",
    "Missing origination charges.",
    "Invalid discount points.",
    "Missing lender credits.",
    "Incorrect loan term.",
    "Missing intro rate period.",
    "Invalid balloon payment.",
    "Missing interest-only payment.",
    "Incorrect negative amortization.",
    "Missing manufactured home type.",
    "Invalid land ownership code.",
    "Missing total units.",
    "Incorrect multifamily units.",
    "Missing submission of application.",
    "Invalid initially payable status.",
    "Missing reverse mortgage code.",
    "Incorrect open-end line of credit.",
    "Missing business purpose code.",
    "Invalid submission status.",
    "Missing last submission date.",
    "Incorrect edit status.",
    "Missing applicant demographics.",
    "Invalid ethnicity selection.",
    "Incorrect race selection.",
    "Missing sex information.",
    "Invalid age.",
    "Incorrect income.",
    "Missing debt-to-income ratio.",
    "Invalid credit score model.",
    "Missing denial reason details.",
    "Incorrect total points and fees.",
    "Missing origination charges.",
    "Invalid discount points amount.",
    "Missing lender credits information.",
    "Incorrect loan term details.",
    "Missing introductory rate period.",
    "Invalid balloon payment status.",
    "Missing interest-only payment indicator.",
    "Incorrect negative amortization status.",
    "Missing manufactured home property type.",
    "Invalid land property interest code.",
    "Missing total units in property.",
    "Incorrect multifamily affordable units count.",
    "Missing submission of application method.",
    "Invalid initially payable to institution.",
    "Missing reverse mortgage indicator.",
    "Incorrect open-end line of credit status.",
    "Missing business or commercial purpose.",
    "Invalid HMDA submission status.",
    "Missing last submission date.",
    "Incorrect edit status discrepancy.",
    "Missing applicant demographic information.",
    "Invalid ethnicity details.",
    "Incorrect race selection.",
    "Missing sex information.",
    "Invalid age.",
    "Incorrect income.",
    "Missing debt-to-income ratio.",
    "Invalid credit score model.",
    "Missing denial reason details.",
    "Incorrect total points and fees.",
    "Missing origination charges.",
    "Invalid discount points amount.",
    "Missing lender credits information.",
    "Incorrect loan term details.",
    "Missing introductory rate period.",
    "Invalid balloon payment status.",
    "Missing interest-only payment indicator.",
    "Incorrect negative amortization status.",
    "Missing manufactured home property type.",
    "Invalid land property interest code.",
    "Missing total units in property.",
    "Incorrect multifamily affordable units count.",
    "Missing submission of application method.",
    "Invalid initially payable to institution.",
    "Missing reverse mortgage indicator.",
    "Incorrect open-end line of credit status.",
    "Missing business or commercial purpose.",
    "Invalid HMDA submission status.",
    "Missing last submission date.",
    "Incorrect edit status discrepancy.",
    "Missing applicant demographic information.",
    "Invalid ethnicity details.",
    "Incorrect race selection.",
    "Missing sex information.",
    "Invalid age.",
    "Incorrect income.",
    "Missing debt-to-income ratio.",
    "Invalid credit score model.",
    "Missing denial reason details.",
    "Incorrect total points and fees.",
    "Missing origination charges.",
    "Invalid discount points amount.",
    "Missing lender credits information.",
    "Incorrect loan term details.",
    "Missing introductory rate period.",
    "Invalid balloon payment status.",
    "Missing interest-only payment indicator.",
    "Incorrect negative amortization status.",
    "Missing manufactured home property type.",
    "Invalid land property interest code.",
    "Missing total units in property.",
    "Incorrect multifamily affordable units count.",
    "Missing submission of application method.",
    "Invalid initially payable to institution.",
    "Missing reverse mortgage indicator.",
    "Incorrect open-end line of credit status.",
    "Missing business or commercial purpose.",
    "Invalid HMDA submission status.",
    "Missing last submission date.",
    "Incorrect edit status discrepancy."
]
