security__apps__name = [
  "Online Banking Portal",
  "Mobile Banking App",
  "Fraud Detection System",
  "Customer Relationship Management (CRM)",
  "Loan Origination System",
  "Mortgage Processing System",
  "Credit Card Processing System",
  "Investment Management System",
  "Wealth Management Platform",
  "Financial Planning Tool",
  "Core Banking System",
  "General Ledger System",
  "Accounts Payable System",
  "Accounts Receivable System",
  "Human Resources Management System (HRMS)",
  "Payroll System",
  "Employee Self-Service Portal",
  "Time and Attendance System",
  "Learning Management System (LMS)",
  "Compliance Management System",
  "Risk Management System",
  "Anti-Money Laundering (AML) System",
  "Know Your Customer (KYC) System",
  "Cybersecurity Monitoring System",
  "Intrusion Detection System (IDS)",
  "Intrusion Prevention System (IPS)",
  "Security Information and Event Management (SIEM)",
  "Vulnerability Management System",
  "Patch Management System",
  "Identity and Access Management (IAM)",
  "Single Sign-On (SSO)",
  "Multi-Factor Authentication (MFA)",
  "Data Loss Prevention (DLP)",
  "Encryption Management System",
  "Cloud Security Platform",
  "Data Warehouse",
  "Business Intelligence (BI) Dashboard",
  "Reporting System",
  "Customer Data Platform (CDP)",
  "Marketing Automation Platform",
  "Email Marketing System",
  "Social Media Management Tool",
  "Content Management System (CMS)",
  "Website Analytics Platform",
  "Search Engine Optimization (SEO) Tool",
  "Customer Support Ticketing System",
  "Live Chat Platform",
  "Call Center Management System",
  "Knowledge Base System",
  "Project Management Software",
  "Collaboration Platform",
  "Document Management System",
  "Contract Management System",
  "Legal Case Management System",
  "Audit Management System",
  "Vendor Management System",
  "Supply Chain Management System",
  "Facilities Management System",
  "Energy Management System",
  "Environmental Management System",
  "Health and Safety Management System",
  "Business Continuity Planning System",
  "Disaster Recovery System",
  "Incident Response System",
  "Change Management System",
  "Configuration Management System",
  "IT Service Management (ITSM) System",
  "Help Desk System",
  "Network Management System",
  "Server Management System",
  "Database Management System (DBMS)",
  "Application Performance Monitoring (APM) Tool",
  "Testing Automation Tool",
  "Release Management System",
  "Source Code Management System",
  "Continuous Integration/Continuous Delivery (CI/CD) Pipeline",
  "Artificial Intelligence (AI) Platform",
  "Machine Learning (ML) Platform",
  "Robotic Process Automation (RPA) Tool",
  "Chatbot Platform",
  "Voice Assistant Integration",
  "API Management Platform",
  "Data Integration Platform",
  "Enterprise Service Bus (ESB)",
  "Message Queue System",
  "Event Streaming Platform",
  "Blockchain Platform",
  "Internet of Things (IoT) Platform",
  "Augmented Reality (AR) Application",
  "Virtual Reality (VR) Application",
  "3D Modeling Software",
  "Computer-Aided Design (CAD) Software",
  "Geographic Information System (GIS)",
  "Remote Desktop Application",
  "Virtual Private Network (VPN)",
  "File Transfer Protocol (FTP) Client",
  "Secure File Transfer Protocol (SFTP) Client",
  "Payment Gateway",
  "Payment Processing Platform",
  "Point of Sale (POS) System",
  "Customer Loyalty Program Management",
  "Digital Signature Application",
  "Expense Reporting System",
  "Travel Booking System",
  "Budgeting and Forecasting Software",
  "Tax Preparation Software",
  "Financial Reporting Tool",
  "SharePoint Collaboration",
  "Team Communication Platform",
  "Video Conferencing Application",
  "Instant Messaging Platform",
  "Social Collaboration Tool",
  "Performance Appraisal System",
  "Succession Planning Tool",
  "Applicant Tracking System (ATS)",
  "Employee Training Portal",
  "Safety Incident Reporting System",
  "Regulatory Reporting System",
  "Data Governance Tool",
  "Data Quality Management Platform",
  "Data Catalog Software",
  "Data Lineage Application",
  "Master Data Management (MDM) System",
  "API Testing Tool",
  "Code Review Tool",
  "Container Orchestration Platform",
  "Cloud Cost Management Tool",
  "Cloud Migration Tool",
  "Threat Intelligence Platform",
  "Endpoint Detection and Response (EDR)",
  "Web Application Security Scanner",
  "Mobile Application Security Testing (MAST)",
  "Security Awareness Training Platform",
  "Digital Asset Management (DAM)",
  "Campaign Analytics Dashboard",
  "Marketing Resource Management (MRM)",
  "Customer Journey Mapping Tool",
  "Voice of the Customer (VoC) Platform",
  "Customer Feedback System",
  "Service Level Agreement (SLA) Management",
  "Field Service Management System",
  "Inventory Tracking Application",
  "Warehouse Management System (WMS)",
  "Transport Management System (TMS)",
  "Asset Tracking System",
  "Building Management System (BMS)",
  "Sustainability Reporting Tool",
  "Environmental Monitoring System",
  "Occupational Health System",
  "Crisis Management Platform",
  "Knowledge Graph Platform",
  "Natural Language Processing (NLP) Engine",
  "Image Recognition Software",
  "Predictive Maintenance System",
  "Digital Twin Platform",
  "Robotic Process Monitoring",
  "Process Mining Tool",
  "Test Data Management",
  "API Documentation Tool",
  "Microservices Management Platform",
  "Serverless Computing Platform",
  "Edge Computing Platform",
  "Digital Forensics Tool",
  "Security Orchestration, Automation, and Response (SOAR)",
  "Hardware Asset Management",
  "Software Asset Management",
  "IT Asset Discovery Tool",
  "Data Classification Tool",
  "Data Encryption Key Management",
  "Data Minimization Tool",
  "Data Retention Policy Management",
  "Data Subject Access Request (DSAR) Tool",
  "Privacy Impact Assessment (PIA) Tool",
  "Compliance Training Platform",
  "Regulatory Change Management",
  "Internal Audit Tool",
  "External Audit Portal",
  "Legal Document Automation",
  "E-Discovery Platform",
  "Third-Party Risk Management",
  "Supplier Relationship Management (SRM)",
  "Procurement Analytics Tool",
  "Contract Lifecycle Management (CLM)",
  "Financial Consolidation Software",
  "Treasury Risk Management",
  "Portfolio Management System",
  "Actuarial Software",
  "Insurance Claims Processing",
  "Policy Administration System"
]
