small_business_banking__loans__purpose = [
  "Working capital for daily operations.",
  "Expansion of business premises.",
  "Purchase of new equipment.",
  "Inventory acquisition for peak season.",
  "Debt consolidation to reduce interest.",
  "Refinancing existing business debt.",
  "Startup funding for new venture.",
  "Marketing and advertising campaign.",
  "Renovation of retail space.",
  "Hiring new staff and training.",
  "Technology upgrade for efficiency.",
  "Acquisition of another business.",
  "Funding for research and development.",
  "Bridge loan for short-term needs.",
  "Seasonal cash flow management.",
  "Emergency funding for unexpected costs.",
  "Purchase of commercial vehicle.",
  "Investment in new software.",
  "Funding for export activities.",
  "Expansion into new markets.",
  "Real estate purchase for business.",
  "Leasehold improvements.",
  "Funding for franchise purchase.",
  "Working capital for growth.",
  "Equipment repair and maintenance.",
  "Payroll funding during slow periods.",
  "Funding for product development.",
  "Purchase of raw materials.",
  "Expansion of online presence.",
  "Funding for trade show participation.",
  "Acquisition of intellectual property.",
  "Funding for legal expenses.",
  "Business restructuring costs.",
  "Funding for sustainability initiatives.",
  "Purchase of land for development.",
  "Funding for employee benefits.",
  "Expansion of production capacity.",
  "Funding for training programs.",
  "Acquisition of existing inventory.",
  "Funding for business relocation.",
  "Purchase of office furniture.",
  "Funding for sales team expansion.",
  "Investment in cybersecurity.",
  "Funding for international expansion.",
  "Purchase of specialized machinery.",
  "Funding for community projects.",
  "Expansion of service offerings.",
  "Funding for business certification.",
  "Purchase of delivery vehicles.",
  "Funding for quality control systems.",
  "Expansion of warehouse space.",
  "Funding for environmental compliance.",
  "Purchase of heavy machinery.",
  "Funding for disaster recovery planning.",
  "Expansion of research facilities.",
  "Funding for educational programs.",
  "Purchase of specialized tools.",
  "Funding for business incubation.",
  "Expansion of customer support.",
  "Funding for industry events.",
  "Purchase of safety equipment.",
  "Funding for employee wellness programs.",
  "Expansion of data storage capacity.",
  "Funding for renewable energy projects.",
  "Purchase of laboratory equipment.",
  "Funding for arts and culture initiatives.",
  "Expansion of distribution network.",
  "Funding for agricultural development.",
  "Purchase of medical equipment.",
  "Funding for social impact projects.",
  "Expansion of training facilities.",
  "Funding for infrastructure development.",
  "Purchase of construction equipment.",
  "Funding for tourism initiatives.",
  "Expansion of retail locations.",
  "Funding for technology transfer.",
  "Purchase of telecommunications equipment.",
  "Funding for urban development.",
  "Expansion of manufacturing facilities.",
  "Funding for rural development.",
  "Purchase of scientific instruments.",
  "Funding for maritime activities.",
  "Expansion of transportation services.",
  "Funding for aerospace projects.",
  "Purchase of energy efficient equipment.",
  "Funding for mining operations.",
  "Expansion of logistics network.",
  "Funding for forestry initiatives.",
  "Purchase of advanced robotics.",
  "Funding for fisheries development.",
  "Expansion of healthcare facilities.",
  "Funding for water resource management.",
  "Purchase of precision tools.",
  "Funding for waste management projects.",
  "Expansion of educational resources.",
  "Funding for sustainable agriculture.",
  "Purchase of digital printing equipment.",
  "Funding for environmental remediation.",
  "Expansion of renewable energy infrastructure.",
  "Funding for conservation projects.",
  "Purchase of high-performance computing.",
  "Funding for cultural preservation.",
  "Expansion of public transportation.",
  "Funding for historical preservation.",
  "Purchase of automated assembly lines.",
  "Funding for community development.",
  "Expansion of telecommunications infrastructure.",
  "Funding for emergency services.",
  "Purchase of advanced diagnostic tools.",
  "Funding for scientific research.",
  "Expansion of broadband internet access.",
  "Funding for technological innovation.",
  "Purchase of specialized software licenses.",
  "Funding for educational technology.",
  "Expansion of smart city infrastructure.",
  "Funding for artificial intelligence research.",
  "Purchase of 3D printing equipment.",
  "Funding for augmented reality development.",
  "Expansion of virtual reality applications.",
  "Funding for blockchain technology initiatives.",
  "Purchase of quantum computing hardware.",
  "Funding for space exploration projects.",
  "Expansion of nanotechnology research.",
  "Funding for genetic engineering research.",
  "Purchase of biotechnology equipment.",
  "Funding for pharmaceutical development.",
  "Expansion of medical research facilities.",
  "Funding for public health initiatives.",
  "Purchase of medical imaging equipment.",
  "Funding for mental health services.",
  "Expansion of elder care facilities.",
  "Funding for pediatric healthcare.",
  "Purchase of prosthetic devices.",
  "Funding for medical device development.",
  "Expansion of rehabilitation services.",
  "Funding for palliative care.",
  "Purchase of assistive technology.",
  "Funding for telemedicine initiatives.",
  "Expansion of health education programs.",
  "Funding for preventative medicine.",
  "Purchase of medical transport vehicles.",
  "Funding for medical waste disposal.",
  "Expansion of pharmaceutical manufacturing.",
  "Funding for medical supply distribution.",
  "Purchase of medical sterilization equipment.",
  "Funding for medical research ethics.",
  "Expansion of medical informatics.",
  "Funding for medical simulation training.",
  "Purchase of medical robotics.",
  "Funding for medical tourism initiatives.",
  "Expansion of medical transcription services.",
  "Funding for medical billing and coding.",
  "Purchase of medical records management systems.",
  "Funding for medical translation services.",
  "Expansion of medical staffing agencies.",
  "Funding for medical equipment leasing.",
  "Purchase of medical insurance software.",
  "Funding for medical malpractice insurance.",
  "Expansion of medical data analytics.",
  "Funding for medical supply chain management.",
  "Purchase of medical waste recycling equipment.",
  "Funding for medical emergency preparedness.",
  "Expansion of medical disaster relief.",
  "Funding for medical volunteer programs.",
  "Purchase of medical training simulators.",
  "Funding for medical student scholarships.",
  "Expansion of medical research funding.",
  "Funding for medical technology patents.",
  "Purchase of medical device prototypes.",
  "Funding for medical clinical trials.",
  "Expansion of medical regulatory compliance.",
  "Funding for medical device marketing.",
  "Purchase of medical device packaging equipment."
]
