small_business_banking__business_due_diligence__site_visit_notes = [
  "Business premises verified at stated address with visible signage and active operations. Retail location approximately 2,500 sq. ft. with inventory consistent with business type.",
  "Office located on 3rd floor of professional building with company name on directory and door. 5 employees present during visit with appropriate equipment for stated business.",
  "Manufacturing facility operating at full capacity with 15 workers present. Equipment and inventory levels consistent with reported production volume and business description.",
  "Restaurant location verified with seating for approximately 75 customers. Kitchen and food preparation areas observed with appropriate health department certificates posted.",
  "Retail store operating in strip mall with prominent signage. Customer traffic moderate with 3 employees working. Inventory levels consistent with expected business volume.",
  "Medical office confirmed at stated location with professional signage. Waiting room with 4 patients observed, reception staff and medical professionals present during visit.",
  "Warehouse facility approximately 15,000 sq. ft. with company signage. Observed shipping/receiving operations with inventory levels consistent with wholesale distribution business.",
  "Construction company office verified with company vehicles displaying logo parked outside. Equipment storage yard adjacent to office with machinery consistent with business type.",
  "Professional services firm located in downtown office building. Reception area staffed with company logo displayed. Conference room and individual offices observed during tour.",
  "Auto repair shop operating with 4 service bays, all occupied with vehicles under repair. Parts inventory and equipment consistent with stated business activities.",
  "Salon and spa verified at location with appropriate signage. 6 treatment rooms observed with specialized equipment. 4 staff members present serving clients during visit.",
  "Technology company occupying entire 4th floor of office building. Approximately 30 employees observed working at computer workstations consistent with software development activities.",
  "Convenience store operating at stated location with branded signage. Store approximately 1,800 sq. ft. with inventory and customer traffic consistent with business type.",
  "Manufacturing operation in industrial park with correct signage. Production line active with finished goods and raw materials inventory consistent with reported business activity.",
  "Law firm occupying suite in professional building with firm name displayed. Multiple attorneys and support staff observed with law library and client meeting rooms as described.",
  "Automotive dealership verified with showroom, service center, and vehicle inventory consistent with franchise brand and reported business volume.",
  "Dental practice in medical office complex with professional signage. Reception area, 4 treatment rooms, and specialized dental equipment observed during tour.",
  "Wholesale distribution facility with loading docks active during visit. Warehouse inventory levels consistent with reported business volume and product mix.",
  "Restaurant under renovation as disclosed in application. Construction activity observed consistent with stated business plans and timeline for opening.",
  "Retail clothing store verified in shopping mall location with branded signage. Inventory levels and store size approximately 3,200 sq. ft. consistent with business model.",
  "Engineering firm occupying suite in office park with company name displayed. Drafting stations, specialized software, and 12 employees observed during visit.",
  "Landscaping business with office, equipment storage yard, and company vehicles all displaying consistent branding. Inventory of plants and materials observed on premises.",
  "Healthcare facility operating with appropriate medical equipment and staff. Patient flow observed consistent with described business model and specialty.",
  "Manufacturing plant with production line operational during visit. Raw materials and finished goods inventory consistent with reported production capacity.",
  "Accounting firm located in professional office building with firm name on directory and suite entrance. Staff observed working at approximately 8 workstations.",
  "Auto parts store verified at location with appropriate signage and branding. Inventory levels and store layout consistent with franchise standards and business model.",
  "Construction contractor operating from combined office/warehouse facility. Equipment and materials storage observed with vehicles displaying company logo.",
  "Veterinary clinic with professional signage at stated location. Waiting area with clients, examination rooms, and specialized equipment observed during tour.",
  "Grocery store operating in standalone building with pharmacy department as described. Store size and inventory consistent with reported business volume.",
  "Insurance agency located in street-level office with company signage. Three agents observed with appropriate licensing certificates displayed as required by state regulations.",
  "Manufacturing operation with assembly line and 25 workers present. Inventory levels of raw materials and finished products consistent with reported production volume.",
  "Restaurant with approximately 50 seats operating at location with proper signage. Kitchen facilities observed with appropriate health certificates displayed.",
  "Retail store in strip mall operating with visible inventory and 2 employees serving customers during visit. Square footage approximately 1,800 sq. ft. as reported.",
  "Law office in downtown building with firm name on directory and suite door. Conference room and individual offices consistent with size of practice described.",
  "Medical practice with waiting room, examination rooms, and medical equipment consistent with specialty. Staff observed including physician and support personnel.",
  "Distribution warehouse approximately 25,000 sq. ft. with loading docks active during visit. Inventory levels consistent with wholesale business volume reported.",
  "Technology company occupying suite in office building with 15 employees observed at workstations. Server room and development environment consistent with business description.",
  "Construction company with office, equipment yard, and storage facilities at reported location. Heavy equipment with company logo observed on premises.",
  "Professional services firm in office building with company name on directory. Approximately 10 staff members observed in open workspace configuration.",
  "Automotive service center with 6 repair bays, customer waiting area, and parts department consistent with franchise standards and business description.",
  "Manufacturing facility producing goods consistent with business description. Production equipment and employee count align with reported business volume.",
  "Dental office with 5 treatment rooms equipped with specialized dental equipment. Patient flow observed consistent with reported business capacity.",
  "Convenience store with attached gas station operating at reported location. Store inventory and fuel pumps consistent with franchise brand and standards.",
  "Architectural firm occupying suite in office building with company name displayed. Design workstations, conference room, and approximately 8 staff members observed.",
  "Restaurant with dining room seating approximately 100 customers operating at stated location. Kitchen facilities and staff level consistent with reported capacity.",
  "Retail store in downtown location with street-level entrance and appropriate signage. Inventory levels and store size consistent with business description.",
  "Accounting office located in professional building with firm name displayed. Conference room and individual offices observed during tour with 6 staff present.",
  "Manufacturing operation with automated production line observed. Raw materials inventory and finished goods storage consistent with reported production levels.",
  "Physical therapy clinic with treatment areas and specialized rehabilitation equipment. Staff including licensed therapists observed working with patients.",
  "Distribution facility with warehouse storage, inventory management system, and loading area active during visit. Square footage approximately 18,000 sq. ft. as reported.",
  "Technology startup in shared office space with dedicated suite displaying company name. Development team of 8 observed working on products consistent with business description.",
  "Construction company office with plans room, estimating department, and company vehicles with logo observed in parking area consistent with business description.",
  "Legal office in multi-tenant building with firm name on suite entrance. Conference room and attorney offices observed with legal reference materials present.",
  "Auto dealership with showroom, vehicle inventory, and service department operating as described. Staff levels and facility size consistent with franchise standards.",
  "Manufacturing plant producing goods aligned with business description. Employee count approximately 40 with production output consistent with reported capacity.",
  "Medical office in professional building complex with appropriate signage. Waiting area, examination rooms, and medical equipment consistent with specialty practice.",
  "Wholesale business with showroom and warehouse facilities at reported location. Inventory levels consistent with described business model and industry.",
  "Engineering firm occupying office space with company name displayed. Specialized software, plotting equipment, and professional staff observed during visit.",
  "Restaurant with bar area operating at reported location with health department certification posted. Kitchen facilities and dining capacity consistent with business plan.",
  "Retail store in mall location with appropriate signage and branding. Store size approximately 2,500 sq. ft. with inventory levels consistent with business type.",
  "Dental practice with reception area and treatment rooms at reported location. Specialized equipment and licensed professionals observed during visit.",
  "Distribution warehouse with inventory management system, shipping/receiving area, and product storage consistent with wholesale business description.",
  "Technology company occupying office space with appropriate signage. Development environment and employee workstations consistent with software business model.",
  "Professional services firm in office building with company identification displayed. Conference facilities and individual offices consistent with business description.",
  "Construction company headquarters with administrative offices and equipment storage yard. Vehicles and machinery with company identification observed on premises.",
  "Manufacturing facility producing goods consistent with business description. Raw materials, production equipment, and finished inventory observed during tour.",
  "Medical practice specializing in reported field with appropriate equipment and licensed professionals. Patient flow consistent with described business volume.",
  "Retail establishment with inventory and store layout consistent with business description. Customer traffic and staffing levels appropriate for reported sales volume.",
  "Accounting firm in professional building with appropriate signage. Office configuration and staff count consistent with described business operations.",
  "Automotive service center with repair bays, parts department, and customer service area consistent with reported business model and brand standards.",
  "Law firm occupying suite with firm name displayed on building directory and entrance. Conference facilities and attorney offices configured as described.",
  "Distribution operation with warehouse storage, inventory control system, and shipping department active during visit consistent with business description.",
  "Technology company with development team workstations, server infrastructure, and collaboration spaces consistent with software development business.",
  "Restaurant operation with dining area, kitchen facilities, and staff levels consistent with reported capacity and business concept.",
  "Retail store operating at reported location with signage and merchandise display consistent with business description and reported sales volume.",
  "Healthcare facility with waiting area, examination rooms, and medical equipment appropriate for specialty. Licensed professionals observed during visit.",
  "Manufacturing operation with production line, quality control department, and inventory storage consistent with reported business activities.",
  "Professional services firm in office setting with appropriate business identification. Workspace configuration and staff count aligned with business description.",
  "Construction company with administrative offices and equipment storage area. Vehicle fleet with company identification consistent with business scale.",
  "Dental practice with reception area, treatment rooms, and specialized equipment consistent with reported business operations.",
  "Wholesale distribution facility with inventory storage, order fulfillment area, and shipping department operating as described in business profile.",
  "Technology firm with workspace configuration supporting reported business activities. Equipment and personnel appropriate for described operations.",
  "Automotive dealership with showroom, inventory lot, and service department operating consistent with franchise standards and reported volume.",
  "Legal practice in professional building with appropriate signage. Office configuration and staff composition consistent with reported firm size and specialty.",
  "Medical office with appropriate licensing displayed and specialized equipment for reported specialty. Patient volume consistent with described practice.",
  "Retail operation with store layout, inventory levels, and staffing consistent with reported business model and sales volume.",
  "Manufacturing facility producing products aligned with business description. Production capacity and employee count consistent with reported volume.",
  "Accounting office with professional configuration and appropriate licensing displayed. Staff count and workspace aligned with reported business size.",
  "Distribution operation with warehouse facilities, inventory management, and logistics capabilities consistent with wholesale business description.",
  "Technology company occupying office space with development environment supporting reported business activities. Staff composition appropriate for business model.",
  "Restaurant with dining capacity, kitchen facilities, and staffing levels consistent with reported business volume and concept.",
  "Professional services firm in office setting with appropriate business identification and workspace configuration supporting described activities.",
  "Construction business with administrative offices and equipment yard. Vehicle fleet and machinery inventory consistent with reported project capacity.",
  "Healthcare practice with waiting area, treatment rooms, and medical equipment appropriate for specialty. Staff composition includes licensed professionals.",
  "Retail establishment with store layout, merchandise display, and inventory levels consistent with reported business type and sales volume.",
  "Manufacturing operation with production facilities, equipment, and staffing levels consistent with reported manufacturing capacity and product line.",
  "Law firm in professional setting with appropriate identification and office configuration. Attorney and support staff count aligned with described practice.",
  "Automotive service operation with repair facilities, parts inventory, and customer service area consistent with reported business model.",
  "Distribution warehouse with inventory storage, order processing, and shipping capabilities consistent with wholesale business description.",
  "Technology startup with workspace configuration supporting software development activities. Equipment and team composition appropriate for business model.",
  "Medical practice with facility layout, equipment, and staff composition appropriate for specialty. Patient flow consistent with reported business volume.",
  "Retail operation with store configuration, inventory levels, and staffing appropriate for reported business type and sales volume.",
  "Professional services firm in office setting with workspace configuration supporting reported business activities. Staff composition aligned with service model.",
  "Construction company with administrative facilities and equipment resources consistent with reported project capacity and business description.",
  "Manufacturing facility with production capabilities aligned with reported business activities. Raw material and finished goods inventory consistent with volume.",
  "Dental practice with reception area, treatment rooms, and specialized equipment consistent with reported business operations and patient volume.",
  "Wholesale operation with showroom, inventory storage, and order fulfillment capabilities consistent with reported business model.",
  "Technology company with development environment, collaboration spaces, and team configuration supporting reported business activities.",
  "Restaurant with dining facilities, kitchen operations, and staff composition consistent with reported business concept and customer capacity.",
  "Accounting firm with office configuration and professional staff aligned with reported business size and service offerings.",
  "Automotive dealership with sales facilities, vehicle inventory, and service department consistent with franchise standards and reported volume.",
  "Distribution operation with warehouse facilities and logistics capabilities aligned with reported business model and volume expectations.",
  "Healthcare facility with appropriate medical equipment, licensed professionals, and patient capacity consistent with specialty practice description.",
  "Retail store with merchandise presentation, inventory levels, and staffing consistent with reported business type and sales projections.",
  "Legal practice with office configuration and professional staff composition appropriate for reported firm size and specialty areas.",
  "Manufacturing operation with production line, quality control measures, and inventory management consistent with reported business activities.",
  "Professional services firm with workspace configuration and team composition supporting specialized business operations as described.",
  "Construction business with administrative support, equipment resources, and project management capabilities aligned with reported business scale.",
  "Technology firm with development infrastructure, team organization, and workspace configuration supporting reported business focus.",
  "Medical practice with facility design, specialized equipment, and professional staff appropriate for reported specialty and patient volume.",
  "Wholesale distribution operation with inventory management, order processing, and fulfillment capabilities consistent with business description.",
  "Automotive service center with repair facilities, technical capabilities, and customer service functions aligned with reported business model.",
  "Restaurant operation with dining capacity, food preparation facilities, and service staff consistent with reported business concept.",
  "Retail establishment with store layout, product assortment, and customer service approach aligned with reported business positioning.",
  "Manufacturing facility with production capabilities, quality systems, and workforce aligned with reported business output and product line.",
  "Professional services firm with office environment, team composition, and client service capabilities consistent with reported business model.",
  "Distribution operation with logistics infrastructure, inventory management, and order fulfillment consistent with wholesale business description.",
  "Healthcare practice with medical facilities, equipment resources, and professional staffing appropriate for specialty and patient volume.",
  "Technology company with workspace configuration, development resources, and team organization supporting reported business activities.",
  "Construction company with project management capabilities, equipment resources, and administrative support consistent with business scale.",
  "Retail operation with merchandising approach, inventory management, and customer service aligned with reported business concept.",
  "Legal practice with office facilities, professional staff, and client service capabilities appropriate for reported firm specialization.",
  "Automotive business with facilities, technical capabilities, and customer service functions consistent with reported business model.",
  "Manufacturing operation with production infrastructure, workforce, and output capabilities aligned with reported business activities.",
  "Professional services firm with workspace design, team composition, and service delivery capabilities consistent with business description.",
  "Medical practice with healthcare facilities, equipment resources, and professional staff appropriate for reported specialty focus.",
  "Distribution business with warehouse infrastructure, inventory systems, and logistics capabilities aligned with wholesale operation description.",
  "Technology firm with development environment, team organization, and workspace configuration supporting reported business activities.",
  "Restaurant with food service facilities, kitchen capabilities, and customer capacity consistent with reported business concept.",
  "Construction business with project support, equipment resources, and administrative capabilities aligned with reported operation scale.",
  "Retail establishment with store design, product presentation, and customer service approach consistent with reported business positioning.",
  "Manufacturing facility with production capabilities, workforce, and output capacity aligned with reported business activities and industry.",
  "Professional services operation with office environment, team composition, and client service approach consistent with business description.",
  "Healthcare practice with medical facilities, specialized equipment, and professional staffing appropriate for reported specialty focus.",
  "Automotive operation with service facilities, technical capabilities, and customer support functions aligned with reported business model.",
  "Distribution business with warehouse infrastructure, inventory management, and fulfillment capabilities consistent with wholesale description.",
  "Technology company with workspace configuration, development resources, and team organization supporting reported business focus.",
  "Legal practice with office facilities, professional staff composition, and client service capabilities aligned with reported specialization.",
  "Retail operation with store layout, merchandise assortment, and customer service approach consistent with reported business concept.",
  "Construction company with project management resources, equipment assets, and administrative support aligned with business scale.",
  "Manufacturing operation with production infrastructure, quality systems, and workforce appropriate for reported business activities.",
  "Professional services firm with workspace design, team organization, and service delivery capabilities consistent with business description.",
  "Medical practice with healthcare facilities, patient capacity, and professional staffing aligned with reported specialty and business scale.",
  "Distribution operation with logistics infrastructure, inventory systems, and order fulfillment capabilities consistent with wholesale model.",
  "Technology firm with development environment, team composition, and workspace configuration supporting reported business activities.",
  "Restaurant operation with dining facilities, food preparation capabilities, and service staff consistent with reported business concept.",
  "Automotive business with service facilities, technical capabilities, and customer support functions aligned with reported operation model.",
  "Retail establishment with store design, product assortment, and customer service approach consistent with reported business positioning.",
  "Manufacturing facility with production capabilities, workforce resources, and output capacity aligned with reported business activities.",
  "Professional services operation with office environment, team organization, and client service approach consistent with business description.",
  "Healthcare practice with medical facilities, specialized equipment, and licensed professionals appropriate for reported specialty focus.",
  "Distribution business with warehouse infrastructure, inventory management, and logistics capabilities aligned with wholesale description.",
  "Technology company with workspace configuration, development resources, and team composition supporting reported business activities.",
  "Construction operation with project support, equipment assets, and administrative capabilities consistent with reported business scale.",
  "Legal practice with office facilities, professional staff, and client service capabilities aligned with reported firm specialization.",
  "Retail operation with merchandising approach, inventory management, and customer service consistent with reported business concept.",
  "Manufacturing business with production infrastructure, quality systems, and workforce appropriate for reported business activities.",
  "Professional services firm with workspace design, team organization, and service delivery capabilities aligned with business description."
]
