small_business_banking__suspicious_activity_reports__supporting_documentation = [
  "Transaction history report showing structured cash deposits across multiple branch locations with aggregate amounts and timestamps.",
  "Wire transfer documentation showing multiple international transfers to high-risk jurisdictions with inconsistent beneficiary information.",
  "Account statements showing rapid movement of funds with minimal business-related transactions during 90-day monitoring period.",
  "Customer due diligence records revealing discrepancies in stated business purpose compared to observed transaction activity.",
  "Branch surveillance footage showing multiple individuals making deposits to same business account on single day.",
  "Check images showing altered payee information and suspicious endorsements on multiple deposited items.",
  "Currency transaction reports filed for related cash transactions showing potential structuring patterns over two-week period.",
  "Account opening documentation with potentially falsified business registration information and verification discrepancies.",
  "Site visit reports documenting minimal business activity at registered address inconsistent with transaction volumes.",
  "Internal communication logs documenting customer's evasive responses to routine due diligence questions.",
  "Transaction monitoring system alerts showing pattern of high-risk activities triggered over six-month period.",
  "Law enforcement information request regarding business account holder's potential connection to ongoing investigation.",
  "Credit report showing multiple business entities with same ownership structure involved in similar suspicious activities.",
  "Loan documentation revealing contradictory business information compared to account opening records.",
  "IP access logs showing account accessed primarily from foreign jurisdictions inconsistent with stated business location.",
  "Corporate structure documentation revealing connection to previously filed SARs on related business entities.",
  "Customer correspondence containing contradictory explanations for unusual transaction patterns when questioned.",
  "Currency strap markings and bundling methods on cash deposits consistent with street-level narcotics proceeds.",
  "Beneficial ownership certification showing potentially nominee owners with no apparent connection to business operations.",
  "International trade documentation showing significant discrepancies between stated goods value and market prices.",
  "Corporate resolution containing unauthorized signatures compared to verified signature cards on file.",
  "Customer identification documentation with security feature inconsistencies suggesting potential counterfeit ID.",
  "Wire transfer details showing structured amounts sent to same beneficiary through multiple originators.",
  "Branch employee observations regarding unusual customer behavior and inconsistent transaction explanations.",
  "Business tax returns showing revenue significantly inconsistent with deposit activity in account.",
  "News articles and public information linking business principals to financial crimes or regulatory violations.",
  "Check stock verification results indicating counterfeit items deposited to business account.",
  "Electronic funds transfer records showing circular movement of funds between related entities without business purpose.",
  "Customer risk assessment history showing escalation to high-risk rating based on accumulated suspicious activities.",
  "Transaction pattern analysis comparing activity to industry benchmarks showing significant deviations.",
  "Secretary of State business registration records showing recently created entity with minimal capital.",
  "Site visit photographs documenting apparent shell office location with no visible business operations.",
  "Account statements from multiple financial institutions showing potential layering of transactions.",
  "Cash shipment records documenting unusually large currency deposits from business typically generating electronic payments.",
  "Vendor verification results indicating several payees appear to be shell entities with no confirmed operations.",
  "Enhanced due diligence report documenting potential connections to politically exposed persons not previously disclosed.",
  "Prior SAR filings on related customers showing similar transaction patterns and suspected activities.",
  "Business website analysis revealing inconsistencies with stated business model and transaction activities.",
  "Remote deposit capture data showing deposits originated from locations inconsistent with business operations.",
  "Foreign bank account documentation not disclosed during account opening or subsequent reviews.",
  "Social media research revealing business activities inconsistent with those stated to financial institution.",
  "Signature analysis indicating same individual signing for multiple apparently unrelated businesses.",
  "Loan proceed utilization documentation showing funds used for purposes inconsistent with stated business needs.",
  "Transaction data showing unusual after-hours banking patterns inconsistent with normal business operations.",
  "Customer correspondence requesting unusual account structure or transaction handling without business justification.",
  "Vendor verification showing multiple payments to entities later identified in negative news for fraud schemes.",
  "ATM surveillance photos showing same individual conducting transactions for multiple business accounts.",
  "Government watch list matching information for business principal or related party requiring further investigation.",
  "Bank secrecy act filing history showing pattern of structured transactions across multiple accounts.",
  "Customer contact records documenting resistance to providing standard business documentation when requested.",
  "Email communications containing potentially fraudulent investment solicitations sent from business account.",
  "Analysis of transaction timing showing suspicious coordination of deposits and withdrawals across accounts.",
  "Third-party information indicating business may be operating in regulated industry without required licensing.",
  "Currency transaction report exemption requests containing potentially false business information to avoid filing requirements.",
  "Business insurance documentation showing coverage inconsistent with transaction activity and stated operations.",
  "High-risk merchant category code history showing changes to potentially mask actual business activities.",
  "Credit card processing statements showing excessive chargeback rates suggesting potential fraudulent activity.",
  "Customer complaint information regarding potentially fraudulent business practices or investment solicitations.",
  "Background check results revealing criminal history of business principal not disclosed during onboarding.",
  "Trade finance documentation containing discrepancies in shipping information and invoice amounts.",
  "Internal fraud alerts regarding similar business accounts involved in confirmed fraudulent schemes.",
  "Cash intensive business exemption analysis showing activity inconsistent with approved exemption parameters.",
  "Customer email communications containing references to high-risk or sanctioned jurisdictions not previously disclosed.",
  "Transaction details showing payments to online gambling entities despite prohibition in account agreement.",
  "Certified business financial statements showing significant discrepancies compared to observed account activity.",
  "Wire transfer documentation containing incomplete or inconsistent beneficiary information across multiple transactions.",
  "Account opening documentation from foreign affiliate showing potentially contradictory business information.",
  "Unusual document requests such as requesting correspondence be held at branch or special handling instructions.",
  "Payment processor information showing business processing transactions for third parties without proper registration.",
  "Customer demographic data showing shared addresses or contact information across apparently unrelated businesses.",
  "Electronic banking access records showing login locations inconsistent with business physical location.",
  "Federal or state regulator information requests regarding business activities or principals.",
  "Transaction pattern analysis showing unusual spikes in activity corresponding with known fraud threat patterns.",
  "Business marketing materials collected during site visit inconsistent with stated account purpose.",
  "Returned mail history indicating business not actually operating at provided address.",
  "Information sharing between financial institutions regarding suspicious activity involving same customers.",
  "Cash deposit analysis showing distinctive bundling or packaging methods consistent with illicit source.",
  "Customer authentication failure records showing multiple unsuccessful login attempts from foreign locations.",
  "Employee relationship information revealing undisclosed connections between business and bank personnel.",
  "Banking center visitor logs showing unusual meeting patterns or unidentified individuals accessing account.",
  "Telephone call recordings documenting inconsistent explanations for business activities or transactions.",
  "Analysis of check sequences showing unusual patterns or potential parallel endorsement schemes.",
  "Comparison of transaction activity before and after regulatory inquiries showing behavioral changes.",
  "Physical currency examination notes indicating potential counterfeit detection at time of deposit.",
  "Customer-to-customer transfer patterns showing potential funnel account or money mule characteristics.",
  "Online banking bill payment records showing payments to entities associated with high-risk activities.",
  "Source of funds documentation containing inadequate explanation for substantial account activity.",
  "Debit card transaction analysis showing usage in locations inconsistent with business operations.",
  "Branch employee affidavits regarding unusual customer behavior or transaction requests.",
  "Property records search revealing undisclosed real estate holdings inconsistent with stated business size.",
  "Analysis of check memo fields showing potentially coded language or unusual notations.",
  "Mobile deposit data showing same items deposited multiple times across different accounts.",
  "Customer correspondence requesting transaction structuring to avoid reporting or documentation requirements.",
  "Wire transfer recall requests or disputes indicating potential business email compromise activity.",
  "International correspondent bank information regarding suspicious transaction patterns through intermediaries.",
  "Comparison of stated employee count with payroll transaction volume showing significant discrepancies.",
  "Documentary evidence of business activities in jurisdictions not disclosed during account opening.",
  "Cashier's check purchase records showing structured buying behavior across multiple branches.",
  "Change in transaction patterns immediately following account review or enhanced due diligence inquiry.",
  "Review of authorized signer additions showing potentially unrelated individuals gaining account access.",
  "Currency denomination analysis showing predominance of $20 bills consistent with illicit cash sources.",
  "Customer explanation letters containing contradictory information about business operations.",
  "Analysis showing transaction patterns designed to evade automated monitoring system thresholds.",
  "Account statement analysis showing minimal operational expenses inconsistent with business type.",
  "Safe deposit box access records showing visits coordinated with large cash deposits.",
  "Vendor validation failures for entities receiving substantial payments from business account.",
  "Sequential bill serial numbers identified during cash deposit processing suggesting unusual source.",
  "Review of check signatures showing inconsistencies or potential forgery compared to signature card.",
  "Treasury management service configuration requests designed to obscure transaction audit trail.",
  "Transaction detail showing payments to virtual asset service providers not disclosed in business profile.",
  "Business principal travel records inconsistent with transaction locations and timing patterns.",
  "Information from other financial institutions regarding closed accounts due to suspicious activity.",
  "External database results showing business address associated with multiple unrelated entities.",
  "Comparison of stated inventory levels with financial activity showing unexplained discrepancies.",
  "Analysis of transaction description fields showing potential code words or structured language patterns.",
  "Cash delivery service records showing unusual delivery patterns or denominations requested.",
  "Transaction amounts analysis showing predominance of just-below-threshold transactions across accounts.",
  "Customer identification document analysis showing potential alterations or inconsistencies.",
  "Comparison of business tax identification usage across multiple apparently unrelated entities.",
  "Transaction review showing payments to entities identified in fraud bulletins or criminal investigations.",
  "Analysis of ATM deposit packaging showing distinctive counting or bundling methods.",
  "Secured credit card collateral funds traced to potentially suspicious sources.",
  "Digital wallet transaction data showing unusual virtual currency exchange patterns.",
  "Analysis of transaction timing showing coordinated activity just outside business operating hours.",
  "Money order serial number analysis showing sequential purchases across different locations.",
  "Electronic funds transfer memo fields containing unusual coding or potential instructions.",
  "Branch cash order history showing unusual denomination requests associated with account.",
  "Safe deposit box contents inventory following abandonment revealing suspicious documents.",
  "Business customer referral chain analysis showing connections to previously filed SARs.",
  "External database search results linking business to adverse media regarding financial crimes.",
  "Transaction analysis showing potential layering through multiple accounts before final destination.",
  "Remote deposit capture image analysis showing potential alterations or invalid items.",
  "Cash transaction patterns showing coordination between business and personal accounts.",
  "Account profile change history showing frequent modifications to mask transaction patterns.",
  "Comparison of stated sales tax payments with reported business revenue showing discrepancies.",
  "Analysis of international wire beneficiary addresses showing high-risk jurisdiction patterns.",
  "Customer identification document inconsistencies between multiple accounts or relationships.",
  "Night deposit activity patterns suggesting intentional avoidance of teller interaction.",
  "ACH batch processing records showing potential commingling of funds across businesses.",
  "Transaction pattern analysis showing coordination with external events linked to fraud schemes.",
  "Secured loan collateral verification showing potentially overvalued or nonexistent assets.",
  "Business location lease documentation inconsistent with stated size or type of operations.",
  "Analysis of mobile check deposit endorsements showing inconsistencies or alterations.",
  "Login credential sharing patterns suggesting unauthorized access to business accounts.",
  "Third-party check endorsement patterns suggesting potential check kiting or fraud scheme.",
  "Branch surveillance showing same individuals conducting transactions for multiple businesses.",
  "Account balance maintained just below threshold that would trigger enhanced monitoring.",
  "Document examination results showing potentially altered or fraudulent business records.",
  "Transaction data showing suspected nominees conducting activity on behalf of undisclosed parties.",
  "Business website domain registration information inconsistent with stated business age.",
  "Customer due diligence responses containing verifiable falsehoods about business operations.",
  "Analysis showing potential structuring of wire transfers to avoid internal review thresholds.",
  "Account statements showing minimal point-of-sale activity despite retail business model.",
  "Evidence of potential collusion between multiple customers conducting coordinated transactions.",
  "Customer service call recordings documenting unusual or suspicious account inquiries.",
  "Notary verification showing potentially fraudulent notarization on business documents.",
  "Internal fraud investigation results linking account to previously identified fraud scheme.",
  "Analysis of deposit composition showing unusual payment types for stated business model.",
  "Digital forensic analysis of suspected altered documents provided by business customer.",
  "Comparison of stated business inventory turnover with financial transaction patterns.",
  "Transaction detail showing payments to entities involved in previous investment scams.",
  "Customer explanation for source of funds contradicted by transaction evidence in account.",
  "Analysis showing transaction patterns consistent with known money laundering typologies.",
  "Evidence of potential gambling proceeds based on transaction patterns and merchant categories.",
  "Credit report showing multiple business entities created in short timeframe with same ownership.",
  "Beneficial ownership information showing connection to previously sanctioned individuals.",
  "Physical cash examination notes indicating mixed currencies or unusual foreign denominations.",
  "Evidence of potential shell company network based on address and ownership overlaps.",
  "Location analysis of check issuers showing unusual geographic distribution unrelated to business.",
  "Comparison of signature cards across multiple accounts showing potential unauthorized signers.",
  "Loan application documentation containing materially false information about business operations.",
  "Evidence of potential invoice fraud based on payment verification with supposed vendors.",
  "Customer explanation letters containing provably false justifications for transaction activity.",
  "Account activity showing unusual funds flow through recently established business entities.",
  "Business tax return review showing reported income inconsistent with account deposits.",
  "Security camera footage showing potentially structured cash deposits by multiple couriers.",
  "Comparison of business industry code with actual transaction activity showing discrepancies.",
  "Analysis showing transaction patterns associated with potential investment fraud schemes.",
  "Evidence of potential bust-out fraud based on credit line utilization and payment patterns.",
  "Statements from multiple accounts showing coordinated movement of funds without business purpose.",
  "Business license verification showing operations in jurisdictions not disclosed to bank.",
  "Analysis of check deposit timing showing potentially coordinated kiting activity.",
  "Evidence from site visit indicating minimal or nonexistent business operations at location.",
  "Customer explanation for unusual activity refuted by documentary evidence in transaction history.",
  "Account statements showing excessive personal expenses paid from business account."
]
