small_business_banking__adverse_action_notices__primary_reason = [
  "Insufficient income: The income available to support debt payments is inadequate based on our debt-to-income requirements.",
  "Delinquent past or present credit obligations with others as reported by credit reporting agency.",
  "Excessive obligations in relation to income as determined by our debt service coverage ratio analysis.",
  "Insufficient cash flow: Business cash flow is inadequate to support requested debt payments based on our underwriting standards.",
  "Limited credit experience as shown by the absence of established revolving credit accounts in good standing.",
  "Bankruptcy filing by business entity or guarantor within the past seven years.",
  "Inadequate collateral: The value of collateral offered is insufficient relative to the requested loan amount.",
  "Garnishment, attachment, foreclosure, repossession, collection action or judgment present in credit history.",
  "Unacceptable payment history on existing credit obligations with multiple late payments in the past 12 months.",
  "Insufficient business cash reserves to manage seasonal fluctuations or potential disruptions in cash flow.",
  "Length of time business has been established is less than our two-year minimum requirement.",
  "Credit application incomplete with required information not provided despite multiple requests.",
  "Excessive existing debt relative to business income as shown by debt-to-income ratio exceeding our guidelines.",
  "Insufficient business net worth relative to total business liabilities based on our leverage ratio requirements.",
  "Unverifiable income or revenue with significant discrepancies between reported and documented figures.",
  "Character of credit history as reflected by serious derogatory information in credit bureau report.",
  "Value or type of collateral not sufficient based on our loan-to-value requirements for this loan type.",
  "Inadequate business debt service coverage ratio below our minimum requirement of 1.20:1 based on historical financial performance.",
  "Number of recent credit inquiries suggests excessive seeking of new credit obligations.",
  "Insufficient equity investment in project with owner contribution below our minimum requirement of 20%.",
  "Temporary or irregular employment or income source lacks stability required for long-term credit obligation.",
  "Deteriorating trend in business revenue or profitability over past three reporting periods.",
  "Excessive concentration of revenue from single customer representing over 50% of total business revenue.",
  "Information provided by credit reporting agency indicates too many accounts currently past due.",
  "Unable to verify business location or operations through site visit or independent verification sources.",
  "Delinquent property taxes, payroll taxes, or other government obligations as verified during underwriting.",
  "Inadequate business working capital ratio below our minimum requirement of 1.2:1 for industry type.",
  "Length of time since derogatory public record or collection is too recent for approval consideration.",
  "Insufficient time in current business location or market area based on our stability requirements.",
  "Excessive cash-out from property equity relative to business purpose or working capital needs.",
  "Limited management experience in current business industry or operation type.",
  "Provided business plan does not demonstrate viable strategy for loan repayment from operations.",
  "Inadequate business credit history as reflected by limited or negative payment history with suppliers.",
  "Number of recent credit obligations still too new to establish satisfactory repayment pattern.",
  "Excessive existing contingent liabilities creating unacceptable risk of future payment obligations.",
  "Unable to verify critical information contained in application through independent sources.",
  "Business or personal tax returns show losses or inadequate income to support requested credit.",
  "Unacceptable type of credit requested based on our current lending policy and risk criteria.",
  "Inaccurate or false information provided on application materials discovered during verification.",
  "Inadequate cash management practices as evidenced by frequent NSF items or overdraft activity.",
  "Collateral offered is not acceptable per our lending policy for requested loan type or purpose.",
  "Unstable or declining industry sector creating elevated risk for business operations and repayment capacity.",
  "Debt consolidation request includes credit obligations currently past due or in collection status.",
  "Business ownership structure creates unacceptable liability or operational risk for lending relationship.",
  "Significant variances between financial statements and tax returns without adequate explanation.",
  "Insufficient customer diversification with excessive concentration in volatile market segment.",
  "Pending litigation against business or guarantor with potential material impact on operations.",
  "Loan purpose is not acceptable under our current business lending policy and risk guidelines.",
  "Financial statements reveal significant adverse trends in liquidity, profitability, or leverage ratios.",
  "Existing loan agreement default or covenant violation with this or other financial institutions.",
  "Credit check reveals collection actions, charge-offs, or settlements that demonstrate poor credit management.",
  "Demonstrated unwillingness to meet credit obligations as evidenced by repeated payment delinquencies.",
  "Business debt-to-worth ratio exceeds our maximum guideline of 3:1 for industry classification.",
  "Excessive number of outstanding loans or credit obligations creating overextended credit position.",
  "Recent decline in personal credit score of guarantor below our minimum requirement of 680.",
  "Gross profit margin below industry standard indicating potential pricing or cost control issues.",
  "Substantial tax liens or judgments filed against business or guarantor remain unsatisfied.",
  "Recent high-risk or high-balance credit acquisitions increasing overall financial obligations.",
  "Information obtained from credit reporting agency does not meet our established credit standards.",
  "Business revenue trend shows significant decline over past four quarters without recovery plan.",
  "Financial condition or management succession plan not well-documented in loan application materials.",
  "Collateral depreciation rate exceeds proposed loan amortization creating negative equity position.",
  "Financial statement quality insufficient with only tax returns provided versus required reviewed statements.",
  "Inadequate inventory management with turnover ratio significantly below industry standards.",
  "Inadequate accounts receivable quality with aging exceeding industry standards for collectability.",
  "Length of time between adverse public records and current application does not meet our guidelines.",
  "Excessive personal withdrawals from business affecting debt service capacity and working capital.",
  "Unstable business revenue with significant monthly fluctuations without seasonal justification.",
  "Lease terms for business premises expire during proposed loan term without renewal options.",
  "Inadequate business succession planning for owner-dependent operation with aging owner.",
  "Character and capacity assessment below our lending standards based on interview and application review.",
  "Insufficient credit references or trade references to establish business credit worthiness.",
  "Recent bankruptcy discharge date within our seven-year exclusion period for new credit extension.",
  "Repayment ability not demonstrated through historical cash flow or realistic financial projections.",
  "Collection actions or charge-offs within the past 24 months exceeding our risk tolerance guidelines.",
  "Inadequate business profit margins to support growth strategy outlined in loan application.",
  "Information obtained from credit reporting agency indicates excessive revolving credit utilization.",
  "Collateral appraisal revealed significant deferred maintenance affecting value and marketability.",
  "Debt service requirements would consume excessive percentage of available business cash flow.",
  "Previous loan relationship with our institution experienced payment problems or charge-off.",
  "Limited management depth with operations critically dependent on single individual without succession plan.",
  "Significant discrepancies between application information and verification findings without resolution.",
  "Inability to verify income or employment through standard documentation or third-party verification.",
  "Collateral located in declining market area with negative value trend over past 12 months.",
  "Business projections reflect unrealistic growth assumptions compared to historical performance and industry benchmarks.",
  "Operating expenses as percentage of revenue significantly exceed industry standards without justification.",
  "Business fixed charge coverage ratio below our minimum requirement of 1.15:1 based on historical performance.",
  "Credit history includes recent vehicle repossession or property foreclosure within past 36 months.",
  "Business liquid assets insufficient to cover 60 days of operating expenses per our cash reserve requirement.",
  "Personal guarantor debt-to-income ratio exceeds our maximum guideline of 43% for contingent liability assessment.",
  "Excessive reliance on single supplier or vendor creating unacceptable operational dependency risk.",
  "Material misrepresentation of financial information discovered during verification process.",
  "Length of employment or time in business below our minimum stability requirement of 24 months.",
  "Unacceptable landlord reference or history of commercial lease defaults based on verification.",
  "Tax return analysis reveals inadequate income to support existing and proposed debt obligations.",
  "Significant undisclosed liabilities discovered during underwriting process affecting debt service capacity.",
  "Business debt yield ratio below our minimum requirement of 10% for commercial property financing.",
  "Recent derogatory public record information as reported by credit reporting agency.",
  "Inadequate owner investment in business with excessive reliance on debt financing for operations.",
  "Collateral is not sufficient based on specific type, condition, or marketability for loan purpose.",
  "Monthly business revenue inadequate to support requested payment amount plus existing obligations.",
  "Environmental assessment revealed conditions requiring remediation affecting collateral value or usability.",
  "Lack of established bank account relationship with satisfactory balance management history.",
  "Demonstrated poor business credit management with multiple trade payment delinquencies reported.",
  "Business debt-to-EBITDA ratio exceeds our maximum guideline of 4.0 for industry classification.",
  "Information obtained from credit reporting agency indicates excessive new account acquisition.",
  "Previous business failure or closed business with unpaid creditors within past 48 months.",
  "Recent credit delinquencies of 60 days or more within past 12 months exceeding our guidelines.",
  "Inadequate evidence of required business licenses, permits, or professional certifications.",
  "Business cash flow-to-debt ratio below our minimum requirement of 1.5:1 for requested financing.",
  "Accounts receivable quality and aging does not meet our minimum standards for eligible collateral.",
  "Guarantor's personal financial strength insufficient to provide adequate secondary repayment source.",
  "Information provided by credit reporting agency indicates recent high credit utilization ratios.",
  "Current economic conditions in business sector create excessive risk for proposed credit relationship.",
  "Business plan reflects inadequate market analysis or competitive assessment for success probability.",
  "Recent significant management changes creating instability in business operations and direction.",
  "Inadequate credit history to demonstrate willingness and ability to repay debt obligations.",
  "Property securing loan does not meet our minimum standards for condition or marketability.",
  "Unacceptable prior business relationship with our institution involving policy exceptions or accommodations.",
  "Business debt service coverage ratio trend shows significant deterioration over past four quarters.",
  "Credit bureau information indicates debt management plan or consumer credit counseling participation.",
  "Projected debt service coverage ratio based on realistic forecasts fails to meet minimum requirement.",
  "Recent charge-off or collection account with financial institution within past 36 months.",
  "Business profitability inadequate with net income below 5% of revenue for past fiscal year.",
  "Insufficient documentation provided to validate income, assets, or business performance claims.",
  "Length of credit history does not meet our minimum standards for establishing payment patterns.",
  "Collateral offered is outside our normal lending territory creating servicing and monitoring challenges.",
  "Excessive recent growth without corresponding increase in operational infrastructure or controls.",
  "Prior default with government guaranteed loan program within SBA exclusion period guidelines.",
  "Payment shock from proposed debt obligation excessive relative to existing payment history.",
  "Business financial statements reveal excessive related-party transactions affecting true profitability.",
  "Information provided by credit reporting agency indicates multiple recent past-due accounts.",
  "Business seasonal performance currently in low cycle period with inadequate reserves for debt service.",
  "Unacceptable business credit report with multiple collection accounts and slow payment history.",
  "Collateral value declined significantly since original purchase or prior appraisal review.",
  "Projected loan-to-value ratio exceeds our maximum guideline of 75% for property type and location.",
  "Business tax return analysis reveals inadequate income trend to support additional debt obligations.",
  "Recent credit report information shows delinquent child support or court-ordered payments.",
  "Significant outstanding medical collection accounts affecting overall credit profile and score.",
  "Irregular or incomplete business financial record keeping preventing accurate risk assessment.",
  "Business financial trends show declining gross revenue over past three reporting periods.",
  "Absence of established credit references to demonstrate responsible use and management of credit.",
  "Collateral property has limited use alternatives affecting liquidation value and marketability.",
  "Monthly debt service for proposed loan would exceed 45% of verified monthly business income.",
  "Credit report indicates multiple recent inquiries suggesting financial stress or credit shopping.",
  "Loan request exceeds our internal exposure limit for business size and industry classification.",
  "Financial statement analysis reveals inadequate financial ratios for business type and loan purpose.",
  "Unacceptable payment history with utilities, landlords, or suppliers based on reference checks.",
  "Business operating margins below industry benchmark indicating potential operational inefficiency.",
  "Limited credit history with insufficient trade lines to establish credit management patterns.",
  "Verification of business operations revealed inconsistencies with application representations.",
  "Proposed loan structure does not match business cash flow cycle or repayment capacity.",
  "Business current ratio below our minimum requirement of 1.2:1 indicating working capital constraint.",
  "Excessive personal or family living expenses reducing available income for business obligations.",
  "Previous modification or workout arrangement on existing debt within past 36 months.",
  "Collateral property lacks necessary features or improvements for specialized business use.",
  "Adverse business credit report showing past-due supplier accounts or collection activity.",
  "Significant gaps in business operating history indicating business instability or interruption.",
  "Inventory turnover ratio significantly below industry standard suggesting potential obsolescence.",
  "Business location in declining market area with adverse economic conditions affecting stability.",
  "Recent credit obligation default or charge-off exceeding our risk tolerance threshold.",
  "Accounts receivable concentration with excessive reliance on single payor or customer.",
  "Negative cash flow from business operations in recent fiscal period as shown on tax returns.",
  "Information obtained from credit reporting agency indicates excessive secured debt obligations.",
  "Business concept or model unproven in local market creating elevated failure risk assessment.",
  "Business debt-to-assets ratio exceeds our maximum guideline of 60% for industry classification.",
  "Market analysis indicates significant competitive threats to business model and revenue stability.",
  "Inconsistent income pattern with fluctuations exceeding 25% between reporting periods.",
  "Property does not meet our minimum standards for general condition and deferred maintenance.",
  "Business demonstrates inadequate cash management practices through account review and analysis.",
  "Credit bureau information indicates identity theft alerts requiring additional verification steps.",
  "Inadequate insurance coverage for business operations, professional liability, or collateral property.",
  "Length of time accounts have been established is insufficient to demonstrate stability.",
  "Excessive existing contingent liabilities through personal guarantees on other business debts.",
  "Business operates in highly regulated industry with pending adverse regulatory changes.",
  "Previous foreclosure or deed in lieu of foreclosure within our seven-year exclusion period.",
  "Tax liens or delinquent taxes indicate pattern of financial difficulty or cash flow problems.",
  "Business or personal bankruptcy discharged less than 48 months ago exceeding our guidelines.",
  "Employment instability with job changes or industry transitions within past 24 months.",
  "Information provided by credit reporting agency indicates payment patterns inconsistent with loan terms.",
  "Debt consolidation request includes excessive percentage of unsecured or high-interest obligations.",
  "Application reflects excessive debt relative to business size and documented revenue streams.",
  "Credit history contains recent judgments, tax liens, or garnishments within past 36 months."
]
