consumer_banking__statement__descriptions = [
    "Account maintenance fee",
    "ATM withdrawal",
    "Balance adjustment",
    "Bill payment (recurring)",
    "Cash deposit",
    "Check deposit",
    "Check printing charge",
    "Closing balance",
    "Credit interest",
    "Debit card purchase",
    "Direct deposit",
    "Dividend payment",
    "Electronic transfer",
    "Excess activity fee",
    "Foreign transaction fee",
    "Interest charge",
    "Late payment fee",
    "Loan payment",
    "Minimum payment due",
    "Money transfer",
    "Opening balance",
    "Overdraft fee",
    "Returned check fee",
    "Savings withdrawal",
    "Service charge",
    "Statement closing date",
    "Stop payment fee",
    "Transaction fee",
    "Wire transfer fee",
    "Account statement period",
    "ACH debit",
    "ACH credit",
    "Adjustment credit",
    "Adjustment debit",
    "Annual fee",
    "Auto loan payment",
    "Available balance",
    "Bank charge",
    "Bill payment (one-time)",
    "Branch deposit",
    "Card replacement fee",
    "Cash advance",
    "Cash back reward",
    "CD interest",
    "Check card purchase",
    "Credit card payment",
    "Currency exchange",
    "Daily balance",
    "Deposit correction",
    "Electronic check deposit",
    "Escrow payment",
    "External transfer",
    "FDIC insured",
    "Finance charge",
    "Funds transfer",
    "Gift card purchase",
    "Incoming wire",
    "Insufficient funds fee",
    "IRA contribution",
    "Late fee",
    "Maintenance charge",
    "Mobile check deposit",
    "Monthly average balance",
    "Mortgage payment",
    "New account bonus",
    "Non-sufficient funds",
    "Online banking transfer",
    "Outgoing wire",
    "Overdraft protection",
    "Paper statement fee",
    "Payment received",
    "Phone payment",
    "Previous balance",
    "Purchase refund",
    "Recurring payment",
    "Refund credit",
    "Reward redemption",
    "Safe deposit box fee",
    "Savings deposit",
    "Statement cycle",
    "Student loan payment",
    "Tax payment",
    "Teller deposit",
    "Third-party payment",
    "Travel notification",
    "Utility bill payment",
    "Variable rate adjustment",
    "Withdrawal limit",
    "Account activity summary",
    "Account balance details",
    "Account number",
    "Account type",
    "Available credit",
    "Billing cycle",
    "Cash withdrawal",
    "Customer service contact",
    "Deposit details",
    "Electronic funds transfer",
    "Financial institution",
    "Funds availability",
    "Interest rate",
    "Merchant name",
    "Payment due date",
    "Payment history",
    "Pending transactions",
    "Previous statement date",
    "Statement period",
    "Transaction date",
    "Transaction details",
    "Transaction history",
    "Transfer between accounts",
    "Account access information",
    "Account alerts",
    "Account closure notice",
    "Account maintenance",
    "Account security",
    "Account statement",
    "Account summary",
    "ATM fees",
    "Authorization hold",
    "Balance inquiry",
    "Bank address",
    "Bank contact information",
    "Bill pay service",
    "Card activation",
    "Card PIN change",
    "Card replacement",
    "Card transaction dispute",
    "Cash deposit limit",
    "Check clearing policy",
    "Check deposit hold",
    "Check image",
    "Credit limit increase",
    "Customer rewards program",
    "Debit card activation",
    "Debit card replacement",
    "Direct deposit setup",
    "Electronic statement option",
    "Fee schedule",
    "Fraud prevention tips",
    "Lost or stolen card",
    "Mobile banking access",
    "New account opening",
    "Online account access",
    "Overdraft opt-in",
    "Paper statement option",
    "Payment processing time",
    "Privacy policy",
    "Recurring transfer setup",
    "Security measures",
    "Statement delivery options",
    "Transaction limits",
    "Travel notification service",
    "Wire transfer instructions",
    "Account reconciliation tips",
    "ATM locator",
    "Balance transfer offer",
    "Branch hours and locations",
    "Contactless payment",
    "Credit monitoring service",
    "Customer support",
    "Digital wallet",
    "Financial education resources",
    "Fraud alert",
    "Identity theft protection",
    "Investment advice",
    "Loan application status",
    "Mobile deposit",
    "Online security tips",
    "Overdraft protection options",
    "Payment reminders",
    "Personal financial management",
    "Referral program",
    "Rewards program details",
    "Security breach notification",
    "Spending analysis tools",
    "Transaction dispute process"
]
